### ISSUE TITLE
[10.2] No network connection after reboot.

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#100]
It was completely random and I couldn't reproduce it but it may be worth checking out 
https://dl.dropboxusercontent.com/u/40426219/logcattt.txt (taken after boot while trying to search network operator and changing network type (obviously none of this options worked))

**Comment by mikeNG** [comment]
I don't see anything useful/related in the log :/

**Comment by ghost** [comment]
Sorry then. As I said it was a one time thing and I don't have a clue what caused it (100% not my fault because everything is stock).

**Comment by ghost** [comment]
Oh and one last question: Next time should I get dmesg and logcat or just logcat?

**Comment by mikeNG** [comment]
for radio problems, messages are usually present in logcat & in radio log.

**Comment by ghost** [comment]
Thanks.

**Comment by ghost** [comment]
It happened again. Phone turned off without any reason and after booting up network was down. I managed to make a radio log this time and it's definitely relevant: https://dl.dropboxusercontent.com/u/40426219/radiolog.txt
Edit: While tapping everything network related that I could think of I noticed that airplane mode is on but when I tried to disable it option just grayed out https://dl.dropboxusercontent.com/u/40426219/Screenshot_2013-10-24-16-12-00.png

**Comment by mikeNG** [comment]
I was able to reproduce this too but it's too hard for me to find the source of the problem.
CM is merging a ton of sources from CodeAurora and something in that probably causes this issue.

**Comment by novanto** [comment]
I'm having the same problem. The airplane mode is somewhat on when this happened, and I have to reboot many times to get back the mobile network.

**Comment by ghost** [comment]
I'm pretty sure it was fixed in CM10.2. Maybe try flashing .587 ftf. Also one reboot was always enough for me.

**Comment by mikeNG** [comment]
Does anybody still has this issue?

**Comment by ghost** [comment]
Happened a few times in first alpha but stopped after updates.

**Comment by mikeNG** [comment]
Ok, I'm closing this for now
