### ISSUE TITLE
[CM11] [ikoyan] Camera sometimes not working

### ISSUE THREAD

**Issue by aichitho** [LegacyXperia/local_manifests#1005]
Hello!
Very often, when I want take a photo, the picture freezes, but no photo is taken. I can still use all the options fluently (f.i. turning on/of the flash)

It's not app related, because it occurs in different camera apps (even in what's app).
I couldn't reproduce yet, in which specific situation it happens/doesn't happen, but it is most of the time.

I think I got an error once. It was something like "cannot access the camera" but im not sure anymore.

Version:11-20150830-UNOFFICIAL-LegacyXperia-iyokan

off topic:
please don't give up cm11 for cm12. I've been looking for a fast and stable rom for a long time, but haven't found anything better than cm11 yet, although it's still nightly! Thank you for your great work!

**Comment by WaLmeN** [comment]
You need to install an older kernel , as the kernel of the package 20150830 camera is Not working :
Camera
video recording
Touchpads

Sorry for bad english, Google translate :P

**Comment by aichitho** [comment]
Oh thank you very much, I'll try that!

Edit: Is there even a kernel for cm11 with camera working? And which is the latest one?
(Sorry I could only find a changelog for 3.4kernel, which seems to be the one since the initial release?)

**Comment by XSmile2008** [comment]
Hi! I have same problem on my Xperia mini (smultron). I take photo and picture is just freeze... And camera is not working until reboot. How to fix this?
In other camera apps i got something like this message "camera is unavailable", "camera error", etc.

**Comment by realcatgirly** [comment]
Provide logs and update to the latest version plus kernel (the boot.IMG in
the zip must be flashed via fastboot)

Vlad Starikov notifications@github.com schrieb am Di., 1. Dez. 2015 20:47:

**Comment by XSmile2008** [comment]
Yesterday I found this post http://forum.xda-developers.com/showpost.php?p=54029583&postcount=5524

for camera freeze while taking pictures or any other camera problem
uncheck Kernel samepage merging(KSM) in settings>performance> memory mangement 
and then reboot 

After I turn off KSM camera works fine)))

Why I don't find this in FAQ, topic header in XDA? When I read forum I find that many users have this problem.
