### ISSUE TITLE
No Music visualization

### ISSUE THREAD

**Issue by realcatgirly** [LegacyXperia/local_manifests#1007]
I have Urushi with 12062015. 
But now the music visualization in Music/eleven is gone. Same for the lockscreen and even WhatsApp (you know this little visualization next to an audio).
A reboot doesn't help. 
I noticed also that the boot time has increased from ~5min to ~8min.

What can I do?

**Comment by avsaponchik** [comment]
after upgrading from cm-12.1-20150831-UNOFFICIAL-LegacyXperia-iyokan to cm-12.1-20151206-UNOFFICIAL-LegacyXperia-iyokan visualization died too. fixed it by disabling and enabling again.
I'm using poweramp pro + Smart Launcher Pro + default LX lock screen
![screenshot_2015-12-14-16-33-26](https://cloud.githubusercontent.com/assets/1337953/11782288/2600338a-a2ab-11e5-8b54-308ed84126d2.png)

**Comment by realcatgirly** [comment]
I'll try this

**Comment by realcatgirly** [comment]
Won't work for me. Visualization in whatsapp is there. But in eleven the
bars are going high and then they disappear

**Comment by realcatgirly** [comment]
I now use play music. I first tried it, visualization was there. But now its also gone. I tried reenableing and rebooting. Nothing works. The shiny visualization is very important to me.

**Comment by realcatgirly** [comment]
Strange. Since Yesterday all works perfectly fine. All is there.

**Comment by avsaponchik** [comment]
After upgrading to latest Iyokan build im having visualization even for system notifications or button clicks or phone unlocking etc etc you know :)

**Comment by realcatgirly** [comment]
Yes, I noticed it too

**Comment by realcatgirly** [comment]
its only working when i have a Bluetooth Speaker connected. then the visualization is there. but via aux or internal Speaker there is no visualization

**Comment by realcatgirly** [comment]
Visualization is only present when playing via Bluetooth or USB.

**Comment by realcatgirly** [comment]
Very Strange. Since yesterday all working perfectly fine.
