### ISSUE TITLE
[cm12.1-20151206-urushi] Display rotates 180 deg when changing DPI

### ISSUE THREAD

**Issue by cajhin** [LegacyXperia/local_manifests#1008]
1. go to Settings > Display > LCD Density
2. change from 240 (default) to 280

Result: phone reboots immediately, and beginning with the Sid boot animation, the display is rotated 180 degrees.
A nasty side problem is that the touch panel is _not_ rotated, so in order to click a button, you have to tap where the button would be if the screen wasn't rotated.

Workaround: somehow navigate to the settings and change back to 240 dpi.
The phone will reboot and still be rotated. Restart again and everything is back to normal.

I recommend you disable the LCD Density setting for now. Let me know if you actually need logs for this.

**Comment by realcatgirly** [comment]
Try more restarts with 280 dpi

**Comment by mikeNG** [comment]
You can just turn the screen off and then back on. I couldn't find out what causes this issue yet

**Comment by mikeNG** [comment]
#919
