### ISSUE TITLE
[cm12.1 cm11 ][urushi][20151204] only noise is recorded using Soundrecorder/Camera app

### ISSUE THREAD

**Issue by s0rl0v** [LegacyXperia/local_manifests#1011]
Happy New Year! :smile: :santa: 
I found a bug in the audio recording. Strange, but everything works ok during a telephone conversation.
- Using stock sound recording application after recording a random speech and its playback only noise is audible;
- Guitar Tuner can not identify a pitch, the arrow moving at random;
- When calling through WhatsApp a receiver complains that he hears only noise;
- Same audio noise is present in recorded cam videos (true for cm11, cm12; cm13 with the Snap app works fine).

UPD: Sound recording is not working correctly (maybe just for my urushi) for cm11, cm12.1 and cm13.

Logs:
- [dmesg.log](http://pastebin.com/pZxRR7xf)
- [last_kmsg.log](http://pastebin.com/WtfTwSQs)
- [logcat.log](http://pastebin.com/hweyDB8t)
- [event.log](http://pastebin.com/evCcSCX1)

Maybe the problem is here:

```
01-01 21:00:06.707 I/MediaFocusControl(  566):  AudioFocus  requestAudioFocus() from android.media.AudioManager@41a41b68com.android.soundrecorder.SoundRecorder$4@41a8d158
01-01 21:00:06.777 E/Recorder( 2606): audiosourcetype 1
01-01 21:00:06.777 E/MediaProfiles(  228): The given audio encoder 8 is not found
01-01 21:00:06.777 E/MediaProfiles(  228): The given audio encoder 8 is not found
01-01 21:00:06.777 E/MediaProfiles(  228): The given audio encoder 8 is not found
01-01 21:00:06.777 E/MediaProfiles(  228): The given audio encoder 8 is not found
01-01 21:00:06.777 E/MediaProfiles(  228): The given audio encoder 8 is not found
01-01 21:00:06.777 E/MediaProfiles(  228): The given audio encoder 8 is not found
01-01 21:00:06.787 D/AudioHardware7x30(  228): AudioHardware::openInputStream devices 80000004 format 1 channels 12 samplerate 48000
01-01 21:00:06.787 D/AudioSource(  228): Start autoramp from 500000
01-01 21:00:06.787 D/StagefrightRecorder(  228): No encoder is needed, use the AudioSource directly as the MediaSource for LPCM format
01-01 21:00:06.787 D/AudioHardware7x30(  228): AudioStreamInMSM72xx::standby()
01-01 21:00:06.827 D/AudioHardware7x30(  228): outputDevices = 2
01-01 21:00:06.827 I/AudioHardware7x30(  228): do input routing device 80000004
01-01 21:00:06.827 I/AudioHardware7x30(  228): Routing audio to dual mic real stereo
01-01 21:00:06.827 D/AudioHardware7x30(  228): new_rx = 17
01-01 21:00:06.827 D/AudioHardware7x30(  228): new_tx = 32
01-01 21:00:06.827 D/AudioHardware7x30(  228): case PCM_REC
01-01 21:00:10.471 D/AudioHardware7x30(  228): AudioStreamInMSM72xx::standby()
01-01 21:00:10.471 D/AudioHardware7x30(  228): Deroute pcm in stream
01-01 21:00:10.481 D/AudioHardware7x30(  228): outputDevices = 2
01-01 21:00:10.481 I/AudioHardware7x30(  228): do input routing device 80000004
01-01 21:00:10.481 I/AudioHardware7x30(  228): Routing audio to dual mic real stereo
01-01 21:00:10.481 D/AudioHardware7x30(  228): new_rx = 17
01-01 21:00:10.481 D/AudioHardware7x30(  228): new_tx = 32
01-01 21:00:10.541 D/AudioHardware7x30(  228): outputDevices = 0
01-01 21:00:10.561 D/AudioHardware7x30(  228): AudioStreamInMSM72xx::standby()
```

**Comment by realcatgirly** [comment]
My sound works. Maybe a hardware Problem

ShamanHasThreeHands notifications@github.com schrieb am Do., 31. Dez.
2015 15:33:

**Comment by s0rl0v** [comment]
Hi, **TomTomcrafter001**!
Do you have any problems with audio in recorded cam videos? And what is your device? Urushi?

Found in this thread - [Stereo recording not working](https://github.com/LegacyXperia/local_manifests/issues/141):

> Can someone test stock rom and see how the 2 mics behave? The current kernel & audio sources we have allow using only one microphone for recording. Most devices use the main mic for calls and the secondary mic for camera/audio recording.
> -mikeNG commented on 22 Jan 2014

Maybe the problem is in the secondary mic. :santa:

**Comment by realcatgirly** [comment]
I have urushi but cm 12. Sorry

**Comment by s0rl0v** [comment]
Okay. Btw, thank you for the quick reply :smiley:

**Comment by s0rl0v** [comment]
Has anyone, except me, experienced this bug?

**Comment by mikeNG** [comment]
Sound recording works fine on my urushi on cm11

**Comment by s0rl0v** [comment]
Hello, Mike! Thank you for all your work ! :smile: 
I did a little research and It seems the noise overlaps the useful signal, so I can hear my voice only when I speak into the second mic directly.

Back to the stock, there is no noise at all.  I will try to flash CM11 over the stock and see if anything changes.

**Comment by realcatgirly** [comment]
My Sound works fine, too. I have urushi on Cyanogenmod 12.1

ShamanHasThreeHands notifications@github.com schrieb am Di., 2. Feb. 2016
05:28:

**Comment by s0rl0v** [comment]
Hi, TomTomcrafter001! On the latest ROM?

**Comment by realcatgirly** [comment]
Yes. Build 20151206

ShamanHasThreeHands notifications@github.com schrieb am Di., 2. Feb. 2016
06:43:

**Comment by s0rl0v** [comment]
Thanks. It seems the problem is on my side.

**Comment by s0rl0v** [comment]
Gave a shot of tequila to the mic. Now it works.

**Comment by s0rl0v** [comment]
The effect lasted for few hours. Tequila definitely works :smile: , but I need a more permanent solution.
I think I need to disassemble and clean the device. Someday. For now I simply disabled the secondary mic.

**Comment by Nonage** [comment]
haha
