### ISSUE TITLE
[CM12.1]lags after some minuets that i dont use my phone

### ISSUE THREAD

**Issue by amirreza817** [LegacyXperia/local_manifests#1014]
after some minuets that i do not use my phone and again i want to use it it has lags and problems whit touch like something in build 587 in neo l(phoenix)
please help is it because of kernel?or low ram?

**Comment by realcatgirly** [comment]
I have this when I leave the phone for ~30 min and then use it and launch an app. Most of the time its super laggy and sometimes it reboots.
Latest Cyanogenmod Build on Urushi
