### ISSUE TITLE
[cm12.1][urushi] music playing bugs via BT/USB

### ISSUE THREAD

**Issue by realcatgirly** [LegacyXperia/local_manifests#1019]
When I play music via Bluetooth or USB OTG (Headset) the Music stops randomly. Even in Eleven. This is annoying and forces me to use 3,5 mm jack.
Which logs do you need?

**Comment by MardonHH** [comment]
try change build.prop line lpa.decode=true to lpa.decode=false

**Comment by realcatgirly** [comment]
OK I'll try and say if it is working

**Comment by realcatgirly** [comment]
Thanks ! Working so far. Sometimes there is a very short lag but it works. 

#Closed

**Comment by realcatgirly** [comment]
Please commit These build.prop changes to cm13
