### ISSUE TITLE
Audio buffer too small on coconut for cm-10.2_coconut-LX-20131013-NIGHTLY.zip ?

### ISSUE THREAD

**Issue by mskyaxl** [LegacyXperia/local_manifests#102]
The sound on coconut for the latest release of CM 10.2 20131013 is jerky.

My guess is that the audio buffer is too small.
Bellow I've attached the logcat although I couldn't find something bad in it.

the log was recorded during listening musing using Apollo. The issue was pressend but in the log I could not found nothing.

https://gist.github.com/anonymous/7022984

let me know if you need aditional logs,

**Comment by mikeNG** [comment]
Duplicate of #83
