### ISSUE TITLE
2 problems

### ISSUE THREAD

**Issue by QuantumTarek** [LegacyXperia/local_manifests#1023]
keyboard lags it can't keek up with my typing speed and i'm getting an error when i try to install musixmatch.... i think because musixmatch should be installed on the internal storage

**Comment by realcatgirly** [comment]
what class of sdcard do you have?

**Comment by realcatgirly** [comment]
if it is laggy try to restart the device. works for me

**Comment by QuantumTarek** [comment]
cm12.1 20151206 haida

**Comment by QuantumTarek** [comment]
class 4

**Comment by MrAnilJean** [comment]
Use a class 10 micro sd card, my phone is haida too but haven't any problem about typing on keyboard and installing apps...

**Comment by avsaponchik** [comment]
@MrBingoO, try Greenify

**Comment by QuantumTarek** [comment]
okay i will use class 10 but why i cant install musixmatch , this is the only app that i cant install

**Comment by MrAnilJean** [comment]
Maybe you have not enough space on your device, normally it's important to use a class10 sdcard... If you can buy 16GB or more... If this problem appear again use TrackID
