### ISSUE TITLE
[CM12.1][Haida] OMTP does not work with my phone

### ISSUE THREAD

**Issue by MrAnilJean** [LegacyXperia/local_manifests#1024]
I have 3 different ear phones with OMTP standard and i tried to listen music with my device but it doesn't recognise my ear phones, after that i tried with a normal ear phone with TRS audio jack and it's work perfect. In the last i test with a orginal sony headset extra made for this device, i was suprised because it does not recognise too. For more information about TRS and OMTP Audio Jack please check this page https://en.m.wikipedia.org/wiki/Phone_connector_(audio)

**Comment by Dexus1977** [comment]
Use apple headset with mic and put a wire to hold pressed the mic button. Works great! Otherwise by and adapter from eBay :)

**Comment by MrAnilJean** [comment]
I know this trick, but i prefer better ear phones,  i think this problem can not be fixed with an adapter.  @Dexus1977

**Comment by mikeNG** [comment]
@MrAnilJean this is a hardware limitation on semc devices, it can't be fixed without an adapter

**Comment by realcatgirly** [comment]
Maybe a USB device. Audio via USB is working. Mic idk

**Comment by mikeNG** [comment]
You can get a CTIA to OMTP adapter, there's even a sony ericsson one available if you search on ebay.

**Comment by MrAnilJean** [comment]
Okey, i will buy an adapter, normally my phone(haida) and 2011 line semcs supports OMTP but my phone does not recognise an ear phone with OMTP standards, that is absolutely abnormal. @mikeNG Thank you for the comments

**Comment by mikeNG** [comment]
Hmm you are right I remembered this in reverse. Sony ericsson should support OMTP but not CTIA: https://talk.sonymobile.com/t5/FAQ/Problem-using-headset-accessory-not-supported/td-p/347872

I don't know if the adapter will help you then

**Comment by MrAnilJean** [comment]
Okey, i have idea... I will test some other devices(hallon,haida and anzu)(all of them have cm12.1 as os) with my ear phone(OMTP)... 2-3 days later i will send the result without adapter and with adapter(maybe)... @mikeNG
