### ISSUE TITLE
[CM13] Live lockscreen enables itself

### ISSUE THREAD

**Issue by realcatgirly** [LegacyXperia/local_manifests#1027]
i saw this live lockscreen in Settings. it basically Displays this "Color" daydream as Background on the lockscreen. but after a reboot it activates itself. then i have to turn it on and off to disable it(until next reboot)

CM13 Alpha Build from AdrianDC
Urushi

**Comment by mikeNG** [comment]
CM13 isn't released officially yet

**Comment by realcatgirly** [comment]
OK. But if this issue is present in the official release I reopen this thing
