### ISSUE TITLE
[CM13] Cellular Data

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#1028]
Cellular data wont work, dont know why, but this issue I had in 12.1, too, but after finding network operators it works, i tried it here to but it didnt work
P.S. Phone calls are working

**Comment by ghost** [comment]
In my smultron... in every boot, I put the phone in airplane mode then off the airplane mode... Then cellular data work again...

**Comment by ntdvj** [comment]
in my smultron i must change prefered network (to 2g then back to 3g) everytime after boot to make cellular data work

**Comment by avsaponchik** [comment]
@raixer i got same problem as you and same solution on my Pro and NeoV

**Comment by niks255** [comment]
I have this bug too, logcat doesn't show anything. Switcher just doesn't do anything, unless you switch airplane mode on/off.

**Comment by joyvoll** [comment]
Hallo, I have the same problem. No cellular data, since CM 13. All solutions that are mentioned above
do not work for me. What can I do else?

My Phone is Xperia NEO V

**Comment by avsaponchik** [comment]
Fixed in fresh LX13 build (iyokan + clean install)

**Comment by niks255** [comment]
Is it? It's not for me.

**Comment by avsaponchik** [comment]
Fresh build, iyokan, everything is just fine.

**Comment by niks255** [comment]
Agreed. This issue can be marked as solved.
