### ISSUE TITLE
[cm13][mango] Smiley menu on physical keyboard Fn button

### ISSUE THREAD

**Issue by alex-dot** [LegacyXperia/local_manifests#1035]
Now in CM13 the menu for smileys pops up when I press the blue Fn-button on my physical keyboard on my Sony Xperia Pro mini. This is particularly annoying as the button is needed to type in numbers and special symbols (like ! or ?).

**Comment by MardonHH** [comment]
Goto Keyboard settings -> Advanced
Disable Emoji for physical Keyboard.
Its activated by default.

@mikeNG guess you can close this

**Comment by gabri-hell** [comment]
Great job Mardon, I hadn't seen this well hidden option.
Fixes the problem.
Thx

**Comment by MardonHH** [comment]
@alex-dot 
since this is no issue plz close this

**Comment by alex-dot** [comment]
Sorry, I was able to try this just now. Thanks for the tip!
