### ISSUE TITLE
[cm13][anzu] camera can't connect error

### ISSUE THREAD

**Issue by allanjojo** [LegacyXperia/local_manifests#1036]
I have just installed cm13 on my xperia arc which works perfectly fine except the camera doesnt work with the stock or any other app. Tried restarting it and even did a fresh install.No change so far....Plz help

**Comment by MardonHH** [comment]
Camera works fine on Arc S.
Did you maybe accidentially activated KSM? If so disable it ;)

**Comment by allanjojo** [comment]
i dont know what that is and how to disable.. pls tell me

**Comment by realcatgirly** [comment]
KSM is Kernel Samepage Merging. You can disable it with various Kernel Apps.

**Comment by allanjojo** [comment]
ok i checked with the kernel auditor ksm is disabled...

**Comment by allanjojo** [comment]
the camera was missing after installing the rom and the flash light in the quick setting in the notification is also missing
is this for my phone only or for all xperia arc?

**Comment by MardonHH** [comment]
Both works fine here on my anzu

**Comment by realcatgirly** [comment]
Did you install the newest cm13 kernel?

**Comment by MardonHH** [comment]
always use the kernel provided with the rom zip!

**Comment by allanjojo** [comment]
i used the same same kernel provided in the zip but now i got a new problem.so i flash the phone with the lt18i stock rom and even in that the camera does not respond.... so i think the hw stoped working mayb...

**Comment by allanjojo** [comment]
anyways thnx 4 d help

**Comment by MardonHH** [comment]
hmm if its also on stock then cam maybe defective. so no bug in cm13

@allanjojo so close this issue plz
