### ISSUE TITLE
[CM13][ALL2011][2016xxxx] MTP mode sometimes needs to be chosen again to make it works properly

### ISSUE THREAD

**Issue by avsaponchik** [LegacyXperia/local_manifests#1046]
1. Connect your phone to PC
2. Drag taskbar and switch from Charging to MTP
3. Sometimes your phone will not appear in Your Computer.
4. To make it appear again you need to go to taskbar and switch from MTP to MTP again.
   This bug is only specific to LX13.

**Comment by realcatgirly** [comment]
On all devices I guess. My uruahi is affected, too

**Comment by realcatgirly** [comment]
urushi. Damn can't edit on the phone

**Comment by ntdvj** [comment]
i found this bug on all marshmallow custom room. my friend using cm13 and aosp marshmallow on his redmi note and need to togle mtp too.

**Comment by bykidi** [comment]
Iyokan, April build, bug is still here

**Comment by avsaponchik** [comment]
FIXED with pre-release test CM14.1 build by AdrianDC
