### ISSUE TITLE
Dsp manager fails again

### ISSUE THREAD

**Issue by Abhi0167** [LegacyXperia/local_manifests#105]
when switched in 'EXTREME' bass, sound quality become very very harsh after voluming up........It was a common issue in cm 10.1 now in 10.2 it hits again

**Comment by djey47** [comment]
Something related to higher sound volume set in Kernel (see latest changelog) ?
("Increase volume a little bit more (kernel)")

Harsh sound is a common issue when amplifier is set too high vs volume. Expecting loud but clear sound is a nonsense :)

**Comment by mikeNG** [comment]
This happens on all phones. We can't have both loud volume & clear sound. Issue closed.
