### ISSUE TITLE
[CM13] Google Play & Google Services constantly crashing on SMULTRON

### ISSUE THREAD

**Issue by dhanu14327** [LegacyXperia/local_manifests#1050]
@mikeNG Hi, I installed cm13 for smultron yesterday. I have been using custom roms for a couple of years now.. yesterday i bought a new **samsung EVO uhs-1 16GB** card and installed cm13 ( **cm-13.0-20160227**-UNOFFICIAL-LegacyXperia-smultron.zip and **gapps from Mardon-MDPI**_GAPPS-6.0-20160330-tb-signed.zip ) Installation was easy but soon as phone booted it began to show errors like **"Unfortunately Google Play Services Has Stopped" & "Unfortunately Google Play Has Stopped"** i did a lot of searching and i came across this **msg from Mardon "The problem is not in gapps as the actual packages are working on older cm builds. Its a problem in cm rom."** Could you pls take a look into this matter. The rom is awsme but it is unusable with the presence of  this issue

**Comment by dhanu14327** [comment]
just for your info, **I had done a clean installation**. wiped everything, cache, data, factory reset etc etc.

**Comment by FibreFoX** [comment]
@dhanu14327 this is already reported ;)
https://github.com/LegacyXperia/local_manifests/issues/1049

will be fixed soon, they are working on it

Could you close this issue?

**Comment by dhanu14327** [comment]
@FibreFoX thank u for the info. good to knw that they knw this issue & are working on it.

**Comment by derMart** [comment]
please don't close issues before they are fixed (its hard to find them if they are)
