### ISSUE TITLE
[cm-13.0-20160327][smultron][gapps] Google Play Store and Play Services force closing

### ISSUE THREAD

**Issue by derMart** [LegacyXperia/local_manifests#1054]
On cm-13.0-20160327 latest verions of Google Apps are not working.
Play store cannot be opened and crashes on launch. Google Play Services occasionally crash.

This applies to the [Google Apps linked in the installing intructions of Marshmallow](http://forum.xda-developers.com/android/apps-games/hdpi-google-apps-6-0-1-upd-20160121-t3307611)
 -> MDPI_miniGAPPS-6.0-20160323-tb-signed.zip
According to [post 41](http://forum.xda-developers.com/showpost.php?p=66172713&postcount=41) (and some posts before) this is an issue of cm13 at all (or just legacyxperia)?

I can verify MDPI_miniGAPPS-6.0-20160323 works on cm-13.0-20160227-smultron

I have tried replacement GApps available at xda but none of them worked with lx cm13. Some just are not possible to install.

best
Martin

**Comment by derMart** [comment]
referencing #1049, #1050 -> please don't close issues BEFORE they are fixed (so people won't find them)

**Comment by dhanu14327** [comment]
@derMart dev already knws this issue and has replied in various posts that he is gonna fix this in next build which is already in progress. so keeping the issue open makes no sense. do close this issue as it has been pointed out a couple of times.

**Comment by dhanu14327** [comment]
![bbnbcnb](https://cloud.githubusercontent.com/assets/18307696/14414908/fb29fd1c-ffb6-11e5-9b72-d918d7c94c74.JPG)

**Comment by derMart** [comment]
@dhanu14327 thanks for your comment. I don't want to start a conversation about software development especially not inside this thread and sorry for this but apart that - I am very impressed that you exactly know how software development works and are able to tell other people after just 2 posts and 5 days registered on Github - I will give you this comment: Keeping an issue open until it is fixed first is not about ignorance or any other offending action disrespecting anybodies work or effort. It makes a lot of sense to do so. The issue system in here is not only for the volunteers willing to fix something, It is also for anybody experiencing the same problem and documentation in general. If an issue is open while unfixed it better reflects the current development state and is much easier to find. This is important for example to find workarounds such as https://github.com/LegacyXperia/local_manifests/issues/1049#issuecomment-204295618, not to duplicate issues and apart from that it is best practice in software development / documentation.

**Comment by dhanu14327** [comment]
@derMart well thanks for clearing that, jst to let u knw i have been using custom roms for the last 4 years. you maybe right in pointing out the number of posts or my joining date on this site, that doesnt surely tell u that i m new to this site. i have been using @mikeNG's rom for a very long time and have always been an unregistered user here. i never had any problem with his rom so i didnt comment or post anything. but this time as i have mentioned in my posts i came across some bugs which i wanted to point out. thats y u assumed me to be a newbe here. I do respect your point of view and i think u may be right. if i have offended u in any ways, i am sorry it was unintentional. hope we r good :)

**Comment by mkroshana** [comment]
So still no progress on that bug ???

**Comment by reset1820** [comment]
Is there any progress? Thanks :)

**Comment by avsaponchik** [comment]
![screenshot_20160418-202655](https://cloud.githubusercontent.com/assets/1337953/14613240/30feeebe-05a4-11e6-96f3-867848cd1c8b.png)
![screenshot_20160418-202733](https://cloud.githubusercontent.com/assets/1337953/14613242/31297008-05a4-11e6-98bc-93b647a8a0a2.png)
