### ISSUE TITLE
[CM11] CM 11 - still in progress or discontinued ?

### ISSUE THREAD

**Issue by gsb9** [LegacyXperia/local_manifests#1056]
According to the changelog I see several newer builds, but the latest available cm-11 build is 20151116.

Will there be any actual updates to cm11, or is it discontinued here?

Thanx for your great work,

**Comment by mikeNG** [comment]
There will be a new build in the following days, I just had some networking issues this week and have still one patch from April's security bulletin pending to be merged.

**Comment by gsb9** [comment]
thank you in advance.
