### ISSUE TITLE
CM13 [latest] SMULTRON unable to update, signature verification failed

### ISSUE THREAD

**Issue by dhanu14327** [LegacyXperia/local_manifests#1057]
need help.... I am getting error while installing latest update for SMULTRON CM13
i am able to flash the boot file, but when sideloading the zip file i am getting the following messages in this order
1) verifying update package......
2) failed to verify whole-file signature
3)signature verification failed
4)installation aborted

i tried to install the march version and it installs just fine.... @mikeNG @MardonHH  pls reply
Last edited by dhani14327; Today at 09:19 PM. Reason: tried it once more. . . . these were the exact errors.
Already mentioned in XDA thread no: 936

**Comment by mikeNG** [comment]
Check if md5 matches the downloaded file, if not, download again

**Comment by dhanu14327** [comment]
it matches 
i have downloaded the file one more time.... let me check this time.

**Comment by dhanu14327** [comment]
rom installed. it seems that the program i used to check md5 messed with the file somehow.
i found the System APKs correpted while trying to extract.

Thank you @mikeNG for replying. Thanks for the rom :)
