### ISSUE TITLE
CM10.2 2013-10-13 Iyokan / Xperia Pro - Autobrightness not working

### ISSUE THREAD

**Issue by fred777** [LegacyXperia/local_manifests#106]
Auto brightness worked fine with CM10.1, but when I switched to cm-10.2_iyokan-LX-20131013-NIGHTLY it completely stopped working. I can enable / disable it, but doesn't make a difference and if I go to level setup, the current brightness sensor readout is not shown anymore...

**Comment by mikeNG** [comment]
Will be fixed in next build
