### ISSUE TITLE
Touchscreen have no function when I restart me Phone ...

### ISSUE THREAD

**Issue by DJChiller** [LegacyXperia/local_manifests#1065]
Hey,

I have a Problem with my Sony Ericsson Xperia Arc (LT15i) ...

I can install the mod and all works after the installation..... Now my problem, after I restart my Phone the Touchscreen don't have a function. I don't understand it .... Can anybody solve my problem?

Kind regards,
DJC

**Comment by Djfe** [comment]
does the touchscreen work in the recovery or in other roms?

**Comment by DJChiller** [comment]
Only in the Rom-Mod

**Comment by Djfe** [comment]
which mod?/what do you mean by mod?
