### ISSUE TITLE
[CM13][20160417][Urushi] Microphone/Speaker problem

### ISSUE THREAD

**Issue by Jodiethegreat** [LegacyXperia/local_manifests#1069]
i use line free call and detect this problem. also when receive call, me cant receive friends voice, i only hear my voice during call..
Thanks

**Comment by Jodiethegreat** [comment]
Error (.104)

**Comment by s0rl0v** [comment]
Normal calls work fine to me, Whatsapp works flawlessly... I don't think that's a LX problem. Maybe it's something to do with Line/LX compatibility.

**Comment by Jodiethegreat** [comment]
Hmmm..
Normal calls work fine to me too..
But this problem happening after using cm13..
Maybe i shold report to line too..because i dont understand with this..

I've been looking for this error on google..i found article that tell about sound policy,but i dont understand..haha

**Comment by wakpitunna** [comment]
Same with you, When I call with Line apk, its show text " Error microphone/speaker" and then closed. if I call with BBM apk, I can hear and see video my friend but he isn't hear my voice. But if I call with Whatsapp, everthing its okay and normal call its okay too. :-)

**Comment by wakpitunna** [comment]
Same with you, When I call with Line apk, its show text " Error microphone/speaker" and then closed. if I call with BBM apk, I can hear and see video my friend but he isn't hear my voice. But if I call with Whatsapp, everthing its okay and normal call its okay too. :-) | Smultron cm13
