### ISSUE TITLE
20131013 - increased RAM usage?

### ISSUE THREAD

**Issue by fred777** [LegacyXperia/local_manifests#107]
With CM10.1 2013819 which had "Dalvik optimization for low memory (~512mb) devices", the amount of free RAM (in settings/apps/increased a lot on my Xperia Pro. From 100..120 to about 120..140MB after reboot.

Now, with CM10.2 20131013, I get only around 80..100MB of free RAM after reboot.

**Comment by mikeNG** [comment]
Will probably be back in the next release.
I disabled some hardware acceleration that consumed RAM
