### ISSUE TITLE
zRam on urushi causes high cpu usage

### ISSUE THREAD

**Issue by agoston** [LegacyXperia/local_manifests#1072]
Hi,

I've installed the latest available image of legacyXperia urushi over the weekend.
Awesome thing you made!

The battery, which lasted for 2-3 days using sony's 4.0 android beta, lasted a mere 20 hours only however (leaving it asleep). I started digging in, and found a 128MB zRam in there. After adding a swapoff+zram reset to /system/etc/init.d/, the battery usage suddenly went back to previous levels.

I am unsure why zram would offer any advantage over simply allowing android to use that extra 128MB of ram. Even android low memory doc ( https://source.android.com/devices/tech/config/low-ram.html ) states the effects on memory is negligible but cpu usage would get very high.

Do you think it makes sense not to use zram on 512MB devices? Or, like altogether?

**Comment by koxelez** [comment]
I've been considering running my phone without zRam at all. It might make sense on phones with 1GB+ of RAM, but with out punny 512MB, the poor thing spends most of its time compressing memory, and crashing on OOM conditions
