### ISSUE TITLE
[CM11][Sources]Kernel not building

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#1084]
I want build kernel for my sx active with cm11 and i have an error
`lartz@KDEneon5:~/lx/android/system$ make -j4 bootimage
build/core/main.mk:46: ********************************************************************************
build/core/main.mk:47: \*  You are using version 4.1 of make.
build/core/main.mk:48: \*  Android is tested to build with versions 3.81, 3.82 and 4.0
build/core/main.mk:49: \*  see https://source.android.com/source/download.html
# build/core/main.mk:50: ********************************************************************************

PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=4.4.4
CM_VERSION=11-20160730-UNOFFICIAL-LegacyXperia-satsuma
TARGET_PRODUCT=cm_satsuma
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_BUILD_APPS=
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a-neon
TARGET_CPU_VARIANT=scorpion
HOST_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.4.0-31-generic-x86_64-with-neon-16.04-xenial
HOST_BUILD_TYPE=release
BUILD_ID=KTU84Q
# OUT_DIR=/home/lartz/lx/android/system/out

Checking build tools versions...
/home/lartz/lx/android/system/out/target/product/satsuma/obj/APPS/SignatureTest_intermediates
/home/lartz/lx/android/system/external/busybox/scripts/gcc-version.sh: line 11: cc: command not found
/home/lartz/lx/android/system/external/busybox/scripts/gcc-version.sh: line 11: cc: command not found
/home/lartz/lx/android/system/external/busybox/scripts/gcc-version.sh: line 11: cc: command not found
find: ‘src’: No such file or directory
build/core/copy_headers.mk:15: warning: overriding recipe for target '/home/lartz/lx/android/system/out/target/product/satsuma/obj/include/qcom/display/copybit.h'
build/core/copy_headers.mk:15: warning: ignoring old recipe for target '/home/lartz/lx/android/system/out/target/product/satsuma/obj/include/qcom/display/copybit.h'
build/core/copy_headers.mk:15: warning: overriding recipe for target '/home/lartz/lx/android/system/out/target/product/satsuma/obj/include/qcom/display/copybit_priv.h'
build/core/copy_headers.mk:15: warning: ignoring old recipe for target '/home/lartz/lx/android/system/out/target/product/satsuma/obj/include/qcom/display/copybit_priv.h'
find: ‘bootable/recovery/res-320’: No such file or directory
No private recovery resources for TARGET_DEVICE satsuma
mkdir -p /home/lartz/lx/android/system/out/target/product/satsuma/obj/KERNEL_OBJ
Export includes file: build/libs/host/Android.mk -- /home/lartz/lx/android/system/out/host/linux-x86/obj/STATIC_LIBRARIES/libhost_intermediates/export_includes
mkdir -p /home/lartz/lx/android/system/out/target/product/satsuma/system/lib/modules
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/libcurl/curl/curlbuild.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/libcurl/curl/curl.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/libcurl/curl/curlrules.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/libcurl/curl/curlver.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/libcurl/curl/easy.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/libcurl/curl/mprintf.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/libcurl/curl/multi.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/libcurl/curl/stdcheaders.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/libcurl/curl/typecheck-gcc.h
Header: /home/lartz/lx/android/system/out/host/linux-x86/obj/include/libexpat/expat.h
Header: /home/lartz/lx/android/system/out/host/linux-x86/obj/include/libexpat/expat_external.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/libexpat/expat.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/libexpat/expat_external.h
Header: /home/lartz/lx/android/system/out/host/linux-x86/obj/include/libpng/png.h
Header: /home/lartz/lx/android/system/out/host/linux-x86/obj/include/libpng/pngconf.h
Header: /home/lartz/lx/android/system/out/host/linux-x86/obj/include/libpng/pngusr.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/libpng/png.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/libpng/pngconf.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/libpng/pngusr.h
Header: /home/lartz/lx/android/system/out/host/linux-x86/obj/include/selinux/selinux.h
Header: /home/lartz/lx/android/system/out/host/linux-x86/obj/include/selinux/label.h
Header: /home/lartz/lx/android/system/out/host/linux-x86/obj/include/selinux/context.h
Header: /home/lartz/lx/android/system/out/host/linux-x86/obj/include/selinux/avc.h
Header: /home/lartz/lx/android/system/out/host/linux-x86/obj/include/selinux/android.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/selinux/selinux.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/selinux/label.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/selinux/context.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/selinux/avc.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/selinux/android.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/protobuf-c/include/google/protobuf-c//protobuf-c.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/protobuf-c/include/google/protobuf-c//protobuf-c-private.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/libsonivox/eas.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/libsonivox/eas_types.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/libsonivox/eas_reverb.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/libsonivox/jet.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/libsonivox/ARM_synth_constants_gnu.inc
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/libwpa_client/wpa_ctrl.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/qcom/display/gralloc_priv.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/qcom/display/copybit.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/qcom/display/copybit_priv.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/qcom/display/display_config.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/qcom/display/mdp_version.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/qcom/display/qdMetaData.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/qcom/display/IQService.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/qcom/display/IQClient.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/gps.utils//loc_log.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/gps.utils//loc_cfg.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/gps.utils//log_util.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/gps.utils//linked_list.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/gps.utils//msg_q.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/librpc/rpc/clnt.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/librpc/rpc/pmap_clnt.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/librpc/rpc/rpc.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/librpc/rpc/rpc_router_ioctl.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/librpc/rpc/svc.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/librpc/rpc/types.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/librpc/rpc/xdr.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/libloc_api-rpc/inc/loc_api_cb.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/libloc_api-rpc/inc/loc_api_common.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/libloc_api-rpc/inc/loc_api.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/libloc_api-rpc/inc/loc_api_fixup.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/libloc_api-rpc/inc/debug.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/libloc_api-rpc/inc/loc_apicb_appinit.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/libloc_api-rpc/inc/loc_api_rpc_glue.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/libloc_api-rpc/inc/loc_api_sync_call.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/mm-core/omxcore/OMX_Audio.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/mm-core/omxcore/OMX_Component.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/mm-core/omxcore/OMX_ContentPipe.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/mm-core/omxcore/OMX_Core.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/mm-core/omxcore/OMX_Image.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/mm-core/omxcore/OMX_Index.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/mm-core/omxcore/OMX_IVCommon.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/mm-core/omxcore/OMX_Other.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/mm-core/omxcore/OMX_QCOMExtns.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/mm-core/omxcore/OMX_Types.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/mm-core/omxcore/OMX_Video.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/mm-core/omxcore/qc_omx_common.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/mm-core/omxcore/qc_omx_component.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/mm-core/omxcore/qc_omx_msg.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/mm-core/omxcore/QOMX_AudioExtensions.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/mm-core/omxcore/QOMX_AudioIndexExtensions.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/mm-core/omxcore/OMX_CoreExt.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/mm-core/omxcore/QOMX_CoreExtensions.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/mm-core/omxcore/QOMX_FileFormatExtensions.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/mm-core/omxcore/QOMX_IVCommonExtensions.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/mm-core/omxcore/QOMX_SourceExtensions.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/mm-core/omxcore/QOMX_VideoExtensions.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/mm-core/omxcore/OMX_IndexExt.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/mm-core/omxcore/QOMX_StreamingExtensions.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/mm-core/omxcore/QCMediaDefs.h
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/mm-core/omxcore/QCMetaData.h
Import includes file: /home/lartz/lx/android/system/out/host/linux-x86/obj/STATIC_LIBRARIES/libhost_intermediates/import_includes
Header: /home/lartz/lx/android/system/out/target/product/satsuma/obj/include/mm-video/DivxDrmDecrypt/DivXDrmDecrypt.h
Export includes file: build/tools/acp/Android.mk -- /home/lartz/lx/android/system/out/host/linux-x86/obj/EXECUTABLES/acp_intermediates/export_includes
Import includes file: /home/lartz/lx/android/system/out/host/linux-x86/obj/EXECUTABLES/mkbootfs_intermediates/import_includes
Export includes file: system/core/cpio/Android.mk -- /home/lartz/lx/android/system/out/host/linux-x86/obj/EXECUTABLES/mkbootfs_intermediates/export_includes
Export includes file: external/libsepol/Android.mk -- /home/lartz/lx/android/system/out/host/linux-x86/obj/STATIC_LIBRARIES/libsepol_intermediates/export_includes
Yacc: checkpolicy <= external/checkpolicy/policy_parse.y
prebuilts/misc/linux-x86/bison/bison -d -v -o /home/lartz/lx/android/system/out/host/linux-x86/obj/EXECUTABLES/checkpolicy_intermediates/policy_parse.cpp external/checkpolicy/policy_parse.y
Lex: checkpolicy <= external/checkpolicy/policy_scan.l
Import includes file: /home/lartz/lx/android/system/out/host/linux-x86/obj/STATIC_LIBRARIES/libsepol_intermediates/import_includes
/bin/bash: flex: command not found
build/core/binary.mk:396: recipe for target '/home/lartz/lx/android/system/out/host/linux-x86/obj/EXECUTABLES/checkpolicy_intermediates/policy_scan.cpp' failed
make: **\* [/home/lartz/lx/android/system/out/host/linux-x86/obj/EXECUTABLES/checkpolicy_intermediates/policy_scan.cpp] Error 127
make: **\* Waiting for unfinished jobs....
touch /home/lartz/lx/android/system/out/host/linux-x86/obj/EXECUTABLES/checkpolicy_intermediates/policy_parse.hpp
echo '#ifndef 'policy_parse_h > /home/lartz/lx/android/system/out/host/linux-x86/obj/EXECUTABLES/checkpolicy_intermediates/policy_parse.h
echo '#define 'policy_parse_h >> /home/lartz/lx/android/system/out/host/linux-x86/obj/EXECUTABLES/checkpolicy_intermediates/policy_parse.h
cat /home/lartz/lx/android/system/out/host/linux-x86/obj/EXECUTABLES/checkpolicy_intermediates/policy_parse.hpp >> /home/lartz/lx/android/system/out/host/linux-x86/obj/EXECUTABLES/checkpolicy_intermediates/policy_parse.h
echo '#endif' >> /home/lartz/lx/android/system/out/host/linux-x86/obj/EXECUTABLES/checkpolicy_intermediates/policy_parse.h
rm -f /home/lartz/lx/android/system/out/host/linux-x86/obj/EXECUTABLES/checkpolicy_intermediates/policy_parse.hpp
lartz@KDEneon5:~/lx/android/system$ `

@mikeNG , @MardonHH

**Comment by mikeNG** [comment]
The error is pretty obvious, 2 lines after you execute your command.

**Comment by mikeNG** [comment]
Actually your error is "/bin/bash: flex: command not found". You should install flex.

**Comment by ghost** [comment]
Thanks, @mikeNG
