### ISSUE TITLE
[CM11][IYOKAN][20160417] Back and Menu button not working

### ISSUE THREAD

**Issue by ohharsad** [LegacyXperia/local_manifests#1091]
I just flashed using build in kernel and open gapp,
only home button are working..

**Comment by s0rl0v** [comment]
Did you wipe the data partition?

**Comment by ohharsad** [comment]
@okeer before install zip, i wipe data first..

**Comment by s0rl0v** [comment]
Ok, that's good. And system partition?

**Comment by ohharsad** [comment]
@okeer okay the step i do, flash boot.img in the zip using xperia flasher, then wipe everything include system, install LX then install openGapp.. on setup wizard AOSP keyboard crash..

**Comment by s0rl0v** [comment]
Seems so. Flashed this build on my urushi - apps get killed instantly.
You may try to disable setup wizard via editing build.prop and then pushing it using adb.
1. Extract build.prop from zip;
2. add "ro.setupwizard.enterprise_mode=0" to the end;
3. adb root;
4. adb remount
5. adb push build.prop /system/build.prop
6. adb shell chmod 644 /system/build.prop
7. adb reboot.
It MAY help but as I can see this build is broken and I suggest you to use the previous one.

**Comment by ohharsad** [comment]
seem it problem with my phone maybe, i already try 2 LX different previous rom and kernel, still same.. i try find way to make it work.. now running ICS stock rom back..

**Comment by s0rl0v** [comment]
Did you try to flash only the ROM? Without gapps?

**Comment by ohharsad** [comment]
Worked by flashing CM11-20150811 ROM and kernel
flash without gapp..
now i trying different gapp..

**Comment by s0rl0v** [comment]
Check these [GAPPS packaged by Mardon](http://forum.xda-developers.com/android/apps-games/hdpi-google-apps-4-4-4-upd-20150513-t3108049)

**Comment by ohharsad** [comment]
sorry for the late reply, i already use PA gapp.. now my phone working properly.. 
Thanks for the Help.. :)
