### ISSUE TITLE
Slowdown with airplane mode on.

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#110]
When airplane mode is enabled phone slows down to a crawl.
https://dl.dropboxusercontent.com/u/40426219/airplanemodeondmesg.txt dmesg
https://dl.dropboxusercontent.com/u/40426219/airplanemodeon.txt logcat

**Comment by JovieBrett** [comment]
I'm having the same problem on my Smultron with the latest CM10.2 nightly Build102413.

**Comment by mid-kid** [comment]
Same thing on haida CM10.2 NIGHTLY-20131024.

**Comment by mikeNG** [comment]
Yes the recently merged telephony changes in cm have created a mess. I'll see if there is something I can do.

**Comment by JovieBrett** [comment]
@mikeNG, another issue wherein when I hold & press the Network Mode in quick tile settings, Network Mode settings force closes. Here's the logcat https://www.dropbox.com/s/lpen7o1yxgz30rn/NetworkModeSettings.txt

Additional logcat for the Airplane Mode bug https://www.dropbox.com/s/qy3gvea3qtpj23v/AirplaneMode.txt

**Comment by ghost** [comment]
Fixed in new build.
