### ISSUE TITLE
no responses to posted issues?

### ISSUE THREAD

**Issue by boldcompany** [LegacyXperia/local_manifests#1107]
Thanks to the developers of LegacyXperia for producing an excellent way to salvage devices that might otherwise head for the rubbish heap. Excellent work.

Question: I have noticed that the most recently posted questions have received no response whatsoever. At this point, is the LegacyXperia project abandoned? Or is there just a lull?

**Comment by niks255** [comment]
It's not abandoned. We read all these issues, but don't always respond to them.

**Comment by boldcompany** [comment]
Thank you, niks255. I appreciate your swift reply. Just wanted to check before I spent time posting issues.
