### ISSUE TITLE
[cm13-20161109] [smultron] Can't install root

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#1116]
I can't install Magisk/SuperSU because boot.img is not detected.
Also I can't really set root in developer settings because it doesn't have "Apps" or "Apps and ADB" options.

**Comment by mishaor** [comment]
That's a "feature" of SEMC's bootloader when working with non-stock versions ROMs that aren't based on stock ROM (LegacyXperia CM/AOSP is the example). When you trying to encrypt/factory reset/reboot to recovery or Fastboot (called bootloader mode, but don't be fooled: it's not bootloader, it's Fastboot. Flashmode is the real bootloader mode (used to fully flash the stock firmware (but it doesn't locks bootloader for you))), it just normally reboots the phone.

**Comment by nussbaumer** [comment]
flash https://mirrorbits.lineageos.org/su/addonsu-13.0-arm-signed.zip

**Comment by ghost** [comment]
@nussbaumer
Thanks! It worked like a charm. :+1:
