### ISSUE TITLE
LT15-anzu roms too large for /system partition

### ISSUE THREAD

**Issue by tiwsii** [LegacyXperia/local_manifests#116]
When using only the latest official sony firmware for lt15 (4.1.B.0.587 that is) and not the ones for lt18-arc s, partitioning is this:
/system  312.5MB
/data       380.0MB
/cache    101.5MB

So installing a 10.2 rom leaves about 64MB free but that doesn't fit gapps. If someone installs gapps cwm doesn't give any warning that there is no space so this can cause issues. e.g. wifi calibration fails to write a firmware file so wifi doesn't work.
I'm guessing most people don't have this issue because they have flashed lt18 firmwares to lt15

These are probably related:
https://github.com/LegacyXperia/local_manifests/issues/101
https://github.com/LegacyXperia/local_manifests/issues/95

**Comment by mikeNG** [comment]
Interesting, thanks for noticing this. So in order to remove the vendor partition & increase /system space :
LT15i (Arc) users need to flash LT18i (Arc S) ftf
MT15i (Neo) users need to flash MT11i (Neo V) ftf

I will update my xda threads
