### ISSUE TITLE
[CM10.2]{Smultron} Wifi not working with the latest build release! (Build110113)

### ISSUE THREAD

**Issue by JovieBrett** [LegacyXperia/local_manifests#117]
Rechecked and flashed the correct kernel, still Wifi is not really working :(

**Comment by aeoeue** [comment]
on mango working after calibration.
Further information here:
http://forum.xda-developers.com/showpost.php?p=47008262&postcount=68

**Comment by Klami** [comment]
on anzu arc S working after calibration too

**Comment by ghost** [comment]
Logs taken when trying to enable wifi:
https://dl.dropboxusercontent.com/u/40426219/wifi.txt logcat
https://dl.dropboxusercontent.com/u/40426219/wifidmesg.txt dmesg
After calibration everything is fine for me too.

**Comment by JovieBrett** [comment]
Found Elroysk's solution on the thread, sorry! 
Thank you @aeoeue, @Klami  and @pypcz ^_^
Fixed! Closed.
