### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by KiranAK47** [LegacyXperia/local_manifests#118]
All bugs in CM10.2-20131001 onwards 
1. For some reason after using the phone for a while the ram gets clogged with only just 2 apps running and slows the phone down.
2. Status bar the alignment quick panel logo gets pushed out of the screen if any changes in clock display.
All the above bug appears after using the phone for a while.

**Comment by ch61** [comment]
Hi Thanks for the awesome work!
I wonder why it is only in every other version that I can get the wifi to work.
cm-10.2_mango-LX-20131101-NIGHTLY does NOT
cm-10.2_mango-LX-20131024-NIGHTLY WORKS
cm-10.2_mango-LX-20131013-NIGHTLY does NOT
cm-10.2_mango-LX-20131001-NIGHTLY WORKS
Thanks in advance
Regards
Claus

**Comment by ghost** [comment]
Every bug should be reported separately with description, logs and/or screenshots. Build number and phone model is needed as well. I suggest you close this issue and make a new ones for every bug separately with logs and everything as said above.
