### ISSUE TITLE
[CM10.2][Anzu] Proccess com.android.phone has stopped

### ISSUE THREAD

**Issue by zalazdi** [LegacyXperia/local_manifests#120]
I have 20131001. When I'm updating to newer version, this error appears on boot. Can't use the phone. I tested all never versions (10-13, 10-24, 11-01) and it's the same.

**Comment by louniszenad** [comment]
I have the same issue on iyokan

**Comment by djey47** [comment]
Please, post logs. Nothing can be done without them.

**Comment by zalazdi** [comment]
How can i get the logs, if i cant run a phone?

**Comment by mikeNG** [comment]
Use the included kernel

**Comment by zalazdi** [comment]
Ok, i flashed boot.img from zip and now it's works. I thought that kernel wasn't changed. Thanks for help ;)
