### ISSUE TITLE
CM 10.2 : Anju : USB Mass Storage is not working from 20131001 release.

### ISSUE THREAD

**Issue by ksranjith786** [LegacyXperia/local_manifests#121]
In my Xperia Arc S, USB Mass storage is not working, "Turn on USB storage" keeps loading until screen goes off.

**Comment by ghost** [comment]
Just tested and it's working on my Arc s.

**Comment by ksranjith786** [comment]
Please let me know how shall i debug it. Its not working from past 3 builds. 
Is there any workaround for this ?

**Comment by ghost** [comment]
Wipe everything and flash newest build. Remember to use kernel from zip. If your problem is fixed then close this issue.

**Comment by ksranjith786** [comment]
I have been doing the same steps when i update my build. Even though I couldnt able to connect as USB storage.

**Comment by mikeNG** [comment]
It's working fine here, nothing changed in the latest builds that could break usb

**Comment by ksranjith786** [comment]
Though I have tried connecting to many Laptops, I couldnt able to connect as USB storage.
Is there any way for you guys to debug from logging/any meachanism. 
Any work around for this ? so that you can confirm this issue ?

**Comment by ksranjith786** [comment]
Can anybody who uses Xperia Arc S phone users confirm me the workingness of USB Mass Storage Mode ?
