### ISSUE TITLE
[10.2] WiFi Hotspot issue

### ISSUE THREAD

**Issue by duxxyuk** [LegacyXperia/local_manifests#124]
WiFi hotspot worked in cm-10.2_urushi-LX-20131024-NIGHTLY but not it cm-10.2_urushi-LX-20131101-NIGHTLY.

The wifi from the phone appears to configure itself correctly but from other devices I can not get an IP address... 

nb. I ran the wifical.sh in order to get the wifi in classic AP client mode working.

Thank you enormously for the terrific work you're doing on our old phones :)

**Comment by a17r** [comment]
Same here, WiFi client tries to connect to the phone but fails with 'bad password', still happening on cm-10.2_urushi-LX-20131108-NIGHTLY. Not sure how to best attach the dmesg.log of the phone here; just pasting as comment?

**Comment by mikeNG** [comment]
@a17r use pastebin.com

**Comment by a17r** [comment]
Here it is then: http://pastebin.com/xnGtLSgX

**Comment by ghost** [comment]
You've got a load of:

wl12xx: WARNING Unable to flush all TX buffers, timed out (timeout 500 ms

in the log. That seems to mean that the wifi chipset is in an odd state.
I was seeing high battery drain and interruptions.
The 20131112 build fixed it. I did a full factory reset before I installed the build.

**Comment by mikeNG** [comment]
Might be fixed again in next build

**Comment by a17r** [comment]
mikeNG, do you plan another 10.2 build or are you focused entirely on 11?

**Comment by mikeNG** [comment]
I plan to make a final build and stop 10.1 and 10.2 so I can focus on 11 and focus on the new kernel I'm going to bring. My priority is to fix the display issues in the new kernel and then I'll look into wifi one more time.

**Comment by a17r** [comment]
This is fixed now with cm-10.2_urushi-LX-20131204-RELEASE, I could connect to the Ray just fine. Stability testing can't be done properly where I am right now, but so far it looks like a superb final release.

**Comment by mikeNG** [comment]
So I am closing this for now
