### ISSUE TITLE
WIFI doesn,t work on xperia mini pro mango..

### ISSUE THREAD

**Issue by nauman0313** [LegacyXperia/local_manifests#126]
i flashed the required rom android 4.3.1 and its kernel, but i can not able to turn on wifi ,,, what can i do,, please help,,, otherwise i will return to its stable 4.0 rom.. with sad,,,, because i love legacy xperia,,

**Comment by ghost** [comment]
Calibration is broken.
Works fine once you do it manually.

http://forum.xda-developers.com/showpost.php?p=47008262&postcount=68

#119

**Comment by mikeNG** [comment]
Works on latest release
