### ISSUE TITLE
[10.2] Battery drain - 20131101

### ISSUE THREAD

**Issue by Natureknight** [LegacyXperia/local_manifests#128]
Im experiencing a huge battery drains while MOBILE DATA is turned on. Im never turn off mobile data and anything in settings->battery seems right. After a few days of investigeting the battery drain, i've just made a test:

2 hours on those settings (my default ones):
-internet location on
-gps satellite location off
-mobile data on
-auto sync off
-hotword detection off

Result:
 i left the phone for 2 hours without touching it (no calls, messages, nothing)
After 2 hours i was drained from 78% to 72% of my battery (-3%/h)

Then i tried with this settings:
-mobile data off
-internet location off
-gps sattelite location on

And charged my battery back to 78%

Result: 
After 2 more hours without any activity: still 78% battery! 

Xperia Arc S (anzu) - cm10.2 20131101 NIGHTLY

EDIT: I think implementation of feature such like "Stamina mode" (turn off mobile data when deep sleep) will be great also

**Comment by ghost** [comment]
Can you install BetterBatteryStats and find out what the top kernel wakelock is when you are seeing the high drain.

**Comment by Natureknight** [comment]
Ye, i think was DATA5 but I'll check and tell you exaclty what you need :) Im turning off my mobile data for now to save battery and turn on only when i need it ... not so confortable but :|

**Comment by mikeNG** [comment]
Any news on this?

**Comment by GX3** [comment]
I have the same problem on smultron LX-20131112-NIGHTLY
when 3g on battery drains in 6 hours (half the time I was used to on stock SE rom)
now 57% in 3h18m

wakelock detector for rates 17% awake
2.28H deep sleep

![screenshot_2013-11-28-11-30-56](https://f.cloud.github.com/assets/6057974/1639037/4cca0232-5818-11e3-9edf-b4de75b034f2.png)
![screenshot_2013-11-28-11-30-50](https://f.cloud.github.com/assets/6057974/1639046/6df53238-5818-11e3-9f16-77694068a2fe.png)

looks like the 3g hardware module consumes too much battery (6MB transfered this morning, but I installed an app from play store)

**Comment by GX3** [comment]
tried to disable and enable gps

now battery is really fine issue is not there anymore it seems to be somewhat related to that
