### ISSUE TITLE
SE Coconut (Live with Walkman WT19i) CM Logo rotating

### ISSUE THREAD

**Issue by AnasAzeem007** [LegacyXperia/local_manifests#130]
I just installed the Nightlies (cm-10.2_coconut-LX-20130809-NIGHTLY.zip)  from (http://legacyxperia.basketbuild.com/download.php?file=main/cm10.2/coconut/nightlies/cm-10.2_coconut-LX-20130809-NIGHTLY.zip). The ROM is successfully installed but when I rebooted my device, it never get pass from the  CyanogenMode Logo. I've installed this ROM using fastboot.

Any help. Should I downgrade or what?

**Comment by mid-kid** [comment]
How do you want to install a rom with fastboot?
Usually, you install the kernel (boot.img) with fastboot, reboot to CWM, wipe everything, and install the zip.
[The forum thread](http://forum.xda-developers.com/showthread.php?t=2397233) says exactly the same.

Sounds like PEBKAC to me.

**Comment by AnasAzeem007** [comment]
Yeah! I'm new to it that's why the terms used maybe inappropriate.
But I did the same thing first and then re-installed it (by rebooting it to CWM) but it was no help.

**Comment by mikeNG** [comment]
You should have no problems if you follow the requirements & installation steps _exactly_

**Comment by AnasAzeem007** [comment]
I did it and this time its fine. The only thing I didn't do is installing the gapps package. And its working fine.

One more thing the camera app isn't working, it gives some weird output.
