### ISSUE TITLE
hallon wifi no upload speed to external IP, normal upload speed to internal IP

### ISSUE THREAD

**Issue by cagali** [LegacyXperia/local_manifests#131]
Using cm-10.2_hallon-LX-20131108-NIGHTLY.zip. Still no upload speed thru wifi to external IP, e.g. use speedtest.net app. However file upload thru ftp to an internal IP works normally.

**Comment by ghost** [comment]
I can use speedtest.net app without any problems. I'm on Arc S so maybe this bug doesn't affect my phone or maybe there is something wrong with your internet connection.

**Comment by mikeNG** [comment]
I just tried speedtest and it works without any problem.

**Comment by mikeNG** [comment]
Also, no logs provided = issue closed

**Comment by cagali** [comment]
Sorry for no logs. Will attach next time. :)
