### ISSUE TITLE
hallon mt15i WIFI no upload speed to external IP after a few seconds, normal upload speed to internal IP.

### ISSUE THREAD

**Issue by cagali** [LegacyXperia/local_manifests#132]
Close if this is the "the kernel still has it's 0,01mbps upload speed issue" on XDA thread.

Using cm-10.2_hallon-LX-20131108-NIGHTLY.zip. 
Still no upload speed thru WIFI to external IP after a few seconds, e.g. use speedtest.net app. 
However file upload thru ftp to an internal IP works normally. 
Speedtest on another PC in the same network have normal result.

Speedtest.net result: 
DL 8.58
UL 0.07
Ping 13

log: http://pastebin.com/xQfApVEX

**Comment by mikeNG** [comment]
Same as #97
Wifi drops like hell
