### ISSUE TITLE
Camera Problem

### ISSUE THREAD

**Issue by Pops** [LegacyXperia/local_manifests#134]
Why the camera writes mono instead of stereo sound?

**Comment by ghost** [comment]
It's in stereo since yesterday. You can close this issue now.

**Comment by mikeNG** [comment]
@pypcz have you tried this and can confirm it's working?

**Comment by ghost** [comment]
Files are saved with stereo sound but I can't test channel separation because my headphones are dead and I can't hear much difference with my cheap speakers.

**Comment by ghost** [comment]
I've done some testing and: 
-secondary mic is definitely working
-sound in both channels is slightly different (tested with spectrogram)
-secondary mic is more sensitive
Hope it's helpful.

**Comment by mikeNG** [comment]
Ok, I'm closing this. secondary mic wasn't even working before
