### ISSUE TITLE
[10.2] Battery drain on mobile data or wifi

### ISSUE THREAD

**Issue by WolfAyron** [LegacyXperia/local_manifests#139]
I'm facing two problems with my coconut.
Unlocked the bootloader 2 days ago, installed cm10.2 20131108nightly that day, and today the latest, 20131112nightly
The battery drains so quick like never before when Mobie Data or WiFi is turned on.

**Comment by axcs** [comment]
I take this topic to report my battery problem.
In LWW (coconut) and using cm-10.2_coconut-LX-20131108-NIGHTLY.zip and the in-built kernel, Battery drain very fast.

-internet location on
-gps satellite location off
-gps sattelite location on

-mobile data off
-auto sync off
-12 sms per day
- without long calls (2 minute call)
- wifi internet (30 minutes Active)

And have lost the battery too fast, with android 2.3 and android 4.0 battery could stand for 24 hours with the same usage. Charging at the 13:00 and 21:00 and the battery is already at 14%.

May try to analyze or fix the problem somehow?

In BetterBatteryStats the RILJ apppers

Img:
![2388768](https://f.cloud.github.com/assets/5928308/1530846/780f8804-4c56-11e3-95eb-44041f50e4c5.png)

**Comment by mikeNG** [comment]
No logs provided
