### ISSUE TITLE
[10.2] TTS stopped working

### ISSUE THREAD

**Issue by DanielMalmgren** [LegacyXperia/local_manifests#140]
Text-to-speach isn't working for me lately. I first thought Googles tts upgrade (from 2.1.0 to 2.4.3) was the problem, but I restored the old version from backup and it still doesn't work. So I don't know if this is a ROM problem? Logcat at http://pastebin.ca/2475849, hope anyone understands it better than me. During that logcat I pushed "listen to example" in the tts settings twice.

Oh, and about the "Synthesis request for unsupported locale: eng-gbr" in the log, I've tried both brittish and american, none of them works.

**Comment by ghost** [comment]
Google TTS is working great on my Arc S.

**Comment by DanielMalmgren** [comment]
@pypcz What version of Google TTS? Btw, forgot to mention, I'm on Ray.

Btw I also tried changing system language to english (I'm normally using swedish) in case it would make any difference, but it didn't.

**Comment by ghost** [comment]
Updated 2.4.3 version. No problems whatsoever.

**Comment by DanielMalmgren** [comment]
Strange. Well, let's hope someone here is able to interpret my logcat. Either my google-fu is weak today or the errors I get are very unusual...

**Comment by mikeNG** [comment]
Have you tried a clean install?

**Comment by DanielMalmgren** [comment]
Clean install of entire ROM? No. Seems like a little overkill, but I guess that'd be a last resort. Since it seems I'm alone with this problem I guess it's something wrongly configured in my phone.

**Comment by mikeNG** [comment]
Yes. Maybe take a full backup and make a clean install to see if it's working so you can return easily to your previous state.
