### ISSUE TITLE
Stereo recording not working

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#141]
20131112 says it fixed this, however I was unable to get it working. What method are you using for testing? I tried both ant recorder and recforge, both of which claim to support stereo recording, but couldn't get them to work.

**Comment by ghost** [comment]
New build introduced a fix for a second microphone but nobody said that stereo recording is working. Things are kind of broken right now but I feel like we can expect a real stereo recording in a near future.

**Comment by mikeNG** [comment]
Any news on this? I'd like to fix it.

**Comment by ghost** [comment]
I can't really test it because video recording in CM11 is broken. If you want me to test it with some apps or whatever then just ask.

**Comment by mikeNG** [comment]
Ok then better wait for next build

**Comment by ghost** [comment]
kindly tell me, when is the next release of CM11.

**Comment by ghost** [comment]
Sound works when recording video from the lower mic on smultron (I assume this is the primary mic). No sound from the upper mic. This is on a build from 20131227 including cherry #56361.

**Comment by ghost** [comment]
I'm on CM11 build 01-14. Stereo recording still isn't working. I've tested with EZ Voice Recorder Pro, which apart from offering stereo recording, also lets you choose the mic source and lets you set all the features related to voice recording such as autogain, noise and echo cancelation, and "tuning" (so you can get unprocessed audio, as in when google voiec search is trying to recognize your voice) I wasn't able to determine if, when I changed from front to back mic, the recording source actually changed or not; I didn't notice any real change in the audio either way. If this is a feature that only works in certain apps, that's fine, but someone will have to tell me what app to test with.

**Comment by mikeNG** [comment]
Can someone test stock rom and see how the 2 mics behave? The current kernel & audio sources we have allow using only one microphone for recording. Most devices use the main mic for calls and the secondary mic for camera/audio recording.

**Comment by thck** [comment]
Yes, I can switch to stock ICS on hallon and test it. Just tell me, which activities should I try (switching microphones in rec app settings and stereo recording?) and which logs do you need.

**Comment by mikeNG** [comment]
Should be fixed in latest builds
