### ISSUE TITLE
[CM10.2]{Smultron} Bluetooth QuickTile settings force close!

### ISSUE THREAD

**Issue by JovieBrett** [LegacyXperia/local_manifests#142]
Latest Nightly Build111213 on Xperia Mini.
Whenever I try to hold and press the Bluetooth on Quick Tile settings, the Bluetooth settings force closes.
Here's the catlog: http://goo.gl/4DRuWA

**Comment by bhanucbs-13** [comment]
Same problem in Xperia Pro

**Comment by bhanucbs-13** [comment]
Its only open when bluetooth is on. Otherwise froce close.
And also force close when go direct into bluetooth by setting menu

**Comment by ghost** [comment]
I can confirm that it doesn't work on Arc S too.

**Comment by gederickson** [comment]
same problem on Xperia Ray
Only open when bluetooth is On

**Comment by Institor666** [comment]
Confirm this on wt19i (LwW)

**Comment by Diago27** [comment]
I found a similar bug for Bluetooth FC on iyokan in latest LX CM 10.2-20131112-Nightly. Logs are at the link ... 
https://gist.github.com/Diago27/7484182
