### ISSUE TITLE
Primary microphone does not work in a camera app.

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#143]
Sound is recorded only with a secondary microphone (how the hell it menages to record videos with 2 channel sound is beyond me). When calling or recording sound with other apps that are using primary mic everything is all right so it seems like it's a camera only bug.

**Comment by ghost** [comment]
It would be nice if somebody could test it and report below. Just cover 1st and then 2nd microphone with your finger while recording something.

**Comment by mikeNG** [comment]
Merged in #141
