### ISSUE TITLE
Anzu cm-10.2_anzu-LX-20131112-NIGHTLY Bluetooth error

### ISSUE THREAD

**Issue by SSVENOM** [LegacyXperia/local_manifests#144]
I install this rom today. When I try to open bluetooth, its giving an error.

My Phone is Xperia Arc LT15i

Have a nice day...

**Comment by Diago27** [comment]
I found a similar bug for Bluetooth FC on iyokan in latest LX CM 10.2-20131112-Nightly. Logs are at the link ... 
https://gist.github.com/Diago27/7484182

**Comment by ghost** [comment]
Read before posting https://github.com/LegacyXperia/local_manifests/issues/142

**Comment by mikeNG** [comment]
Duplicate
