### ISSUE TITLE
repaired cm-10.2_anzu-LX-20131112-NIGHTLY ( Lock Screen )

### ISSUE THREAD

**Issue by luismytronic** [LegacyXperia/local_manifests#145]
seems to be no VAT on goods estava not the location tucked sorry and thanks

**Comment by ghost** [comment]
So you are saying that weather on lock screen doesn't work because it cannot connect to yahoo servers right? I'm too tired to test it, maybe tomorrow.

**Comment by mikeNG** [comment]
Only english please
