### ISSUE TITLE
[10.2] Status bar quick settings icon alignment

### ISSUE THREAD

**Issue by KiranAK47** [LegacyXperia/local_manifests#146]
When ever a change is made in the clock display style ie. AM or PM as normal or large the alignment of the quick setting icon is as shown in the image below.
this bug is in all the builds of legacy xperia CM10.1 and cm10.2 roms.
The pic was taken from cm_anzu-LX-20130908-RELEASE.zip build.
I have noticed the same in all the other builds too. Please fix.
The issue doesn't show immediately but after using it for a while.
![20110113_101909](https://f.cloud.github.com/assets/5837545/1556708/9cea4acc-4ee7-11e3-8a6b-a328f59c6f6c.jpg)

**Comment by ghost** [comment]
You can take screenshots by pressing power and volume down at the same time...

**Comment by KiranAK47** [comment]
Thankyou very much pypcz.
Here is the exact problem that i have taken snaps.
Clock style- none, normal and small respectively.
![screenshot_2013-11-17-12-11-35](https://f.cloud.github.com/assets/5837545/1557964/cc793994-4f53-11e3-99a5-dd7c7f0aa090.png)
![screenshot_2013-11-17-12-10-35](https://f.cloud.github.com/assets/5837545/1557965/d635f76a-4f53-11e3-9fb2-c73c1921ad72.png)
![screenshot_2013-11-17-12-11-01](https://f.cloud.github.com/assets/5837545/1557966/e461669e-4f53-11e3-8a9c-e3c6391e6c14.png)

**Comment by ghost** [comment]
It's the same on my phone. To reproduce go to Settings\Date & time and uncheck 24-hour format option then go to Settings\Interface\Status bar and change AM\PM style.

**Comment by JovieBrett** [comment]
It's the same issue I also encountered with my Smultron since the first build of CM10.1. But someone said that's only an issue to all MDPI layouts, I don't know why it's happening on HDPI too.

**Comment by KiranAK47** [comment]
so is there a permanent fix for that ? because i find it very annoying !

**Comment by mikeNG** [comment]
No know solutions, this bug exists since 10.1

**Comment by mikeNG** [comment]
Only temp solution is to disable am/pm

**Comment by mikeNG** [comment]
Cannot be fixed. Simplest solution is to disable AM/PM (I don't think it's that hard to understand if the time is PM or AM that you have to look at your phone...)
