### ISSUE TITLE
[10.2] Permanently rotated call screen after call-in while hw keyboard opened

### ISSUE THREAD

**Issue by piotrwie** [LegacyXperia/local_manifests#148]
(mango, lxp131112)
[screenshot_2013-11-17-16-54-51](https://f.cloud.github.com/assets/2567691/1558724/cb227716-4fa5-11e3-8bce-4e077e004abf.png)
steps:
1. open hw keyboard (i had terminal app opened in foreground, but i'm unsure if it is important)
2. make someone call your number

expect:
the regular call in window appears

actual:
i got a completely displaced (permanently!) dial in window, i have a screenshot for reference (like the functions buttons in two columns on right, only few digits of caller are available and almost no place for name).

unfortunately this is permanent, eg after closing hw keyboard the same wrong call (both out and in) window is shown in both horizontal and vertical configs...

for me temporary solution is to disable the call screen rotation at all.

most important is to see full callers name and number in this  dialog. the rest is less important.

**Comment by tomasSK** [comment]
i have same problem on iyokan

**Comment by mikeNG** [comment]
does it exist in older builds?

**Comment by piotrwie** [comment]
The lxp131112 is first cm10.2 build which I flashed. On 10.1 I didn't notice the problem.
I can try one or two other builds today if I have time... shall I also flash kernel in case I try the downgraded nighties?

BTW, the 'broken' way dial window appears somehow fixes after some time. Maybe after I get dialin with kb folded?
Now I think the broken layout somehow toggles.
Maybe it's because some layout manager decides that the contents of all icons (speaker/mute/digit pad/others) is too big to fit in one vertical column?
FYI: The unfolded kb rotates the dial activity window. For older releases (10.1) i'm almost sure that everything was rotated 90 degs: both graphics and layout (to match the kb orientation).
There's a chance that this is related to the concept of 10.2 (visible in lockscreen), where only the icons (content) get rotated, but not layout. I.e in lockscreen the unlock/lock sliders still have the same direction no matter if display is rotated or not (along shorter screen side)

Maybe the icons need to be lower for mango? 

Michael Bestas notifications@github.com napisał(a):

**Comment by piotrwie** [comment]
Now I can't reproduce the problem.
Michael, I think we need to wait to get proper reproduction sequence.
Now when I call my phone from any number, the dial-in window is totally 'broken'. See attachment (the caller's image becomes a strange 'background' instead of having the picture consistent).
But this may be by design.... I'm unsure.
![screenshot_2013-11-18-07-57-22_b](https://f.cloud.github.com/assets/2567691/1560945/7bcc1a30-501f-11e3-9bcd-fab0d16738ef.PNG)
(edit: the picture is 'anonymised' with black boxes on my name and number)

**Comment by mikeNG** [comment]
hmm maybe take some logcats but I don't know if I will be able to do something about this... it seems to be a global CM bug and not device specific... it's just that there are not many phones with hardware keyboards to reproduce this issue

**Comment by mikeNG** [comment]
you should flash the kernel too if you downgrade builds

**Comment by mikeNG** [comment]
Any news on this?

**Comment by piotrwie** [comment]
No news. Im using 10.2 mainly and couldnt repr. i'll try later playing with bigger fonts.

**Comment by mikeNG** [comment]
So this can be closed?

**Comment by piotrwie** [comment]
Hello,
Please do close if noone else observed it. I couldn't repr it after submitting.
