### ISSUE TITLE
(mango, lxp131112) auto screen brightness, lowest vale setting not respected

### ISSUE THREAD

**Issue by piotrwie** [LegacyXperia/local_manifests#149]
steps: 
1. set non default params for lowest (0 lux) light conditions (for example 25%)
2. use phone in such light conditions

expexted:
brightness level set in step 1 active

actual:
10% (judged by my 'naked eye') present regardless of level.

you can tell the difference because during setting percentage for any level the display is permanently set to dragged value of slider.
UPDATE:
I managed to repair problem by temporarily disabling auto adjust. and moving slider and then enabling auto adj back. probably its problem of leftovers from 10.1 (data partition wasnt formatted).

**Comment by ghost** [comment]
You'll see all sorts of problems if you don't clear the data partition and move between ROMS based on 10.1 and 10.2.
