### ISSUE TITLE
[10.2] FC on adding caller's phone number to existing contact (while search for existing contact)

### ISSUE THREAD

**Issue by piotrwie** [LegacyXperia/local_manifests#151]
(mango, lxp131112)
steps:
1. make someone call your number (make sure number is not attached to any contact
2. answer or reject the call
3. look at list of recent calls
4. try to add number to existing contact 
5. go into the 'find contact' field in the displayed window
6. press any letters.

expected:
the list is narrowed down along with new letters pressed

actual:
only first letter is accepted, than FC after second key input.

screenshot attached of moment 'just before FC' (first letter is already there)
(dump shows some cursor problems?)
Reproducible on xperia keyboard and regular AOSP keyboard and HW keyboard.
![screenshot_2013-11-18-08-09-56_b](https://f.cloud.github.com/assets/2567691/1560962/c17e36ca-5020-11e3-8afe-e268c68318d0.PNG)

I can send dump if needed (I don't know how to attach txt file to the issue)

**Comment by ghost** [comment]
This isn't LegacyXperia specific. I can reproduce it on other kit running a CM 10.2 nightly.

**Comment by mikeNG** [comment]
provide a logcat when the crash happens

**Comment by ghost** [comment]
http://pastebin.com/ST9U85BW

**Comment by piotrwie** [comment]
http://pastebin.com/QPFhQSFE
Hello,
There you'll find my paste. I didnt know how to use the uploads, hope its fine this way.

stashcroft notifications@github.com napisał(a):

**Comment by djey47** [comment]
Bug still here on 20131204 build, haida.

Same log as provided one.

**Comment by mikeNG** [comment]
try latest RC1 build

**Comment by djey47** [comment]
Looks like it has been solved so far. Can't reproduce on 20131216 build.

Good job :+1:
