### ISSUE TITLE
how to enable 720p recording on xperia neo?

### ISSUE THREAD

**Issue by taha001** [LegacyXperia/local_manifests#152]
Dear developer..
720p recording is disabled on cm10.2 due to ram issues.
but the ram problem is effectively getting solved by using ram xpander and link2sd.
Applications such as apollo music player etc can b linked to sd card and ram can be use for the 720p purpose.kindly please help in enabling 720p on xperia neo............:)

**Comment by mikeNG** [comment]
we have already talked so many times about this. 720p performance on android 4.1+ roms is crap, records at average 10-12 fps and not worth the ram (about 22mb).
