### ISSUE TITLE
Auto activate 3G on tethering

### ISSUE THREAD

**Issue by erseco** [LegacyXperia/local_manifests#154]
A lot of people only activate 2G for better battery performance (12h with 3G, 35h with 2G in Xperia Mini st15i

But will be interesting an option to auto activate/deactivate 3G when usb and wifi tethering is activated ¿is this possible?

Thanks!

**Comment by mikeNG** [comment]
Not possible, implementation will be complicated. Also, cm-10.2 is feature-frozen so no new features.
