### ISSUE TITLE
HDMI does not work

### ISSUE THREAD

**Issue by mikeNG** [LegacyXperia/local_manifests#157]

**Comment by L3RAT** [comment]
Hi! If someone is interested in kernel implementation of HDMI, I have created a list of files needed to consider, when thinking about it:

https://www.dropbox.com/s/vsxsjx7ftbm47e9/Semc_Anzu_HDMI.doc?dl=0

Have fun!

**Comment by L3RAT** [comment]
http://forum.xda-developers.com/showpost.php?p=59953839&postcount=168
