### ISSUE TITLE
Keyboard backlight blinking together with low battery light.

### ISSUE THREAD

**Issue by mikeNG** [LegacyXperia/local_manifests#160]

**Comment by tomasSK** [comment]
and also with all LED notifications....not only battery light.

**Comment by A-n-D** [comment]
And also when touch on screen it turns keyboard backlight on in lx Rom,, in stock rom, only pressing any key turns keyboard's backlight, n touching screen doesn't do it.

**Comment by mikeNG** [comment]
Should be fixed on latest build
