### ISSUE TITLE
Frequently not charging after connecting to charger

### ISSUE THREAD

**Issue by mikeNG** [LegacyXperia/local_manifests#163]
Very often when I connect the charger, the phone shows "Charging" but the battery is actually not charging. Even it seems like it is discharging quite fast, no matter the Phone is switched on or off. Sometimes the Phone even does not show "Charging". The problem occurs when I use the original Sony or universal power adapter + USB cable. I have never had this problem with single-purpose power adapter with "integrated" micro USB cable.

**Comment by mikeNG** [comment]
mikeNG commented a month ago 
If it was easy I would have fixed it already. The battery code is too complex for me to understand. We either choose the old 2.6.32 code that causes hard reboots on 100% charge or we choose the new code that has some issues like this.

I prefer the second one for obvious reasons.
If someone wants, you can take a look at the code. I have too many bugs to solve and I'm all alone, nobody seems interested anymore for 2011 xperias.

**Comment by mikeNG** [comment]
mikeNG commented 23 days ago 
Wait for the next build, there are some changes that might affect charging with non-standard chargers.

 Itchythefirst commented a day ago 
Unfortunately the problem is still there :-( But it is really weird. I am able to charge the phone using original SE power adapter with 1.5$ noname cable but i am definitelly not able to charge the phone using the very same power adapter and the original SE power cable (http://images.esellerpro.com/2477/I/477/456/lrgscaleEC-1.jpg). Also i can charge my GF's Xperia Active(stock ROM) with absolutely no problem using the original SE power adapter and the original SE cable ;-(

**Comment by ghost** [comment]
The same where with kernel 3.4, but work with kernel 3.0

**Comment by jh71** [comment]
Same issue here, Iyokan on the last nighly, after a complete wipe (!) the phone finally wanted to recharge. I tried with all possible combinations of original and other cables and chargers.

**Comment by mikeNG** [comment]
cm-10.1 is EOL now so I'm closing the issue
