### ISSUE TITLE
Pattern unlock too small

### ISSUE THREAD

**Issue by mikeNG** [LegacyXperia/local_manifests#164]
The pattern unlock is a lot smaller than usual (coming from CM10) on my Xperia Mini. No matter what size I set it to (3x3, 4x4, 5x5), it still only takes up about 2/3 of the unlock screen width, and half the height. This is the case in both cm10.1-20130815 and cm10.1-20130822. It sounds like this might be a known ("framework") issue, but I wanted to post it here just to make sure it's known about:

http://forum.xda-developers.com/showpost.php?p=42802295&postcount=2

**Comment by mikeNG** [comment]
mspacek commented 3 months ago
IMO, there's lots of space, it's just being used somewhat inefficiently. Maybe the clock could be moved up? Maybe the carrier and emergency call text could be put on the same line? There's also some excess space between the user message and the clock. Wish I'd taken a screenshot in CM10 for comparison...

![screenshot_2013-08-26-07-01-11](https://f.cloud.github.com/assets/799467/1026131/79b30cda-0e58-11e3-85b8-42c61e3b38be.png)

**Comment by mikeNG** [comment]
vulpesvelox commented 3 months ago
Here are screenshots from X8 running CM10.

![screenshot_2013-08-26-19-09-28](https://f.cloud.github.com/assets/3000578/1027559/8e89d33a-0e73-11e3-9a5a-c88095187edd.png)
![screenshot_2013-08-26-19-09-58](https://f.cloud.github.com/assets/3000578/1027561/932b0382-0e73-11e3-876b-0443b0a17ce9.png)

**Comment by di72nn** [comment]
There are fixes for cm-10.1 and cm-10.2 (sw320dp-mdpi).
Somebody please test cm-10.1.

Before: http://i.imgur.com/Udr3PTZ.png ( http://i.imgur.com/oShn0so.png )
After: http://i.imgur.com/QUd1bgp.png ( http://i.imgur.com/qKqqKJ0.png )

**Comment by zweif** [comment]
In frameworks/base/packages/Keyguard/res/values-sw320dp/dimens.xml I commented out keyguard_security_height. After that the pattern was a bit larger. Also date wasn't showing anymore. I don't think that's a good solution, but maybe a point to start (modify that value?).

Edit: removed pictures. Before-pictures can be found here: https://github.com/LegacyXperia/local_manifests/issues/164#issuecomment-63168982

**Comment by mikeNG** [comment]
@zweif if I'm not wrong, this affects the normal keyguard too and will hide date/weather/etc. I don't think this is the right solution.

**Comment by zweif** [comment]
Oh you're right. I didn't think of that. Should I remove that comment?

**Comment by mikeNG** [comment]
You can leave it for reference. I see some space could be saved on the bottom text and on top of the clock. Maybe you can take a look at that

**Comment by zweif** [comment]
I think moving up the clock would affect all lockscreen widgets and I don't know how it would look like. With this emergency_carrier_area at the bottom, I don't really know what to do.

**Comment by di72nn** [comment]
@zweif you can check out the changes I made - saved some space on top of the clock (looks like my "before" screenshot was taken after that part, oops) and moved the carrier text a bit lower. I guess you can move clock even more upwards and make emergency area thinner (maybe expand to full width if necessary; anyway I don't think anyone using it much).
P.S. Pardon my English.

**Comment by zweif** [comment]
I tried to change the cLock widget. I set a negative top margin (-20 dp) to clock_panel (files appwidget.xml and appwidget_small.xml). So we could increase this keyguard_security_height value I think.
Other effects to cLock widget is, that it's lifted in general, and on my mdpi screen in landscape layout and 4x4 gridsize in Trebuchet, I can see complete numbers. But in portrait I can see the upper edge of date. (I like that in general)
![screenshot_2014-11-14-18-13-49](https://cloud.githubusercontent.com/assets/6281450/5050348/dbff6544-6c2d-11e4-8894-2ff02975631d.png)

Edit: It also lifts analog clock partially out of this view. But I think this can be changed.

**Comment by di72nn** [comment]
@zweif try to set android:paddingTop in layout-port/keyguard_widget_pager.xml to 0.

**Comment by zweif** [comment]
@di72nn That would affect all locsreen widgets? I think there should be a padding between them and status bar.

**Comment by zweif** [comment]
![screenshot_2014-11-15-01-55-56](https://cloud.githubusercontent.com/assets/6281450/5055823/fb1d9468-6c6a-11e4-8208-994e80fd4db4.png)![screenshot_2014-11-15-01-56-10](https://cloud.githubusercontent.com/assets/6281450/5055825/00f6a4ec-6c6b-11e4-9940-a2b192ec8901.png)
![screenshot_2014-11-15-01-55-42](https://cloud.githubusercontent.com/assets/6281450/5055828/0b76e508-6c6b-11e4-8273-50cd2d58eda8.png)![screenshot_2014-11-15-01-55-36](https://cloud.githubusercontent.com/assets/6281450/5055830/1036484a-6c6b-11e4-9411-8023b92fe345.png)

What I've done:
-lift LockClock digital clock (affects cLock widget everywhere - don't know if we can do that)
-set widget pager top padding to 0, maybe we shouldn't do that for all screens
-set keyguard_security_height to... 340 dp?

I think it can be optimized, but the first impression is not that bad.

Edit: But now there's a huge empty space between clock and keyguard selector if I disable pattern unlock. It's a difficult problem.

**Comment by zweif** [comment]
A new attempt without changing widget pager and security height:

![screenshot_2014-11-13-10-47-49](https://cloud.githubusercontent.com/assets/6281450/5027667/e55752c0-6b31-11e4-87e3-d74da64a8bb7.png)![screenshot_2014-11-15-12-04-33](https://cloud.githubusercontent.com/assets/6281450/5057426/afc48dbe-6cbf-11e4-9c38-fc15084488b0.png)
![screenshot_2014-11-13-13-22-17](https://cloud.githubusercontent.com/assets/6281450/5028198/897116ce-6b38-11e4-882c-1837e2a0526c.png)![screenshot_2014-11-15-11-49-15](https://cloud.githubusercontent.com/assets/6281450/5057429/b8646688-6cbf-11e4-9c39-7a303ca50262.png)

I left this LockClock change, but that's not necessary. The circles are a bit cut off on top and bottom, especcialy when using more than 3x3 dots.

**Comment by zweif** [comment]
Any feedback on this?

**Comment by zweif** [comment]
I pushed a commit to gerrit:
http://review.cyanogenmod.org/#/c/78962/

**Comment by mikeNG** [comment]
Oops I missed this, will give it a try soon
