### ISSUE TITLE
SD card unexpected unmounts

### ISSUE THREAD

**Issue by mikeNG** [LegacyXperia/local_manifests#165]
First I thought something was wrong with my SD card, but it seems to be fine, working good with other devices... and as some other users have experienced this problem as well it might be ROM problem. Here I attach last kernel log, hope it helps

http://sdrv.ms/17SnYkQ

**Comment by mikeNG** [comment]
aidenn commented 25 days ago 
Hi,
I've been having the same problem with my Mango since I switched to a 32 GB SDHC from SanDisk (class 4). It was very frequent in releases before September (sorry for not being specific, I remember seeing mike's first comment in this thread and thinking "finally!" ;). Then I experimented with ext4, which had its own DRM problems (but no unexpected unmounts) and now I went back to FAT32.

The incidence of these unexpected card disappearances and auto-remounting is much, much rarer now, I've only seen it happen once yesterday (previously it happened all the time), however I'd like to have a completely bug-free phone, so I have to ask - is there hope of this issue disappearing completely, or do I have to change the card to get a stable experience?

**Comment by hdhoang** [comment]
I occasionally have SD card suddenly unmounted too, and more frequently when there's heavy IO going on. In CM 10 it caused a ROM reboot, then the phone runs without SD card until I fully reboot it. In CM 11 (from the first build) the situation is better because the card is automatically remounted.

I'm trying to repro this with logcat, which should be easier now that I download and listen to music a lot on this card.

**Comment by hdhoang** [comment]
I have triggered the bug twice now by listening to a particular file. Both times, the card isn't remounted. 

Here are logcat https://www.dropbox.com/s/yd0yyknnwklm5jq/sd_umount_logcat.txt and dmesg https://www.dropbox.com/s/x5xwv22ldhad3b5/sd_umount_dmesg.txt Search for /Music/, that's where I started listening to the song.

**Comment by hdhoang** [comment]
https://www.dropbox.com/s/ftzbr6oz4rkophf/sd_remounted_logcat.txt 
https://www.dropbox.com/s/2g0qwtgst14rjsa/sd_remounted_dmesg.txt

I had another case this morning. the card is remounted right away and usable, but apps moved there FC with class-not-found exception.

logcat starts from headset connected, dmesg starts at 9858

**Comment by mikeNG** [comment]
cm-10.1 is EOL now so I'm closing the issue
