### ISSUE TITLE
[10.1-10.2] Key backlight remains on after boot

### ISSUE THREAD

**Issue by mikeNG** [LegacyXperia/local_manifests#167]
I happen to be when you start the phone (without touching anything), once you rip and charge all the screen turns off as it should. but the keys are lit button to go back and the advanced menu.
remain lit until you turn on the screen again this is a mistake or is it?

**Comment by mikeNG** [comment]
proparham commented 2 months ago 
For me it only happens when device boots up and when i turn the screen on it will b fine until next boot.

 sz4bi commented 2 months ago 
confirmed, the same happens here, but it is a minor issue, except your phone restarts in your pocket and drain battery

 mikeNG commented 7 days ago 
I might have found a fix for this. will be included in next 10.2 build to test, if it's working I will include it in final 10.1 build too.

**Comment by mikeNG** [comment]
@proparham @sz4bi Any news on this?

**Comment by proparham** [comment]
@mikeNG i'm on 10.2 and i think its fixed .my phone's battery is dead . after getting a replacement i will check again

**Comment by mikeNG** [comment]
should be fixed in all versions
