### ISSUE TITLE
[10.1-10.2] hw keyboard remains lit when folded

### ISSUE THREAD

**Issue by mikeNG** [LegacyXperia/local_manifests#168]
i could not isolate exact steps but frequently when disconnectin phone from supply, the hw kb keys remain lit when phone is closed. this is not well visible at daylight, but in dark (need to see it through the narrow gap from side of phone).
happens sporadic, however battery drain from this can be much higher....
when i open kb and close it, issue is frequently fixed, but not always. sometimes i need to reconnect supply.
2 participants    

 mikeNG commented 7 days ago 
I might have found a fix for this. will be included in next 10.2 build to test, if it's working I will include it in final 10.1 build too.

 piotrwie commented 7 days ago 
Michael, I'm unsure of the problem in 10.2. I'd give it a 'sporadic' tag. In 10.2 I've never noticed it, but to be honest I wasn't looking for it, either... It just didnt shout at me. I know that in 10.1 there were some settings to change the hw keyboard lighting intensity. But adjusting them (especially setting to 100%) didn't solve the problem back then...
BTW, is it possible to port the settings to 10.2, along with the nice 'rampup' and 'rampdown' of the screen backlight intensity? It's cosmetics, but at least I didnt see any direct problems with it back on 10.1...
Although I'd give the algorithm a small 'kick': when the phone is out of sleep (you get it out of pocket) and immediately switch it on, it should reset it's averaging tail. It looks like the algo is working even though the phone is in sleep. And when you pick it in bright place, for first good few secs you need to guess what's on the display because it's 'acquiring' the high value samples and slowly accomodates... i didn't check the code. These are my guesses... but the observation is valid. The screen adjusted very slowly in 10.1 (which is tunable by settings, I know), but in the specific event of wakeup, the phone should settle backlight much faster. Probably quickest solution is to cut the averaging at this point.

Michael Bestas notifications@github.com napisał(a):
…

 mikeNG commented 7 days ago 
Backlight settings are present in 10.2 too.
About auto brightness, I have never looked into it because the code is simply better than cm9 & cm10 that ALS was not working. I don't have the time to look into this more, there are more important bugs to solve first

**Comment by mikeNG** [comment]
@piotrwie Any news on this?

**Comment by piotrwie** [comment]
no news, i'm trying to look at it sporadically, could not find it on 10.2. i didnt see it on both december releases for 10.2.

**Comment by mikeNG** [comment]
Should be fixed then.

**Comment by asusm930** [comment]
Mike, this issue is happening in Latest Release CM10.1 for Xperia Mini Pro. Was there a fix? May I know the details of it so I can have a look and tinker around? thank you!
