### ISSUE TITLE
(cm11.0) apps on the second partition

### ISSUE THREAD

**Issue by Apocalypse2** [LegacyXperia/local_manifests#169]
I've Created a second partition on my sd for apps .. When I pass the apps can not be run, quits unexpectedly ... how to fix that?

**Comment by JovieBrett** [comment]
It is also happening in my Smultron with CM11 Alpha Build 11/27.

**Comment by ghost** [comment]
hello, same here (Smultron, build 11/27). Tried various apps to fix permissions, unsuccessfully.

---

Edit : sorry for my incompetence, no send report button appeared, no how-to-send-report found on http://legacyxperia.github.io/... I just wanted to indicate that this was not an isolated bug.
I won't bore you any longer.
BTW, thank you to all the team for their great work

/\
|
|

**Comment by mikeNG** [comment]
"same here" isn't helping. with no logs I'm no magician to know what happens

**Comment by azakosath** [comment]
Here is the logcat after trying to launch 4 apps linked to 2nd partition (ext4) via Link2SD:
https://gist.github.com/azakosath/7717868

the device is coconut

I tried to install again Link2SD after a data wipe and a fresh ROM installation, it links the new apps to the second partition normally, but they give FCs when trying to launch. I hope you find time to have a look into this.

Thnx Mike...

**Comment by mikeNG** [comment]
```
E/dalvikvm(9395): Dex cache directory isn't writable: /data/dalvik-cache
```

**Comment by azakosath** [comment]
OK, changing the permissions to "writable by others" did the work.
Thanx again Mike.

**Comment by JovieBrett** [comment]
@mikeNG do you know what is MemTrack Module? because I notice alot of error shows about "Memtrack module"
Anyway apps don't force close if I did not include "Application File" from linking using Link2SD. Linking Dalvik-cache and library files works fine for apps.
Here's the log: http://goo.gl/GyQhSp

EDIT
Thank you Mike! it worked on meh Smultron :-)

**Comment by mikeNG** [comment]
So this is probably a script issue, maybe it needs update for 4.4. Better contact the author and give him this fix

**Comment by mikeNG** [comment]
@JovieBrett Memtrack is used in combination with ION, it tracks and gains back unused portions of memory. It can't be used with our current pmem kernel

**Comment by JovieBrett** [comment]
I mailed the developer of Link2SD, hope he fix it asap.
Thank you Mike.

**Comment by JovieBrett** [comment]
It seems that the dev of Link2SD has been fixed this issue. He'll probably release a new update soon.

**Comment by mikeNG** [comment]
I'm closing the issue since it's not a rom bug
