### ISSUE TITLE
Normal Camera and Focul PicSphere Not working

### ISSUE THREAD

**Issue by godofdeath95** [LegacyXperia/local_manifests#17]
The title says it all, this is on the Sony Ericsson Xperia Arc S running cm10.2 unofficial nightly build
I would provide a logcat, but I'm not sure how to do that? :'(

**Comment by avinashrocks1990** [comment]
camera works just the camera preview is buggy 
it's already mentioned in the status of cm 10.2 rom
close the thread

**Comment by mikeNG** [comment]
I will leave this open so there won't be any more duplicate bugs about camera opened.

**Comment by godofdeath95** [comment]
@avinashrocks1990 stock cm10.2 camera app works, just the preview that doesn't, however the picsphere in focul actually does not work.

**Comment by avinashrocks1990** [comment]
i know focal is in alpha stage 
i would better if you report it on cm bug tracker 
but as far as i know team cm knows about this bug

**Comment by n1kolaa** [comment]
@avinashrocks1990  how you think to report it on cm bugtrucker if we lose offical suport on jellYbean 4.1

**Comment by avinashrocks1990** [comment]
this is a general bug every device is facing this problem with focal so i think you can report
