### ISSUE TITLE
cm-11.0-20131127-LX-NIGHTLY-anzu(Improvement list)

### ISSUE THREAD

**Issue by KiranAK47** [LegacyXperia/local_manifests#172]
1.Lock screen layout shadow is a little buggy.
2.Notification bar isn't transparent.
3.Quick access ribbon disappears after clicking the quick settings icon.
4.Cuts in audio playback.

**Comment by mikeNG** [comment]
1. provide screenshot
2. isn't it transparent when you are in home screen or in the launcher?
3. CM upstream bug
4. user specific bug

Please file seperate bugs for seperate issues or update existing ones if they already exist
