### ISSUE TITLE
(cm11.0) Freezing base internet app

### ISSUE THREAD

**Issue by Xematos** [LegacyXperia/local_manifests#174]
Base internet app freez for a second while scrolling a website. Same for Opera.

**Comment by zxcvbnnm** [comment]
The same problem here. I try with stock internet app and Dolphin.

**Comment by FernandoUFS** [comment]
The same problem here [2]

**Comment by LillyWho** [comment]
List of working Browsers [coconut]

Android Browser: works but with freeze and lags sometimes
Firefox: white screen, seems that is doesn't start
Firefox beta: same
Chrome: works but sometimes freeze and empty site after using another app

**Comment by mikeNG** [comment]
Duplicate of #181
