### ISSUE TITLE
(cm11) Installation of gapps causes hang

### ISSUE THREAD

**Issue by tomasz89** [LegacyXperia/local_manifests#175]
I have an Xperia Arc S and have installed the following:

cm-11.0-20131127-LX-NIGHTLY-anzu.zip
gapps-kk-20131119-lite.zip

I have wiped everything except my SD card on installation.

On its on, CM11 works fine. On installation of the gapps, I can't get to the home screen. Nothing appears on the desktop, no icons. I can access settings through the pull down menu from the top, things appear to generally work in there..

**Comment by babuilyas** [comment]
while installing gapps it seems halted and it took 3-5 minutes.

**Comment by tomasz89** [comment]
Despite having an Arc S, flashing back to stock LT18i seemed to fix the problem.
http://forum.xda-developers.com/showthread.php?p=44596318#post44596318
