### ISSUE TITLE
CM 11.0 : Anju : Clear button is missing in Background apps screen.

### ISSUE THREAD

**Issue by ksranjith786** [LegacyXperia/local_manifests#176]
Long key press on  "Home" button gives background apps, in which "Close" icon is missing. Now, we have to manually clear each app individually.

Is it a bug or FAD ?

**Comment by ghost** [comment]
It's a CM feature and it's not available yet. Wait for new builds.

**Comment by ksranjith786** [comment]
Also "USB Connection settings" in Settings -> Storage.. is not available.

**Comment by mikeNG** [comment]
Fixed
