### ISSUE TITLE
[11.0] bug in preview in photo editor

### ISSUE THREAD

**Issue by aleksandar-stefanovic** [LegacyXperia/local_manifests#178]
-build20131128-smultron
While previewing original photo (by pressing the original picture), the preview only goes to the half of the picture, and when you go over the half, it swaps positions of the original and edited.
![screenshot_2013-11-28-11-42-52](https://f.cloud.github.com/assets/6058082/1639126/1f1aaf56-581a-11e3-9377-138c985625ba.png)
![screenshot_2013-11-28-11-42-55](https://f.cloud.github.com/assets/6058082/1639128/218eadd2-581a-11e3-9298-ef48bfb5a582.png)

**Comment by mikeNG** [comment]
This is not a bug, it's the intended behaviour
