### ISSUE TITLE
K-9 font/graphical glitches.

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#182]
I'm not sure if this is LX issue or not but I think it's worth a look.
https://dl.dropboxusercontent.com/u/40426219/LOGZ/k9glitches.txt
![screenshot_2013-11-28-11-02-45](https://f.cloud.github.com/assets/5565504/1639369/c21e9f56-581e-11e3-8449-682ad9bd70a3.png)

**Comment by JovieBrett** [comment]
Mike said this is an issue related to graphics driver since CM10.

**Comment by ghost** [comment]
It never happened for me on CM 10, 10.1 or 10.2. so it's definitely fixable.

**Comment by JovieBrett** [comment]
It just occurs randomly.

**Comment by ghost** [comment]
It's happening every time I want to read an email. I know that it could happen from time to time in a launcher or something but now it's really frequent and annoying. Maybe it's K-9 issue or maybe not.

**Comment by mikeNG** [comment]
It's adreno libs bug, we can't fix it unless we use other libs, which don't exist.

**Comment by ghost** [comment]
So the only thing we can do is to hope that some adreno 205 device will get kitkat update? Shit sucks.

**Comment by mikeNG** [comment]
No, we can get new libs working by rewriting the kernel, making it support ION instead of PMEM and then we can get rid of the legacy display/media/audio repositories and use the shiny new CM repos. That will lead to non-working camera in the beginning but it will extend the life of the devices. I have already started slowly working on this, but it will take time.

**Comment by mikeNG** [comment]
if we try to use newer libs with the current kernel, they simply don't work because they aren't compatible with PMEM allocator

**Comment by ghost** [comment]
Yeah, I heard about this new kernel you are working on and that's some high level wizardry to me. I wish I could help you with this but I was always too lazy to learn programming. When I think about this I regret it a little but then I'm lazy again. Thanks and good luck.
