### ISSUE TITLE
(CM 11)[coconut]No transparent status bar

### ISSUE THREAD

**Issue by nivdeep** [LegacyXperia/local_manifests#183]
I think the status bar is not transparent and no action for menu button in app drawer and couldn't change storage mode and terrible freeze in web view.I am using CM VERSION 11-20131127-UNOFFICIAL-COCONUT and BUILD DATE NOV27 11:57:00 EST 2013,BUILD NUMBER cm_coconut-userdebug 4.4KRT16S710677fb00 test-keys

**Comment by tee-yankov** [comment]
Change ro.config.low_ram=true to false in your build.prop. This might affect RAM management, though.

**Comment by nivdeep** [comment]
What is that for ?

**Comment by nefelim4ag** [comment]
Ebough comment ro.config.low_ram=true => #ro.config.low_ram=true

**Comment by nivdeep** [comment]
Still not transparent not even translucent

**Comment by azakosath** [comment]
I guess is transparent only on launcher, check out my coconut's homescreen
![screenshot_2013-12-03-14-58-18](https://f.cloud.github.com/assets/5717336/1663775/49201fe8-5c1b-11e3-8d5b-5f169234ace2.png)

I suppose you did save the file and reboot after editing.... Didn't you???

**Comment by mikeNG** [comment]
will be fixed in next build

**Comment by nivdeep** [comment]
I didn't notice that i didn't saved it,but now i got it working after saving it.
Thank u guys for noticing the problem and responding to it,
MIKE THANK U FOR THE TREAT BUT V R EXPECTING FOR BETTER TASTE IN THE NEXT VERSION.
