### ISSUE TITLE
CM 11 Faceunlock

### ISSUE THREAD

**Issue by bhanucbs-13** [LegacyXperia/local_manifests#184]
Faceunlock is missing in iyokan

**Comment by LillyWho** [comment]
It's the same on coconut. I think it's not a bug, it is just not integrated into the gapps package. It is only the lite version.

**Comment by azakosath** [comment]
It is integrated in the lite version, you just need to make some room in system folder. So, delete some apps you don't need, or move them to data and flash gapps over again.
