### ISSUE TITLE
CM 11.0 if enable ART, phone not boot

### ISSUE THREAD

**Issue by nefelim4ag** [LegacyXperia/local_manifests#186]
1. Setting
2. Developer options
3. Select runtime - ART
4. Press power button
5. Reboot

Phone still booting forever

**Comment by poloth** [comment]
+1

**Comment by lobanten** [comment]
+2

**Comment by virtrue** [comment]
+3

**Comment by mikeNG** [comment]
"+50000" isn't helping. with no logs I'm no magician to know what happens

**Comment by virtrue** [comment]
i don't know how to find log when i can't boot my phone

**Comment by HiyakeIchirou** [comment]
Google it. Don't just say "don't know" and expect answers from other users.

**Comment by Divefire** [comment]
From http://www.androidpolice.com/2013/11/06/meet-art-part-1-the-new-super-fast-android-runtime-google-has-been-working-on-in-secret-for-over-2-years-debuts-in-kitkat/ 

"Activating it requires a restart to switch from libdvm.so to libart.so, but be prepared to wait about 10 minutes on the first boot-up while your installed apps are prepared for the new runtime. Warning: Do not try this with the Paranoid Android (or other AOSP) build right now. There is an incompatibility with the current gapps package that causes rapid crashing, making the interface unusable."

Sounds like a bug for all AOSP builds right now, best to leave it alone for the moment?

**Comment by virtrue** [comment]
I flashed back to 4.3,but i find some one use ARC have same problem,his log(from XDA):11-27 22:47:12.887: E/dex2oat(1090): Failed to write dex file /system/framework/framework.jar to /cache/dalvik-cache/system@framework@boot.art@classes.oat: No space left on device
I think it is useful

**Comment by JovieBrett** [comment]
As Google states, ART is still in BETA mode so expect some things that might not work at all. Even if ART will be able to boot on our devices, there are alot of apps will cause incompatibility errors with it. As I tried on my N7, half of the Google apps are force closing, pretty unusable -_-

**Comment by mikeNG** [comment]
/cache partition is running out of space that's why art is failing.

**Comment by LillyWho** [comment]
Same on coconut
Would wiping the /cache partition in cwm fix the problem? I will try it out when i've got time.

**Comment by virtrue** [comment]
wipe cache may come back to dalvik,try to wiping dalvik cache.

**Comment by virtrue** [comment]
Can  link2sd solve this problem?but link2sd may not working in 4.4

**Comment by nefelim4ag** [comment]
Virtrue, Link2sd today get update to 4.4 and good working with app before updating.

MikeNG can you turn on art on your Xperia 2011(if you have phone)?
I can try turn on my device and after filing, try do back up and try catch logs from backup.
Which logs need to help and where to send logs?

**Comment by taha001** [comment]
guys...i have hallon and it reboots in dalvik mode even after rebooting in art mode

**Comment by virtrue** [comment]
someone on chinese bbs said add dalvik.vm.dexopt-data-only=1  in bulid.prop may solve this problem,who has time to try?I only have time in weeken

**Comment by JovieBrett** [comment]
@virtrue I'll try!

**Comment by JovieBrett** [comment]
@virtrue WHOA! IT WORKED! @mikeNG it worked! Try it!
EDIT
Almost all of the apps force close including system apps...
EDIT
Checked storage capacity via Link2SD and here's what I found
It seems that the ART is stored in internal memory because internal memory is full.

**Comment by nefelim4ag** [comment]
virtrue, i try this, satsuma still boot forever)

**Comment by virtrue** [comment]
my sk17i worked on ART,1.uninstall all  app,2.add dalvik.vm.dexopt-data-only=1 to build.prop 3.change to ART

**Comment by o2droid** [comment]
It works on 20131210 release.

**Comment by proshekycheung** [comment]
Hello GitHub,
Sorry about that my english is poor

**Comment by proshekycheung** [comment]
I have a non rooted Samsung SM-G5308W,I changed /system/library/libdvm.so to libart.so ,and the phone just reboot forever.

**Comment by TomTomcrafter001** [comment]
i think this is not for Samsung phones.
