### ISSUE TITLE
CM11-Anzu-MX Player Force Close issue

### ISSUE THREAD

**Issue by Natureknight** [LegacyXperia/local_manifests#188]
When i try to play video from MX Player, it force closes the app.

**Comment by uunium** [comment]
Have same problem. (Anzu)
there is some logs think it`s maked right, and will help.
https://app.box.com/s/obtl9p12s9les7yqd1f8

**Comment by amishmm** [comment]
Just to help developer. MX players works in coconut.

So possibly this bug is only for Anzu.

Did you try clear cache and data for MX player?

**Comment by ghost** [comment]
What format and resolution were files you all tried to play? Is there any chance that you are using outdated MX Player app? I'm on Arc S and video playback is working flawlessly.

**Comment by uunium** [comment]
Using last version of MX palyer, cashe was cleared and app reinstaled. Trying *.avi files 640x352.

**Comment by Natureknight** [comment]
Tried with latest version of MX player + mx player codev v7 and both, software and hardware decoders FC when play a video. Tried to delete cache and try again - the same FCs

**Comment by ghost** [comment]
I can play low res avi files without any problems but 720p videos are causing MX Player to fc.

**Comment by padishah** [comment]
It can playback videos with hw decoding(only limited formats). But it crashes if you try to play using sw decoder.
 Latest cm11 alpha on iyokan

**Comment by karandpr** [comment]
For S/W decoding it's most probably ffmpeg error which need to be resolved by MX Player side .
