### ISSUE TITLE
[11.0] "end the call" button, during incoming call

### ISSUE THREAD

**Issue by sandumarizoi** [LegacyXperia/local_manifests#196]
Version :.20131127-coconut

during incoming call, visible button "end the call" at the background , like in active call

**Comment by uunium** [comment]
Have same problem on anzu, but this is not critical. And have another one issuse cant make normal contact photo from vertical photo. Screenshots on box :
https://app.box.com/s/d9n8xy847vjjmdwmlpmc
https://app.box.com/s/mncn0rd4rvablxn1gc09

**Comment by mikeNG** [comment]
Any news on latest build?

**Comment by uunium** [comment]
Contact photo is normal now, but end call button is visible on Nightly 20131225 cm11.
