### ISSUE TITLE
[CM11][urushi] No USB storage menu.

### ISSUE THREAD

**Issue by johnnytifosi** [LegacyXperia/local_manifests#198]
The first time the phone is connected to PC a menu pops up with ticks for MTP and PTP. If both of them are unchecked, then you can't get your phone recognised by the PC because there is no option in storage settings to choose USB storage mode.

**Comment by VladislavKoldobskiy** [comment]
Aaand we suddenly found "Charge only" USB mode! That's actually useful :P
By the way, USB Mass Storage mode is buggy/deprecated, so it has been removed.

**Comment by Diaz1999** [comment]
![screenshot_2013-12-06-16-42-13](https://f.cloud.github.com/assets/4738738/1691109/08f20764-5e5b-11e3-87c1-1ae492e8a0ef.png)

Where's the "Charge Only" USB Mode? There's no "Charge Only" USB Mode in my coconut

**Comment by VladislavKoldobskiy** [comment]
Uncheck both options and you'll get it :P
I'd call this a feature rather than the bug...

**Comment by mikeNG** [comment]
Will be fixed in next build
