### ISSUE TITLE
[CM11][Anzu] problem with wechat

### ISSUE THREAD

**Issue by dani010** [LegacyXperia/local_manifests#202]
in wechat program we i want to shake or find people near by suddenly wechat close and i have to open it again

**Comment by ghost** [comment]
Citation from LX CM11.0 thread:
"Logs are needed (logcat/dmesg/last_kmsg), not just "got FC" or "+1" useless replies."

**Comment by mikeNG** [comment]
No logs provided.

**Comment by dani010** [comment]
where can i find logs ?
