### ISSUE TITLE
cm11 [20131128] [mini pro]

### ISSUE THREAD

**Issue by cburbara** [LegacyXperia/local_manifests#204]
I am very happy that you have released kitkat for mini pro :3
I found some bug that I hope you solve in the next update!
-distortion to lock / unlock the screen
-a strange bug when I take a panoramic photo
just need more stability in the games is very good, and you could improve the battery life.

PS: I saw the screenshots of the post from XDA, and the notification bar is transparent! but in SK17 rom it is not! It's black! could you make it transparent?

**Comment by Apocalypse2** [comment]
so that the notification bar is transparent you have to delete the "ro.config.low_ram = true" command in build.prop

**Comment by LillyWho** [comment]
could you maybe a screenshot from the panorama bug?

**Comment by linusseelinger** [comment]
The lock screen problem looks very much like a problem with the small screen size. The same happens on the SIM PIN screen, the buttons are cut off (yet working)

**Comment by saeedk** [comment]
not work google now & voice search

**Comment by mikeNG** [comment]
File seperate bugs for seperate issues
