### ISSUE TITLE
[11.0] camera button don't launch camera app

### ISSUE THREAD

**Issue by sandumarizoi** [LegacyXperia/local_manifests#206]
Version :.20131127-coconut

camera button don't launch camera app on long press

**Comment by Klami** [comment]
anzu (lt18i) too

**Comment by poloth** [comment]
Haida (mt11i) too

**Comment by aeoeue** [comment]
mango too

**Comment by shenglinW** [comment]
neo (mt15i) too

**Comment by azakosath** [comment]
Neither logcat, nor dmesg capture any changes while pressing the camera button. Key Test app shows normally keystrokes:
keycode: 27 and scancode=212 for camera
and
keycode: 80 and scancode= 528 for focus

Device: coconut

**Comment by linusseelinger** [comment]
Confirming for mango. However, after installing Focal from play store, it launches Focal when pressing the button.
(unfortunately, Focal gives me a strange green flickering, the default app works fine)
Maybe the default app is just not hooked up to the button event?

**Comment by DimitrisLiafos** [comment]
Same problem with my LWW device too. Only solution i found is installing a secondary camera app and then the camera button is hooked to it automatically.

**Comment by s-kostyuk** [comment]
Supports, haida.

**Comment by natanE** [comment]
same for me. coconut with 20131211

**Comment by mikeNG** [comment]
Ok this is a known bug, "same for me" answers are not helpful.

**Comment by s-kostyuk** [comment]
OK, how to help really? :)

**Comment by mikeNG** [comment]
Nothing can be done for now, still need to port some features from cm10.2 to fix this.

**Comment by siddharthnair96** [comment]
So Mike your trying to say that we can re assign keys normally... And that only after you port things from CM10.2 will the camera key work

**Comment by mikeNG** [comment]
Possible fix is in the works. I will try it on Sunday.

**Comment by s-kostyuk** [comment]
Fixed in cm-11.0-20131225 for haida. Camera launching, focusing and photographing works normally.

**Comment by mikeNG** [comment]
works on 1225 for me too
