### ISSUE TITLE
cm 10.1 legacy xperia bugs on my xperia mini st15i

### ISSUE THREAD

**Issue by prasad278** [LegacyXperia/local_manifests#208]
for the past half month i am using Legacy Xperia 10.1 On my xperia mini st15i
Follwing are the bugs i found on my device

1)default camera app has a problem(when exposed to indoor light camera screen turns blue & also the images taken )
2)gallery somtimes crashes 
3)Default music app or any other music player plays only half songs & skips to next one,even the song titles are displayed wrong,so everytime i have to clear the data 7 cache.
4)volume is low for speaker,inbetween the volume suddenly rises or decreses with headphones
5)cannot remove some system apps 
6)cannot integrate some apps into system which was possible in stock rom
7)blueetoth not working
8)

**Comment by Apocalypse2** [comment]
What build are you?

**Comment by Apocalypse2** [comment]
My cm10.1 works with all

**Comment by mikeNG** [comment]
1. File seperate issues for seperate bugs.
2. 10.1 support is stopped.

**Comment by prasad278** [comment]
my build version iscm_smultron -userdebug 4.2.2 JDQ39E eng mike 20130909.000632 test keys
also one important thing is that amy music palyer be it apollo or poweramp plays some half songs also it dispalys wrong title
Date: Fri, 6 Dec 2013 07:39:22 -0800
