### ISSUE TITLE
[CM 11.0][sk17i mango] when i use the hardware keyboard the touchscreen stop working... 

### ISSUE THREAD

**Issue by Alexhcx** [LegacyXperia/local_manifests#209]
In the beginning seems okay, but now when i pull out the keyboard the touch screen stop working, i dont know if this is a bug or my xperia mini pro...

**Comment by knizmi** [comment]
Might be actually just your device. Regarding the touchscreen my Mini Pro works just fine and nobody else has reported this yet.

**Comment by Alexhcx** [comment]
this sucks man! i will wait until next update to see this...maybe the digitizer of my phone is broken...lets see...

**Comment by karandpr** [comment]
No logs .Closed !
