### ISSUE TITLE
cm 10.2: Wifi is showing enabled in the power consumption overview, even when it is disabled

### ISSUE THREAD

**Issue by the-dreamer** [LegacyXperia/local_manifests#21]

**Comment by avinashrocks1990** [comment]
i think you haven't read the features of android 4.3 
it's mentioned that wifi is always enabled in a low power state for location service

**Comment by the-dreamer** [comment]
Wifi _is_ disabled manually via settings.

**Comment by avinashrocks1990** [comment]
yes that's what i said even if you disable it manually it will be active in a low power state 
i don't know how you don't know this as it was a hot topic for discussion after 4.3 was launched 
people all over internet arguing about it's merit and demerits

**Comment by the-dreamer** [comment]
Okay. I didn't know that. But this location service will not work due the scanning bug which i have also posted :-/

Can you give me a link to read about this issue?

**Comment by the-dreamer** [comment]
Okay, removing checkbox now also disabling wifi :-)

**Comment by avinashrocks1990** [comment]
there's an option in wifi advanced option to disable this feature 
try it out and report back

**Comment by the-dreamer** [comment]
my comment above is already the result of it :-)

**Comment by mikeNG** [comment]
So, this issue can be closed?

**Comment by the-dreamer** [comment]
Yes!
