### ISSUE TITLE
[CM11-20131127 - MT15i] Wifi's always on, consume much engergy event turn it off.

### ISSUE THREAD

**Issue by nguyentrunght** [LegacyXperia/local_manifests#213]
Toggle Wifi off has no effect to power consumption, Over a night (1-6h) battery level decreases from 100-62% with wifi off but in battery history, wifi take much time online and consume about 35% battery.

@LegacyXperia Thank for your effort, your contributions are good for all of us, who love experia but has not much money to upgrade :D.
All seems good, smooth and less FC . Thank for that.

**Comment by taha001** [comment]
buddy...it doesnt turnoff from status bar...go to settings and try turning it off from there.. i too had same problem

**Comment by xange** [comment]
did you turn on "scanning always available" in advanced settings? it keeps wifi on even thought you turn it off from anywhere. it must be uncheck

**Comment by nguyentrunght** [comment]
@xange : after posting that, i check advanced setting then turn it off  ( i don't think that enable by default after install the new ROM - because that many rom didn't turn it on after installation) thank,
Now screen is the most battery-hungry as normal but seem the battery life still not good as expected, Hope that will be fixed soon.

**Comment by fqdb** [comment]
"it doesnt turnoff from status bar"

Also doesn't turn off when you select a profile that should turn wifi off.

This bug is still present in the 20140603 nightly.

https://i.imgur.com/l7FzdYt.png

You can see from the screenshot that wifi stays on all night, but doesn't work (phone is never awake to sync).

**Comment by ghost** [comment]
"it doesnt turnoff from status bar"
nope, it does for me

cm-11-20140608-anzu(0603 probably the same)
