### ISSUE TITLE
status bar not transparent [cm11]

### ISSUE THREAD

**Issue by taha001** [LegacyXperia/local_manifests#214]
Status bar not transparent unlike kitkat 4.4 features it

**Comment by nefelim4ag** [comment]
https://github.com/LegacyXperia/local_manifests/issues/183
This is not a bug, close issue

**Comment by taha001** [comment]
but in kitkat4.4 it has to be transparent...right bro?

**Comment by djey47** [comment]
-> with low RAM setting in build.prop -> not transparent.
-> without low RAM setting -> transparent.

Those are the features.

**Comment by mikeNG** [comment]
Duplicate of #183

Why nobody checks for already open issues?!!!!!!
