### ISSUE TITLE
[11.0] Repeating Bluetooth crashes

### ISSUE THREAD

**Issue by DarkEmporer** [LegacyXperia/local_manifests#217]
Version :.20131127-LX-NIGHTLY-anzu

[Precondition]
Device is paired with vehicle head-unit for HFP. Pairing successful.
[Behavior]
Device connects to head-unit, but immediately connection is lost again. Process of connecting/reconnecting repeats indefinitely.
Contacts, SMS and Call Lists are not received by the head-unit.

Please see log for details https://gist.github.com/DarkEmporer/380d433304178e7a9be0

**Comment by maqninou** [comment]
Same here with BT headset MW600

**Comment by nguyentrunght** [comment]
for me (MW600), DSP's hang while receive an incomming call. Reconnecting's successful at first try and seldom occur.

**Comment by maqninou** [comment]
Same here. I think it's related to audio effects

2013/12/8 nguyentrunght notifications@github.com

**Comment by DarkEmporer** [comment]
Still happens with the cm-11.0-20131210-LX-anzu nightly build.

**Comment by mikeNG** [comment]
Any news on latest build?

**Comment by DanielMalmgren** [comment]
I'm not 100% it's the same issue, but ever since upgrading to 10.2 (now on 11) I've ha problems with Bluetooth sometimes (seemingly random) disconnecting in the middle of the night. Can't say for sure (since it's very intermittent), but I think these problems are gone since upgrading to 20131225.

**Comment by DanielMalmgren** [comment]
Correction to my last statement. I no longer get crashes in the middle of the night, now instead I get crashes when my phone wakes up to play my wakeup music. The same second it starts playing it disconnects and immediately reconnects bluetooth.

**Comment by DanielMalmgren** [comment]
After running 20140113 version for about three days now I haven't had one single bt crash, so it seems these problems are gone now at least on my phone.

**Comment by nguyentrunght** [comment]
Not related but with this new nightty version. Does your phone  reboote
frequently?
