### ISSUE TITLE
cm 10.2: Wifi scanning is broken

### ISSUE THREAD

**Issue by the-dreamer** [LegacyXperia/local_manifests#22]

**Comment by the-dreamer** [comment]
Some additional information: It seems that scanning is working only once. Only after disabling and enabling wifi. Than it is not working anymore.

**Comment by avinashrocks1990** [comment]
provide some logs without them it's useless

**Comment by the-dreamer** [comment]
I have enabled wifi and was pressin scanning two times and after that i disabled wifi again.

/main logcat

I/ActivityManager(  519): START u0 {act=android.settings.SETTINGS flg=0x10200000 cmp=com.android.settings/.Settings} from pid 28477
D/BluetoothAdapter(32031): 1099652832: getState() :  mService = null. Returning STATE_OFF
I/Adreno200-EGL(32031): <qeglDrvAPI_eglInitialize:294>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_JB.04.01.01.00.036_msm8960_JB_CL2644550_release_AU (CL2644550)
I/Adreno200-EGL(32031): Build Date: 07/31/12 Tue
I/Adreno200-EGL(32031): Local Branch:
I/Adreno200-EGL(32031): Remote Branch: quic/master
I/Adreno200-EGL(32031): Local Patches: NONE
I/Adreno200-EGL(32031): Reconstruct Branch: AU_LINUX_ANDROID_JB.04.01.01.00.036 +  NOTHING
D/BluetoothAdapter(32031): 1099652832: getState() :  mService = null. Returning STATE_OFF
I/ActivityManager(  519): Displayed com.android.settings/.Settings: +840ms
I/ActivityManager(  519): START u0 {act=android.intent.action.MAIN cmp=com.android.settings/.SubSettings (has extras)} from pid 32031
I/ActivityManager(  519): Displayed com.android.settings/.SubSettings: +321ms
D/WifiService(  519): setWifiEnabled: true pid=32031, uid=1000
D/Tethering(  519): sendTetherStateChangedBroadcast 1, 0, 0
D/Tethering(  519): InitialState.processMessage what=4
D/Tethering(  519): sendTetherStateChangedBroadcast 0, 0, 0
D/CommandListener(  220): Setting iface cfg
D/CommandListener(  220): Trying to bring down wlan0
D/WifiHW  (  519): added/removed p2p interface. add: 1
D/BluetoothAdapter(  612): 1099721240: getState() :  mService = null. Returning STATE_OFF
I/ActivityManager(  519): Start proc com.avast.android.antitheft for broadcast com.avast.android.antitheft/.service.BootListener: pid=2488 uid=10010 gids={50010, 3003, 1007, 1015, 1028}
I/wpa_supplicant( 2486): Successfully initialized wpa_supplicant
W/GAV2    ( 2488): Thread[main,5,main]: Need to call initialize() and be in fallback mode to start dispatch.
D/BluetoothAdapter(32031): 1099652832: getState() :  mService = null. Returning STATE_OFF
D/BluetoothAdapter(  612): 1099721240: getState() :  mService = null. Returning STATE_OFF
D/CommandListener(  220): Setting iface cfg
D/CommandListener(  220): Trying to bring up p2p0
D/BluetoothAdapter(32031): 1099652832: getState() :  mService = null. Returning STATE_OFF
I/GAV2    ( 2488): Thread[GAThread,5,main]: No campaign data found.
D/AlarmManagerService(  519): Kernel timezone updated to -120 minutes west of GMT
W/InputMethodManagerService(  519): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@422772c0 attribute=null, token = android.os.BinderProxy@42105608
W/InputMethodManagerService(  519): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@41bb1a10 attribute=null, token = android.os.BinderProxy@42105608
W/InputMethodManagerService(  519): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@41d3a7d0 attribute=null, token = android.os.BinderProxy@42105608
W/InputMethodManagerService(  519): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@41e04b80 attribute=null, token = android.os.BinderProxy@42105608
D/WifiService(  519): setWifiEnabled: false pid=32031, uid=1000
D/WifiHW  (  519): close sockets 1
D/CommandListener(  220): Clearing all IP addresses on wlan0
I/wpa_supplicant( 2486): p2p0: CTRL-EVENT-TERMINATING
I/wpa_supplicant( 2486): CTRL_IFACE monitor[0]: 2 - No such file or directory
I/wpa_supplicant( 2486): wlan0: CTRL-EVENT-TERMINATING
D/BluetoothAdapter(  612): 1099721240: getState() :  mService = null. Returning STATE_OFF
D/BluetoothAdapter(  612): 1099721240: getState() :  mService = null. Returning STATE_OFF
D/BluetoothAdapter(32031): 1099652832: getState() :  mService = null. Returning STATE_OFF
D/BluetoothAdapter(32031): 1099652832: getState() :  mService = null. Returning STATE_OFF
W/Settings(  787): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
W/Netd    (  220): No subsystem found in netlink event
W/Netd    (  220): No subsystem found in netlink event
D/NetlinkEvent(  220): Unexpected netlink message. type=0x11
D/NetlinkEvent(  220): Unexpected netlink message. type=0x11
D/BluetoothAdapter(32031): 1099652832: getState() :  mService = null. Returning STATE_OFF
D/BluetoothAdapter(32031): 1099652832: getState() :  mService = null. Returning STATE_OFF
I/Adreno200-EGL(28477): <qeglDrvAPI_eglInitialize:294>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_JB.04.01.01.00.036_msm8960_JB_CL2644550_release_AU (CL2644550)
I/Adreno200-EGL(28477): Build Date: 07/31/12 Tue
I/Adreno200-EGL(28477): Local Branch:
I/Adreno200-EGL(28477): Remote Branch: quic/master
I/Adreno200-EGL(28477): Local Patches: NONE
I/Adreno200-EGL(28477): Reconstruct Branch: AU_LINUX_ANDROID_JB.04.01.01.00.036 +  NOTHING
I/ActivityManager(  519): Process com.google.android.gsf.login (pid 2446) has died.
I/Choreographer(28477): Skipped 41 frames!  The application may be doing too much work on its main thread.

**Comment by mikeNG** [comment]
Wait for next release and report back

**Comment by mikeNG** [comment]
Will be probably fixed in next build
