### ISSUE TITLE
cm11 - urushi (20131127)

### ISSUE THREAD

**Issue by jafarm** [LegacyXperia/local_manifests#222]
1.after ending a call, the call end screen stays for a few seconds
2.no option to disable lockscreen widgets.
3.when i enabled the navigation bar via build.prop, the app drawer became 5X5. the widgets are not not fuly seen. how to get the default app drawer back?
4.camera seems very slow while recording but no problem in the recorded clips.
5.the

**Comment by mikeNG** [comment]
File one issue per bug
