### ISSUE TITLE
Google App

### ISSUE THREAD

**Issue by bhanucbs-13** [LegacyXperia/local_manifests#223]
Please give us full version Google app. not lite one for kitkat... if there is space problem then remove that app which are also in android market.. And one thing more Great job

**Comment by the-dreamer** [comment]
Exactly this is happened with the light version!

**Comment by padishah** [comment]
you can google search for it

**Comment by mikeNG** [comment]
All apps available in market are already removed.
Plus, this is not a bug.

**Comment by bhanucbs-13** [comment]
Did i said that this is a bug.. I just requesting you and your team for that.

**Comment by mikeNG** [comment]
This is called a BUG tracker
