### ISSUE TITLE
CANNOT ADD WIDGET SCREENS

### ISSUE THREAD

**Issue by taha001** [LegacyXperia/local_manifests#224]
Cannot add widget screens on lock.

**Comment by Diaz1999** [comment]
![screenshot_2013-12-06-07-09-13](https://f.cloud.github.com/assets/4738738/1691035/67ad7876-5e59-11e3-981b-14e61d0d941d.png)

Just change this line in build.prop
from:
ro.config.low_ram=true
to:
ro.config.low_ram=false
then reboot

**Comment by taha001** [comment]
i did..but only status bar got transparent..nothing else

**Comment by Diaz1999** [comment]
I don't know anymore, but that screenshot was from my phone running my own build cm-11-20131203-NIGHTLY-coconut with source from LegacyXperia

**Comment by padishah** [comment]
after adding build.prop go to settings>lock screen>widget paper and tick it

**Comment by taha001** [comment]
worked!!!...thank u guys!
