### ISSUE TITLE
screenOnAnimation CM11 source

### ISSUE THREAD

**Issue by fakhrodin** [LegacyXperia/local_manifests#227]
Hello,
Just came across this problem in cyanogen source:
screenOnAnimation  is defined wrong in frameworke_base_core...values config.xml

```
<integer name="config_screenOnAnimation">-1</integer>

<!-- True will enable the electron beam screen-off animation. -->
<bool name="config_screenOffAnimation">true</bool>
```

it is boolean in overlay as it should be

Thanks

**Comment by JovieBrett** [comment]
So did it fixed the buggy Screen on animation? or not? :-)

**Comment by fakhrodin** [comment]
I don't know!
I'm just building a personal project and I encountered this error

**Comment by JovieBrett** [comment]
Oh, okay :-)

**Comment by mikeNG** [comment]
It needs http://review.cyanogenmod.org/#/c/54900/ and http://review.cyanogenmod.org/#/c/54901/
