### ISSUE TITLE
[CM11.0-20131127-coconut] Soft reboot during call

### ISSUE THREAD

**Issue by azakosath** [LegacyXperia/local_manifests#229]
During this call I had the hands-free plugged and I was fooling around with the "hold on" option on screen. Here is the log: https://gist.github.com/azakosath/7794720
The reboot happened around 19:05.
The battery level dropped almost 10% during the reboot.
I didn't try to reproduce it.

**Comment by mikeNG** [comment]
logcat is needed for soft reboots...

**Comment by azakosath** [comment]
Next time then, I will try to be faster..... I'm closing the issue for now...
