### ISSUE TITLE
[CM11.0-20131127-coconut] Possibility to open the desktop settings on the background, being in the applications menu

### ISSUE THREAD

**Issue by sandumarizoi** [LegacyXperia/local_manifests#232]
possibility to open desktop settings on the background, by "menu" button , being in the applications menu

**Comment by Diaz1999** [comment]
![screenshot_2013-12-06-16-27-31](https://f.cloud.github.com/assets/4738738/1691027/1f139a8c-5e59-11e3-949d-f80a6d6a2413.png)

That's GEL bug, not the CM's bug
