### ISSUE TITLE
CM11 Xperia active (Satsuma) “Unfortunately, Process com.android.phone has stopped unexpectedly”

### ISSUE THREAD

**Issue by a9402465** [LegacyXperia/local_manifests#233]
I have installed CM11 on my Xperia active and then tried to restore all my apps with Titanium backup. Now after booting I constantly get the message: “Unfortunately, Process com.android.phone has stopped unexpectedly” and the phone functionality is gone (no connection to network. Does anybody know, what the problem might be?

**Comment by ghost** [comment]
Well maybe something's broken because you restored buttload of crap? This is a bug tracker not your personal Q&A service.

**Comment by a9402465** [comment]
It is indeed caused by the Titanium Backup restoration. After restoring only essential features it seems to work now.
