### ISSUE TITLE
[cm-11.0-20131127-LX-NIGHTLY-hallon.zip] Gapps Not Working

### ISSUE THREAD

**Issue by EvertonDeveloper** [LegacyXperia/local_manifests#234]
I flashed on my hallon this version cm-11.0-20131127-LX-NIGHTLY-hallon.zip an flashed this gapps gapps-kk-20131119-lite.zip, but playstore and others google services not working. So i tried flash another gapps for 4.4 and the phone boot stop on screen with the message "Android is upgrading | staring apps", as if the launcher was not working, because i go to cmw and clean the data and cache and boot again, and i can access the settings of the phone.

Sorry bad english

**Comment by tee-yankov** [comment]
What's probably happening is: You didn't follow the thread's instructions carefully and you're system partition is too small for the GApps. Try reflashing the whole thing but thise time remove some things from the GApps or flash Slim ones.
