### ISSUE TITLE
[10.2]Mango random reboots and sometimes stops

### ISSUE THREAD

**Issue by Micha-Btz** [LegacyXperia/local_manifests#238]
In the morning after i get up, i notice that my device is hang up. I have to take the battery out and in to get it started. Sometimes it just reboots and i has to insert the sim pin and sometimes the device is stopped completely. 

It is quite difficult to get a log, often there is no things logged.
But i got one http://pastebin.com/pb6TqhLB

The thing it happen nearly at the same time in the morning between 4-5 oclock.
For govenor i use smartassv2 and i/o Sched is sio.

Is there somestimg like a cron job that runs every day at the same time?

**Comment by Micha-Btz** [comment]
i'm on lx cm 10.2

**Comment by Apocalypse2** [comment]
cm10.1 or install cm11 which is much better than cm10.2

**Comment by mikeNG** [comment]
I don't see anything on the logs.
I don't have this problem and nobody else reported having such issues

**Comment by Micha-Btz** [comment]
phone is rebooting this night at 5am, but nothing in the logs.
can i attatch it to the pc and log the complete night? 
maybe there is an entry in the log possible.

**Comment by mikeNG** [comment]
you can try it.
another solution is to wake up before 5am to see what happens

**Comment by mikeNG** [comment]
any news?

**Comment by Micha-Btz** [comment]
maybe i got him, it's not so easy, i have logged several night trough, without luck.
i have had some reboot and one hangs last week.
take a look 
 http://pastebin.com/QhWNMa7x

**Comment by mikeNG** [comment]
Something is enabling/disabling wifi and bluetooth all the time and then for some reason the kernel crashes.
I think this is caused by some app you have installed

**Comment by Micha-Btz** [comment]
i close this, because the problem is llama app without llama the rom is stable like steel. :-)
i have contacted the developer of llama will see if we find a solution.
