### ISSUE TITLE
Low External Speaker Volume

### ISSUE THREAD

**Issue by sonuame** [LegacyXperia/local_manifests#247]
I flashed the ROM and its incredibly awesome to have it permanently.
but apart from that, I found its External Speaker Volume is way less than it used to be in my GB rom.

Is there any Mod or fix for that??

ROM i flashed : http://forum.xda-developers.com/showthread.php?t=2545354

**Comment by ghost** [comment]
It's a bug tracker not Q&A.

**Comment by sonuame** [comment]
awryt..my Bad..
