### ISSUE TITLE
[CM11][Anzu] wechat

### ISSUE THREAD

**Issue by dani010** [LegacyXperia/local_manifests#248]
when i wnat to use shake or people nearby in wechat after 1 sec shows a black screen and then wechat close , i dont know how to give u log , plz say me the way to give u the log , tnx

**Comment by ghost** [comment]
http://forum.xda-developers.com/showpost.php?p=47850217&postcount=3

**Comment by dani010** [comment]
i cant get logs , cvan any one test wechat in legacy xperia 4.4 and give mike logs ???

**Comment by mikeNG** [comment]
If it is so hard to get logs... then it is so hard for me to find the problem
