### ISSUE TITLE
LIST OF BUGS cm-11.0-20131128

### ISSUE THREAD

**Issue by flavio23** [LegacyXperia/local_manifests#249]
BUGS CM11.0

GOOD AFTERNOON / MORNING
- The physical keyboard blinks when you open it.
- The screen lockscreen is flawed: eg clock
- Missing options to configure the phone to your own taste
- The phone is not fully translated into Spanish (my case)
- The battery life is not as long as other ROMS
- No Radio

::PHONE - MANGO:: MINI PRO

**Comment by FibreFoX** [comment]
`No Radio` -> there is a page already, where it is listed:
https://github.com/LegacyXperia/local_manifests/wiki/CM11.0-kernel-3.4-status

`The battery life` its not a bug, its more a question about modifications, u should provide more details or even change your cpu/memory-management-settings

`Missing options to configure the phone to your own taste` :) details? What do you miss, is that feature available in older releases (10.1 or 10.2) ?

**Comment by ghost** [comment]
Read this: http://forum.xda-developers.com/showpost.php?p=47850217&postcount=3 then report every issue separately with logs, screenshots, description. Complaints and suggestions should be posted in xda threads.

**Comment by flavio23** [comment]
# Sorry to mention the battery life as BUG and if you fix that.
- On the configuration options are not as many as those of cm10.1, there if you can configure your own taste cell. I hope you add those things in the next version :)
- Where I found the problem was when reprodusco music while I activated the option "sound when locking screen" when a small block that spoils the sound lag (TRY) occurs

THANKS FOR THE SOLUTION OF THE RADIO: D

SORRY FOR MY BAD ENGLISH
GREETINGS
