### ISSUE TITLE
Home Button not working on anzu

### ISSUE THREAD

**Issue by Martin-Schultz** [LegacyXperia/local_manifests#25]
with both nightly builds of cm 10.2 from basketbuild,the home button on my anzu device has no function. back and menu buttons work properly.

**Comment by jlmcr87** [comment]
It works, you have an LT15i right? This is what you have to do:

1-Flash an official sony firmware from LT18i. With this you change the partitions (no vendor partition like in LT15i)
2-Flash legacy Xperia rom.

Please Mike close this
