### ISSUE TITLE
touch not wotking in cm 11 for wt19i

### ISSUE THREAD

**Issue by MMZCustoms** [LegacyXperia/local_manifests#250]
touch not working in my wt19i have installed latest cm 11 .. 
please help me....

**Comment by MMZCustoms** [comment]
pls help meeee....

**Comment by ghost** [comment]
Read this: http://forum.xda-developers.com/showpost.php?p=47850217&postcount=3

**Comment by MMZCustoms** [comment]
but ..
how to get this log files ....
bcoz, my phone not working ... only am geting the start screen. touch not working.,so i cant go to other options...

**Comment by MMZCustoms** [comment]
i installed the cm 10.2  also, that hav the same problem. touch not working.

**Comment by WolfAyron** [comment]
Then the problem might be related to your device. I also own a wt19i device and never met this problem. I'm on CM10.1 now and also used CM10.2 for some weeks. No touch problem.

**Comment by MMZCustoms** [comment]
bt, when am installing old ics it is working.... 

:-(

**Comment by WolfAyron** [comment]
Well, I don't know. Sorry I have no ideas.

**Comment by mikeNG** [comment]
No logs
