### ISSUE TITLE
CyanogenMod Screencast not working

### ISSUE THREAD

**Issue by mikeNG** [LegacyXperia/local_manifests#253]
I/d       ( 3452): Starting encoder
I/OMXClient( 3452): Using client-side OMX mux.
E/OMX-VENC-720p(  235): 
E/OMX-VENC-720p(  235): WARNING: Unsupported Color format [2130708361]
E/OMX-VENC-720p(  235): 
E/OMX-VENC-720p(  235): WARNING: Unsupported Color format [2130708361]
E/OMX-VENC-720p(  235): 
E/OMX-VENC-720p(  235):  venc_set_intra_period: nPFrames = 300 nBFrames = 0
I/ACodec  ( 3452): setupVideoEncoder succeeded
I/DisplayManagerService(  637): Display device added: DisplayDeviceInfo{"hidden:screen-recording": 320 x 480, 60.0 fps, density 1, 1.0 x 1.0 dpi, touch NONE, rotation 0, type VIRTUAL, owner com.cyanogenmod.screencast (uid 10072), FLAG_SECURE}
E/FramebufferNativeWindow(  232): fb buffer 0 allocation failed w=320, h=480, err=Out of memory
D/RecordingDevice( 3452): encoder output format changed: {csd-1=java.nio.ByteArrayBuffer[position=0,limit=8,capacity=8], height=480, mime=video/avc, csd-0=java.nio.ByteArrayBuffer[position=0,limit=13,capacity=13], what=1869968451, width=320}
I/OMXClient( 3452): Using client-side OMX mux.

**Comment by dinoomanovic** [comment]
There are other screencasting apps on Play Store that produce same freezing behaviour as Screencast.
I don't know if this can help, but there is SCR Free app on Play Store that is working with following settings:
Encoder: FFmpeg software MPEG4 encoder
Resolution: 640x360 - 360p (others should also work)
Bitrate: 10Mbps 
Frame rate: up to 15fps

So it produces output:
I/ActivityManager(  626): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.iwobanas.screenrecorder.free/com.iwobanas.screenrecorder.RecorderActivity} from pid 943
I/ActivityManager(  626): Start proc com.iwobanas.screenrecorder.free for activity com.iwobanas.screenrecorder.free/com.iwobanas.screenrecorder.RecorderActivity: pid=3792 uid=10095 gids={50095, 1028, 1015, 3003}
W/InputMethodManagerService(  626): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@41e57328 attribute=null, token = android.os.BinderProxy@41d5e6b0
W/GAV2    ( 3792): Thread[main,5,main]: Need to call initialize() and be in fallback mode to start dispatch.
W/ActivityManager(  626): Activity pause timeout for ActivityRecord{41c34070 u0 com.iwobanas.screenrecorder.free/com.iwobanas.screenrecorder.RecorderActivity t11 f}
V/scr_RecorderService( 3792): Service initialized. version: 35
D/scr_RecorderProcess-0( 3792): setState STARTING
D/scr_RecorderProcess-0( 3792): Starting native process
D/su      ( 3816): su invoked.
D/su      ( 3816): starting daemon client 10095 10095
D/su      ( 3822): su invoked.
I/Choreographer( 3792): Skipped 72 frames!  The application may be doing too much work on its main thread.
D/scr_RecorderProcess-0( 3792): Native process started
D/su      ( 3822): db allowed
D/su      ( 3822): 10095 /system/xbin/su executing 0 /data/data/com.iwobanas.screenrecorder.free/files/screenrec using binary /system/bin/sh : sh -c /data/data/com.iwobanas.screenrecorder.free/files/screenrec
D/scr_RecorderProcess-0( 3792): setState READY
W/BackupManagerService(  626): dataChanged but no participant pkg='com.android.providers.settings' uid=10095
I/InputManager-JNI(  626): Setting show touches feature to enabled.
I/InputReader(  626): Reconfiguring input devices.  changes=0x00000008
D/AndroidRuntime( 3824): 
D/AndroidRuntime( 3824): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime( 3824): CheckJNI is OFF
D/dalvikvm( 3824): Trying to load lib libjavacore.so 0x0
D/dalvikvm( 3824): Added shared lib libjavacore.so 0x0
D/dalvikvm( 3824): Trying to load lib libnativehelper.so 0x0
D/dalvikvm( 3824): Added shared lib libnativehelper.so 0x0
D/dalvikvm( 3824): No JNI_OnLoad found in libnativehelper.so 0x0, skipping init
E/cutils-trace( 3824): Error opening trace file: No such file or directory (2)
D/dalvikvm( 3824): Note: class Landroid/app/ActivityManagerNative; has 180 unimplemented (abstract) methods
E/memtrack( 3824): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 3824): failed to load memtrack module: -2
D/AndroidRuntime( 3824): Calling main entry com.android.commands.am.Am
I/ActivityManager(  626): Start proc com.android.settings for broadcast com.android.settings/.cyanogenmod.superuser.SuReceiver: pid=3836 uid=1000 gids={41000, 1028, 1015, 3002, 3001, 3003}
W/ActivityManager(  626): Unable to start service Intent { flg=0x10000000 cmp=com.iwobanas.screenrecorder.free/com.iwobanas.screenrecorder.RecorderActivity } U=0: not found
I/ActivityManager(  626): START u0 {flg=0x10000000 cmp=com.iwobanas.screenrecorder.free/com.iwobanas.screenrecorder.RecorderActivity} from pid 3792
D/CountryDetector(  626): No listener is left
I/ActivityManager(  626): START u0 {cmp=com.iwobanas.screenrecorder.free/com.iwobanas.screenrecorder.settings.SettingsActivity} from pid 3792
I/ActivityManager(  626): Process com.android.mms (pid 2981) has died.
W/ContextImpl( 3792): Implicit intents with startService are not safe: Intent { act=com.google.android.gms.analytics.service.START (has extras) } android.content.ContextWrapper.bindService:517 com.google.analytics.tracking.android.AnalyticsGmsCoreClient.connect:82 com.google.analytics.tracking.android.GAServiceProxy.connectToService:279 
W/GAV2    ( 3792): Thread[GAThread,5,main]: Service unavailable (code=1), will retry.
W/ActivityManager(  626): Unable to start service Intent { act=com.google.android.gms.analytics.service.START (has extras) } U=0: not found
I/GAV2    ( 3792): Thread[GAThread,5,main]: No campaign data found.
D/libEGL  ( 3792): loaded /system/lib/egl/libEGL_adreno200.so
D/libEGL  ( 3792): loaded /system/lib/egl/libGLESv1_CM_adreno200.so
D/libEGL  ( 3792): loaded /system/lib/egl/libGLESv2_adreno200.so
I/Adreno200-EGL( 3792): <qeglDrvAPI_eglInitialize:294>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_JB.04.01.01.00.036_msm8960_JB_CL2644550_release_AU (CL2644550)
I/Adreno200-EGL( 3792): Build Date: 07/31/12 Tue
I/Adreno200-EGL( 3792): Local Branch: 
I/Adreno200-EGL( 3792): Remote Branch: quic/master
I/Adreno200-EGL( 3792): Local Patches: NONE
I/Adreno200-EGL( 3792): Reconstruct Branch: AU_LINUX_ANDROID_JB.04.01.01.00.036 +  NOTHING
D/OpenGLRenderer( 3792): Enabling debug mode 0
I/ActivityManager(  626): Displayed com.iwobanas.screenrecorder.free/com.iwobanas.screenrecorder.settings.SettingsActivity: +1s96ms (total +6s85ms)
E/ActivityThread(  943): Performing stop of activity that is not resumed: {com.android.launcher3/com.android.launcher3.Launcher}
E/ActivityThread(  943): java.lang.RuntimeException: Performing stop of activity that is not resumed: {com.android.launcher3/com.android.launcher3.Launcher}
E/ActivityThread(  943):    at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3167)
E/ActivityThread(  943):    at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3254)
E/ActivityThread(  943):    at android.app.ActivityThread.access$1100(ActivityThread.java:145)
E/ActivityThread(  943):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1233)
E/ActivityThread(  943):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/ActivityThread(  943):    at android.os.Looper.loop(Looper.java:136)
E/ActivityThread(  943):    at android.app.ActivityThread.main(ActivityThread.java:5081)
E/ActivityThread(  943):    at java.lang.reflect.Method.invokeNative(Native Method)
E/ActivityThread(  943):    at java.lang.reflect.Method.invoke(Method.java:515)
E/ActivityThread(  943):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
E/ActivityThread(  943):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/ActivityThread(  943):    at dalvik.system.NativeStart.main(Native Method)
I/ActivityManager(  626): Activity reported stop, but no longer stopping: ActivityRecord{41dfcaa0 u0 com.android.launcher3/.Launcher t1}
D/AndroidRuntime( 3824): Shutting down VM
W/ContextImpl( 3792): Implicit intents with startService are not safe: Intent { act=com.google.android.gms.analytics.service.START (has extras) } android.content.ContextWrapper.bindService:517 com.google.analytics.tracking.android.AnalyticsGmsCoreClient.connect:82 com.google.analytics.tracking.android.GAServiceProxy.connectToService:279 
W/ActivityManager(  626): Unable to start service Intent { act=com.google.android.gms.analytics.service.START (has extras) } U=0: not found
W/GAV2    ( 3792): Thread[Service Reconnect,5,main]: Service unavailable (code=1), using local store.
D/MtpService( 1954): updating state; isCurrentUser=true, mMtpLocked=false
D/MtpService( 1954): addStorageLocked 65537 /storage/sdcard0
D/MtpService( 1954): updating state; isCurrentUser=true, mMtpLocked=false
D/MtpService( 1954): starting MTP server in MTP mode
D/MtpService( 1954): addStorageLocked 65537 /storage/sdcard0
I/EntropyMixer(  626): Writing entropy...
D/YouTube ( 2056): apps.youtube.app.prefetch.PrefetchService$DeviceStateReceiver.onReceive:565 Got device state change intent: android.intent.action.ACTION_POWER_CONNECTED
D/YouTube ( 2056): apps.youtube.app.prefetch.PrefetchService.onStartCommand:167 PrefetchService started at 15 Dec 2013 20:26:52 GMT
D/YouTube ( 2056): apps.youtube.app.prefetch.PrefetchService.p_:245 Download snapshot restored
D/YouTube ( 2056): apps.youtube.app.prefetch.PrefetchService.onDestroy:215 PrefetchService destroyed at 15 Dec 2013 20:26:52 GMT
D/MobileDataStateTracker(  626): default: Broadcast received: android.intent.action.ANY_DATA_STATE apnType=default
D/MobileDataStateTracker(  626): default: Received state=DISCONNECTED, old=DISCONNECTED, reason=(unspecified)
I/scr_NativeProcessRunner( 3792): start deviceId: b93b274fc74e62e7
I/scr_RecorderProcess-0( 3792): startRecording /storage/sdcard0/ScreenRecorder/SCR_20131215_212718.mp4
D/scr_RecorderProcess-0( 3792): setState RECORDING
D/scr_RecorderProcess-0( 3792): settings rotation: 0 audioSource: MUTE resolution: 640 x 360 frameRate: 15 transformation: CPU videoBitrate: BITRATE_10_MBPS samplingRate: SAMPLING_RATE_16_KHZ colorFix: false videoEncoder: -2 verticalFrames: false
I/screenrec( 3822): SETTINGS rotation: 0, audioSource: x, resolution: 640 x 360, padding: 0 x 0, frameRate: 15, mode: CPU, colorFix: 0, videoEncoder: -2, verticalFrames: 0
I/screenrec( 3822): swapping dimensions
V/screenrec( 3822): Screenshot width: 360, height: 640, stride: 360, format 1, size: 921600
V/screenrec( 3822): Setup finished. Starting rendering loop.
D/SizeAdaptiveLayout(  812): com.android.internal.widget.SizeAdaptiveLayout{41ae7aa0 V.E..... ......I. 0,0-0,0 #7f070060 app:id/adaptive}child view android.widget.FrameLayout{41b057a8 G.E..... ......ID 0,0-0,0 #10202d6 android:id/status_bar_latest_event_content} measured out of bounds at 95px clamped to 96px
D/SizeAdaptiveLayout(  812): com.android.internal.widget.SizeAdaptiveLayout{41b9bbb0 V.E..... ......I. 0,0-0,0 #7f070060 app:id/adaptive}child view android.widget.FrameLayout{421df6f8 G.E..... ......ID 0,0-0,0 #10202d6 android:id/status_bar_latest_event_content} measured out of bounds at 95px clamped to 96px
D/SizeAdaptiveLayout(  812): com.android.internal.widget.SizeAdaptiveLayout{41fdabe0 V.E..... ......I. 0,0-0,0 #7f070060 app:id/adaptive}child view android.widget.FrameLayout{41e77298 G.E..... ......ID 0,0-0,0 #10202d6 android:id/status_bar_latest_event_content} measured out of bounds at 95px clamped to 96px
D/SizeAdaptiveLayout(  812): com.android.internal.widget.SizeAdaptiveLayout{41ae7aa0 V.E..... ......I. 0,0-0,0 #7f070060 app:id/adaptive}child view android.widget.FrameLayout{41b057a8 G.E..... ......ID 0,0-0,0 #10202d6 android:id/status_bar_latest_event_content} measured out of bounds at 95px clamped to 96px
D/SizeAdaptiveLayout(  812): com.android.internal.widget.SizeAdaptiveLayout{41b9bbb0 V.E..... ......I. 0,0-0,0 #7f070060 app:id/adaptive}child view android.widget.FrameLayout{421df6f8 G.E..... ......ID 0,0-0,0 #10202d6 android:id/status_bar_latest_event_content} measured out of bounds at 95px clamped to 96px
D/SizeAdaptiveLayout(  812): com.android.internal.widget.SizeAdaptiveLayout{41fdabe0 V.E..... ......I. 0,0-0,0 #7f070060 app:id/adaptive}child view android.widget.FrameLayout{41e77298 G.E..... ......ID 0,0-0,0 #10202d6 android:id/status_bar_latest_event_content} measured out of bounds at 95px clamped to 96px
V/PanelView(  812): animationTick called with dtms=0; nothing to do (h=304.0 v=2357.804)
D/scr_RecorderProcess-0( 3792): stopRecording
D/scr_RecorderProcess-0( 3792): setState STOPPING
V/screenrec( 3822): command thread completed
W/KeyguardTouchDelegate(  812): dismiss(): NO SERVICE!
V/screenrec( 3822): finished - stopping
V/screenrec( 3822): Closing FFmpeg output 1
D/scr_RecorderProcess-0( 3792): Flushing output
V/screenrec( 3822): Writing trailer
W/scr_RecorderProcess-0( 3792): stderr: 0 - stop requested from thread main
V/screenrec( 3822): streams and codecs cleanup
V/screenrec( 3822): FFmpeg output closed
V/screenrec( 3822): exiting main thread
D/su      ( 3816): client exited 0
D/scr_RecorderProcess-0( 3792): Waiting for native process to exit
D/scr_RecorderProcess-0( 3792): Native process finished
D/scr_RecorderProcess-0( 3792): setState FINISHED
D/scr_RecorderProcess-0( 3792): Return value: 0
V/PanelView(  812): animationTick called with dtms=0; nothing to do (h=854.0 v=-3000.0)
V/KeyguardTouchDelegate(  812): Connected to keyguard
D/SizeAdaptiveLayout(  812): com.android.internal.widget.SizeAdaptiveLayout{41ae7aa0 V.E..... ......ID 0,0-480,96 #7f070060 app:id/adaptive}child view android.widget.FrameLayout{41b057a8 V.E..... ......ID 0,0-480,96 #10202d6 android:id/status_bar_latest_event_content} measured out of bounds at 95px clamped to 96px
D/scr_RecorderProcess-1( 3792): setState STARTING
D/scr_RecorderProcess-1( 3792): Starting native process
W/InputMethodManagerService(  626): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@41ca1880 attribute=null, token = android.os.BinderProxy@41cce9c0
D/scr_RecorderProcess-1( 3792): Native process started
D/su      ( 3882): su invoked.
D/su      ( 3882): starting daemon client 10095 10095
D/su      ( 3888): su invoked.
D/su      ( 3888): db allowed
D/su      ( 3888): 10095 /system/xbin/su executing 0 /data/data/com.iwobanas.screenrecorder.free/files/screenrec using binary /system/bin/sh : sh -c /data/data/com.iwobanas.screenrecorder.free/files/screenrec
D/scr_RecorderProcess-1( 3792): setState READY
D/AndroidRuntime( 3889): 
D/AndroidRuntime( 3889): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime( 3889): CheckJNI is OFF
D/dalvikvm( 3889): Trying to load lib libjavacore.so 0x0
D/dalvikvm( 3889): Added shared lib libjavacore.so 0x0
D/dalvikvm( 3889): Trying to load lib libnativehelper.so 0x0
D/dalvikvm( 3889): Added shared lib libnativehelper.so 0x0
D/dalvikvm( 3889): No JNI_OnLoad found in libnativehelper.so 0x0, skipping init
E/cutils-trace( 3889): Error opening trace file: No such file or directory (2)
D/dalvikvm( 3889): Note: class Landroid/app/ActivityManagerNative; has 180 unimplemented (abstract) methods
E/memtrack( 3889): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 3889): failed to load memtrack module: -2
D/AndroidRuntime( 3889): Calling main entry com.android.commands.am.Am
D/AndroidRuntime( 3889): Shutting down VM

**Comment by s-kostyuk** [comment]
Supports. Rec. application causes system UI freezing. Log: http://pastebin.com/05PwjC9K. App on Google Play:  https://play.google.com/store/apps/details?id=com.spectrl.rec. SCR Free works normally, as was noticed above.

Maybe, of course, it's problem of application, not OS, but nevertheless

**Comment by mikeNG** [comment]
Works with the new ION kernel but video has artifacts
