### ISSUE TITLE
cm-11.0-20131210-LX-NIGHTLY-anzu(Google keyboard FC's)

### ISSUE THREAD

**Issue by KiranAK47** [LegacyXperia/local_manifests#255]
![screenshot_2013-12-10-16-16-40](https://f.cloud.github.com/assets/5837545/1713406/f3661b4c-6189-11e3-80ba-cdf818bd9961.png)
Keyboard doesn't work at all.

**Comment by mikeNG** [comment]
Google keyboard is not part of this ROM.
Also, no logs provided
