### ISSUE TITLE
cm-11.0-20131210-LX-NIGHTLY-anzu(Very less phone memory even though i use Arc S)

### ISSUE THREAD

**Issue by KiranAK47** [LegacyXperia/local_manifests#256]
![screenshot_2013-12-10-16-25-04](https://f.cloud.github.com/assets/5837545/1713417/33dcdd6e-618a-11e3-9d73-7b6ffbb0a67c.png)
It says 110Mb used where as i have never installed a single app.
Typically in Arc S i get around 420 Mb. But in this its very less.

**Comment by mikeNG** [comment]
that's dalvik-cache

**Comment by KiranAK47** [comment]
does doin a dalvik cache wipe clear the 110 mb that has been used ?

**Comment by mikeNG** [comment]
yes and dalvik will be generated again, taking 110mb again
you can't do anything to free that space

**Comment by KiranAK47** [comment]
thank you mike for informing me that. I appreciate your work. Hope to get that 110mb in the future releases.
