### ISSUE TITLE
[cm11 20131210 coconut] bootloop when flashing new nightly caused by blockdevice error

### ISSUE THREAD

**Issue by LillyWho** [LegacyXperia/local_manifests#259]
I flashed the new nightly a few hours ago.
The phone tried to boot for 15 minutes until I canceled it.
I remembered the ART issue and wiped /cache and dalvik cache. The /chache was successfully wiped but the dalvik cache refused to wipe with an entry in the log that was like: failed to partition [blockdevice normally mapped as /data]: is not a blockdevice

it can be fixed by flashing the old kernel, wiping dalvik, data, and cache.
Then test it by hotbooting the new kernel. If it boots up and displays in Settings -> Apps that some space of the /data partition is used you can proceed with flashing the new kernel.

I can't provide any logs because they are corrupt for some reason.

**Comment by mikeNG** [comment]
follow the new instructions **exactly**
