### ISSUE TITLE
SIM Card Messages Not Displaying

### ISSUE THREAD

**Issue by azam426** [LegacyXperia/local_manifests#26]
Inbox Messages Saved on the SIM card not Displaying on CM10.2 on Iyokan. I didn't test on Anzu or any other. But i tested with CM10.1 on Iyokan, It is working on CM10.1. But CM10.2 only having that issue.

**Comment by mikeNG** [comment]
Any news with the latest build?

**Comment by mikeNG** [comment]
no feedback
