### ISSUE TITLE
[cm11 20131210 mango] bootlooping after installing the new nightly

### ISSUE THREAD

**Issue by mrmurthi** [LegacyXperia/local_manifests#260]
I have wiped dalvik cache. then installed the new cm11 nightly via cwm. also, i flashed the kernel provided in the new cm11 nightly. when i try to boot the phone, it is bootlooping and i am unable to get into recovery mode also.

Please help with this.

**Comment by flavio23** [comment]
La estoy descargando.
Espero que no me pase lo mismo.
Prueba con hacerlo otra ves

:PHONE:  MANGO ::

**Comment by mikeNG** [comment]
@flavio23 only english please.

**Comment by mikeNG** [comment]
@mrmurthi  follow the new installation instructions **exactly** step by step
