### ISSUE TITLE
[CM11]{Smultron} Some apps randomly force closes

### ISSUE THREAD

**Issue by JovieBrett** [LegacyXperia/local_manifests#262]
Smultron with Alpha 2 Build121013 and dalvik mode, flashed and followed all the procedures for the new partition layout, there were no problems upon installation however...
I'm using Link2SD with Ext4 partition. Linked all my user apps to the Ext4 partition but some apps force close whenever after a reboot is done (Apps will be functional and working again after I reboot it but force close will be back at some time if I rebooted it again), there are also instances that an app is uninstalled by just a simple reboot. Here's the log: http://goo.gl/2XSSFd
Apps that I found force closing: Titanium Backup (updated version) and Google Play Music.
Hope it helps.

**Comment by karandpr** [comment]
Error due to Link2SD . 
Link2SD is good but it doesn't fsck the partition before boot .
If you are using ext4/3 partition ,regular fsck is required preferably every-time before boot.
