### ISSUE TITLE
[CM11]  Camera

### ISSUE THREAD

**Issue by bhanucbs-13** [LegacyXperia/local_manifests#267]
Version :alphabuild 2

Recording scene fridge in camera recording mode only recording time running. And also there is no recorded video found in iyokan

**Comment by soulpower11** [comment]
Same here. Using xperia neo V

**Comment by KiranAK47** [comment]
The issue is in anzu(arc s) too.
Video is not saved in the gallery .

**Comment by dru1988** [comment]
Also whit mango.

**Comment by soulpower11** [comment]
And camera freezes and force close when taking photos that is under 3MPs and below.

**Comment by mikeNG** [comment]
try alpha 3. Provide logs

**Comment by bhanucbs-13** [comment]
Same in alpha 3

**Comment by soulpower11** [comment]
is this the right log ? http://pastebin.com/Sa3TTQGP for video recording.

and this is the other log for taking pictures http://pastebin.com/G4BGtscP.

it is still the same in alpha 3

**Comment by fotocreaman** [comment]
Same for Mango and Alpha 3
Also camera HW button does not activate the app

**Comment by mikeNG** [comment]
@soulpower11 take logs exactly after you exit the camera app. These logs you posted are incomplete

**Comment by soulpower11** [comment]
This http://pastebin.com/9qAFDeQs ?

and the other log http://pastebin.com/JY1yMctv

**Comment by xange** [comment]
@mikeNG  this is my logcat from Xperia Neo. 

http://pastebin.com/Ng1CWExr

hope it helps :-)

logcat from starting camera apps straight into cam mode, start recording 3 seconds, stop recording and exit apps.

**Comment by mikeNG** [comment]
There is a general problem with video encoder/decoder in 4.4.
I will look into it.

**Comment by dinoomanovic** [comment]
Here's another log, recording 10s video with audio on haida
http://pastebin.com/pQSsxtQy

**Comment by luismytronic** [comment]
mismo problema grabacion de video no funciona (CM11-aida)

**Comment by amir900A** [comment]
also in smultron in alpha 3 :) app hanging after peressing record button ( in video mode )

**Comment by Esarve** [comment]
same here [anzu] app hangs and after pressing stop, camera FCs

**Comment by bhanucbs-13** [comment]
video recording still not working in cm-11.0-20131225-NIGHTLY-LegacyXperia-iyokan

**Comment by mikeNG** [comment]
Fixed in next build

**Comment by anoopg87** [comment]
(Coconut)video recording is not happening. when start recording it freezes :(

**Comment by mikeNG** [comment]
I said "Fixed in next build", not the current build
