### ISSUE TITLE
update.sh not working

### ISSUE THREAD

**Issue by n1kolaa** [LegacyXperia/local_manifests#27]
Error when try to add specific pach with is not mearged
n1kolaa@n1kolaa-ASUS-DEKSTOP ~/android/system $ curl https://raw.github.com/LegacyXperia/local_manifests/cm-10.2/updates.sh > ~/android/system/updates.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1842  100  1842    0     0   6476      0 --:--:-- --:--:-- --:--:--  7675
n1kolaa@n1kolaa-ASUS-DEKSTOP ~/android/system $ chmod a+x updates.sh
n1kolaa@n1kolaa-ASUS-DEKSTOP ~/android/system $ ./updates.sh
From http://review.cyanogenmod.org/CyanogenMod/android_system_core
- branch            refs/changes/74/38174/1 -> FETCH_HEAD
  # Not currently on any branch.
  # You are currently cherry-picking.
  # (all conflicts fixed: run "git commit")
  # 
  
  nothing to commit, working directory clean
  The previous cherry-pick is now empty, possibly due to conflict resolution.
  If you wish to commit it anyway, use:
  
  git commit --allow-empty

Otherwise, please use 'git reset'
From http://review.cyanogenmod.org/CyanogenMod/android_bootable_recovery
- branch            refs/changes/77/36777/3 -> FETCH_HEAD
  error: 'cherry-pick' is not possible because you have unmerged files.
  hint: Fix them up in the work tree,
  hint: and then use 'git add/rm <file>' as
  hint: appropriate to mark resolution and make a commit,
  hint: or use 'git commit -a'.
  fatal: cherry-pick failed
  From http://review.cyanogenmod.org/CyanogenMod/android_hardware_qcom_audio-caf
- branch            refs/changes/84/47484/2 -> FETCH_HEAD
  # Not currently on any branch.
  # You are currently cherry-picking.
  # (all conflicts fixed: run "git commit")
  # 
  
  nothing to commit, working directory clean
  The previous cherry-pick is now empty, possibly due to conflict resolution.
  If you wish to commit it anyway, use:
  
  git commit --allow-empty

Otherwise, please use 'git reset'
From http://review.cyanogenmod.org/CyanogenMod/android_hardware_qcom_audio-caf
- branch            refs/changes/02/48202/1 -> FETCH_HEAD
  # Not currently on any branch.
  # You are currently cherry-picking.
  # (all conflicts fixed: run "git commit")
  # 
  
  nothing to commit, working directory clean
  The previous cherry-pick is now empty, possibly due to conflict resolution.
  If you wish to commit it anyway, use:
  
  git commit --allow-empty

Otherwise, please use 'git reset'
From http://review.cyanogenmod.org/CyanogenMod/android_frameworks_av
- branch            refs/changes/95/46495/1 -> FETCH_HEAD
  # Not currently on any branch.
  # You are currently cherry-picking.
  # (all conflicts fixed: run "git commit")
  # 
  
  nothing to commit, working directory clean
  The previous cherry-pick is now empty, possibly due to conflict resolution.
  If you wish to commit it anyway, use:
  
  git commit --allow-empty

Otherwise, please use 'git reset'
From http://review.cyanogenmod.org/CyanogenMod/android_frameworks_av
- branch            refs/changes/73/48673/1 -> FETCH_HEAD
  # Not currently on any branch.
  # You are currently cherry-picking.
  # (all conflicts fixed: run "git commit")
  # 
  
  nothing to commit, working directory clean
  The previous cherry-pick is now empty, possibly due to conflict resolution.
  If you wish to commit it anyway, use:
  
  git commit --allow-empty

Otherwise, please use 'git reset'
From http://review.cyanogenmod.org/CyanogenMod/android_frameworks_native
- branch            refs/changes/80/47180/1 -> FETCH_HEAD
  # Not currently on any branch.
  # You are currently cherry-picking.
  # (all conflicts fixed: run "git commit")
  # 
  
  nothing to commit, working directory clean
  The previous cherry-pick is now empty, possibly due to conflict resolution.
  If you wish to commit it anyway, use:
  
  git commit --allow-empty

Otherwise, please use 'git reset'
From http://review.cyanogenmod.org/CyanogenMod/android_frameworks_native
- branch            refs/changes/59/47259/1 -> FETCH_HEAD
  # Not currently on any branch.
  # You are currently cherry-picking.
  # (all conflicts fixed: run "git commit")
  # 
  
  nothing to commit, working directory clean
  The previous cherry-pick is now empty, possibly due to conflict resolution.
  If you wish to commit it anyway, use:
  
  git commit --allow-empty

Otherwise, please use 'git reset'
From http://review.cyanogenmod.org/CyanogenMod/android_dalvik
- branch            refs/changes/56/47756/1 -> FETCH_HEAD
  # Not currently on any branch.
  # You are currently cherry-picking.
  # (all conflicts fixed: run "git commit")
  # 
  
  nothing to commit, working directory clean
  The previous cherry-pick is now empty, possibly due to conflict resolution.
  If you wish to commit it anyway, use:
  
  git commit --allow-empty

Otherwise, please use 'git reset'

**Comment by MIXTERek** [comment]
the same issue with mango & coconut after "make clean"

**Comment by n1kolaa** [comment]
i try to build with this error but i got some error with recovery will shere..

**Comment by MIXTERek** [comment]
yes at the moment when is compiling kernel

**Comment by n1kolaa** [comment]
no more problems 
its fixed with lastest updates.sh changes
