### ISSUE TITLE
cm-11.0-20131211-LX-NIGHTLY-haida freeze and reboot

### ISSUE THREAD

**Issue by kylewong1974** [LegacyXperia/local_manifests#271]
I experienced 3-4 system freeze and reboot over the past 10 hours.

http://pastebin.com/UQ3FLhkQ

**Comment by ghanashyamvtatti** [comment]
Are you using the kernel that was provided within the zip file?

**Comment by kylewong1974** [comment]
Yes, boot.img inside the zip

**Comment by ghanashyamvtatti** [comment]
Actually, now even I've been facing similar issues. Not as frequently though.
Try the Dark Kernel and see how that goes.
http://forum.xda-developers.com/showthread.php?t=2549666

**Comment by mikeNG** [comment]
nothing in the logs
