### ISSUE TITLE
xposed frameworks

### ISSUE THREAD

**Issue by edbassman** [LegacyXperia/local_manifests#273]
hi. when instal xposed 2.4.1 and freemwork - process android.process.media has stopped what can i do?

**Comment by rahmandovski** [comment]
dude, just install an new updates from mike's basketbuild.

**Comment by edbassman** [comment]
i have instal latest rom 20131211. i wont use gravity box and greenify that's why i need instal exposed. sory my eng

**Comment by mikeNG** [comment]
xposed is not supported by LX officially, use at your own risk.
you should report this to xposed devs instead
