### ISSUE TITLE
cm-11.0-20131211-LX-NIGHTLY-smultron [st15i smultron] first impressions

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#274]
copied boot.img
cleaned sd-card
factory default reset
installed build and latest gapps

first init of android 4.4, after wizard, apps button not working / apps could not be accessed, after reboot phone everything ok.

default internet browser very slow / poor performance
installed google chrome, much better page browsing

display brightness -- auto setting very dark display, manually adjusted

apps working:

abn amro banking
email
maps
whatsapp
playstore
chrome
ip cam viewer

features working:
camera
wifi
3g

**Comment by mikeNG** [comment]
This is a bug tracker not a discussion thread
