### ISSUE TITLE
[11.0] Automatic brightness is not working - mango

### ISSUE THREAD

**Issue by fotocreaman** [LegacyXperia/local_manifests#275]
Version :  Alpha 3 

When I activate automatic brightness this is not working. The display is too much dimmed. When I try to adjust the curve I see the meter is indicating the presence of light (lux indication goes up) but after adjusting the sliders the display dims again. Sometimes the display lights up for half a second and then dims again.

**Comment by asoderq** [comment]
I also have the same problem with Mango alpha 3. Worked fine on CM10.2.

**Comment by rahmandovski** [comment]
lux keep on 0 lux and 12 lux

**Comment by mikeNG** [comment]
Any news on latest build?

**Comment by rahmandovski** [comment]
Nope. Problem still exist. I though my phone ia broke, but after my friend with his xperia ray had a same problem, maybe is an issue

**Comment by mikeNG** [comment]
This happens only on cm11? Have you tried 10.2 or 10.1?

**Comment by rahmandovski** [comment]
Yes, before using cm11, i have no problem with autobrightness (cm10.2)

**Comment by mikeNG** [comment]
I just tested on my mini, ray & arc and light sensor reports correct values like on cm10.2 (0-9000 lux)

**Comment by rahmandovski** [comment]
I have no idea. Should i do a full wipe ?

**Comment by fotocreaman** [comment]
This is solved on de 2512 release. Everything seems to work on my Mango.
Should I close this?
