### ISSUE TITLE
[Alpha 3 build 20131211 - cm-11.0][Haida] Browser gets stuck-up when you open any page. 

### ISSUE THREAD

**Issue by anilgupta003** [LegacyXperia/local_manifests#276]
When i open browser and tried to open any page. The browser page got stuck-up frequently. Even i am unable to zoom in and zoom out. When i have tried to open a private(incognito) window in browser. It gets stopped and throws an error"Unfortunately, the browser has stopped"

**Comment by mikeNG** [comment]
Duplicate of #181
