### ISSUE TITLE
[11.0] haida//home screen with out icons...app drawers

### ISSUE THREAD

**Issue by Jithug** [LegacyXperia/local_manifests#278]
Version : 20131211-LX-NIGHTLY

long press home screen>settings>default screen>(change to any value)>press home button> Now it brings a home screen without icons..app drawers

**Comment by mikeNG** [comment]
Any news on latest build?

**Comment by xange** [comment]
Bug fixed on neo with build 20131225. But another bug spotted, uncheck "show search bar" will cause the widget in desktop unable to remove. Meaning the search bar will automatically turn to "remove" zone when widget is dragged, but when unchecked, the "remove" zone is missing.
Drag app from app drawer also won't show "app's info" when uncheck the "show search bar" too.
