### ISSUE TITLE
cm-11.0-20131211-LX-Nightly-Coconut - Display turn off issue while on a call

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#279]
This issue has been occurring since I installed "cm-10.2_coconut-LX-20131204-RELEASE.zip" (earlier I used CM 10 official build). Thus I tried "cm-11.0-20131211-LX-NIGHTLY-coconut.zip" to overcome with this issue. Unfortunately still this matter exists. Have cleaned off dust and dirt which were underneath of front cover, but could not help.
This same issue, have noticed in Google search results for some CM recent updates as well. Will be a great help if you could fix this.

Thanks a lot for your effort and time on these CM builds.

**Comment by idlukakas** [comment]
Screen turn off  when I play a video after 1 minute of inactivity (sleep timer).
