### ISSUE TITLE
only 101mb internal space in hallon..alpha 3 build

### ISSUE THREAD

**Issue by taha001** [LegacyXperia/local_manifests#281]
only 101mb internal memory is left after switching to art mode in mt15i !!!
and also phone got somewhat laggy.
whatsapp running in ART mode.....How is that possible?
how can i provide you the logs?

**Comment by soulpower11** [comment]
It is not a bug because ART makes application bigger

**Comment by karandpr** [comment]
A) Please read the second post . 
http://forum.xda-developers.com/showthread.php?t=2545357
B)Logs are not needed since it's not an issue .Art takes more space is a fact .
C)Use this app to take logs 
https://play.google.com/store/apps/details?id=com.tortel.syslog
