### ISSUE TITLE
cm-11.0-20131211-LX-NIGHTLY-anzu - wi-fi not working anymore

### ISSUE THREAD

**Issue by ht204** [LegacyXperia/local_manifests#282]
when i press the wi-fi button it just says it's turned off. nothing happens.

wi-fi worked perfect with cm-11.0-20131127-LX-NIGHTLY-anzu

thanks for great work !

**Comment by ht204** [comment]
logcat deleted.

**Comment by mikeNG** [comment]
1. don't post the logs directly, use pastebin or a similar service
2. the log you provided shows nothing
3. provide dmesg log

**Comment by ht204** [comment]
thanks for writing back,

dmesg log here u go: http://pastebin.com/vUxyjUCs

**Comment by mikeNG** [comment]
again there's nothing in the log
reboot your device and try turning wifi on, then get the log again

**Comment by ht204** [comment]
ok - reboot took 5 mins.

the problem is i can't enable wifi. under settings > slide the wi-fi to on, and it just stays dark grey. i have tried several times, and waited several minuttes. usually it takes like 3 seconds.

just below - if i do the same thing with bluetooth, it takes like 3 seconds and then it turns on and is 'light blue'. so that works.

i have just updated the pastebin with 'fresh' dmesg log.

**Comment by mikeNG** [comment]
The problem is that the log buffer is too small and fills up very quickly, so initial kernel messages are lost.

In the new log there is still no info because it seems that zram crashes all the time. Try disabling zram in performance settings and reboot again getting a new log.

**Comment by karandpr** [comment]
Can you post

```
 lsmod 
```

?

**Comment by ht204** [comment]
disabled zram (was at 18% - default) and rebooted. reboot went faster this time.

updated pastebin log.

using command adb shell dmesg. tried lsmod as su, no output in terminal.

**Comment by flavio23** [comment]
La grabadora sigue sin funcionar

**Comment by ht204** [comment]
? use english, man. accidently closed the thread, ignore that. see above.

**Comment by karandpr** [comment]
Now do one thing 
in adb shell
go to 

```
/system/lib/modules
```

```
insmod compat.ko
insmod cfg80211.ko
insmod mac80211.ko
insmod wl12xx.ko
insmod wl12xx_sdio.ko
```

Then try switching WiFi .
If insmod fails 
paste the log of failure

**Comment by ht204** [comment]
```
root@anzu:/ # cd system/lib/modules

root@anzu:/system/lib/modules # insmod compat.ko
insmod: init_module 'compat.ko' failed (Exec format error)

255|root@anzu:/system/lib/modules # insmod cfg80211.ko
insmod: init_module 'cfg80211.ko' failed (Exec format error)

255|root@anzu:/system/lib/modules # insmod mac80211.ko
insmod: init_module 'mac80211.ko' failed (Exec format error)

255|root@anzu:/system/lib/modules # insmod wl12xx.ko
insmod: init_module 'wl12xx.ko' failed (Exec format error)

255|root@anzu:/system/lib/modules # insmod wl12xx_sdio.ko
insmod: init_module 'wl12xx_sdio.ko' failed (Exec format error)

255|root@anzu:/system/lib/modules # ls
cfg80211.ko
cifs.ko
compat.ko
mac80211.ko
wl12xx.ko
wl12xx_sdio.ko
```

wi-fi still doesn't work after these commands.

**Comment by mikeNG** [comment]
part of the log:

```
version magic '3.4.72-nAa+ preempt mod_unload ARMv7 ' should be '3.4.70-nAa+ preempt mod_unload ARMv7 '
```

seems that you use the wrong kernel this whole time...

**Comment by ht204** [comment]
erm... file that's flashed is: cm-11.0-20131211-LX-NIGHTLY-anzu.zip

from: http://legacyxperia.basketbuild.com/index.php?dir=main/cm11.0/anzu/nightlies/
cm-11.0-20131211-LX-NIGHTLY-anzu.zip    1729 DLs    180.6 MB    12.11.2013 07:46 am

i did not change the zip in any way, i put it on the sd-card direct and used recovery to flash it + the latest gapps: gapps-kk-20131119-lite.zip    19634 DLs   77.6 MB     12.10.2013 06:25 am)

maybe you are confusing it for 1210, since .72 seems newer than .70 ?

**Comment by mikeNG** [comment]
what is your current kernel version? if it's not 3.4.72 then you didn't flash the included boot.img

**Comment by ht204** [comment]
oops. there you go. uname -a command gave a 3.4.70 response, from 11/27. i flashed the same old boot.img... f*ck damn it. i flashed the new boot.img in fastboot mode, then i had to re-install the rom + gapps - and now wi-fi is working fine. i'll close this thread and hope someone else can learn from it... 

thanks for all the help. let me know if there's anything i can test at some point.

ps. you just earned a buck for a beer, mike! - still i wonder about that zram... maybe those settings need to be tweaked. oh well. i guess i'll leave that part up to you :)
