### ISSUE TITLE
Cannot install more than 2 apps while using ART runtime-HALLON(build3)

### ISSUE THREAD

**Issue by taha001** [LegacyXperia/local_manifests#284]
Dear Developer..inspite of your efforts seprating the partitions to new values in internal memory...ART runtime is working flawlessly[THANK YOU 4 YOUR EFFORTS]................but..not more than 2 apps can be installed while using ART runtime.
i tried unstalling apollo music,default browser but to no use.
Google Chrome itself takes around 79mb of internal memory.

Cant we use partition on our sd card for distributing system memory?
As ram can be expanded too by switching it on memory card

view this:http://forum.xda-developers.com/showthread.php?t=2346389

**Comment by padishah** [comment]
Congragulations.! Well done. No one said to switch to ART runtime.
