### ISSUE TITLE
VIDEO RECORDING ISSUE - cm-10.2_coconut-LX-20131112-NIGHTLY

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#285]
Hi,

cm-10.2_coconut-LX-20131112-NIGHTLY  issue.

1.When recording Video, audio not getting recorded
2.Auto brightness problem.(After getting 2 or more calls the brightness automatically going into auto mode)

Kindly help me out..

**Comment by LillyWho** [comment]
i have the coconut too, myabe i can reproduce it.
or it is caused by a modification that you could have done

**Comment by Funt58** [comment]
CM10.2 coconut-LX-20131204-Release
sound recording does not work in the camcorder. SE wt19i

**Comment by mikeNG** [comment]
Duplicate of #258
