### ISSUE TITLE
[CM11][Anzu] wechat problem in lx 4.4.1 build 20131210

### ISSUE THREAD

**Issue by dani010** [LegacyXperia/local_manifests#286]
hi , at first i want to tnx to you for your great works . at the end i find out how to get logs :laughing: there is problem i some part of wechat : 1.using Walkie Talkie 2. add friend with Hold Togheter 3. Shake 4. People Nearby
here is the my log : https://gist.github.com/dani010/7943966

**Comment by karandpr** [comment]
Are you using Link2SD ?

**Comment by dani010** [comment]
no , wechat is not in sd card its in internal storage

**Comment by mikeNG** [comment]
logs show it's an app bug
