### ISSUE TITLE
cm-11.0-20131211-LX-NIGHTLY-mango - recorder bug

### ISSUE THREAD

**Issue by flavio23** [LegacyXperia/local_manifests#288]
- The recorder does not work

**Comment by idlukakas** [comment]
Pls check if anyone already reported this in bugtracker before. Duplicate https://github.com/LegacyXperia/local_manifests/issues/258

**Comment by karandpr** [comment]
Duplicate ! Closed !

**Comment by flavio23** [comment]
OK GRACIAS
