### ISSUE TITLE
Nightly CM11 for Xperia Ray [Wifi and Bowser Bugs]

### ISSUE THREAD

**Issue by egonzalez469** [LegacyXperia/local_manifests#291]
Wifi and native bowser arent workin correctly, wifi is disconectin and conectin and bowser is too slow, i resolve the bowser problem change it by Chrone but wifi issue is a problem in special when i try to play online

**Comment by karandpr** [comment]
Duplicate 
https://github.com/LegacyXperia/local_manifests/issues/181
