### ISSUE TITLE
cm-11.0-20131211-LX-NIGHTLY-coconut - Can't turn wifi on at all.

### ISSUE THREAD

**Issue by Phalk** [LegacyXperia/local_manifests#292]
Clean install, factory reset, wifi won't turn on no matter what I do.

Tried turning it on via console command (svc wifi enable), the console shows the message "Killed".

Sorry if this bug is already known.

**Comment by karandpr** [comment]
What kernel are you using and paste the output of

```
 lsmod 
```

**Comment by Phalk** [comment]
The default kernel included in the zip file. I'll provide some logs...

**Comment by Phalk** [comment]
http://pastebin.com/QuBsGULv - Logcat

I'm kinda new to those business, so I couldnt get the output of this lsmod you asked. If you could give me some directions I would gladly provide it.

Thanks and sorry for being unable to provide enough information.

**Comment by karandpr** [comment]
```
adb shell lsmod
```

In CMD Terminal or

```
lsmod
```

In Terminal Emulator .

**Comment by Phalk** [comment]
Nothing actually happened. Do you need the logs?

**Comment by Phalk** [comment]
In addition, wifi is working properly in the 20131127 release.

**Comment by karandpr** [comment]
The kernel of 20131127 is different from 20131211
The drivers are incompatible with each other .
You are using the wrong kernel .
Please check this issue and fix it accordingly .

https://github.com/LegacyXperia/local_manifests/issues/282
