### ISSUE TITLE
low internal memory due to partioning....need swapping to make device flying

### ISSUE THREAD

**Issue by taha001** [LegacyXperia/local_manifests#293]
Heya...cm11 build3 has new partioning...but it seems to be very low as link2sd aint linking apps to extsd completely resulting into low memory...also art runtime eats up huge amount of memory.

Its been very crucial now to swap our internal memory to external sd card....Dear Developer please provide partitions on sd card so that our devices can breathe with devices having high internal memory.
Thank you very much for ur efforts

**Comment by padishah** [comment]
@taha001 it is not wish list site. it is a bug tracker. you have already sumbitted this issue with art. why dublicating?

https://github.com/LegacyXperia/local_manifests/issues/284

**Comment by taha001** [comment]
let developer answer :@

**Comment by mikeNG** [comment]
No need to answer the same things 100 times but here you go again:
1. ART is not officially supported by me or CM so if you use it you are on your own
2. We cannot depend on the user having a large enough sdcard and having to partition it in a very specific way.

No more discussion on this, I've been saying the same things for 2 weeks and people don't understand
