### ISSUE TITLE
cm-11.0-20131211-LX-NIGHTLY-satsuma Wi-Fi won't turn on

### ISSUE THREAD

**Issue by Thedarkfly** [LegacyXperia/local_manifests#296]
![screenshot_2013-12-14-17-14-30 1](https://f.cloud.github.com/assets/6185837/1748747/c27409ae-64db-11e3-993a-2e71b575408d.png)

When Wi-Fi turned on, the switch stays greyed out and the Wi-Fi doesn't start.

**Comment by karandpr** [comment]
Please flash Latest Kernel . Not an Issue .
https://github.com/LegacyXperia/local_manifests/issues/282
https://github.com/LegacyXperia/local_manifests/issues/292

Closed !
