### ISSUE TITLE
Bluetooth A2DP lag and sound freezes.

### ISSUE THREAD

**Issue by rkkoszewski** [LegacyXperia/local_manifests#297]
While listening to music in my Car Radio via Bluetooth A2DP the sound lags, cracks and freezes for some seconds randomly. I've tried the A2DP function from Bluesoleil (It's purpose is to listen to music from the phone on the PC using A2DP) and the same sound lags, cracks and freezes appear, so it's not caused by the Car Radio nor the PC.

In "LegacyXperia 11.0 Alpha1" on a fresh install it was working properly.. but after some days the sound started to do this kind of strange things.. Now after releasing the latest LegacyXperia 11.0 Alpha3 I've done a clean install (Formatting System, Data, Dalvik & Everything).. And it has the same issues again. 

I've been using LegacyXperia {4.3} and I had the same Bluetooth issues. In Gingerbread and in ICS I never had this issues, so it's probably because of the new Bluetooth Stack introduced in 4.3.

I don't know what causes this.. Sometimes I can listen music for one hour and no lag appears.. and in other moments the sound lags so much it is just annoying listen to..

I've been monitoring CPU and process activity (Using OS Monitor) while it was happening.. and Total CPU usage was barely between 7 to 9%.. So it's not a caused because of too high CPU activity.

I've been using Poweramp and Apollo, having in both the same problem.

From inside of "OS Monitor" when I open the Logcat console of the Bluetooth process no messages appear.. Is there any way of getting the Bluetooth.apk log? Maybe there is a clue of what's happening.

I hope the developers will read this.. Because the ROM is just perfect and smooth but I use Bluetooth A2DP everyday, and it's terribly annoying. Hope we'll find some way to fix this.

Greetings.

**Comment by mikeNG** [comment]
Any news on latest build?

**Comment by rkkoszewski** [comment]
I have updated the ROM to the latest build (with clean install).. Have tested bluetooth for an half hour and until now everything seems to be running fine without any bigger lags or freezes.. I'll come back after some weeks of testing let's see what happens.

**Comment by xange** [comment]
Tested 20131225 build on hallon/neo with mw600 in 1 hour duration. no sound freeze or any bugs detected at the moment.

**Comment by Dilesh** [comment]
for me it dont gets freeze or bugs but phone gets really hot while using the headset with  A2DP

**Comment by rkkoszewski** [comment]
Hello, it's me again. I have updated my ROM to the latest version and I'm getting the cracks and lags again while listening to music using A2DP (Bluetooth).
After a fresh install it was lagging, but after +-1 day it sounds perfectly again. But there are still moments with heavy lags (But they have become more rare).
Anyway here is a link with the recorded lag: http://www23.zippyshare.com/v/31882189/file.html
Maybe somebody knows what could cause this.. (In case of doubt, this didn't happened in stock Sony ROM's)

Greetings.

**Comment by mikeNG** [comment]
Please try latest build and provide logs if this still happens

**Comment by rkkoszewski** [comment]
Hello, right now I'm using build cm-11.0-20140203 and Bluetooth is working correctly. Sound has sometimes micropauses (Which happens whichout Bluetooth too) which may be caused of the older sound system API or whatever. I confirm that on my side (HAIDA) the heavy Bluetooth Sound lags are gone. Thanks for fixing it!!
