### ISSUE TITLE
[CM11.0] Anju : After updating the latest build cm-11.0-20131211, couldnt able to login google account, lost contacts, msgs, crashes

### ISSUE THREAD

**Issue by ksranjith786** [LegacyXperia/local_manifests#301]
After upgrading to cm-11.0-20131211-LX-NIGHTLY-anzu.zip, I am unable to login to Google account, play store is no more accessible, all the contacts, msgs were lost.
Also, most of the apps are stopped abruptly while opened.

**Comment by karandpr** [comment]
No logs .Vague description . This is not a ROM issue .

**Comment by ksranjith786** [comment]
Please let me know, how shall i collect log information.
I couldnt able to login to Google account too.

**Comment by mikeNG** [comment]
there is a whole post in the q&a thread telling how to get logs!

**Comment by ksranjith786** [comment]
For eg, I tried to open "MCube" app, which leads to error "Unfortunately Mcube has stopped".
In /dev/log/system I found some logs.

Do u mean this ?
