### ISSUE TITLE
[cm-11.0-20131211-LX-NIGHTLY-anzu] Firefox for Android hangs on start.

### ISSUE THREAD

**Issue by mischa143** [LegacyXperia/local_manifests#303]
Firefox 26 on my Anzu starts and then displays a black screen. Afterwards I have to press home to back out to the home screen. The stock browser and Chrome work quite well oddly enough. Does anyone else experience this?

Logcat below. Search for lines that have 'org.mozilla.firefox' they will show various timeouts etc.

https://gist.github.com/mischa143/7969554

**Comment by karandpr** [comment]
Application Issue .Contact Firefox team for support .
