### ISSUE TITLE
cm-11.0-20131211-LX-NIGHTLY-haida - Wifi not turning on

### ISSUE THREAD

**Issue by iamporus** [LegacyXperia/local_manifests#316]
Wifi doesn't turn on. The switch appears to be stuck on 'On' but it never turns blue.
Tried restarting the device several times still no success.

For the record, i did performed all the important steps 
- Format /system, then /data and then /cache 

![screenshot_2013-12-18-17-42-12](https://f.cloud.github.com/assets/1303085/1773007/de5057e0-67dd-11e3-976b-ae31e6c521fb.png)

**Comment by soulpower11** [comment]
How you tried reflashing the the kernel. ?

**Comment by iamporus** [comment]
No. I will try that out but
do i need to install the zips (cm11, gapps) again after reflashing the kernel?

**Comment by mikeNG** [comment]
You probably don't have the latest kernel installed.
Wifi should ALWAYS work, it's just you people that forget to flash the same kernel from the zip of the build you are using.

I have closed about 30 issues with the same problem because the kernel wasn't updated.

**Comment by iamporus** [comment]
You were absolutely right ! I downloaded new cm11 build and transferred it to storage but forgot to extract boot.img from it n eventually ended up using the img from eariler cm11 build.
Silly me..
Thanks. Wifi connects fine now.
