### ISSUE TITLE
(Haida CM11) Browser's Crashing & Lagging on cm-11.0-20131211-LX-NIGHTLY-haida Build. 

### ISSUE THREAD

**Issue by pharandeamit** [LegacyXperia/local_manifests#317]
Installed cm-11.0-20131211-LX-NIGHTLY-haida after release after that all working fine except Browsers.  Default Browser & Other 3rd Party browsers also Crashing unexpectedly. also All Browsers lagging while Scrolling Page. here is its System Log- http://d-h.st/g3j

Hope it'll get Fix. :D

**Comment by s-kostyuk** [comment]
Look here: https://github.com/LegacyXperia/local_manifests/issues/181

**Comment by mikeNG** [comment]
Duplicate of #181
