### ISSUE TITLE
[CM11] mango - profile does not change lockscreen

### ISSUE THREAD

**Issue by vkuhnde** [LegacyXperia/local_manifests#319]
I have a pattern lock set in the security settings. In one profile I have set the lockscreen to "lock unsecure" (I don't know the exact English description, this is what I translated) but the phone is still locked with a pattern after activating the profile.

Device: Mango
Build: Alpha 3 2013-12-11

Do you need any logs?

**Comment by mikeNG** [comment]
Was this working in cm10.2?

**Comment by vkuhnde** [comment]
Yes, it was.

**Comment by mikeNG** [comment]
Ok, wait for next build as I can see some commits that affect this got merged a few days ago

**Comment by vkuhnde** [comment]
Ok, thank you :)
