### ISSUE TITLE
[10.1-10.2] Bluetooth connection problem with carkit

### ISSUE THREAD

**Issue by humble-b** [LegacyXperia/local_manifests#32]
I can't seem to get bluetooth working with legacy xperia roms 10.1 and 10.2
If i try to connect to my carkit it finds it, even want's to connect and asks for the link code,, but after entering the code nothing seems to happen and the phone won't connect.

I have a logcat of the problem, but don't know how to attach it on the report..

logcat created with rom version: cm-10.2_mango-LX-20130809-NIGHTLY.zip

**Comment by humble-b** [comment]
I have attached the logcat at the xda developers forum on following link: http://forum.xda-developers.com/showthread.php?p=45063378#post45063378

**Comment by mikeNG** [comment]
Any news with the latest build?

**Comment by humble-b** [comment]
Unfortunately still the same. I had an working bluetooth with older build version from i believe april/may or so, but the later versions stopped working. Same results with 10.1 and 10.2 builds
If needed i can provide another logcat ..

**Comment by mikeNG** [comment]
x-one opened this issue 3 months ago
I connect the phone to the car kit via Bluetooth.
The connection seems to be stable. When the phone rings I answer a call button on the steering wheel. Phone immediately loses the connection with the car kit and the conversation is started. After a while the connection is resumed, and I can talk using the car kit.

Logs:
http://www.mediafire.com/download/47s86px26c8cp0q/2013-08-21_15.29.zip

Another situation. Connects to the car kit. After a short time I lose connection to the car kit. Phone shows that I'm still connected. I do reboo phone, turn off Bluetooth (it takes a very long time), connect it again. Not always helps. Logs will try to attach.
2 participants    

 shouvikonline commented 3 months ago 
I am also facing the same issue.
Another issue I face while listening to music via bluetooth, the volume drops after sometime, and picks up on its own and this keeps repeasting.

**Comment by humble-b** [comment]
I have updated to latest version 10.2. Problem is now that it even won't connect to the carkit.
Will try with latest 11 version and see what happens.

**Comment by humble-b** [comment]
Still the same results with the 11 version. However on google i found out that my carkit (an skoda amundsen build in my skoda superb) uses a protocol or something like that what is called rSAP (remote sim access protocol)
I will try to install http://www.android-rsap.com/installation.html and see if this is something that will help.... Keep you posted..

**Comment by humble-b** [comment]
Unfortunatly the app doesn't work with my sony xperia mini. The problem is described in the website at the compatibility list: rSAP works only on stock Sony ROMs. All CyanogenMod versions seem to have difficulties with the SIM state changes and crash when starting and/or stopping an rSAP connection.

This is most problably the reason why the pairing fails, cyanogenmod simply crashes after creating the key pair. Can cyanogenmod repair this ? The strange thing is that the carkit pairs ok when using cyanogenmod 9, so after using the newer versions the compatibility seems to be lost :-(

**Comment by humble-b** [comment]
For anybody running an amundsen carkit with the same errors i had, i found the solution in to upgrade the bluetooth device connected tot the carkit. after the update the device connects as expected... 

The bluetooth device is named kufatec fiscon so people can find these notes by searching this on google.

The new firmware can be downloaded from this link: 
http://www.fiscon-mobile.eu/products/updates.php

A note which i received from the excellent support from kufatec i received:

For SWP(Pboard)-Version like 3xxx you got HW2.

If you are absolutely unsure you can also detect this by the bluetooth name after you enable the update mode.
If the bluetooth name is "ck5050", then you got HW1.x
If the bluetooth name is "ck5050+", then you got HW2.x

Update for HW 2.x: - manual as well as update files are inside the zip-file:
http://www.kufatec.de/bt_update_3316.zip

Compatibility list for HW 2.x:
http://www.kufatec.de/fiscon/swp_3316.html

Update for HW 1.x: - manual as well as update files are inside the zip-file:
http://www.kufatec.de/__update3126.zip

Compatibility list for HW 1.x:
http://www.kufatec.de/fiscon/swp_312.html

**Comment by x-one** [comment]
After update to Release build 20140302 cm-10.1 problems with BT and car kit disappeared.
I hadn't any disconnections till now (using it everyday).
I wish it disappeared forever :)
Thank you very much :)

**Comment by humble-b** [comment]
Did you upgrdae the carkit firmware or did you just update the CM version ?
If the latter then i am amazed how quick and good the guys work at CM implementation

**Comment by x-one** [comment]
I've only updated CM to latest version (Release build 20140302 - cm-10.1)..
So far so good..
