### ISSUE TITLE
[CM11] (11/12/2013 - anzu) Several Errors

### ISSUE THREAD

**Issue by luismytronic** [LegacyXperia/local_manifests#321]
1º) it will not record video in any resolution

2º) is almost all in English (only a few things out in Spanish and I and selected

3º) leaves rename user's default (OWNER)

4º) unstable web browser

5º) camera button not working

```
         ¡ Repaired as soon as possible and thank you for your work are the best regards !
```

**Comment by xange** [comment]
1.) refer to #267 

4.) 4.4.2 alpha isn't release for xperia 2011 series yet (don't question for latest android version/updates rom, just test what mike released the latest rom for us to test or build yourself a cm11 with 4.4.2 source to test)

5.)  refer to #206 

2 and 3: no idea.....

**Comment by karandpr** [comment]
Read third post on the XDA CM11 Q/A thread .
