### ISSUE TITLE
[CM11][Haida] Browser stutters and crashes when scrolling 

### ISSUE THREAD

**Issue by Oscaruzzo** [LegacyXperia/local_manifests#325]
The default browser does not scroll smoothly. Screen "jumps" up and down in big steps when scrolling and is very un-reactive. After a few second, it just crashes.

This also happens on apps that use an "embedded" html view (Feedly, for example).

If you need any log, please tell me.

Using Nightly 20131211 on Neo V / Haida.

**Comment by dinoomanovic** [comment]
Duplicate of #181
