### ISSUE TITLE
[CM10.2][Mango][BUG][Noise suppression] Voice echo!

### ISSUE THREAD

**Issue by NEM1PRO** [LegacyXperia/local_manifests#328]
In ROM "cm-10.2_mango-LX-20131204-NIGHTLY" and "cm-10.2_mango-LX-20131215-NIGHTLY" I found a bug: my interlocutor complains that hears his voice when I have a speakerphone (i.e. Hands-Free), volume control and on/off noise suppression in dialer does not help! :((( 

p.s. In ROM "cm-10.2_mango-LX-20131108-NIGHTLY" none of this bug! Sound works properly! 
p.p.s. Sorry my bad English...

**Comment by ghost** [comment]
Just as a sidenote, tested this on anzu - Build 20131204 - cm-10.2 and no echo was present. Might be device specific?

**Comment by NEM1PRO** [comment]
Yes, this is possible only on Mini Pro (SK17i, Mango). I have not tested other devices.

**Comment by NEM1PRO** [comment]
Hello, mikeioannina. I wish to inform You that in the last ROM "cm-10.2_mango-LX-20140112-NIGHTLY" has no effect change "Disabled in-call noise suppression". (((((
