### ISSUE TITLE
Mango - Buttons issue

### ISSUE THREAD

**Issue by hcern** [LegacyXperia/local_manifests#332]
The two buttons under display on Sony Ericsson Xperia Mini Pro sometimes activate themselves rapidly and continuously. It is so fast that I can't do anything with device. The same issue is in CWM. This issue isn't in official nightly CM10.0 build.

I think that relevant log lines are here: Logcat - http://pastebin.com/zkqGUpwk starts at line 412

Other logs:
Last_kmsg - http://pastebin.com/YRa81PqV
Dmesg - http://pastebin.com/vY8KZaJm

**Comment by mikeNG** [comment]
which build did you use?

**Comment by hcern** [comment]
I tried many of them, e.g. 10.1 Release, some of 10.2 and last nightly of 11.0 (20131211) and issue is in every build which i tried.

**Comment by hcern** [comment]
If you think which build of official CM10.0. I use last mango nightly build (20130929) but issue isn't also in previous builds.

**Comment by hcern** [comment]
What does label cannotreproduce mean?
