### ISSUE TITLE
[CM11] ntfs on sd card, mount, but android.media stop

### ISSUE THREAD

**Issue by nefelim4ag** [LegacyXperia/local_manifests#334]
I try use ntfs on sdcard with compression, work good, but android.media stop after this.
I don't sure to mark this as bug, but this case can mark "Suggestion"
Any comments?

**Comment by mikeNG** [comment]
non-fat filesystems are not "officially" supported by LX.
Android's support isn't very good too when you use non-fat filesystems.

So, I'm closing this.
