### ISSUE TITLE
CM10.2 crash of apps while spellcheck

### ISSUE THREAD

**Issue by Micha-Btz** [LegacyXperia/local_manifests#335]
every time i write an text equal if sms or mail, the app  crashes if the word is the first of the shown list, mostly on my device is only half shown at the top of the screen. see the image for detail.  reproducible all the time

log
http://pastebin.com/dX7jvmAD

screenie
![screenshot_2013-12-24-22-05-52](https://f.cloud.github.com/assets/4420944/1807303/f7d7cb1c-6ce2-11e3-885d-11e0a9dd68b6.png)

**Comment by mikeNG** [comment]
try latest build
