### ISSUE TITLE
[CM11]  Xperia Pro : Clicking options button in main menu is not providing options to user.but options were slightly visible from backend.

### ISSUE THREAD

**Issue by arumallap** [LegacyXperia/local_manifests#339]
![screenshot_2013-12-25-19-40-46 1](https://f.cloud.github.com/assets/6259521/1808689/b9d22ad8-6d6e-11e3-8094-ef1969a2ba7f.png)

**Comment by mehfil** [comment]
Me too @Xperia Arc
