### ISSUE TITLE
[CM11] Xperia Pro : Unable to sim contacts option.

### ISSUE THREAD

**Issue by arumallap** [LegacyXperia/local_manifests#342]
Unable to save contacts by default to sim...
No options to use sim memory for contacts..
using separate apps from Google play was not as good as default one..
![screenshot_2013-12-25-19-56-59](https://f.cloud.github.com/assets/6259521/1808723/6c02ed62-6d71-11e3-88c9-e5048bf0f4fe.png)

**Comment by sk17iuser** [comment]
I can confirm that. I am missing this feature too.

**Comment by mikeNG** [comment]
what about latest cm11 build?

**Comment by mikeNG** [comment]
Feature added in next build
