### ISSUE TITLE
lockscreen bypass with menu key on xperia mini pro(mango)

### ISSUE THREAD

**Issue by amey6a** [LegacyXperia/local_manifests#343]
hi mike, i am running latest cm11 build 20131211-LX-nightly) just fresh installed, whenever i press menu key on lock screen it just bypass to home screen. is there any thing i can do from my side or have to wait for next build. thanks in advance..........

**Comment by mikeNG** [comment]
wait for today's build

**Comment by amey6a** [comment]
that's what i call full dedication......it will be my honor to donate to a person who really cares.....thank you......
