### ISSUE TITLE
Notification sound in phone speaker when use headset

### ISSUE THREAD

**Issue by ericesteves** [LegacyXperia/local_manifests#344]
when I use headset and a notification appears (eg. a incoming message) The soung rings on phone speaker. It happens too when  I'm listening music in headset. I'm using last build (20131225) on LWW

**Comment by mikeNG** [comment]
what about latest build?

**Comment by ericesteves** [comment]
the problem must persists until build 0302

**Comment by mikeNG** [comment]
Please try latest build and provide logs if this still happens
