### ISSUE TITLE
[CM10.2 and other][Mango][Bug][Physical Keyboard] Impossibility print uppercase letters

### ISSUE THREAD

**Issue by NEM1PRO** [LegacyXperia/local_manifests#345]
Impossibility print on the physical keyboard (Cyrillic layout) of uppercase letters : X (X as the Latin [eks] and Russian Х [ch]), Ж [zhe], Ъ [hard sign], Ю [you].

![2412504](https://f.cloud.github.com/assets/6243837/1809348/b38bad64-6dd9-11e3-9abc-1822ea3bde7e.jpg)

I enclose a separate layout file (in the file .txt) for self-updating InputDevices.apk:
http://forum.xda-developers.com/attachment.php?attachmentid=2474854&d=1388027160

Autor fix: Sylar68
Original post: http://4pda.ru/forum/index.php?s=&showtopic=302719&view=findpost&p=18536059

**Comment by mikeNG** [comment]
Fix included in next cm-10.1, cm-10.2 & cm-11.0 builds
