### ISSUE TITLE
[CM11.0][anzu] wifi doesn't work at all

### ISSUE THREAD

**Issue by mokkin** [LegacyXperia/local_manifests#348]
Today I updated to the actual nightly (20131225) and wifi isn't working anymore. On the last one (20131210) it has worked without any issues for me.

**Comment by mokkin** [comment]
I went back to Alpha 3 (20131211) which works too.

**Comment by mikeNG** [comment]
follow the **exact** installation steps and it will work

**Comment by mokkin** [comment]
@mikeNG I've followed exactly the steps descriped here:
http://forum.xda-developers.com/showthread.php?t=2545354
On my first try I flashed only the new update.zip (1-3 are not necessary it says in the thread)
On the second one I repeated also steps one to three to be sure.

Is there something else important? Sorry for bottering you.
But thank you for this great ROM. If you could publish your bitcoin address I'd like to donate something to you, in case you are mikeioannina

**Comment by mikeNG** [comment]
Make sure you flashed the right kernel from inside the zip. wifi works fine on my anzu

**Comment by mokkin** [comment]
Sorry, you were right. I think I got the old kernel from a wrong directory ...
Now it's working just fine.

@mikeNG Please remember to publish a bitcoin link somewhere for donations.

**Comment by mikeNG** [comment]
I'd like to but currently I don't use bitcoin

**Comment by skoczo** [comment]
Hi, I installed the newest build for Haida(http://legacyxperia.basketbuild.com/index.php?dir=main/cm11.0/haida/nightlies/) and have the same problem. Wifi don't work.
Install steps:
1. Download "cm-11.0-20131225-NIGHTLY-LegacyXperia-haida.zip"
2. Copy file to sd card
3. Install by CWM

Did I do something wrong? When I restored old build (by CWM) everything works fine.

**Comment by ketkul** [comment]
@skoczo Try this...
1. Download "cm-11.0-20131225-NIGHTLY-LegacyXperia-haida.zip"
2. Copy file to sd card
2.1. Extract boot.img from zip
2.2. Reflash the kernel. I think Mike update the kernel, so use the new one.
2.3. Wipe everything.
3. Install by CWM

**Comment by skoczo** [comment]
Do i need to do wipe? How to reflash kernel?

**Comment by mspacek** [comment]
@skoczo Check the wiki for installation guides:

https://github.com/LegacyXperia/Wiki/wiki

**Comment by mspacek** [comment]
@mokkin You can donate to mike via paypal by clicking on the donate link at the xda-developers forum thread here:

http://forum.xda-developers.com/showthread.php?t=2545367

**Comment by mokkin** [comment]
@mspacek I already did to @mikeNG

**Comment by mspacek** [comment]
@mokkin Me too! :)
