### ISSUE TITLE
[Nightly build 20131225 - cm-11.0 - coconut] Back and menu buttons issue

### ISSUE THREAD

**Issue by azakosath** [LegacyXperia/local_manifests#349]
Hi Mike and Merry Christmas,
back and menu buttons are not working in latest build, there is a vibration feedback on touch, but that's it (long press of menu button launches Google Now though). Neither logcat, nor dmesg capture anything... I flashed the update zip normally as all the other times before. I tried again, but this time wiping cache and dalvik cache, no luck. The only thing I didn't do is flashing the gapps (I never do after first installation). Key test app doesn't show anything...

Best wishes for a happy New Year

edit: actually key test app (https://github.com/chrisboyle/keytest/downloads) doesn't recognize any button. I'm sure it worked with apha 1 and 2 builds, I didn't try it with alpha 3. 

edit 2: I can change the action of menu button (e.g. to Recent apps switcher) and it works. But when I try to change home button to open/close menu, then this action doesn't work. So, are the actions "back" and "open/close menu" not working?

edit 3: I just checked the boot.img size in order with the previous build and they are exactly the same. Is there a chance that you forgot to update the boot.img inside the zip?

**Comment by Kro11** [comment]
I have the same problem:( [Nightly build 20131225 - cm-11.0 - coconut]

**Comment by amishmm** [comment]
For me back button and menu button works... coconut 20131225.

Only thing is I have following added in build.prop: (to get expanded desktop)
qemu.hw.mainkeys=0

May you can try that.

**Comment by azakosath** [comment]
@amishxda indeed, after adding that line back button started working, even without reboot, as soon as I saved the file. And after rebooting menu button started working too. But, I can't say that I like how extended desktop looks ;-)
Even key test app is working now....

edit: In order to satisfy my taste (after some searching in Google), I changed the value to 1

**Comment by amishmm** [comment]
Go into settings-interface-expanded desktop - set status bar visible

Now press power button - enable expanded desktop

you will get your normal look back

**Comment by azakosath** [comment]
Oops, we were writing the same time. I've just seen your post. Actually, I was referring to the button bar at the bottom of the screen. Nevertheless, thanks for your help.

**Comment by amishmm** [comment]
Yes if u set it to 1 then button bar will go.

If u set it to 0 and use above settings, button bar will hide automatically and appear when u swipe up from bottom of screen.

I use this setting so that i dont have to press hardware home button which is tough to press when u r in a crowded place or holding mobile plus one more thing in same hand.

**Comment by mikeNG** [comment]
So, qemu.hw.mainkeys=1 fixes the hardware buttons with no visual changes?

**Comment by azakosath** [comment]
That's right...

**Comment by amishmm** [comment]
I think it works like this

If qemu.hw.mainkeys line is missing, then system tries to auto detect hardware buttons, but in current ROM it fails, so they dont work.

when line is present it simply assumes that hardware keys are there, so they magically start working
0 = will also show software buttons
1 = do not show software buttons

**Comment by mikeNG** [comment]
This is weird when looking at the source. qemu.hw.mainkeys is intended only for use with android emulator on pc. I couldn't find the place where the check for hardware keys happens that is affected by qemu.hw.mainkeys.

**Comment by azakosath** [comment]
@Kro11 did you add the line mentioned above to build.prop, save the file and reboot? If yes, then I think you are referring to these issues #12 and #195, where in my opinion the "back" button works, but it's just a bit laggy. 

@mikeNG I think that the issue existed already #254, I didn't see that before I open this one, even though I did search.

**Comment by godlesplay** [comment]
for me back and menu buttons are working but back button doesn't work when I'm updating swiftkey ( I removed stock cm keyboard ) then I must tick swiftkey again in settings>input and then back button is working again (se lww cm11 25.12)

**Comment by Kro11** [comment]
Yes, I have the same problem https://github.com/LegacyXperia/local_manifests/issues/195

**Comment by ksranjith786** [comment]
It worked well with the build. Doesnt find any problem.

**Comment by azakosath** [comment]
Fixed in latest build 20140113, without the need of the additional line in build.prop.

**Comment by azakosath** [comment]
Mike, a strange thing. I've just installed build 20140121 and the buttons were again stopped responding. So, I went to build.prop to add the line for the workaround. When I tried to edit the file I saw that the keyboard wouldn't appear and I went to settings (input and language) to enable it. And by that time buttons started working normally....
Just reporting...

**Comment by mikeNG** [comment]
I had this bug when I flashed some builds without gapps a few days ago... but nothing in the logs indicating where's the problem.

**Comment by godlesplay** [comment]
as I wrote: "for me back and menu buttons are working but back button doesn't work when I'm updating swiftkey ( I removed stock cm keyboard ) then I must tick swiftkey again in settings>input and then back button is working again (se lww cm11 25.12)"

touch buttons doesn't work when keyboard is not enabled, IMO

**Comment by azakosath** [comment]
@godlesplay maybe this is the case, because I don't use the default keyboard either. I'm flashing an Xperia's one after every update. But, I don't remember if I had the AOSP keyboard unchecked or not before flashing the last build and right now I'm too lazy to reflash the ROM over again to confirm that. If this is true, then adding the line to build.prop:

qemu.hw.mainkeys=1or 0

it was just a placebo, because it was forcing us to enable the keyboard.

**Comment by azakosath** [comment]
Ok, here it is. Because, I was lazy and I didn't want to flash the new build over again, I thought to disable Xperia's keyboard and then to freeze AOSP's one. The result was trebuchet to give repeatedly FCs (and some other processes) and I couldn't do anything else than reboot. After reboot, everything was working smoothly except back and menu buttons. So, godlesplay's assumption turns out to be correct.
