### ISSUE TITLE
[10.2-11.0] Android camera green tinge

### ISSUE THREAD

**Issue by jlmcr87** [LegacyXperia/local_manifests#35]
Latest 8/28 build. Android camera shoot animation has a green tinge on anzu

**Comment by jlmcr87** [comment]
![screenshot_2013-08-29-10-31-14](https://f.cloud.github.com/assets/4967467/1048210/1b1e79cc-1086-11e3-9fbc-231ba9ede172.jpg)

**Comment by dinoomanovic** [comment]
Same on haida.
Also Focal preview blinks green.

**Comment by MIXTERek** [comment]
probably all devices (i have mango and coconut and its buggy)

**Comment by djey47** [comment]
Device : haida
App : JB Camera

In addition, I notice a green/violet tint on right hand part of the saved picture + in one part:

![media-20130904](https://f.cloud.github.com/assets/2901949/1079078/b01b8bc6-153d-11e3-8594-102035764a08.jpg)

**Comment by jtdcjtdc** [comment]
have you tried using other camera app?  also at this stock camera app, the end image is not green, if you're concerned with that.

**Comment by mikeNG** [comment]
Can't be fixed, incompatibility between adreno libs, camera libs, kernel display drivers, android display drivers & pmem. Might be fixed if we use an ION based kernel.
