### ISSUE TITLE
[cm11 20131225] wifi not turning on (anzu)

### ISSUE THREAD

**Issue by tonyjkottaram** [LegacyXperia/local_manifests#350]
On previous versions, wifi had issue!! But since upgrading to the latest version, my wifi doesnt switch on.
Hope a fix will be out soon.
Thank you

**Comment by mikeNG** [comment]
follow the **exact** installation steps and it will work

**Comment by tonyjkottaram** [comment]
Do i have to flash the new kernel as that is the only part that i left out!!

**Comment by mikeNG** [comment]
Why???? It is stated multiple times in my xda threads that you ALWAYS need to flash the kernel

**Comment by ingmaki** [comment]
Hi, I am noob in this. I have a SE Xperia Arc S and I had updated my rom to KitKat and the wifi did not work anymore. I tried the last cm-11.0-20140121-NIGHTLY-LegacyXperia-anzu.zip but it does not work yet. Please, can you explain me how I flash the kernel?
