### ISSUE TITLE
[11.0] [Anzu] "Block incoming messages" is not working

### ISSUE THREAD

**Issue by lctncld** [LegacyXperia/local_manifests#353]
Using build from 2013-12-25. Incoming calls are blocked fine.
http://pastebin.com/3tpHE8CM

**Comment by azakosath** [comment]
Edit the number you want to block by adding the national code in frond (with "+" or "00" it doesn't matter).

**Comment by lctncld** [comment]
Actually I was talking about "Unknown numbers". Rule with wildcard to match everything doesn't work either.
Maybe this is related to the dialer app, because it works in [10.2].

**Comment by mikeNG** [comment]
Do you use the stock messaging app?

**Comment by mikeNG** [comment]
please try the latest build

**Comment by lctncld** [comment]
Thank you, this issue is fixed.
