### ISSUE TITLE
[CM11.0][haida]Video mode in camera doesn't work at all.

### ISSUE THREAD

**Issue by maruti40471** [LegacyXperia/local_manifests#354]
After installing cm-11.0-20131225-NIGHTLY-LegacyXperia-haida,the video mode in camera doesn't work (whatsoever be the resolution).Kindly rectify it in the next update.
Thanks for KITKET in xperia 2011 devices.

**Comment by godlesplay** [comment]
recording video is fixed, wait for new nightly
