### ISSUE TITLE
[CM 10.2] Anzu: Build 20131204 - Slider Shortcuts

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#355]
When customizing the Slider Shortcuts by removing all but the left and right (unlock) shortcut it is possible to unlock the phone by sliding to the "now empty" shortcut spaces.  (10:30, 12:00 and 13:30 o'clock possitions). Is this intended?

**Comment by mikeNG** [comment]
Yes. If you press the reset button all the shortcuts are gone too but then you can unlock by pulling the slider at every direction (like AOSP behaviour)
