### ISSUE TITLE
[cm11] Media Provider Scan SD card in Dev Tools FCs

### ISSUE THREAD

**Issue by sidharthgtm** [LegacyXperia/local_manifests#356]
attached log : http://pastebin.com/yB76DWxe

**Comment by ghost** [comment]
It's the same for me.

**Comment by mikeNG** [comment]
https://code.google.com/p/android/issues/detail?id=62134

**Comment by mikeNG** [comment]
why you need to do this?

**Comment by mikeNG** [comment]
If you just want to rescan the sd card, you can simply tap the refresh icon under settings -> storage

**Comment by sidharthgtm** [comment]
in cm11 (latest build) i was facing problem android.media force close so i decided to clear data of Media Storage ..
which worked for it .. eventually the FCs where gone .. but after that gallery did not showed images and even Apollo was not able to detect music ..after a couple of restart in order to  media scanner scan my devices .. i gave Media Scanner a try.. which indeed gave a fc.. i m back to cm10.1 .

I m using a 16 gb sd card with 1 gb ext3 partition in cm10.1 it works great but when i go back to latest cm11 build .. the android.media fc randomly persists.

**Comment by sidharthgtm** [comment]
my bad i could not take any logcat of that error :-1:

**Comment by sidharthgtm** [comment]
i will try the latest build for android.media  fcs error , since this is a ASOP bug . this issue can be closed.

**Comment by mikeNG** [comment]
https://android-review.googlesource.com/#/c/78852/
http://review.cyanogenmod.org/#/c/57514/

**Comment by mikeNG** [comment]
fixed
