### ISSUE TITLE
[cm 11]fastboot mode in my lww

### ISSUE THREAD

**Issue by nivdeep** [LegacyXperia/local_manifests#359]
My lww is not recognized in fastboot mode when i connect it to my windows 8.1 laptop,when i made a search about it i understood it was about drivers which aren't compatible with latest windows update any more,plz provide a solution,im running cm11-20131211-unofficial coconut. 
                                              thank u for ur effort.

**Comment by sidharthgtm** [comment]
Windows 8.1 broke fastboot. 
Use older version of windows..  
Issue not related to rom and development.

**Comment by ghost** [comment]
This is not a tech support. Go away.
