### ISSUE TITLE
Does it work Ant + in cm10.1 or cm10.2?

### ISSUE THREAD

**Issue by lowato** [LegacyXperia/local_manifests#36]
Hi!
I'm spanish, so sorry for my English.
I want to know if the ANT + protocol work in cm10.1 and cm10.2.
Thanks.

**Comment by jlmcr87** [comment]
This is not a forum or a chat for make stupid questions, this is only for report bugs. Please close this

**Comment by mikeNG** [comment]
@jlmcr87 Right

**Comment by lowato** [comment]
Ups!
Sorry, I didn't know it.
