### ISSUE TITLE
[cm11][coconut][build cm-11.0-20131225] VERY SLOW BROWSER

### ISSUE THREAD

**Issue by braianrq** [LegacyXperia/local_manifests#361]
Browser works pretty slow moving and writing, bears much lag. It's the same with the default browser and any other browser like Dolphin Browser, Firefox, Google Chrome, Opera, etc..
Please repair this bug and solve the poblem of Minecraft Pocket Edition - The application has stopped - when the same is minimized, the screen is turned off or when you close the game.

**Comment by ghost** [comment]
Every issue needs to be reported separately with logs attached. Enjoy your closed bug report.
"any other browser like Dolphin Browser, Firefox, Google Chrome, Opera, etc.." NOPE. If you have problems with these browsers then you are doing something wrong.
