### ISSUE TITLE
CM 11 iyokan version - Issue with flight mode

### ISSUE THREAD

**Issue by vivnair** [LegacyXperia/local_manifests#364]
After Air-Plane mode is turned ON and later when we turn it OFF the network does not comes up and the phone is still in air plane mode even though we have switched Air Plane mode OFF.
Have to Reboot the phone after switching off the AirPlane mode to get the network back.

**Comment by djey47** [comment]
This issue seems to exist in CM 10.2 already. But does not happen everytime, and logs don't show anything relevant...  So it won't be fixed.

And yes, rebooting is the only workaround for now.
