### ISSUE TITLE
[cm11][urushi][build cm-11.0-20131225] OUT OF SPACE

### ISSUE THREAD

**Issue by badboyasd** [LegacyXperia/local_manifests#365]
WHEN I INSTALL SOME APP FROM MARKET AND MOVE THEM TO SD CARD, I GET ERROR OUT OF SPACE, AND I CAN'T INSTALL ANY APP. ON CM10.1 , IT WORK WELL .

**Comment by ghost** [comment]
Is your Caps Lock broken? Try hitting your head with a keyboard really hard it should help.

**Comment by padishah** [comment]
pypcz LoL
