### ISSUE TITLE
haida - build cm-11.0-20131225 wi-fi problem

### ISSUE THREAD

**Issue by huseyinzengin** [LegacyXperia/local_manifests#366]
Hello,

latest build has a wi-fi issue. open wi-fi button not work, when you click it seems trying to open wi-fi but not success.

**Comment by ghost** [comment]
Read this http://forum.xda-developers.com/showthread.php?t=2543426 and stop wasting other people's time.

**Comment by huseyinzengin** [comment]
I know this threat. I'm revert back cm-11.0-20131211-LX-NIGHTLY-haida. it work perfect. 4.4.2 has a wi-fi issue. cannot control wifi hardware.
