### ISSUE TITLE
[urushi] [cm10.2-20130828] WiFi 

### ISSUE THREAD

**Issue by tisz03** [LegacyXperia/local_manifests#37]
Just updated to the new nightly. Now Camera app works okay, but WiFi doesn't even work. ( in the last nightly wifi was just dropped sometimes, but disable and enable wifi and was okay again)
If needed any log or something I can help with the problem, let me know.
![screenshot_2013-08-29-13-01-01](https://f.cloud.github.com/assets/5325149/1049105/f7066fd0-109a-11e3-853a-960412bd11a2.png)
![screenshot_2013-08-29-13-01-14](https://f.cloud.github.com/assets/5325149/1049106/f718f11e-109a-11e3-9ba1-8ce8fa200ad3.png)

**Comment by jlmcr87** [comment]
Have you flashed the kernel inside the zip?

**Comment by tisz03** [comment]
Just flashed it right now, well I thought I don't have to flash it to the new update, like with official cm10.
But whatever, now it's okay I think, thanks for help.
