### ISSUE TITLE
[cm11][smultron][build cm-11.0-20131225] random reboots

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#370]
st15i randomly reboots every day.

**Comment by ghost** [comment]
why closed ?

**Comment by cajhin** [comment]
No data. "Random reboots" is like "my device has a problem I think". What should Mike do with that?

Provide a last_kmsg log 
https://github.com/LegacyXperia/Wiki/wiki/Reporting-problems

**Comment by ghost** [comment]
how should I know what the cause is, it is just like it is, random reboots, this means the build does not work properly....I will stop bug reporting, appreciation is not in the vocabulary here.

**Comment by cajhin** [comment]
exactly, how should anyone know what the cause is, unless there is a log file to look at.
That's why Mike said every bug report needs a log file, and I asked you for a last_kmsg log.

**Comment by mikeNG** [comment]
If you didn't even bother reading the bug reporting rules in the Q&A thread in xda, how do you expect appreciation?
