### ISSUE TITLE
[CM10.2][Haida-LX-20131215-NIGHTLY] Crash in Audio FX application

### ISSUE THREAD

**Issue by djey47** [LegacyXperia/local_manifests#372]
Audio FX sometimes FCs when enabled and headphones connected for a while.

See log at :
https://gist.github.com/djey47/8282894

**Comment by mikeNG** [comment]
Any news on latest build?

**Comment by djey47** [comment]
Testing latest build with headphones + Audio FX enabled,  since yesterday, no crash has happened so far. 
I'll continue testing so you can close issue in a few days I hope :)

**Comment by djey47** [comment]
Closed : Issue has gone, thanks.
