### ISSUE TITLE
[10.1-10.2-11.0]Wifi WPA2 Enterprise / 802.1x EAP not working

### ISSUE THREAD

**Issue by streumix** [LegacyXperia/local_manifests#376]
Wifi cannot connect in case of WPA2 enterprise security / 802.1x EAP ( PEAP /  MSCHAPV2 ). Credentials are verified to work with other devices.
Other security modes on other nets (e.g. WPA2) do work.
Tested with any CM 10.2 nightly on urushi/ray starting backing in september 2013 until to the latest 10.2 / 11 nightly.
SEMC stock firmware does work. Is this a generic Android >= 4.2 issue ?
Regards,
Toby

**Comment by rufussino** [comment]
It also does not work on WPA enterprise (tested on eduroam), similar to https://github.com/M66B/cm-xtended/issues/179 .

Syslog here: https://www.dropbox.com/s/kh4eygv63083l9a/2014-01-08_09.17-Githubbug.zip

**Comment by natanE** [comment]
same for me both in 10.2 and 11.0
it was claimed to be solved on other threads, but not for my device/work configuration. (PEAP/MSCHAPv2)
it can connect at home (using WPA2)

worked when changing to MIUI

using coconut

**Comment by rufussino** [comment]
I think it's connected to wpa_supplicant... PEAP/MSCHAPV2 is the problem.

**Comment by lezka2010** [comment]
Sorry,
I no have a log, because my home is very long way to uniwersity. I have CM10.1 NeoV. Please fast fix it

**Comment by rufussino** [comment]
Logs are in my previous comment.

**Comment by lezka2010** [comment]
And ? No fix it ?

**Comment by mikeNG** [comment]
If you ask like this, no. We are not a customer service, we do this as a hobby so please don't demand things.

**Comment by mikeNG** [comment]
@streumix @rufussino wait for next cm11 build and try again.

**Comment by lezka2010** [comment]
Okay, but CM10.1 next bulid repair this ?

**Comment by streumix** [comment]
@mikeNG 
I've just tried the latest available cm-11-nightly for urushi dated 20140113, and it didn't work.
Does this nightly already contain the relevant changes ?
Do I need to do a full factory reset to get things work ? (Up to now I've just upgraded without whiping user data. All I did was deleting and re-adding the WPA2 Enterprise protected network after upgrade) .

Here's the relevant slice of the log file:

http://paste.ubuntu.com/6790397/

**Comment by mikeNG** [comment]
@streumix this is not the latest build, it's not released yet. Next time please use pastebin or a similar service to paste the logs, so we can keep comments on github readable.

**Comment by streumix** [comment]
O.K. - but what's the "critical" date ? 
I don't build stuff by my own and use releases from http://legacyxperia.basketbuild.com/index.php?dir=main/cm11.0/urushi/nightlies
Even though it's called nightly, it's more kind of a bi-weekly schedule. But that's fine. I'll wait for the next release. We'll see.

**Comment by streumix** [comment]
Now I've tested nightly 2014-01-21. No success.
Logs are here:
http://paste.ubuntu.com/6837413/

**Comment by mikeNG** [comment]
wpa_supplicant: SSL: SSL3 alert: write (local SSL3 detected an error):fatal:protocol version
wpa_supplicant: OpenSSL: openssl_handshake - SSL_connect error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number

**Comment by mikeNG** [comment]
So, what changed between https://github.com/M66B/cm-xtended/issues/179 and now? older versions like cm-10.1 & cm-10.2 should not have issues, there was nothing changed in the code that would affect wpa eap

**Comment by pteek** [comment]
WPA2 801.1x/EAP is working for me. TTLS and PEAP-MSCHAPv2 both.

cm-11.0-20140320-NIGHTLY-LegacyXperia-iyokan.

**Comment by fqdb** [comment]
Confirmed working here too (eduroam), but with one note, PEAP-MSCHAPV2 only on this particular network. So if people still have problems, I'd advice them to try PEAP instead of TTLS too if possible.
