### ISSUE TITLE
[CM11.0]{mango/MiniPro][KitKat 4.4.2] LegacyXperia 

### ISSUE THREAD

**Issue by bekesp** [LegacyXperia/local_manifests#377]
1. Google Maps (v7.5.0) flickering and unusable on cm-11.0-20131225-NIGHTLY-LegacyXperia-mango. I reinstall maps, same problem remaining.
2. Audio play lagging sometimes with my SonyEricsson MW600 bluetooth headset.
3. Backlight in Auto mode usually too dark in a room.
4. The builtin browser unusable, it doesn't follow my finger, I must use Google Chrome.

Everything else works fine on Xperia mini pro, mango.
Thanks!

last_kmsg: https://app.box.com/s/zqksn9jjjb6ynky811wy
logcat: https://app.box.com/s/av8rrbbu62ujv4j1z1g1
dmsg: https://app.box.com/s/qgac1pcvf70t1x8l23ar

**Comment by mikeNG** [comment]
File separate bugs for separate issues.
Most of the issues are already present in the bug tracker
