### ISSUE TITLE
GSM signal lost

### ISSUE THREAD

**Issue by happyBOY78** [LegacyXperia/local_manifests#378]
Phone show, that my cell operator is not available and only emergency calls are possible. Restarting of phone solve this issue.
This issue i have 1-2 per week.
I catch logs in this phone state, but i don´t know, if this data will be relavant for Mike.
In gist are 4 files.
https://gist.github.com/happyBOY78/8330086

Quote from other user tauvixc, which have the same problem (taken from Q&A topic) : 

I just wondering. Is anyone had an issue, sometimes the data signal was lost and back alive again? It happened almost all the times, signal was very unstable. There's no such thing when I try to downgrade to CM 9.1.
I've try to change my mobile operator. Still facing this issue.

Edit: This problem was gone till I restarted the phone. And then happened again and again. 

Sent from my MiniPro

**Comment by zweif** [comment]
This happened to me one time.

But before flashing cm11 on stock ICS sometimes (maybe more often than this problem here) my mini pro said something like "sim card not working anymore" and an option to restart to solve the problem. Sometimes the restart didn't solve this and i had to take out sim card.
Maybe this is related to sim card (and this dialog doesn't apper)?

**Comment by happyBOY78** [comment]
NO, this is not related to sim card. I have this idea too, when it hapened first, but placement of sim card in phone is OK.
And dialog on the screen show only "Choosen network is not available, only emergency calls are allowed" - sorry for maybe inaccurate translate, i have my phone in czech language, but sence is correct.
I add, that same gsm network have my girlfriend, and her phone is fine, when this issue happened to me. So,is not network coverage problem, etc..
The issue, you write about i have, when my phone has near contact with the ground :-)))

**Comment by ghost** [comment]
This is old and currently unfixable bug on CM10.2 and 11 (idk about 10.1). It was reported numerous times, for example: https://github.com/LegacyXperia/local_manifests/issues/138 and this one https://github.com/LegacyXperia/local_manifests/issues/100

**Comment by happyBOY78** [comment]
Are you sure, that "my" issue is the same, as issues, you write about ?
In #138 i see problems with airplane mode and network mode switching - not my case,
and in #100 no network after reboot. Not my case too.
Both this issues are after some user activities. Mine not.
My phone lost signal, when it is in my pocket, very randomly, without reason.
Not arguing, just stating ;-)

**Comment by godlesplay** [comment]
my phone lost signal when I go to shop center and I need reboot to get signal back, so maybe you lost your signal when you are for example in "strange" places?

**Comment by happyBOY78** [comment]
No. This happened to me,in "full signal area",in outdoor, in city. Coverage is very good.

**Comment by pteek** [comment]
For me, leaving the phone on 2G/3G mode results in loss of network for hours(random times when phone is sleeping). The phone only seem to get back on the network after it is waken up.

If I set it to 2G only, then everything is much better. Network is lost Rarely.

This also happens in FXP CM10.

cm-11.0-20140320-NIGHTLY-LegacyXperia-iyokan

**Comment by kmARC** [comment]
Anyone experiencing this behaviour? I am, therefore I am surprised that this issue is closed.
