### ISSUE TITLE
[cm-11.0-mango] Kernel crash - reboot

### ISSUE THREAD

**Issue by happyBOY78** [LegacyXperia/local_manifests#380]
I didn´t found issues here on bug tracer, which contain logs, when phone has random reboot (kernel crash) without visible cause.
So, i created this issue. (Sorry, if it is useless).

[cm-11.0-20131225-mango]
https://gist.github.com/happyBOY78/8371022

If Mike did not close this issue, i will attach other logs in future, when my phone have kernel crash again, if it will be helpful for development.

**Comment by mikeNG** [comment]
nothing useful in the log
