### ISSUE TITLE
[11.0] Direct dial does not work.

### ISSUE THREAD

**Issue by amishmm** [LegacyXperia/local_manifests#381]
If you add "Direct dial" shortcut on home screen for any contact, it shows shortcut but clicking on shortcut does not dial directly.

Nothing appears in log when you click the icon. So can not report any log.

"Direct message" works. Only "Direct dial" does not work.

Occurring atleast from last 2 versions of CM11. May be since first alpha.

Using coconut / Wt19i

**Comment by PimpMyAndroid** [comment]
The "Direct dial" widget works fine for me (Anzu) using the latest release, maybe your shortcuts got corrupted have you tried deleting them and creating new ones?

**Comment by amishmm** [comment]
I did not delete old widget but I created new widget with different contact and it did not work.

By latest release do you mean yesterday's release? I have not tried it yet.

**Comment by amishmm** [comment]
It appears that this was Nova launcher bug. Bug disappeared after I uninstalled Nova launcher.
