### ISSUE TITLE
NEW CM11 build with video recording fixed?

### ISSUE THREAD

**Issue by taha001** [LegacyXperia/local_manifests#382]
thank you mike for all your efforts towards our devices..U R LEGACYXPERIA GOD whu is saving our devices.

sorry this is not question answer thread..but i dunno where to ask about it...when is the new build arriving with video recording bugged fixed?

**Comment by ketkul** [comment]
Patience.. its not even uploaded yet....

**Comment by ghost** [comment]
Jesus fucking christ whats wrong with you? Why would you create a new bug report for this? It's like this whole community is ridden with 12 year old retards.

**Comment by o2droid** [comment]
I have haida and video recording on new 2014.01.11 is working ok.

Bug can be closed.
