### ISSUE TITLE
[CM11]  Anzu New 01-11 Problem 

### ISSUE THREAD

**Issue by lofas33** [LegacyXperia/local_manifests#384]
After first boot i get systemui fc still again and again, what i have to do, please help...
Anyway thx for your hard work guys on making our 2011 still awesome.

**Comment by ghost** [comment]
This is not a bug. Do a clean install and try to not break things again this time.

**Comment by lofas33** [comment]
I did clean install three times, i even flash stock firmware and try it again and its still the same...
