### ISSUE TITLE
[cm-11.0-20140111-coconut] MAC address unavailable

### ISSUE THREAD

**Issue by azakosath** [LegacyXperia/local_manifests#385]
Hey Mike,
I remember reading a relevant post in XDA's thread a couple of days after your Christmas present about this issue (screenshot below)
![screenshot_2014-01-12-14-53-42](https://f.cloud.github.com/assets/5717336/1896219/aa719122-7b89-11e3-9b8f-dd9cf23957a4.png)
Another thing I noticed was that the app Net Scan (https://play.google.com/store/apps/details?id=com.wwnd.netmapper&hl=en) would FC as soon as the WiFi was connected. I waited until the new build, and the problem persists, so I'm filling this report. I don't know if these two issues are connected or not. Here is the logcat:
https://gist.github.com/azakosath/8384431
The application was already running when I enabled Wi-Fi and gave FC when it was connected. If the WiFi is already connected then the app is giving FC when you try to launch it (no logcat attached).

Cheers

**Comment by PimpMyAndroid** [comment]
The MAC address issue has been around for a while, if you really need to know your MAC address you can usually get this by logging into your routers hub and look at connected devices. As for your issue with Net Scan I have the same problem on Anzu, it may actually be a problem with the Net Scan app itself, have you contacted the developer? maybe it's not compatible with Kitkat.

**Comment by azakosath** [comment]
Yes, I know how to see my phone's MAC address and this is not my problem. Net Scan was working fine with the two alpha builds, the problem came with the Christmas' build and the MAC address issue as well, that's why I'm wondering if these two issues are connected somehow.

**Comment by cauchyy** [comment]
Hi,

I've rooted my phone as it is mentioned in Cyanogen Wiki. Then I installed build 20131211 as it was mentioned in Mike's dev thread. There is no problem with this build.
I tried to update to build 20131225. I downloaded zip with ROM then from CWM I did "install zip" and wipe cache/dalvik. Everything went smooth but I didn't have MAC address (Wi-Fi Settings - > Advanced) and I couldn't switch on Wi-Fi (switch goes from off to on but it won't change colour to blue and then wifi goes off). There is no way to connect to any wifi network as it is not discovering anything. So I got back to my backup. Unfortunately the same happens with 20140113 update. Everything works beside the lack of MAC address.
I've seen Mike's post that WiFi always work but I followed all 3 rules and still nada.

**Comment by azakosath** [comment]
From Mike's dev thread 1st post (http://forum.xda-developers.com/showthread.php?t=2545367):

[[[Steps required for correct installation (order is important):
1: Flash boot.img in fastboot & reboot into recovery
1.1 (optional): If the device is not booting, reboot to bootloader again and run:
fastboot erase system
fastboot erase userdata
2: Enter recovery, go to mounts and storage
3: Format /system, then /data and then /cache (Important step!)
4: Flash update zip
5: Flash gapps (recommended package is the one provided in the link below)

Steps 1.1, 2 & 3 are not needed when you install new cm11 nightlies on top of older cm11 builds in the future

If you want to return to a ROM that doesn't use the new partition layout, you need to follow the above steps again (only replace boot.img & update zip with the ones you want to use).]]]

Check again step Number 1, always extract and flash new boot.img from zip.

**Comment by cauchyy** [comment]
As I said: I followed Mikes instructions. Without boot.img there wouldn't be recovery where I could install ROM

**Comment by azakosath** [comment]
And as I said ALWAYS extract and flash the NEW boot.img from inside the zip file. Every build needs its own kernel to be fully functional. You can't use build 20131225 with the boot.img from build 20131211, or the opposite, or any build with a boot.img from any other build. ALWAYS flash the boot.img that comes with the zip. I hope I was crystal clear this time. If you search for similar problems, is a common mistake that new users make (even experienced ones sometimes).
EDIT: And the MAC address issue doesn't affect wifi at all.

And have a nice day....;-)

**Comment by cauchyy** [comment]
Well.. I'm also I9100 user with CM10.2 and Omni now. I have never did update with flashing new boot.img. I did it once and then I was installing only new builds in .zip from CWM.
You're crystal clear and now I can see that this instruction is not :)
I got to do points 1 (not 1.1) 4 and 5. I assume that flashing boot.img doesn't affect configuration and any other data and settings stored in my phone. Am I right?

PS. I think that lack of MAC address can make your device unable to connect to router. Because how router will name your device if it doesn't have MAC?

**Comment by azakosath** [comment]
The instructions are also crystal clear (... Steps 1.1, 2 & 3 are not needed when you install new cm11 nightlies on top of older cm11 builds in the future...).
Indeed, flashing new kernel doesn't affect your configuration or any user's data, settings etc. Actually, flashing the update zip doesn't affect all these (unless you have flashed or pushed something in system), that's why Mike is saying "never wipe" (see FAQ section of wiki).
The MAC address is there, we can't see it, but your router can just fine (if you take a look in your router's UI). And, if you check the screenshot in my first comment, just under the IP address there is the MAC address (5C:5B:24:56:51:2D).

And...... I rest my case!

**Comment by cauchyy** [comment]
Jury is pleased :)

Thank you very much! I hope it will do the trick. And have a really nice day....;-)

**Comment by mikeNG** [comment]
Wait for next build and try again.

**Comment by cauchyy** [comment]
azakosath tip works like charm!
PS. What will be in next build if I can ask?
PPS. Mike you're the man! Awsome work!

**Comment by psyke83** [comment]
Hey Mike,

I don't see the fix for wifi in any of your repos. I own a smultron, and I see in the logs the same symptoms that happen on my galaxy5 port using the ath6kl driver. The problem was due to the wpa supplicant private library bundling a driver_nl80211.h header that was outdated. This was causing several issues, such as missing mac address and failure to resume from suspend.

I'm not sure where your private lib is, but you can fix it using the same method as my change for the ath6kl private lib (remove the old header and point the driver to the proper one in hardware_legacy): http://review.androidarmv6.org/#/c/6501/

**Comment by mikeNG** [comment]
please test the latest build, it should be fixed

**Comment by azakosath** [comment]
Yeap, it's fixed already. MAC address is there and the app I was talking about is working like a charm. The only thing is this strange line below IP address is still there (see screenshot in 1st comment).

**Comment by mikeNG** [comment]
@azakosath it's not a "strange line", it's ipv6 :)

**Comment by azakosath** [comment]
Thanks for the clarification. I checked it out on wikipedia....;) As you can see, programming and internet protocols is not my expertise...:P
