### ISSUE TITLE
[haida][CM11] Search bar - Remove shortcut - App Info

### ISSUE THREAD

**Issue by petrkalos** [LegacyXperia/local_manifests#387]
I notice that when you disabling the google search bar from the launcher you cannot remove shortcuts or get "App Info" menu.
When you press-hold the shortcuts you don't get the menu "Remove Icon" in the top.
Also you don't get the menu "App Info"
I had notice these behavior to cm-11.0-20131225-NIGHTLY-LegacyXperia-haida and to 2014 build.

**Comment by mikeNG** [comment]
fixed in latest build with Trebuchet as the default launcher
