### ISSUE TITLE
[cm-11.0-20140111-NIGHTLY-LegacyXperia-haida] Preferred network type

### ISSUE THREAD

**Issue by petrkalos** [LegacyXperia/local_manifests#388]
In Preferred network type I can see only the 3G option but from the QuickBar I can change through different modes.

**Comment by Nikhildangui** [comment]
INSTALL cm-11.0-20140113-NIGHTLY-LegacyXperia-haida.zip
http://legacyxperia.basketbuild.com/index.php?dir=main/cm11.0/haida/nightlies/

for lazy ppl...
your build has problem, do take some extra affords to read xda and other posts  :-1:

**Comment by petrkalos** [comment]
I have seen this bug to these ROMs
- cm-11.0-20131225-NIGHTLY-LegacyXperia-haida.zip
- cm-11.0-20140111-NIGHTLY-LegacyXperia-haida.zip (I knew it was problematic) 
- cm-11.0-20140113-NIGHTLY-LegacyXperia-haida.zip (currently running)

So it's not related to my laziness or to the problematic ROM

**Comment by PimpMyAndroid** [comment]
I have the exact same problem on my phone using cm-11.0-20140113-NIGHTLY-LegacyXperia-anzu.zip
So Nikhildangui your unhelpful explanation is utter crap, if you don't understand the problem keep your comments to yourself.

**Comment by mikeNG** [comment]
Can you explain where to find the "Preferred network type" option? I've never used it before

**Comment by petrkalos** [comment]
Yes of course.
It's in settings->more...->mobile networks->preferred network type

**Comment by mikeNG** [comment]
This option wasn't present in previous android versions right? I'm trying to find where's the problem...

**Comment by PimpMyAndroid** [comment]
I'm not sure if you mean just your builds or android in general, if it's the latter then yes there has always been the option.

**Comment by nedimlisica** [comment]
It was there in older versions, only under different name (Use only 2G networks).
I'm running my own build on Mango from 20140118 and both 2G and 3G options are avilable.

**Comment by mikeNG** [comment]
RIght, I understand now.
In the latest build released today, both 2G and 3G options are available on my phone too.
@petrkalos can you confirm?

**Comment by petrkalos** [comment]
I will as soon as I go home.

**Comment by petrkalos** [comment]
Doesn't seem to be resolved.
Same behaviour. Should I wipe data/system?

**Comment by Nikhildangui** [comment]
mike: i have been getting options to choose network type since your very second build of legacy xperia cm11, sorry cant remember about first build though.
i always 2G only mode, it has the option to choose and works well too

**Comment by mikeNG** [comment]
This is tested on multiple devices and works
