### ISSUE TITLE
Edit Light - pulse length and speed hides behind Ok-Test-Cancel

### ISSUE THREAD

**Issue by amishmm** [LegacyXperia/local_manifests#390]
Please see screenshot attached.

When you try to adjust Light pulse settings.

You can not adjust pulse length and speed because that setting hides behind Ok-Test-Cancel buttons.

It does not allow to DRAG the setting up or down to change it.

![screenshot_2014-01-14-13-04-13](https://f.cloud.github.com/assets/3330468/1910335/8f266fdc-7d14-11e3-9593-bf3068df1dd3.png)

**Comment by taha001** [comment]
in hallon it is proper..try changing your dpi value to 180

**Comment by amishmm** [comment]
Umm, I dont like to change default settings.

I am not an android programmer but I think right solution would be to attach a scroll bar to that frame. (or something similar)

**Comment by Apocalypse2** [comment]
rotates the screen to the right and scroll down and you can make change

**Comment by amishmm** [comment]
@Apocalypse2 I had already tried it, thats not working. I can not scroll down (i.e. drag up)

**Comment by mikeNG** [comment]
@amishxda is this present on older CM versions too?

**Comment by amishmm** [comment]
I dont remember. But I remember it used to work when i was on CM10.1 or 10.2.

Its not working since last two CM11 atleast. I did not check in previous CM11 versions.

**Comment by mikeNG** [comment]
I've tried to fix this, but it's nearly impossible without modifying the layout. If we add scrolling, it interferes with the color picker.

**Comment by amishmm** [comment]
There is lots of space on top and bottom, cant we increase height? (Not an android developer so dont have idea how easy that is.)

**Comment by mikeNG** [comment]
Should be fixed in latest build

**Comment by amishmm** [comment]
Yes fixed! Thanks! :)
