### ISSUE TITLE
cm-11.0-20140111-NIGHTLY-LegacyXperia-coconut: Web pages appear distorted in browser

### ISSUE THREAD

**Issue by natanE** [LegacyXperia/local_manifests#392]
using built-in web browser (or any other app that depends on it such as Mail reader) the page dispaly is distorted. doesn't happen on previous releases

**Comment by natanE** [comment]
i've tried wiping all data, reset to factory default, burning ROM again - nothing, issue still present. reverting to previous version "solve" the issue.

**Comment by mikeNG** [comment]
Please use the latest build, 20140111 was removed because of this bug.
webview problems are fixed
