### ISSUE TITLE
CM10.2 Powersave Performanceprofile does not work properly

### ISSUE THREAD

**Issue by Telemuddi** [LegacyXperia/local_manifests#393]
Today i've tested the performance profiles while playing music on apollo.

The issue is that the phone on powersave doesn't slow down the cpu. It hangs on max frequency(conservative governor). On performance its the same(with performance governor) but on balanced its fine.
I think its not normal.

Phone is mango with CM10.2 20140112 nightly.

**Comment by mikeNG** [comment]
what exactly do you mean by "hangs on max frequency" ?

**Comment by Telemuddi** [comment]
The phone always use the max. frequency who is chosen in the menu. it doesn't switch to an lower frequency.

**Comment by mikeNG** [comment]
conservative is supposed to keep the cpu in the lowest frequencies most of the time... I'll test it

**Comment by mikeNG** [comment]
it works fine here, tested all 3 profiles

**Comment by Telemuddi** [comment]
Hm ok. I forgot that i installed viper audio. After the next nightly i will test it without viper.

**Comment by mikeNG** [comment]
try latest build

**Comment by Telemuddi** [comment]
Ok the problem comes with viper audio and affects only the powersave profile. The cpu stays with it on 768mhz, in balanced or performance the cpu switches between 368-1400mhz(with viper audio).

So i dont use powersave to hear music in the future.
