### ISSUE TITLE
[anzu cm11] Apps in SD Card disappeared

### ISSUE THREAD

**Issue by sdamaceno** [LegacyXperia/local_manifests#396]
I've installed apps and I've moved them to SD Card, formatted as exFAT.
When I rebooted the phone, my apps disappeared.

Using: anzu CM11.0 nightly build 20140113 Xperia Arc S Lt18i.
SD Card Micro SDHC 16GB Class 2.

**Comment by nonphanu** [comment]
I've got a same issue

**Comment by mikeNG** [comment]
test latest build

**Comment by sdamaceno** [comment]
still not working.. same behavior

**Comment by mikeNG** [comment]
provide some proper logs then

**Comment by sdamaceno** [comment]
For tests, I installed Adobe Reader and moved to SD. Rebooted and it disappeared. The same was occured with Foursquare.

I have uploaded logcat. http://goo.gl/YoJWB0

I have uploaded kmsg too, after installing apps and moving them to sd...
- before reboot: http://goo.gl/CDnRdl
- after reboot: http://goo.gl/mQMeCh

and a folder with logs generated by SysLog app http://goo.gl/Qc5bPi

Please guide me if it's needed to provide other information.

**Comment by sdamaceno** [comment]
I've noticed 2 files in the hidden directory .android_secure
sdcard/.android_secure/com.adobe.reader-1.asec
sdcard/.android_secure/com.joelapenna.foursquared-1.asec

**Comment by mikeNG** [comment]
the problem seems to be exfat... can you try with standard fat32?

**Comment by sdamaceno** [comment]
yes, I'm trying fat32 some days and really seems the problem is exfat
thank you

**Comment by mikeNG** [comment]
so, I'm closing this. I will try to find why exfat doesn't work
