### ISSUE TITLE
EAP 802.1x Eduroam Connect Problem CM10.1

### ISSUE THREAD

**Issue by lezka2010** [LegacyXperia/local_manifests#397]
I am not able to connect Wifi on my Office network (802.1x EAP). I am asked to give my User id and Password, when I enter user ID and password it shows connecting but does not get connected. Please find the logcat of the same at the below link.

cm_haida-LX-20131108-NIGHTLY.zip CM10.1

Please FIX it

**Comment by mikeNG** [comment]
Duplicate of #376 and no logs
