### ISSUE TITLE
[10.2 RC2 Ray] cLock weather widget is active

### ISSUE THREAD

**Issue by cajhin** [LegacyXperia/local_manifests#399]
(might be a CM bug)
I have the weather widget disabled in settings, but I can see in the logs that it is still active; for example,

19:43:59.941 D/YahooWeatherProvider( 3462): Weather updated: WeatherInfo for Frankfurt am Main (20066703) @ Wed Jan 15 19:39:18 CET 2014: Cloudy(26), temperature 4Â°C, low 3Â°, high 5Â°, humidity 80%, wind 14km/h at S, forecasts: day 1: high 5Â°, low 3Â°, Light Rain Late(11); day 2: high 9Â°, low 4Â°, Light Rain(11); day 3: high 9Â°, low 1Â°, AM Clouds/PM Sun(30); day 4: high 8Â°, low 1Â°, Cloudy(26); day 5: high 7Â°, low 2Â°, Cloudy(26)

This _may_ also be the reason for some issues I had in 10.2 RC2:
- cLock is # 3 in Settings > Battery
- a "suspend_[??]" wakelock for 2h per day (this doesn't show up at all in RC1)
- sth turns on GPS occasionally
- overall, poor battery and too much trouble

**Comment by amishmm** [comment]
Not a solution but you can set weather update on manual mode (or high number of hrs), that may stop it for remaining active.

**Comment by mikeNG** [comment]
probably a CM bug related to the latest cLock overhaul

**Comment by mikeNG** [comment]
I got battery drain in the first days too but now it's normal again, can't reproduce this issue anymore
