### ISSUE TITLE
launcher and gallery fc

### ISSUE THREAD

**Issue by avinashrocks1990** [LegacyXperia/local_manifests#4]
logcat
https://docs.google.com/file/d/0B7z0NoNc5ecUNHRrYTJyUm9hQ1E/edit?usp=sharing

**Comment by mikeNG** [comment]
When did the FC happen?

**Comment by avinashrocks1990** [comment]
alpha 1 normal usage 
haven't encountered it in alpha 2

**Comment by mikeNG** [comment]
Ok, I will close it for now
