### ISSUE TITLE
[10.1-10.2] Maps Jittery

### ISSUE THREAD

**Issue by webolim** [LegacyXperia/local_manifests#40]
The screen tends to jitter when in Google maps

**Comment by mkj** [comment]
It seems more like a Maps bug to me - anyone tried other devices with the same res running 4.3?

**Comment by hawrehas** [comment]
same problem here!

"Arun Av" wrote in 10.1 thread in xda:
"Hey guys, i just found out that the flickering screen bug in latest Google maps (maybe cuz of graphics driver of our devices?) can be solved by setting the dpi of Google maps to 140 (xposed). However, the dialogue pop-up asking to turn on gps is still buggy but overall as i can observe, 140 dpi solves 80% of the flickering issue that's present in 160 dpi. Check it out."

Didn't try it, but maybe this helps someone to identify the problem !?

**Comment by pcfighter** [comment]
it's same issue as https://github.com/M66B/cm-xtended/issues/172#issuecomment-24282553

**Comment by mikeNG** [comment]
Can't be fixed, incompatibility between adreno libs, camera libs, kernel display drivers, android display drivers & pmem. Might be fixed if we use an ION based kernel.
