### ISSUE TITLE
cm11: Cant turn on bluetooth

### ISSUE THREAD

**Issue by mowgli80** [LegacyXperia/local_manifests#400]
Am using 01/13 anzu build with arc s. logcat - http://pastebin.com/Wdx3Tnhd

Let me know if you need any further info.

**Comment by PimpMyAndroid** [comment]
I'm also using anzu (20140113), Bluetooth turns on but cannot find any of my Bluetooth devices?

**Comment by mowgli80** [comment]
Just to clarify, bluetooth turns on for me and am able to connect to my car head unit. Only for this instance, it did not and was rectified by rebooting the phone.

**Comment by PimpMyAndroid** [comment]
Thanks, just rebooted, made devices searchable and everything is OK now, battery drain is negligible.

**Comment by PimpMyAndroid** [comment]
I think this can be closed now.
