### ISSUE TITLE
(CM10.2)LocationServices Don't work With Google Apps

### ISSUE THREAD

**Issue by LiveBoy** [LegacyXperia/local_manifests#408]
CM Ver: cm10.2 coconut LX 20140112 NIGHTLY

Hi
I have problem with Location in ROM. When i want to use Google now for example,it can't detect my location and use it to search or cClock either.But GPS work correctly with all apps.

Thanks all for create this wonderful ROM...

**Comment by LiveBoy** [comment]
Thank you for Closing...

**Comment by mikeNG** [comment]
not following the rules = closed !

**Comment by LiveBoy** [comment]
I didn't know it need log...but i follow all the rules in wiki...i search,i use last kernel,last nightly release and ...

anyway here is the log.It detect my location in my country but in previous releases it detects my city and sometimes my area...

D/YahooWeatherProvider( 3056): Weather updated: WeatherInfo for Iran (23424851) @ Wed Jan 22 18:41:39 GMT+03:30 2014: Partly Cloudy(29), temperature 16Â°C, low 5Â°, high 17Â°, humidity 27%, wind 0km/h at N, forecasts: day 1: high 17Â°, low 5Â°, Clear(31); day 2: high 20Â°, low 6Â°, Mostly Sunny(34); day 3: high 17Â°, low 3Â°, Partly Cloudy(30); day 4: high 14Â°, low 4Â°, Partly Cloudy(30); day 5: high 17Â°, low 5Â°, Partly Cloudy(30)
