### ISSUE TITLE
battery bug

### ISSUE THREAD

**Issue by sumantaadk** [LegacyXperia/local_manifests#412]
XPERIA RAY. I left my device idle on 70 percent at night. When I wake up my battery was finished. Device was off. Then I remove Kitkat and install jellybean

**Comment by ghost** [comment]
If you want this problem to be looked at you have to provide logs. Use BetterBatter Stats (BBS) to do so. Get it from here: http://forum.xda-developers.com/showthread.php?t=1179809

and read this: https://github.com/LegacyXperia/Wiki/wiki/Reporting-problems

Thank you.
