### ISSUE TITLE
[CM11]{Smultron} Removing a widget on lockscreen doesn't remove.

### ISSUE THREAD

**Issue by JovieBrett** [LegacyXperia/local_manifests#413]
CM11 Nightly Build01212014 on Smultron. I cannot remove widgets on lockscreen, cannot produce logcat on this kind of issue :(

**Comment by azakosath** [comment]
Probably, because of low_ram prop is enabled by default. Just change it to false in build.prop and it will be ok.

**Comment by mikeNG** [comment]
will be fixed in next build

**Comment by JovieBrett** [comment]
@mikeNG thanks! Fix will be included on the next build :D
