### ISSUE TITLE
[CM11.0-mango] Can't turn on WIFI

### ISSUE THREAD

**Issue by morinocat** [LegacyXperia/local_manifests#414]
I use in CM11.0. (cm-11.0-20140121-NIGHTLY-LegacyXperia-mango.zip)
(20140113, 20131225 ... is all same)

But I Can't turn on WIFI.

Perhaps, Is it bug of CM11.0?

Plz help me.

ps. Sorry... My English is poor.

**Comment by azakosath** [comment]
Perhaps, you didn't read this :

https://github.com/LegacyXperia/Wiki/wiki/Reporting-problems

**Comment by ghost** [comment]
Perhaps, you forgot about kernel.
This sweet wiki should cover all your future perhapses: https://github.com/LegacyXperia/Wiki/wiki

**Comment by morinocat** [comment]
Thank you!! I will read that. 
I am sorry for my mistake.
