### ISSUE TITLE
[CM11] Phone app layout error when opening keypad.

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#415]
starting with:
![untitled-1](https://f.cloud.github.com/assets/5565504/1984084/626a180c-8423-11e3-9b69-397a829559da.jpg)
first tap:
![untitled-2](https://f.cloud.github.com/assets/5565504/1984091/784e86c6-8423-11e3-98e3-1fe710c022c5.jpg)
second tap:
![untitled-1](https://f.cloud.github.com/assets/5565504/1984099/92c05a70-8423-11e3-9915-bbf9243aae7f.jpg)
and finally third:
![untitled-3](https://f.cloud.github.com/assets/5565504/1984100/98ed41c4-8423-11e3-8a41-212ea447acc5.jpg)

It does not happen when dialer is loaded into RAM.
I'm on Arc S btw.

**Comment by mikeNG** [comment]
hmm I can't reproduce that, I tried killing dialer but it works fine

**Comment by ghost** [comment]
I'll do a factory reset and test it when new build is released.

**Comment by mikeNG** [comment]
I think I'll do a release today

**Comment by ghost** [comment]
Damn, you know how to make your testers happy!

**Comment by ghost** [comment]
Apparently this is caused by disabled animations in developer settings. I don't know if this can be considered as a bug because it's caused by settings normal users are not supposed to touch.
Edit: I think that's all and you can close this issue if you think it's not a bug.

**Comment by mikeNG** [comment]
Yeah there's not much to be done here... it would be a waste of time (for me) to try and find where's the problem since a user isn't supposed to alter these settings.
