### ISSUE TITLE
call interface delay

### ISSUE THREAD

**Issue by padishah** [LegacyXperia/local_manifests#416]
During incoming/outgoing call the interface to answer or end call is delayed up to 3-6 sec. The phone rings but you can't accept or reject a call as a result. During outgoing call : when you press call button a black screen will appear first and after a while the interface appears. 
The dialer app is OK, it launches quickly

Build from 2014.01.22
Device iyokan

**Comment by nedunilavan** [comment]
Clear data of Dialler.apk solves this issue but may occurs after some time.

**Comment by padishah** [comment]
I don't think that it is related with dialer. Dialer is OK for me

**Comment by Nikhildangui** [comment]
mike even ill like to confirm the same issue on Haida CM11 built , 
the main practical issue is, if accidentally any contact is clicked it places call, and to disconnect it its takes around 3 seconds as screen goes black for while, and til then person at other end gets miss call,

UPDATE: i found temporary  work around, i clears delvik chache once 15 days, it speed ups my phone and dialer a little bit

**Comment by pteek** [comment]
Also present on iyokan on latest build cm-11.0-20140320-NIGHTLY-LegacyXperia-iyokan.

**Comment by mikeNG** [comment]
Provide logs if this still happens in latest build which will be released tomorrow

**Comment by pteek** [comment]
This issue is pretty much fixed. The lag is a lot less than before and is manageable. There is about 1 sec extra time when there is a black screen and no call ui. Some calls dialed by mistake still get though before we can end them.

It used to be about 4-5 sec lag and now its .5-1 sec. I will add logs.

**Comment by mikeNG** [comment]
Well this should be difficult to improve more, since our devices are pretty low-end for today's standards.
