### ISSUE TITLE
Wifi Not working with coconut(Live with Walkman). On clicking on wifi its not starting at all.

### ISSUE THREAD

**Issue by crabypatty** [LegacyXperia/local_manifests#417]
Wifi Not working with coconut(Live with Walkman). On clicking on wifi its not starting at all.

**Comment by mikeNG** [comment]
Perhaps, you didn't read this :

https://github.com/LegacyXperia/Wiki/wiki/Reporting-problems

**Comment by ghost** [comment]
go into  WiFi > Menu-Advanced > untick "scanning always available" if that doesn't work do a proper bug report.

**Comment by crabypatty** [comment]
After Flashing the Kernel(boot.img) the problem was solved.

On Fri, Jan 24, 2014 at 2:47 PM, skaveelicious notifications@github.comwrote:

> go into WiFi > Menu-Advanced > untick "scanning always available" if that
> doesn't work do a proper bug report.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LegacyXperia/local_manifests/issues/417#issuecomment-33207796
> .

## 

Kindly revert in case of any concerns.

Antriksha Somani  | Assistant Professor
MIT | Indore
Mob: 9907005621
 [image: email] crabypatty@gmail.com
Note: No trees were destroyed in the sending of this message, however, a
significant number of electrons were terribly inconvenienced.
