### ISSUE TITLE
Struck on boot screen [CM11 - Mango - Nightly build 20140121]

### ISSUE THREAD

**Issue by mrmurthi** [LegacyXperia/local_manifests#418]
I have updated the latest nightly on my xperia mini pro. I did not do 'WIPE DATA' as this is an update to the earlier version.

I have flashed the kernel that comes with the nightly. But, the screen is getting struck on the boot screen (Legacy Xperia screen).

Earlier I have changed my system font using iFont, but after that default font is restored. There were no problems with that.

Could you please help with this?

Thank You.

**Comment by mrmurthi** [comment]
i have tried complete wipe of data using fastboot and flashed the kernel that came with previous build. 

it still did not work. I am not able to boot in to recover mode also. the phone is struck on the boot screen. Please help.

**Comment by happyBOY78** [comment]
I have similar problem. Same phone (mango) and same build.
Previously, i flash all nigthly builds without any issue. (i was 10.1 and 10.2 user in the past too)
Now, my phone stoped in bootlogo.
I make all steps correct, i was previously on LX11 20140113-NIGHTLY-LegacyXperia-mango
For sure, i try make "clean" install too - format  /System /Data /Cache and install ROM&gapps...the same issue.

Then, i flash kernel from 20140113, restore my last cwm backup...and phone boot fine.

When my phone stoped in bootlogo, i make last_kmsg via adb in cwm.
I hope, it help https://gist.github.com/happyBOY78/8585463

**Comment by mrmurthi** [comment]
Thank you. somehow i managed to boot into recovery and restored my backup.

Team,
solution to this issue would be appreciated.

**Comment by Diabb** [comment]
Have you install supersu from chainfire ?
Is cause stuck boot screen

**Comment by SquallATF** [comment]
I have get the same issue on my anzu and have the same kmsg
I also tried flash old kernel then booted but wifi doesn't work.

**Comment by happyBOY78** [comment]
Thanks to @Diabb , you solve my problem. I used SuperSU. After changing to CM superuser and installed latest nightly by standard way, all works fine.

**Comment by SquallATF** [comment]
Implement corrected sysinit (init.d) system (1/2)
cherries+=(57603)
Implement corrected sysinit (init.d) system (2/2)
cherries+=(57604)

this change caused boot failed

**Comment by Diabb** [comment]
can explain me more that causes Stuck boot, thanks

**Comment by SquallATF** [comment]
I flashed new version boot.img then can't boot, the last_kmsg like happyBOY78 posted. I replaced old version init.rc and init.cm.rc into new version boot.img then booted.
I have just added link2sd's mount script, may not be compatible with new version init scripts
but I have no more time to test it.

**Comment by Diabb** [comment]
OK thanks

**Comment by mikeNG** [comment]
The 2 changes that broke boot were removed.
Wait for next build.
