### ISSUE TITLE
Music Player cannot fast forward/backward via bluetooth

### ISSUE THREAD

**Issue by nguyentrunght** [LegacyXperia/local_manifests#419]
Hi devs,

I currently install  cm-10.2_hallon-LX-20140112-NIGHTLY.zip and see that the function FF/FB via bluetooth device cannot use ( i use MW600 and it works well with others CM version - players are Apollo or Google Music) .Others functions work properly (next, back, volume, play/pause...).

Your revise and fixed will be appreciated. 
Thank for your contribution.

**Comment by mikeNG** [comment]
cm-10.2 is EOL now, so I'm closing the issue
