### ISSUE TITLE
[10.1-10.2-11.0] Congested keypad on Lock Screen

### ISSUE THREAD

**Issue by mrmurthi** [LegacyXperia/local_manifests#42]
I am using CM10.2 on Sony Xperia Mini Pro (Mango). When I set a lock security with PIN, the numbers on the keypad are overlapping on each other. The second line starts over the below part of 1st line. 

Is there a way to reduce the size of the keypad so that it will fit on the screen? I tried removing the weather panel and alarm panel from the lock screen, but it is not working.

Thank You.
Murthi.

**Comment by MIXTERek** [comment]
change the DPI to 140 and all will work corect

**Comment by mrmurthi** [comment]
But, everything else is working fine. Only issue is with keypad on lockscreen. The normal keypad is also working fine. please check the screenshot for the issue. the numbers on the lockscreen overlap over one another. is there a way to solve this issue?

![screenshot](https://f.cloud.github.com/assets/5346085/1062019/88b1e392-121c-11e3-864f-292efbf47c37.png)

**Comment by mrmurthi** [comment]
Hi MIXTERek,

I have changed the DPI and the keypad is looking good now. But, the weather widget is not appearing on the lockscreen. It is appearing in landscape mode but not in normal mode.

**Comment by mikeNG** [comment]
will be fixed in all next LX builds: 10.1/10.2/11.0 :D
