### ISSUE TITLE
KK 4.4.2 is the newest Kernel supporting ext2 Link2SD?

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#420]
I'm right now using  {4.4.2}{ROM} PolygonKK:Triangle {r1.4/Release} from xda.
It is really strange but I can not really use the Link2SD method to link apps to the ext2-partition. Someone said it might not be supported by the kernel, but I think that shouldn't be a problem, because it is working for a lot of other people.

I linked my apps (e.g. Facebook) to my 2nd partition (ext2) but it still is listed in my internal storage (data), not really got switched to ext2.
Also happened to other apps, not really working. Any solutions?
I already asked in the xda-threads for my phone and for the ROM, but only one other person has the same problem, everybody else doesn't. Any solutions?

Phone is rooted.

**Comment by alexptrn** [comment]
I'm using arc s cm 11.0 and Link2SD (using ext4 filesystem) with no problem.

I have followed this steps:
- Partition sd card with AParted by the phone: fat32 as first partition and ext4 as second (IMPORTANT).
- Install Link2SD
- Open Link2SD and set ext4 as partition to link apps (IMPORTANT)
- By the left menu on Link2SD follow linking steps.

If you intend to follow these steps, before proceed, you must delete all partitions in your sd card (backup your data).
I recommend you to leave auto link option activated in Link2SD.

**Comment by Nikhildangui** [comment]
this is nt the place to ask for the solution... if you have problem with something and its not working report it.. dont ask here how to make it work...
mover your sh*t from here
