### ISSUE TITLE
will HDMI ever going to work in kitkat?

### ISSUE THREAD

**Issue by taha001** [LegacyXperia/local_manifests#422]
There is major HDMI bug in our devices and it is been long that there is no news whether it is goin to work or not.
The presence of HDMI in our devices makes them different and more powerful wih respect to efficieny than other devices.
I hope that LEGACY XPERIA LORDS will make it work.
Thank you for your efforts dear developers.

**Comment by xange** [comment]
this is a bug report site, not asking question.......... admin close plz.....
