### ISSUE TITLE
I can not sign into Google Play

### ISSUE THREAD

**Issue by kubiss017** [LegacyXperia/local_manifests#423]
I can not sign into Google Play, writes me: "Could not sign in.. Can not establish a reliable connection to the server. This could be a temporary problem or your Android device may not be provisioned for data services. If it continues, call Customer Care. " Help me

I have SE Xperia Mini Pro SK17i, CM11 20140122 NIGHTLY

**Comment by sidharthgtm** [comment]
check date & time also your timezone

**Comment by kubiss017** [comment]
not working... help me

**Comment by azakosath** [comment]
Force stop it and launch it again.

**Comment by kubiss017** [comment]
not working

**Comment by Diabb** [comment]
You connect by wifi or data ? Try wipe Google service or look Google can send answer 

http://forum.xda-developers.com/showthread.php?t=2110225
If don't work reflash with proper gapps suggest http://forum.xda-developers.com/showthread.php?t=2012857

**Comment by kubiss017** [comment]
Already it's works !! Thanks
