### ISSUE TITLE
[cm11 20140121][urushi] Gesture typing in AOSP keyboard not working in some languages

### ISSUE THREAD

**Issue by johnnytifosi** [LegacyXperia/local_manifests#424]
Gesture typing is not working in AOSP keyboard for Greek language and also for Serbian according to the FAQ thread.
http://forum.xda-developers.com/showthread.php?t=2543426&page=181

logcat http://pastebin.com/qyuGpk62
dmsg http://pastebin.com/K2v6nPbL
I couldn;t get last_kmsg log.

**Comment by EreMaijala** [comment]
Finnish also affected.

**Comment by mikeNG** [comment]
You need to import the dictionaries for your language under keyboard settings, since they were removed from the build to save space.
You can find the dictionaries here: https://github.com/CyanogenMod/android_vendor_cm/tree/cm-11.0/overlay/dictionaries/packages/inputmethods/LatinIME/java/res/raw
