### ISSUE TITLE
after last nightly Viber Voice Calling stopped working (crashing)

### ISSUE THREAD

**Issue by Nikhildangui** [LegacyXperia/local_manifests#428]
after installing cm-11.0-20140121-NIGHTLY-LegacyXperia-haida, performance it increased big time buy i am facing issues i never came across over last any alpha build of CM11 (great mike)

every build is installed by me like an new fresh rom, flashed kernal, wiped everything and flashed Rom

VIBER WORKS FINE but when i place VOICE CALL and the moment call is received at other end viber crashes, 
giving stopped working message, but i can still send text messages viber as it dosent closes down

log attached,

**Comment by mikeNG** [comment]
please use pastebin / gist or another similar service to post the logs.

**Comment by Nikhildangui** [comment]
http://pastebin.com/uZwXqELB

MikeNG please find the log at pastebin  :+1:

**Comment by Nikhildangui** [comment]
mike few helpful words...
one guy replied me in forums saying.. its issue with latest viber and not Rom
but what i observed is in last nightly build i had updated the viber to latest and it was still working fine. (thought it was update not fresh install of viber from play store)

**Comment by mikeNG** [comment]
try latest build, I didn't find time to test it

**Comment by Nikhildangui** [comment]
i am planning to skip 6-nov-14 build .. as my neo v is my daily driver i cant afferd to flash this time.. mainly because i do full wipe every time i go for new nightly
will try in next built

thanks
