### ISSUE TITLE
[CM11][Satsuma] OK Google voice command stop working

### ISSUE THREAD

**Issue by ketkul** [LegacyXperia/local_manifests#429]
This isn't a major issued, so feel free to close it.
I am using cm-11.0-20140113-NIGHTLY-LegacyXperia-satsuma and "OK Google" voice command work great when Google Now and Hotword Detection enable on Google Home Experienced Launcher. But its stopped working on cm-11.0-20140121-NIGHTLY-LegacyXperia-satsuma.

Did anyone facing same problem and able to solve it? Any help will be much appreciated.

**Comment by ketkul** [comment]
Ok, i found the cause is because of low_ram prop is enabled by default.

Thanks

**Comment by mikeNG** [comment]
Can you post a logcat when low_ram prop is enabled? it would be nice to have it working with low_ram enabled

**Comment by ketkul** [comment]
Sorry can't post the log, because there's no log changed when low_ram prop was enabled.
It just not responding to voice command.

**Comment by mikeNG** [comment]
weird
