### ISSUE TITLE
Busybox issue

### ISSUE THREAD

**Issue by iksorek** [LegacyXperia/local_manifests#43]
Do only i have problems with busybox on mango?
Trying to use mounts2sd, but it shows busybox not configured correctly. I tried to download other from market but all instalations fail.
Build 28/8/13, included kernel used.

**Comment by MIXTERek** [comment]
i'm using busybox on mango and work correct. backup your data and wipe all :)

**Comment by mikeNG** [comment]
Busybox works fine here too.

**Comment by mikeNG** [comment]
I'm closing this. busybox is included by default in all CM builds and works
