### ISSUE TITLE
[Enhancement] Switching System reset button from POWER+HOME to POWER+CAMERA HARD PRESSED or anything else

### ISSUE THREAD

**Issue by sidharthgtm** [LegacyXperia/local_manifests#431]
I have been using legacy rom from cm10.1 and love this function of System reset. But have suffered from accidental press of this combination while taking out the mobile from pocket a several times.
I always respect the functions and feature which @mikeNG implements on this rom.
This is only a suggestion . I respect you .
Will look forward for your reply .. Thnx

Device i use : Xperia Mini ST15i

**Comment by godlesplay** [comment]
it's hard to press power and home at the same time while taking out the mobile from pocket... just take out your phone via edges of phone

**Comment by sidharthgtm** [comment]
See .. its hard i know but it can occur accidentally. With [POWER] + [CAMERA HARD PRESSED] it will become way better . Its just a suggestion let Mike see it.

**Comment by mikeNG** [comment]
Not all devices have camera key so this is not possible.
I agree with godlesplay, I never managed to restart any of my 3 phones (mini, ray, arc) that way...

**Comment by sidharthgtm** [comment]
Thnx for listening mike
