### ISSUE TITLE
[CM11.0] mmc1_detect wakelock (when using sd_ext?)

### ISSUE THREAD

**Issue by krikoCodeCook** [LegacyXperia/local_manifests#433]
Possibly when using a script for linking programs to sd_ext, "mmc1_detect" wakelock appears to be preventing the phone from going into deep sleep and it spend more time at lowest possible frequency, causing higher battery drain.

Currently I've tested with:
- links2sd (but I've dumped all logs and assumptions, since there seems to be a problem with the cache being recreated on the device)
- mounts2sd

Before installing CM11, I've reformatted my SD card to eliminate any problems with fs corruption (it is a new class 10 sd, works on fxp CM10 without causing this wakelock)

After installing CM11 (ftf ICS flash, flashed provided kernel, formatted partitions in specified order, installed rom and gapps) I proceeded with installing some applications:
- cpuSpy (shows spent cpu states)
- BetterBatteryStats
- WakeLock Detector
- LegacyXpera Center (for log collection)
- Mounts2sd

Note: after removing mounts2sd script and app, the mmc1_detect wakelock still appears. Is it possible that the rom is somehow "contaminated" due to some leftovers? If so, then I'll reformat partitions and reflash the rom just to eliminate the possibility of this bug being present only in this scenario (might be random luck the first time this wakelock did not appear without using sd_ext)

Version / build: cm-11.0-20140121-NIGHTLY-LegacyXperia-haida

Logs:
https://www.dropbox.com/s/71urfhfotln0xq6/bugreport_mount2sd.zip
or
https://drive.google.com/file/d/0B1ZKsglImPy3RXNJTVdoUEU0M3M/edit?usp=sharing

I hope there is enough info to narrow down the issue to the core problem.

**Comment by krikoCodeCook** [comment]
UPDATE

I've retried with a fresh rom, without sd_ext scripts (though the partition is present on sd - but it's not being mounted).
I started at step 2  (kernel was already flashed) which claims to format partitions in specific order, flashed zip and gapps. Installed the same apps as in first post.

Still same wakelock starts surfacing on top. So to my testing it's not due to mount scripts - maybe somehow the sd_ext presence could interfere, this was not excluded.

---

Logs taken from a ~20 min uptime (BBS and LegacyXperia Center):

https://www.dropbox.com/s/gbjbczw2tgv3i5u/report.zip
or
https://drive.google.com/file/d/0B1ZKsglImPy3RXNJTVdoUEU0M3M/edit?usp=sharing

**Comment by krikoCodeCook** [comment]
Update:

Testing with latest build cm-11.0-20140203-NIGHTLY-LegacyXperia-haida

Fresh install with same apps as before EXCEPT mount2sd or any of ext_sd scripts.
The wakelock still surfaces. Collected the logs with LegacyXpera Center.

---

https://www.dropbox.com/s/agwbew2g45illss/bugreport_7.2.2014.zip
or
https://drive.google.com/file/d/0B1ZKsglImPy3MFJlWXBCR3psbkk/edit?usp=sharing

**Comment by mikeNG** [comment]
Thanks for all the info, but I wasn't able to reproduce this wakelock, testing all week in my 3 devices. From a first look, I didn't find any indication in the logs. I'm using sd_ext in 1 of the 3 devices, makes no difference. Maybe you can try with a different SD for a while and see what happens?

**Comment by krikoCodeCook** [comment]
I've managed to get hold onto an older 512MB SD Card (it was originally included with my new Nokia N95, but never used). I created just one fat32 partition, nothing else.

I've used same steps as above, EXCEPT I didn't enter my google account at first run. Then proceeded installing same apps as before from apk's.
At first boot everything is fine, phone is entering deep-sleep (from 15 min running it was the same ratio as on FXP CM10). But after the first reboot, the mmc1_detect wakelock started to surface again.

The only change before rebooting was setting the battery percentage to show inside the circle.

From observations, I thought the partition gets "dirty" because when rebooting the phone, I noticed it shuts down very quickly in any case (~2-3 seconds), without displaying the safe SD removal notification like in other roms (e.g. GB, stock ICS, FXP CM10, etc...).
But it didn't matter - I've tried to put the SD card again into pc, rechecking for damage, trying even booting without SD - same wakelock shows up.

Will try with more test (clean reinstall, etc.) again later.

**Comment by krikoCodeCook** [comment]
UPDATE: same observations with new 8GB class 10 cards - everything is ok after fresh install under same conditions, until first reboot.

**Comment by krikoCodeCook** [comment]
I've tested with another card - 2GB to confirm the issue again.
Installed all listed apps (no google account entered on start). The mmc1_detect  wakelock can be observed the same way as with other cards.

Was one of the devices you have tested a haida device (maybe it's a specific bug tied to a specific HW platform)?

**Comment by mikeNG** [comment]
No, I only have anzu, smultron & urushi. Have you ever tested any older builds (10.1/10.2)?

**Comment by krikoCodeCook** [comment]
With cm-10.2-20140207-NIGHTLY-LegacyXperia-haida the wakelock is present and same goes for cm-10.1-20131108-NIGHTLY-LegacyXperia-haida.

Should I try older versions of those roms? Should I go with oldest - cm10.1 gradually?

**Comment by mikeNG** [comment]
Maybe try with some older builds, unfortunately I have deleted most old builds. There might be some recent kernel changes that caused this, that's why I'm asking

**Comment by mikeNG** [comment]
By the way, how much battery drain are we talking about?

**Comment by krikoCodeCook** [comment]
Just a quick update to this bug - sorry I have exams.
It was about 7-8% per hour. A night of standby could exhaust battery completely if it wasn't on charger.

I took some unusual "unclean" steps compared to previous installation. Didn't have the time to test what really removed this battery drain and rampant wakelock.

Mentioned full steps are in this post: http://forum.xda-developers.com/showpost.php?p=51709497&postcount=3019
Deep sleep works fine, it's great as in FXP CM10. The only suspicious step is an upgrade from CM10 (no ICS ftf flash!), I cannot see how other steps could contribute to this. List of installed apps is also much bigger by now and battery drain is minimal.

Will try to do some test, but not that soon.
Thank you for you time!

**Comment by krikoCodeCook** [comment]
I'm unable to reproduce high wakelock usage under cm-11.0-20140319-NIGHTLY-LegacyXperia-haida build.

It works fine even when flashing over clean ICS ftf. Maybe it was somehow fixed in latest kernel. Closing.

**Comment by mkj** [comment]
I'm seeing what looks like the same issue with cm-11-20140604-UNOFFICIAL-LegacyXperia-mango. The previous release 20140512 didn't have the problem.  I'm not using sd_ext, all a pretty standard install. Lots of programs moved to sd card with Titanium Backup though, if that's a possible cause?

Any debugging details I can send?

**Comment by krikoCodeCook** [comment]
Collect logs with LegacyXperia center and upload.
This wakelock seems to be "normal", but it shouldn't come up as most occurring (on top of list).

If nothing seems to help, you might want to try a proper clean reinstall:
- seus firmware reflash
- ftf flash (not sure if ftf is the same, if it is skip this)
- reinstall LXP following posted steps in official guide

And after installation leave it for 10min for it to settle, then reboot. At first boot it never enters deep sleep in my experience.

**Comment by emaijala** [comment]
I'm now seeing this too on cm-11-20140604-UNOFFICIAL-LegacyXperia-iyokan. I don't think it was there in the cm-11.0-20140320-NIGHTLY-LegacyXperia-iyokan build. Not sure about  cm-11-20140512-UNOFFICIAL-LegacyXperia-iyokan. After about 14 hours since unplugged from charger,  suspend_backoff has had a kernel wakelock for about 8 hours and mm1_detect 1:22 hours. Battery drain is 4.6% per hour with the phone having been mostly idle for the whole day. There has been only 156 seconds of deep sleep. I'm using sd_ext with Mounts2SD. I changed the memory card to a Sandisk Ultra 32 GB at the same time I upgraded to 20140604 build, so there' a chance it somehow makes a difference. I'm pretty sure I haven't rebooted since I did the upgrade (and last kernel log is not available, which supports that too), so that doesn't seem to make a difference here. Logs:

BetterBatteryStats: http://pastebin.com/WDs2Gsqv
dmesg: http://pastebin.com/SLSZhKNm
logcat system: http://pastebin.com/bJ9YpBbP
logcat main: http://pastebin.com/fGbiWXpG

**Comment by krikoCodeCook** [comment]
Have you changed any settings perhaps under performance menu?
I see you have suspend_backoff wakelock too.

**Comment by emaijala** [comment]
Only max clock to 1,2GHz, as far as I remember. From reading a lot of stuff I understood that suspend_backoff kicks in when something else causes too frequent resume from deep sleep, like mmc1_detect seems to. So I think it may be a symptom caused by mmc1_detect.

**Comment by krikoCodeCook** [comment]
Ok, could you revert to stock frequency, and uncheck "set at boot" tick? Then reboot.
Monitor cpu states for e.g. with cpu spy: https://play.google.com/store/apps/details?id=com.bvalosek.cpuspy

After reboot leave it 5 to 10 min for it to settle, reset counters in cpu spy and then put it into standby for about 5 min and recheck cpu states (you might need to press refresh to see new data).
Does it enters deep sleep now?

**Comment by emaijala** [comment]
Sure, but now the problem's not on. I rebooted this morning and deep sleep is back to normal. I'll see if it goes haywire again with the default frequency.

**Comment by emaijala** [comment]
It's happening again and with the default frequency. mmc1_detect wake lock count 17874:
http://pastebin.com/tn5iW8Fd

**Comment by eldigo** [comment]
I have the same issue, with the lasted build  cm-11-20140604-UNOFFICIAL-LegacyXperia-mango
For test I put the kernel (fastboot boot.img only) of build  cm-11-20140512-UNOFFICIAL-LegacyXperia-mango back and the mmc1_detects wake locks disappers. Only the wifi and sound weren't working any more because it a  wrong kernel...
But this shows that the wakelock are a kernel issue..

**Comment by eldigo** [comment]
Just updated to cm-11-20140611-UNOFFICIAL-LegacyXperia-mango.
Looking good sofar!

**Comment by enveraltin** [comment]
​I've been suffering from this wakelock too, and it seems the problem is
resolved with 20140611-mango build.

Thanks!​

On Wed, Jun 11, 2014 at 4:17 PM, EldigoR notifications@github.com wrote:

> Just updated to cm-11-20140611-UNOFFICIAL-LegacyXperia-mango.
> Looking good sofar!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LegacyXperia/local_manifests/issues/433#issuecomment-45739172
> .

## 

Enver

**Comment by eldigo** [comment]
... to bad.. Still got the wakelocks with the cm-11-20140611 build..

**Comment by bjo81** [comment]
1175 mmc1_detect wakelocks in 1,5hrs on haida, built on 12.08.2014 :/
