### ISSUE TITLE
[11.0][urushi] Auto-brightness doesn't work

### ISSUE THREAD

**Issue by pkocandr** [LegacyXperia/local_manifests#435]
Although the light sensor is working ok at least according to changing value displayed in auto-brightness levels settings the brightness is not changed at all while the auto option switched on. Tested on cm-11.0-20140121-NIGHTLY-LegacyXperia-urushi.zip.

**Comment by the-dreamer** [comment]
for me it is working as expected.

**Comment by mikeNG** [comment]
Working fine here too on urushi.

**Comment by pkocandr** [comment]
OK, it seems the settings were kind of weird. After I reset them it is working ok too. Closing.
