### ISSUE TITLE
Mango - Trebuchet crash

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#436]
I am using Xperia Mini pro (SK17i) with the last version of CM11 Nightly.
Everything is fine to me except just one crashing matter.

When I sliding up or down the hardware keyboard only at home screen, the message "Unfortunately, Trebuchet has stopped." is frequently shown up.

I had fixed the screen rotation horizontal, but the same crash was happened.

During using any other application, the crash is not happened!!
The message is being shown up only at the home screen when I sliding up or down the hardware keyboard.

Since I am a light user of the custom roms, please let me know or give me a idea how to fix this problem in detail. Thanks in advance.

**Comment by mikeNG** [comment]
provide logcat when the crash happens

**Comment by ghost** [comment]
Below is the logcat result.

--------- beginning of /dev/log/system
I/WindowManager(  629): Screen frozen for +577ms due to Window{41e82670 u0 jackpal.androidterm/jackpal.androidterm.Term}
I/ActivityManager(  629): Config changes=4a0 {0.85 450mcc5mnc ko_KR ldltr sw320dp w320dp h455dp 160dpi nrml port finger qwerty/v/h -nav/h s.36 themeResource=null}
I/WindowManager(  629): Screen frozen for +563ms due to Window{41e82670 u0 jackpal.androidterm/jackpal.androidterm.Term}
I/ActivityManager(  629): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10200000 cmp=org.cyanogenmod.trebuchet/.Launcher} from pid 629
I/ActivityManager(  629): Config changes=4a0 {0.85 450mcc5mnc ko_KR ldltr sw320dp w480dp h295dp 160dpi nrml land finger qwerty/v/v -nav/h s.37 themeResource=null}
E/AndroidRuntime( 3300): FATAL EXCEPTION: main
E/AndroidRuntime( 3300): Process: org.cyanogenmod.trebuchet, PID: 3300
E/AndroidRuntime( 3300): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.cyanogenmod.trebuchet/org.cyanogenmod.trebuchet.Launcher}: java.lang.NullPointerException
E/AndroidRuntime( 3300):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2215)
E/AndroidRuntime( 3300):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2265)
E/AndroidRuntime( 3300):    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3758)
E/AndroidRuntime( 3300):    at android.app.ActivityThread.access$900(ActivityThread.java:145)
E/AndroidRuntime( 3300):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
E/AndroidRuntime( 3300):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 3300):    at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 3300):    at android.app.ActivityThread.main(ActivityThread.java:5081)
E/AndroidRuntime( 3300):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 3300):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 3300):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
E/AndroidRuntime( 3300):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/AndroidRuntime( 3300):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 3300): Caused by: java.lang.NullPointerException
E/AndroidRuntime( 3300):    at org.cyanogenmod.trebuchet.Workspace.restoreInstanceStateForChild(Workspace.java:4172)
E/AndroidRuntime( 3300):    at org.cyanogenmod.trebuchet.Launcher.onRestoreInstanceState(Launcher.java:1931)
E/AndroidRuntime( 3300):    at android.app.Activity.performRestoreInstanceState(Activity.java:916)
E/AndroidRuntime( 3300):    at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1138)
E/AndroidRuntime( 3300):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2183)
E/AndroidRuntime( 3300):    ... 12 more

**Comment by mikeNG** [comment]
still happens in the latest build?

**Comment by basil911** [comment]
yup it does i cant totaly use my phone nw

**Comment by basil911** [comment]
other than reboot

**Comment by mikeNG** [comment]
I can't reproduce this with latest sources on my xperia play which also has a slider.

**Comment by mikeNG** [comment]
Please try latest build and provide logs if this still happens
