### ISSUE TITLE
ebay app barcode scanner no preview

### ISSUE THREAD

**Issue by esemef** [LegacyXperia/local_manifests#438]
In ebay app click "sell an item icon", click "scan your item".

The preview window is always black, although the app does appear to enable the camera as if you can align the barcode blind it will sometimes beep and then the screen goes black. I'm not sure what it's doing at this point as the lock screen will come on & unlocking and going back to the ebay app is usually still a black screen, but I have had it eventually display a matching item.

**Comment by esemef** [comment]
logs at https://gist.github.com/esemef/3a1ea04b39ae14657120

**Comment by mikeNG** [comment]
Please try latest build and provide logs if this still happens
