### ISSUE TITLE
LX 10.2 Nightly - 20140112 (Coconut) - On-call Proximity Sensor bug

### ISSUE THREAD

**Issue by SHOROOP** [LegacyXperia/local_manifests#439]
An annoying bug at 20140112 nightly build. Screen shuts down when I'm calling and don't turns on until call ends.
I think that it's a problem with a proximity or a light sensor. Stable build doesn't have this bug.

**Comment by SHOROOP** [comment]
Bug fixed after editing /system/etc/hw_config.sh (second part of proximity sensor configuration):

  val_cycle=2
  val_nburst=0
  val_freq=2
  val_threshold=5
  val_filter=0

**Comment by mikeNG** [comment]
Hmm I forgot to revert one change since December, will be fixed in today's build. Thanks for pointing it out
