### ISSUE TITLE
Titanium Backup Problems

### ISSUE THREAD

**Issue by seamo123** [LegacyXperia/local_manifests#44]
I've flashed Mike's latest nightly 10.2 ROM (29 Aug) three times and keep coming up against the same problems. Whenever I try to uninstall an app via Titanium it keeps flagging up a 'failed to locate the apk file' message. Whenever I try to restore an app via Titanium it just goes into a 'restoring app' loop until I eventually have to restart the phone - and obviously no restored app is to be found. Titanium also asked for, and got, root access so I don't think there's a problem there. Maybe there's something amiss somewhere with the folders Titanium is reading? Thing is, the folder Titanium is reading the backups from is where the backups are actually located.. so I can't see what the problem is.

One thing I did notice, CWM is quite laggy and also lists my sdcard as 'sdcard0', might this have something to do with it?

**Comment by djey47** [comment]
Some versions of Titanium have been reported to behave weirdly with 4.3. App has just been updated to address those issues. Which TiBackup version are you using actually ?

**Comment by seamo123** [comment]
Version 6.0.2. if I remember correctly.. So if I update then it should work OK?

**Comment by Gary733** [comment]
I have version 6.1.0 of Titanium Backup and it works without any issues.

**Comment by DanielMalmgren** [comment]
Yes, 6.1.0 works without problems for me as well. Also the changelog of 6.1.0 mentions "initial support for Android 4.3". So clearly this is not a problem with neither CM nor LX but with TB 6.0 not handling Android 4.3.

**Comment by seamo123** [comment]
Yeah, updating Titanium worked a treat. Thanks guys.
