### ISSUE TITLE
cm-11.0-20140121-nightly-legacyxperia-anzu clock crashing

### ISSUE THREAD

**Issue by deagle751** [LegacyXperia/local_manifests#442]
Every time when I want to change or add alarms it closes and gives me a error box "unfortunately, clock has stopped"

**Comment by mikeNG** [comment]
provide logs!

**Comment by deagle751** [comment]
for some reason it is working now but this morning and yesterday it still gave the error. as soon as it starts giving the error i will post the logs and sorry for not posting them before because i didnt know how to get them
