### ISSUE TITLE
webview in 2014-03-02 mango build

### ISSUE THREAD

**Issue by vkuhnde** [LegacyXperia/local_manifests#444]
Every time trying to open an app with a WebView, it fcs. WhatsApp feedback shows a java.lang.ClassNotFoundException in dalvik.system.BaseDexClassLoader for the class <b>android.webkit.JniUtil</b>

Logcat: http://pastebin.com/VC3SKKE1
I opened the Browser and a WhatsApp chat (both crash).
Here is a screenshot of the WhatsApp crash feedback: ![screenshot_webview1](https://f.cloud.github.com/assets/6226265/2086888/27dc239a-8e61-11e3-83dc-59e4828c4b29.png)

**Comment by mikeNG** [comment]
Ok this is  a serious bug, I'll take a look

**Comment by chua97** [comment]
hi man.... the calendar has got the same problem D: please fix first whatsap.. i need it D:
thank for work..

**Comment by chua97** [comment]
now crash fb messenger... help please D:

**Comment by rkkoszewski** [comment]
The same problem on Haida (Neo V)

**Comment by mo0nsniper** [comment]
Same issue here. Xperia Pro

**Comment by vkuhnde** [comment]
Did you install the webview fix? See Issue #464 and #466
