### ISSUE TITLE
Google Account Manager Crashed 20140203 Nightlybuild CM11 Mango

### ISSUE THREAD

**Issue by aznantea** [LegacyXperia/local_manifests#445]
Hi, I have problem while adding my google account to my phone. My phone is Xperia Mini Pro SK17i. While I enter My E-Mail and Password it just said "Unfortunately, google account manager has stopped working" and also brpwser just crash while I want to open it.
![screenshot_2014-02-05-21-53-19](https://f.cloud.github.com/assets/6595742/2088013/643d7e56-8e75-11e3-941f-e5389b313675.png)

**Comment by vkuhnde** [comment]
The browser fc could be same as for me: https://github.com/LegacyXperia/local_manifests/issues/444

**Comment by rkkoszewski** [comment]
The same on Haida (Neo V)

**Comment by edips** [comment]
Xperia Arc s has same problem in cm-11.0-20140203-NIGHTLY-LegacyXperia-anzu.zip, but after flashed cm-11.0-20140121-NIGHTLY-LegacyXperia-anzu.zip, it works good. Thank you.

**Comment by nygooz** [comment]
Have the same issue on Haida cm-11.0-20140203-NIGHTLY

**Comment by vkuhnde** [comment]
Did you install the webview fix? See
"[CM11] urushi - all Browser crash": https://github.com/LegacyXperia/local_manifests/issues/464
and
"Google accounts app crashed [mango]": https://github.com/LegacyXperia/local_manifests/issues/466

**Comment by hedgehook** [comment]
i got sam problem in cm-11.0-20140203-NIGHTLY-LegacyXperia-hallon but i can create now account and log in without crashed. And when i open the broswer, it say 'Unfortunately, Broswer has stopped' and same issue for Tweetcaster app.

**Comment by g2p** [comment]
The [webview fix](http://forum.xda-developers.com/showpost.php?p=50122471&postcount=2161) R1Pieces linked worked for me. Thanks!
