### ISSUE TITLE
[CM11] Low youtube videos quality (on haida)

### ISSUE THREAD

**Issue by zidanek1999** [LegacyXperia/local_manifests#446]
Quality of youtube videos is very low on my device (with "EQ" turned on). I'm sure it was better on CM10.2. Do you have any ideas how to fix it ?

**Comment by ghost** [comment]
I don't think it's ROMs fault.
YT:
![screenshot_2014-02-07-21-00-23](https://f.cloud.github.com/assets/5565504/2114020/2c25a77e-9036-11e3-9446-67a4d9560d16.png)
Dailymotion:
![screenshot_2014-02-07-21-07-44](https://f.cloud.github.com/assets/5565504/2114027/3d9669bc-9036-11e3-9407-32c535721dd7.png)
As you can see both of these videos are streamed in highest quality available and  both of them were encoded with the same software by the same person. There must be something wrong with newest YT.

**Comment by zidanek1999** [comment]
That's right, I noticed that other videos have normal quality. I'll wait for next version of youtube.

**Comment by mikeNG** [comment]
app issue
