### ISSUE TITLE
CM11 nightly 20140203 

### ISSUE THREAD

**Issue by egonzalez469** [LegacyXperia/local_manifests#447]
Alguien mas tiene problemas con los administradores de cuentas nisikiera puedo usar la playstore se me cierra cualquier cosa  tenga k tenga k ver con cuentas

**Comment by mikeNG** [comment]
only english please

**Comment by egonzalez469** [comment]
well, i installed cm11 nightly build 20140203 but i cant sign in my google account, then i cant download apps from appstore, i wanted to know if are there more people with this problem?

**Comment by mikeNG** [comment]
#452
