### ISSUE TITLE
[cm-11.0-20140203-NIGHTLY-LegacyXperia-haida.zip] Webview apps crash 

### ISSUE THREAD

**Issue by soulpower11** [LegacyXperia/local_manifests#452]
Messaging crash when opening up a message.

dmesg: http://pastebin.com/jURne3qw
last_kmsg: http://pastebin.com/CWugrS9s
logcat: http://pastebin.com/Pxf0cHzC

**Comment by mikeNG** [comment]
can you check if libwebcore.so is present in /system/lib ?

**Comment by soulpower11** [comment]
No, it is not present.

**Comment by the-dreamer** [comment]
Same here. libwebcore not present.

**Comment by mikeNG** [comment]
can you take it from the previous build?

**Comment by soulpower11** [comment]
hmm it is still the same.

**Comment by the-dreamer** [comment]
same here. Also changing permission to the rw-r-r like other libs change nothing.

BTW: whatsapp is also crashing :-/

**Comment by soulpower11** [comment]
Found out that libharfbuzz.so is also missing, added it back changed permission to rw-r-r, rebooted and it seems like everything is working again, both messaging and browser

**Comment by the-dreamer** [comment]
confirmed. for me also. Browser / whatsapp / email so far i have tested. Thx!

**Comment by badboyasd** [comment]
libharfbuzz.so + libwebcore.so port back from previous build= webview work.

**Comment by mikeNG** [comment]
Flashable zip here http://forum.xda-developers.com/showpost.php?p=50122471&postcount=2161

**Comment by foivos83GreekTester** [comment]
Thank you all.i flash the webview zip and all its work now

**Comment by Seegras** [comment]
Same problem on iyokan.

**Comment by the-dreamer** [comment]
You already found this bug tracker ticket. Why you didn't read this ????????

Because of this reason mike is pissed of a bit.. I can understand it.... ^^

**Comment by Pesta666** [comment]
Webview helped, thank you so much for patch and your amazing ROM, great job!
