### ISSUE TITLE
[cm-11.0-20140203-NIGHTLY-LegacyXperia-coconut.zip] Webview crashes

### ISSUE THREAD

**Issue by CristianoLira** [LegacyXperia/local_manifests#455]
Browser doesn't start webview and crashes immediately after launching (Live With Walkman - coconut).
Any other webview apps also crash.

Log:
http://pastebin.com/WHhjcN3T

**Comment by soulpower11** [comment]
Try this, take libwebcore.so and libharfbuzz.so from the previous build add it to /system/lib and change permission to rw-r-r then reboot.

**Comment by CristianoLira** [comment]
I'll try it. Thanks.

**Comment by mikeNG** [comment]
see #452

**Comment by badboyasd** [comment]
MY XPERIA RAY HAVE SAME ERROR. WEBVIEW CRASHES
cm-11.0-20140203
