### ISSUE TITLE
CM11:Wifi doesnt work when screen goes off & When I click home button leftmost homepage displayed

### ISSUE THREAD

**Issue by bgokul95** [LegacyXperia/local_manifests#456]
Xperia Neo V (haida)
Using CM 11 (20140122)
1.Wifi Buggy Please fix.
2.When I click home button, left most homepage appears and not the middle one.
3.RAM memory became very less.
4."Ok Google" not working.
5.Messaging app not replaced by Hangouts.

**Comment by soulpower11** [comment]
1. Go to Wi-Fi, Advanced, Keep Wi-Fi on during sleep, always. It will keep Wi-Fi on during sleep 
2. What do you mean ??
3. Ram is a problem with our device
4. Change your language to English US or English UK if you are using the latest version
5. Change can use hangouts yourself

**Comment by mikeNG** [comment]
I'm closing this. most of the things you describe are not bugs, please do some research before filing bug reports next time.
