### ISSUE TITLE
[CM11.0] [Coconut] WiFi Issue

### ISSUE THREAD

**Issue by gxgani** [LegacyXperia/local_manifests#457]
Once turned on, doesn't go off nor connects to AP again.

Log: https://gist.github.com/gxgani/54c23d964f515186339c

PS: All the details has been stated in the log description.

**Comment by gxgani** [comment]
Weird, after reboot it seems to work. I'll keep an eye on this issue. Meanwhile, the logs does indicate an adapter failure.

**Comment by mikeNG** [comment]
I couldn't reproduce this, if you had a dmesg log it would be useful.
Closing the issue for now.
