### ISSUE TITLE
(Haida) Have some serious bugs with cm-11.0-20140203-NIGHTLY-LegacyXperia-haida Build

### ISSUE THREAD

**Issue by pharandeamit** [LegacyXperia/local_manifests#458]
Just Flashed clean latest cm-11.0-20140203-NIGHTLY-LegacyXperia-haida build... and after booting up when i tried to add Google account in account Manager Account Manager giving FC...tried many time but same problem... even Link2SD and Root Explorer also giving some time FC... Flashed Rom Twice but no luck same Problem again & again... Reverting back on Previous version..Plz Fix it... Thanks

**Comment by mikeNG** [comment]
Check #452
