### ISSUE TITLE
[cm-11.0-20140203-NIGHTLY-haida]  Application gets crashed automatically.

### ISSUE THREAD

**Issue by anilgupta003** [LegacyXperia/local_manifests#459]
When i open any application like whatsapp, clean master or cymera. it will gets crashed automatically. Please find attached log cat files for the same. It says that "Unfortunately, whatsapp has stopped".

dmsg - http://paste.ubuntu.com/6892910/
last_kmsg - http://paste.ubuntu.com/6892915/
logcat - http://paste.ubuntu.com/6892920/

**Comment by mikeNG** [comment]
See #452
