### ISSUE TITLE
Minecraft PE not working

### ISSUE THREAD

**Issue by braianrq** [LegacyXperia/local_manifests#461]
there was always a problem with Minecraft Pocket Edition, first when you open the game does not display image only shows a black screen but able to hear the sounds of the game, to open it you have to open the Minecraft PE once, close it and open it back and the truth that is very annoying, when you lock the screen while playing Minecraft PE sounds are heard but when you unlock and want to play again, the game stops "Minecraft Pocket Edition has stopped," I always had the same problem and apparently never fixed. 
Sorry for my bad English, I'm Spanish speaking.
this has been happening to me since the rom 4.1 Jelly Bean of coconut and I currently have the 4.4 android rom Kit Kat

**Comment by Apocalypse2** [comment]
run the game and when this black screen keep pressing the start button until q the recent apps menu appears, select minecraft and there it is ...

**Comment by mid-kid** [comment]
Confirmed on haida. (it happened to me in cm 10.2. never tried again since)
Please change the title to something more... peaceful.
Thanks ;)

**Comment by mikeNG** [comment]
Please try latest build and provide logs if this still happens
