### ISSUE TITLE
aosp keyboard How can I download dictionary

### ISSUE THREAD

**Issue by emre1717** [LegacyXperia/local_manifests#463]
How can I download keyboard  dictionary turkish langue pack ?? 

help please

**Comment by ghost** [comment]
THIS IS A BUG TRACKER. FOR BUG REPORTS NOT QUESTIONS. 
Seriously how dumb are you. Ask here http://forum.xda-developers.com/showthread.php?t=2543426

**Comment by emre1717** [comment]
pypcz ??
