### ISSUE TITLE
[CM11] urushi - all Browser crash

### ISSUE THREAD

**Issue by Urcle** [LegacyXperia/local_manifests#464]
When i start standard browser or an other browser like Maxthon or Dolphin the application crashed.

**Comment by vkuhnde** [comment]
Have you installed the webview fix? See here: http://forum.xda-developers.com/showpost.php?p=50122471&postcount=2161
Just download and install zip from sd card via recovery.

**Comment by Urcle** [comment]
Thanks it works :-)
