### ISSUE TITLE
Google accounts app crashed [mango]

### ISSUE THREAD

**Issue by REIZOR008** [LegacyXperia/local_manifests#466]
When I write a login and password, the application crashes СM11 20140203 [mango]

**Comment by vkuhnde** [comment]
Have you already tried the webview fix? Some people said it fixed the Google login issue for them.

Fix see here: http://forum.xda-developers.com/showpost.php?p=50122471&postcount=2161
(Download and install zip via recovery)

**Comment by vbouchaud** [comment]
Hi, it fixed it for me on cm-11.0 20140203 (anzu). Thanks!

**Comment by lofas33** [comment]
Thx a lot! It really fix this problem on Anzu...THX!!

**Comment by Tobii-** [comment]
THX!
login -> 2 factor authentication -> webview -> crash :D
