### ISSUE TITLE
[CM11 Mango] Vibration Problem

### ISSUE THREAD

**Issue by kuntalbd** [LegacyXperia/local_manifests#467]
I flashed cm-11.0-20140113 rom but i am facing strange problem. phones vibration does not work some time. Its not for specific notification. When it doesn't work, its applicable for call, sms, notification and other vibration testing app. 
I followed the instruction and after founding problem, I flashed several times. But problem still exists. 
**\* Vibration works some time, does not work some time.
after that, I tried other ROM like stock GB, ICS, custom SJB 4.2.2. Vibration is working properly on them.
== I searched over internet to find others facing my problem on this build, but not found. Cant understand is it my  problem?

**Comment by Urcle** [comment]
I have the same device and i don´t have this problem.
I will be check it...

**Comment by kuntalbd** [comment]
Thank you bro. I cant figure out why its happening to me.

**Comment by mikeNG** [comment]
It works fine on all my 3 devices...

**Comment by Apocalypse2** [comment]
works well in my coconut

**Comment by kuntalbd** [comment]
Ok then I think its only my device specific problem. Thanks for your reply guys.
