### ISSUE TITLE
[CM10.2] [Mango] Device encryption not working

### ISSUE THREAD

**Issue by pdesanex** [LegacyXperia/local_manifests#468]
It repetendly tried to encrypt my SK17i using the "encrypt phone" feature. After going through the necessary steps for setting up the encryption, the android encryption logo appears. However, no status message pops up ("Wait while your phone is being encrypted. XY% complete.") ... I waited for hours to make sure the encryption finishes -- nothing happens. When at some point I press the home button, the encryption screen just disappears. So does the title bar (it just turns black). After a reboot everything is back to normal (but the phone is not encrypted).

**Comment by pdesanex** [comment]
```
[ 02-10 09:05:50.468   555:  586 I/ActivityManager ]
Displayed com.android.settings/.CryptKeeperConfirm$Blank: +202ms

[ 02-10 09:05:51.059   225:  281 E/Cryptfs  ]
Cannot get size of block device 
```

This seems to be a problem from upstream:
https://jira.cyanogenmod.org/browse/CYAN-87

**Comment by pdesanex** [comment]
Also:
- http://code.google.com/p/freexperia/issues/detail?id=658
- https://github.com/CyanogenMod/cm-kernel/pull/6

**Comment by mikeNG** [comment]
It's not possible to enable encryption on our devices without writing a ton of code from scratch. Not worth for a 3 year old device.
