### ISSUE TITLE
Coconut - Playback control takes too long

### ISSUE THREAD

**Issue by xorgx3** [LegacyXperia/local_manifests#469]
When the screen is off, long pressing the volume keys should switch to next/prev song in the music player. Since the newest cm-11.0-20140203-NIGHTLY it takes too long( i push the button, i have to wait about 30 sec or more and after this time song is changed).
I am using poweramp if this is important.

**Comment by mikeNG** [comment]
which player are you using?

**Comment by xorgx3** [comment]
i was writing: POWERAMP

**Comment by mikeNG** [comment]
whoops didn't see that. I will try to reproduce

**Comment by mikeNG** [comment]
Provide logs if this still happens in latest build which will be released tomorrow
