### ISSUE TITLE
Wifi does not work on 802.1x EAP

### ISSUE THREAD

**Issue by al33m** [LegacyXperia/local_manifests#47]
I am not able to connect Wifi on my Office network (802.1x EAP). I am asked to give my User id and Password, when I enter user ID and password it shows connecting but does not get connected. Please find the logcat of the same at the below link.

http://pastebin.com/sgiCq3E0

Thanks,
al333m

**Comment by mikeNG** [comment]
Wait for next release

**Comment by erseco** [comment]
I have the same problem with the cm_smultron-LX-20130908-RELEASE.zip there are another version that fix this? Thanks!

**Comment by mikeNG** [comment]
Try the latest release please

**Comment by mohsen-pgr** [comment]
I have the same problem with  cm-10.2_anzu-LX-20131013-NIGHTLY.zip,
How I can fix?

**Comment by natanE** [comment]
same problem with cm-10.2_coconut-LX-20131013-NIGHTLY.zip
can't connect a 802.1x network (PEAP/MSCHAPv2) yet able to connect a non-secure network.

WIFI shows "connecting..." for some time then stop trying.

**Comment by mikeNG** [comment]
Any luck with the latest release?

**Comment by ghost** [comment]
Works for me in the 20131112 release.

**Comment by mikeNG** [comment]
Closing this

**Comment by highman** [comment]
I have the same problem with the cm-11-20140703-UNOFFICIAL-LegacyXperia-hallon.zip. There are another version that fix this? Thanks!
