### ISSUE TITLE
[hallon][cm-11.0-20140203] Built-in web browser doesn't work.

### ISSUE THREAD

**Issue by taro-k** [LegacyXperia/local_manifests#470]
Xperia neo with cm-11.0-20140203.
Built-in web browser "unfortunately" stops immediately after started.
If anything I can check for debugging, please let me know. thx!

**Comment by taro-k** [comment]
cm-11.0-20140121 doesn't have this matter.

**Comment by s-kostyuk** [comment]
see here: https://github.com/LegacyXperia/local_manifests/issues/464
