### ISSUE TITLE
[hallon][cm-11.0-20140203] Built-in e-mail app stops

### ISSUE THREAD

**Issue by taro-k** [LegacyXperia/local_manifests#473]
Xperia neo with cm-11.0-20140203.
Built-in e-mail app "unfortunately" stops when displaying a detail of e-mail.

cm-11.0-20140121 doesn't have this matter.
If anything I can check for debugging, please let me know. thx!

**Comment by mokkin** [comment]
Same here with anzu.  The same behaviour appears while opening the browser.

**Comment by taro-k** [comment]
I will try, thanks lot!

**Comment by mokkin** [comment]
@taro-k What will you try?!

**Comment by taro-k** [comment]
Oh, sorry , I totally misunderstood. Reopened.

**Comment by MR-Lzh** [comment]
Me too.The same behaviour appears while opening the browser.And some app can't fully working.

**Comment by soulpower11** [comment]
#452 it have already been fixed.
