### ISSUE TITLE
[11.0] Tethering and portable hotspot

### ISSUE THREAD

**Issue by taro-k** [LegacyXperia/local_manifests#474]
Tethering function at Xperia neo results as follows:
cm-11.0-20140203: "Unfortunately" stops when selected in the menu.
cm-11.0-20140121: Both wifi and usb tethering works fine, great!

If anything I can check for debugging, please let me know. thx!

**Comment by mikeNG** [comment]
provide logs

**Comment by taro-k** [comment]
I pressed the menu "Tethering & portable hotspot",
then it "unfortunately" stopped and the following is the log (adb logcat) of that time:

D/WirelessSettings( 2045): onPreferenceTreeClick: preference=Tethering & portable hotspot
I/ActivityManager( 2045): Timeline: Activity_launch_request id:com.android.settings time:1135135
I/ActivityManager(  618): START u0 {act=android.intent.action.MAIN cmp=com.android.settings/.SubSettings (has extras)} from pid 2045
D/SubSettings( 2045): Launching fragment com.android.settings.TetherSettings
D/BluetoothManagerService(  618): Message: 30
W/ContextImpl( 2045): Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1582 android.content.ContextWrapper.bindService:517 android.bluetooth.BluetoothPan.doBind:148 android.bluetooth.BluetoothPan.<init>:141 android.bluetooth.BluetoothAdapter.getProfileProxy:1201
I/WebViewFactory( 2045): Provider overridden by property: persist.webview.provider=classic
I/dalvikvm( 2045): Rejecting re-init on previously-failed class Landroid/webkit/JniUtil; v=0x0
E/webview ( 2045): failed to load JNI libraries
E/WebViewFactory( 2045): error instantiating provider
E/WebViewFactory( 2045): android.util.AndroidRuntimeException: java.lang.ClassNotFoundException: android.webkit.JniUtil
E/WebViewFactory( 2045):        at android.webkit.WebViewClassic$Factory.<init>(WebViewClassic.java:1309)
E/WebViewFactory( 2045):        at java.lang.Class.newInstanceImpl(Native Method)
E/WebViewFactory( 2045):        at java.lang.Class.newInstance(Class.java:1208)
E/WebViewFactory( 2045):        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:109)
E/WebViewFactory( 2045):        at android.webkit.WebView.getFactory(WebView.java:2054)
E/WebViewFactory( 2045):        at android.webkit.WebView.ensureProviderCreated(WebView.java:2049)
E/WebViewFactory( 2045):        at android.webkit.WebView.setOverScrollMode(WebView.java:2107)
E/WebViewFactory( 2045):        at android.view.View.<init>(View.java:3456)
E/WebViewFactory( 2045):        at android.view.View.<init>(View.java:3512)
E/WebViewFactory( 2045):        at android.view.ViewGroup.<init>(ViewGroup.java:470)
E/WebViewFactory( 2045):        at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:52)
E/WebViewFactory( 2045):        at android.webkit.WebView.<init>(WebView.java:498)
E/WebViewFactory( 2045):        at android.webkit.WebView.<init>(WebView.java:475)
/WebViewFactory( 2045):        at android.webkit.WebView.<init>(WebView.java:455)
E/WebViewFactory( 2045):        at android.webkit.WebView.<init>(WebView.java:444)
E/WebViewFactory( 2045):        at android.webkit.WebView.<init>(WebView.java:434)
E/WebViewFactory( 2045):        at com.android.settings.TetherSettings.onCreate(TetherSettings.java:168)
E/WebViewFactory( 2045):        at android.app.Fragment.performCreate(Fragment.java:1678)
E/WebViewFactory( 2045):        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:859)
E/WebViewFactory( 2045):        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
E/WebViewFactory( 2045):        at android.app.BackStackRecord.run(BackStackRecord.java:684)
E/WebViewFactory( 2045):        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
E/WebViewFactory( 2045):        at android.app.Activity.performStart(Activity.java:5240)
E/WebViewFactory( 2045):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2178)
E/WebViewFactory( 2045):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2265)
E/WebViewFactory( 2045):        at android.app.ActivityThread.access$800(ActivityThread.java:145)
E/WebViewFactory( 2045):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206)
E/WebViewFactory( 2045):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/WebViewFactory( 2045):        at android.os.Looper.loop(Looper.java:136)
E/WebViewFactory( 2045):        at android.app.ActivityThread.main(ActivityThread.java:5081)
E/WebViewFactory( 2045):        at java.lang.reflect.Method.invokeNative(Native Method)
E/WebViewFactory( 2045):        at java.lang.reflect.Method.invoke(Method.java:515)
E/WebViewFactory( 2045):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
E/WebViewFactory( 2045):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/WebViewFactory( 2045):        at dalvik.system.NativeStart.main(Native Method)
E/WebViewFactory( 2045): Caused by: java.lang.ClassNotFoundException: android.webkit.JniUtil
E/WebViewFactory( 2045):        at java.lang.Class.classForName(Native Method)
E/WebViewFactory( 2045):        at java.lang.Class.forName(Class.java:251)
E/WebViewFactory( 2045):        at java.lang.Class.forName(Class.java:216)
E/WebViewFactory( 2045):        at android.webkit.WebViewClassic$Factory.<init>(WebViewClassic.java:1305)
E/WebViewFactory( 2045):        ... 34 more
E/WebViewFactory( 2045): Caused by: java.lang.NoClassDefFoundError: android/webkit/JniUtil
E/WebViewFactory( 2045):        ... 38 more
E/WebViewFactory( 2045): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.JniUtil" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/WebViewFactory( 2045):        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/WebViewFactory( 2045):        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/WebViewFactory( 2045):        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/WebViewFactory( 2045):        ... 38 more
D/AndroidRuntime( 2045): Shutting down VM
W/dalvikvm( 2045): threadid=1: thread exiting with uncaught exception (group=0x41c19c80)
E/AndroidRuntime( 2045): FATAL EXCEPTION: main
E/AndroidRuntime( 2045): Process: com.android.settings, PID: 2045
E/AndroidRuntime( 2045): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.SubSettings}: android.util.AndroidRuntimeException: android.util.AndroidRuntimeException: java.lang.ClassNotFoundException: android.webkit.JniUtil
E/AndroidRuntime( 2045):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2215)
E/AndroidRuntime( 2045):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2265)
E/AndroidRuntime( 2045):        at android.app.ActivityThread.access$800(ActivityThread.java:145)
E/AndroidRuntime( 2045):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206)
E/AndroidRuntime( 2045):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 2045):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 2045):        at android.app.ActivityThread.main(ActivityThread.java:5081)
E/AndroidRuntime( 2045):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2045):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 2045):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
E/AndroidRuntime( 2045):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/AndroidRuntime( 2045):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 2045): Caused by: android.util.AndroidRuntimeException: android.util.AndroidRuntimeException: java.lang.ClassNotFoundException: android.webkit.JniUtil
E/AndroidRuntime( 2045):        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:114)
E/AndroidRuntime( 2045):        at android.webkit.WebView.getFactory(WebView.java:2054)
E/AndroidRuntime( 2045):        at android.webkit.WebView.ensureProviderCreated(WebView.java:2049)
E/AndroidRuntime( 2045):        at android.webkit.WebView.setOverScrollMode(WebView.java:2107)
E/AndroidRuntime( 2045):        at android.view.View.<init>(View.java:3456)
E/AndroidRuntime( 2045):        at android.view.View.<init>(View.java:3512)
E/AndroidRuntime( 2045):        at android.view.ViewGroup.<init>(ViewGroup.java:470)
E/AndroidRuntime( 2045):        at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:52)
E/AndroidRuntime( 2045):        at android.webkit.WebView.<init>(WebView.java:498)
E/AndroidRuntime( 2045):        at android.webkit.WebView.<init>(WebView.java:475)
E/AndroidRuntime( 2045):        at android.webkit.WebView.<init>(WebView.java:455)
E/AndroidRuntime( 2045):        at android.webkit.WebView.<init>(WebView.java:444)
E/AndroidRuntime( 2045):        at android.webkit.WebView.<init>(WebView.java:434)
E/AndroidRuntime( 2045):        at com.android.settings.TetherSettings.onCreate(TetherSettings.java:168)
E/AndroidRuntime( 2045):        at android.app.Fragment.performCreate(Fragment.java:1678)
E/AndroidRuntime( 2045):        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:859)
E/AndroidRuntime( 2045):        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
E/AndroidRuntime( 2045):        at android.app.BackStackRecord.run(BackStackRecord.java:684)
E/AndroidRuntime( 2045):        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
E/AndroidRuntime( 2045):        at android.app.Activity.performStart(Activity.java:5240)
E/AndroidRuntime( 2045):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2178)
E/AndroidRuntime( 2045):        ... 11 more
E/AndroidRuntime( 2045): Caused by: android.util.AndroidRuntimeException: java.lang.ClassNotFoundException: android.webkit.JniUtil
E/AndroidRuntime( 2045):        at android.webkit.WebViewClassic$Factory.<init>(WebViewClassic.java:1309)
E/AndroidRuntime( 2045):        at java.lang.Class.newInstanceImpl(Native Method)
E/AndroidRuntime( 2045):        at java.lang.Class.newInstance(Class.java:1208)
E/AndroidRuntime( 2045):        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:109)
E/AndroidRuntime( 2045):        ... 31 more
E/AndroidRuntime( 2045): Caused by: java.lang.ClassNotFoundException: android.webkit.JniUtil
E/AndroidRuntime( 2045):        at java.lang.Class.classForName(Native Method)
E/AndroidRuntime( 2045):        at java.lang.Class.forName(Class.java:251)
E/AndroidRuntime( 2045):        at java.lang.Class.forName(Class.java:216)
E/AndroidRuntime( 2045):        at android.webkit.WebViewClassic$Factory.<init>(WebViewClassic.java:1305)
E/AndroidRuntime( 2045):        ... 34 more
E/AndroidRuntime( 2045): Caused by: java.lang.NoClassDefFoundError: android/webkit/JniUtil
E/AndroidRuntime( 2045):        ... 38 more
E/AndroidRuntime( 2045): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.JniUtil" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/AndroidRuntime( 2045):        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime( 2045):        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/AndroidRuntime( 2045):        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/AndroidRuntime( 2045):        ... 38 more
W/ActivityManager(  618):   Force finishing activity com.android.settings/.SubSettings
W/ActivityManager(  618):   Force finishing activity com.android.settings/.SubSettings
W/ActivityManager(  618): Activity pause timeout for ActivityRecord{424fa3c0 u0 com.android.settings/.SubSettings t2 f}

**Comment by mikeNG** [comment]
Flash the fix from #452

**Comment by taro-k** [comment]
Wow, it is fixed as well, great thx!
