### ISSUE TITLE
[cm-11.0-20140203-NIGHTLY-LegacyXperia-anzu.zip] cannot change I/O scheduler

### ISSUE THREAD

**Issue by bloedvonwest** [LegacyXperia/local_manifests#475]
The I/O scheduler is stuck at BFQ. When I open the settings under "performance" to change it and tap on sio (or any other) the menu closes, without changing the scheduler. I used kickasskernelizer script by zeppelinrox, which also failed to change it to sio for mmcblk0 (although it was successful for mtdblock0-3).
LX center logs at :
http://s000.tinyupload.com/index.php?file_id=09778489501131831369

**Comment by mikeNG** [comment]
Everything in performance settings works fine here with no "magic" scripts installed. By looking at the logs, I'm pretty sure it's the script that causes this.

**Comment by bloedvonwest** [comment]
this was the case before the "magic script", I used it because the settings didn't work. in any case I'll do a clean install and try again.

**Comment by bloedvonwest** [comment]
Also, thanks for the work. And pls consider getting a bitcoin address :)
