### ISSUE TITLE
Browser closes (own build, cm11)

### ISSUE THREAD

**Issue by zweif** [LegacyXperia/local_manifests#479]
I compiled this rom yesterday. Everything seems to be ok except browser that closes immediately after I try to start it.

```
E/AndroidRuntime( 1842): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.browser/com.android.browser.BrowserActivity}: 
java.lang.IllegalArgumentException: WebViewClassic does not support TEXT_AUTOSIZING layout mode
```

Complete log is here:
https://www.dropbox.com/s/7jxa6m9eeg22ftv/logcat-11-20140212-UNOFFICIAL-LegacyXperia-mango.txt

I don't think that other logs are needed.

**Comment by mikeNG** [comment]
Yes, I forgot to fix that. Try building again, I've pushed the fixes

**Comment by zweif** [comment]
I installed chrome as workaround and don't really want to build again. But if it's important to you I could do it.

**Comment by mikeNG** [comment]
You can only build the browser apk to test it (command: make Browser)
Or I'll try it myself when I find some time

**Comment by nedimlisica** [comment]
Browser is working in a build from a few hours ago.

**Comment by mikeNG** [comment]
Great :)
