### ISSUE TITLE
[CM.11] Suddenly SD-Card broken [ExFat2,App2SD]

### ISSUE THREAD

**Issue by N2Blue** [LegacyXperia/local_manifests#480]
Hello.

It happend already two times, i have 2 Partitions on my SD. The normaly Fat32 and the second primary ext2 for App2SD. But 2 times, when i did nothing with the phone, suddenly my phone could not recognize my SD Card anymore.
On the Computer Windows wanted to format it, because the File-System was broken and i could not get any files back.

I read in the Chancelog, you did lots of improvments in App2SD and ext since my version of 20131211-Nightly-iyokan.
My Question is, will this improvments fix this problem, or were this improvements for other problems?
Or maybe is this an clearly issue of the SD-Card? SD-Card was class 6.

regards

**Comment by ghost** [comment]
Without logs nobody will fix your problem.

**Comment by N2Blue** [comment]
I know, but i cant reproduce it, i said it happend suddenly. First time in a cinema and yesterday at a friends house.

Maybe the problem was known and they fixed it with the update of ext2 drivers etc.

**Comment by ghost** [comment]
Try using ext 2 instead of exFAT like everyone else.

**Comment by N2Blue** [comment]
I meant ext2, my mistake. exFAT2 even dont ecists!

**Comment by akledirs** [comment]
I too have problem with my SDCard and too have 2 partitions. SDCard has broken.

**Comment by ghost** [comment]
Fyi, tested link2SD for about 1 week now, including a ROM update inbetween. No problems so far. sd ext is formated in ext2 format. Tested build 20140203 and 20140319.
