### ISSUE TITLE
Google account manager FC

### ISSUE THREAD

**Issue by sai0909** [LegacyXperia/local_manifests#482]
cannot login with google in cm-11.0-20140203-NIGHTLY-LegacyXperia-coconut kernel version present in zip is 3.4.77 but the nightly update is 3.4.79

**Comment by xange** [comment]
did you flash the webview fix posted by mike in XDA Q&A? search it in there, and 20140203 build is using .77 kernel, .79 will release along with next build. check the build number if you are curious. close plz if fixed your problem

**Comment by sai0909** [comment]
where do i find webview fix ...post link here plz

**Comment by mikeNG** [comment]
It has been posted multiple times! search a bit before opening issues!!
