### ISSUE TITLE
[cm11][mango]20140203-NIGHTLY BUGS

### ISSUE THREAD

**Issue by flavio23** [LegacyXperia/local_manifests#483]
En la anterior version cm-11.0-20140121-NIGHTLY estubo todo bien, ahora tu subes una actualizacion que se supone que deberia ser mejor.Pero esta llena de errores. Que tipo de trabajo haces ? Si vas a hacer algo hazlo bien.
- La aplicacion de sms se cierra cuando quiero escribir algo .
- No se puede acceder a la cuenta google porque se cierra.
- El navegador no responde

No subas actualizaciones que se suponen que deberian ser mejoras cuando en realidad es peor que la anterior

**Comment by mikeNG** [comment]
Only English
