### ISSUE TITLE
Having Isssues With Battery Recharging 

### ISSUE THREAD

**Issue by littlerabbit506** [LegacyXperia/local_manifests#484]
I encountered problems while charging my LWW(coconut) when I connect to power supply via USB. However, from where I deduced the problem is that I an charge when I connect my phone to my pc. Why's that happening? Do anyone have the same problem ?

**Comment by littlerabbit506** [comment]
My phone is with CM11 kenel

**Comment by ghost** [comment]
Yed, i am also having the same issue

**Comment by tjcomserv** [comment]
Hi there, I presume you've tried different cables / chargers?

**Comment by ghost** [comment]
Yes..  I have tried with diff chargers. Only USB its working.

**Comment by littlerabbit506** [comment]
Me also. Is there any work arounds to solve the problem ?

**Comment by tjcomserv** [comment]
This is one of those issues that should have nothing to do with the software on the phone (although I could be wrong). Can you try a different phone. With the cable/charger that doesn't work with your phone.
