### ISSUE TITLE
Keyboard dictionary problem

### ISSUE THREAD

**Issue by TomiOhl** [LegacyXperia/local_manifests#487]
Hello, my problem is that when I try to import english dictionary file, its not doing anything. When I try to import hungarian dictionary file, the keyboard app crashes. Pls help.
Logs. http://www24.zippyshare.com/v/93614545/file.html

P.S.: I´ve tried Google keyboard, but there isn´t hungarian language.

**Comment by tjcomserv** [comment]
Hi there, the linked file seems to be empty...

**Comment by TomiOhl** [comment]
You mean the dictionary file? Then I'll try to redownload it. I couldn't download it on my phone since the browser brings just a page with codes, and firefox downloaded just empty files. Hope I'll have luck. Will report back if the download was successful and close the issue.

**Comment by zweif** [comment]
He means your logs file, but it is not empty. It can be opened with 7zip. There is a folder without name inside. I had this too one time I tried to take the logs with LX-center. Maybe there is an issue in LX-center (should I open a new issue for this?).

**Comment by TomiOhl** [comment]
What? I downloaded it too just to check it and for me there are the logs. So you don't have this problem? How could I manually add the dictionaries?

**Comment by mikeNG** [comment]
So this is still an issue?

**Comment by TomiOhl** [comment]
Actually, now it crashes when I press the import dictionary file option. At the logs it speaks about Xposed, too. I'll try it without Xposed and give you logs next week, cuz now I'm on holidays.

**Comment by TomiOhl** [comment]
Hello, installed latest build 09-07 on mango, first thing I checked was this. FC when tapping on import dictionary file option. Collected logs via LX center, will provide them at evening.

**Comment by TomiOhl** [comment]
Hi, here are the logs: http://www25.zippyshare.com/v/53119009/file.html

Additional info: I tried it with English and Hungarian set as system language, FC in both cases.

**Comment by mikeNG** [comment]
The dictionary in CM is corrupted, I'll see if we can regenerate it
