### ISSUE TITLE
Battery State Showing always 100% after flushing LegacyXperia CM11 (first Nightly) and get back to Stock ICS in MK16i

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#489]
Dear,

I am having Xperia Pro MK16i

I am having problem in battery percentage output shown by android system, after flushing custom kernal which is supplied with legacyXPERIA CM11 rom (no issue at this time) and than I return back to stock ICS kernal, the battery is showing always 100%. Even if I connect charger it shows me charged.

Before flushing legacyXPERIA CM11 kernal, I have tired so many different custom kernal but, I like CM10, 10.1, nAa 3.4.0 kernal and return back to stock ICS, I was not having this issue any time.

For recovery of this issue I have tried to flush again the legacyXPERIA CM11 kernal (it will show the correct battery percentage) and get back to stock ICS will agnain show battery 100%. Than I tried to flush jush my backuped stock GB rom (it will show the correct battery percentage) and get back to stock ICS will show correct battery percentage.

Also the important thing it that, I found that this problem is happening every time i remove the battery.

If any one can help me, please give your suggestions what to do.

**Comment by ksranjith786** [comment]
Even I face the same issue when I flushed SONY Ericsson Xperia Arc S Stock ROM.

**Comment by mikeNG** [comment]
This is not a problem of LX. It's not my fault if you crossflash between android versions all the time.

**Comment by ghost** [comment]
Dear,

I am not blaming you. I just want the solution to the problem.

If I use stock GB this problem is not happing (i.e. If I remove batter and
that start the mobile it shows the correct battery percentage), In case of
stock ICS this problem happens (i.e. If I remove batter and that start the
mobile it shows 100% battery percentage all time)

On Mon, Feb 17, 2014 at 4:57 PM, Michael Bestas notifications@github.comwrote:

> This is not a problem of LX. It's not my fault if you crossflash between
> android versions all the time.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/LegacyXperia/local_manifests/issues/489#issuecomment-35248722
> .

## 

Thanks & Regards,

Chirag Vaghela

**Comment by TomiOhl** [comment]
Then it's a problem with stock ics. It has nothing to do with LX or anything. Tell this to Sony they could fix this bug.

**Comment by ghost** [comment]
dear,

Sony will not help in fixing this, if any one know please help

On Mon, Feb 17, 2014 at 8:07 PM, TomiOhl notifications@github.com wrote:

> Then it's a problem with stock ics. It has nothing to do with LX or
> anything. Tell this to Sony they could fix this bug.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/LegacyXperia/local_manifests/issues/489#issuecomment-35286807
> .

## 

Thanks & Regards,

Chirag Vaghela

**Comment by orzel** [comment]
have the same probleme here. Installed LX, battery was displaying fine, went back to stock ICS and now it always display 100%.

Still no hint on how to fix it ?

**Comment by ksranjith786** [comment]
Please let your phone discharges completely and shut it down. Later, you charge it. It works..

The same happened with my Xperia Arc S phone, later I found its working when I let my phone discharge completely.

**Comment by orzel** [comment]
Doesn't work at all here :-(
Now the phone wont even boot. It starts booting and displays the xperia logo, waits for few seconds, and shuts down, with the sound usually being played when the battery is too low.
