### ISSUE TITLE
Google Manager and built-in Browser stops

### ISSUE THREAD

**Issue by alekei** [LegacyXperia/local_manifests#490]
Cannot add a google account because whenever i try after i add the email and password and i press next the "Google Account Manager" stops.Also the built-in Browser stops whenever i try to launch it.Please help.

**Comment by xange** [comment]
Plz check XDA forum Q&A section before post your bugs here, mike (in fact, everyone) is really fed up of this kind of question, there is a webview fix posted by mike in page 217 of XDA Q&A.
seriously, is it hard to search abit about the bug before post any repeating questions. and close this issue plz.

**Comment by alekei** [comment]
Sorry for being a noobie but I still can't find it http://forum.xda-developers.com/general/help/page217 believe me I wouldn't bother anyone if I would be able to find the solution by myself.call me stupid if you like but on page 217 i still don't find what i look for.however thank you for your time.

**Comment by xange** [comment]
you are on wrong thread, it is in http://forum.xda-developers.com/showthread.php?t=2543426

**Comment by alekei** [comment]
Thank you very much for your help and time.
