### ISSUE TITLE
GAPPS account manger FC after building CM based roms

### ISSUE THREAD

**Issue by 3andala** [LegacyXperia/local_manifests#493]
After building several roms got GAPPS account manger FC
any fix or change repo sync as i use LX webview /webkit was works perfect before 

check logcat form Vanir http://pastebin.com/7rEdSPuY

tried Flashable zip not fixed too 

Thanks in advance
Any help appreciated 
Cheers

**Comment by tjcomserv** [comment]
Hi there, I was having the same issue when flashing the latest nightly for the urushi (ray). However, I built from source and used banks core gapps (http://goo.im/devs/BaNkS/GApps/4.4.2/2-11_GApps_Core_4.4.2_signed.zip) and it worked perfectly. Maybe worth having another go at building.
