### ISSUE TITLE
coconut - phone app crash notification

### ISSUE THREAD

**Issue by gxyf106** [LegacyXperia/local_manifests#496]
On updating to Release edition of cm 10.2, a persistent notification appears,"Unfortunately, the process com.android.phone has stopped" it is a persistent notification, after you dismiss it it comes up again in no time,  so the screen is unusable even for opening an app!! Wiped data, wiped cache, dailvik also. formatted the partitions for sys, cache, etc.
i cant even complete the cm setup after reset.
couldn't get logs, as couldn't open terminal window or run usb debugging!!!
Cant even get a signal to the phone after the issue!!

**Comment by domints** [comment]
Got it too, when used my mango not as primary, and removed phone app, everything is working fine.

**Comment by mikeNG** [comment]
cm-10.2 is EOL now, I'm closing this issue
