### ISSUE TITLE
cm 10 to 11 not working at all

### ISSUE THREAD

**Issue by basil911** [LegacyXperia/local_manifests#497]
frm cm 10 everything crashes even b4 the lock screen....it says android.phone crashed......and on cm 11 it gets stuck on load screen

**Comment by xange** [comment]
_which build you using, which phone's rom you using_ (please provide on every issue you report), did you make a clean install from CM10 to CM11, provide logcat if possible, no one will fix anything if no logs provided. did you follow the WHOLE procedure on installing the correct rom? installing the wrong one will cause these FCs too.

**Comment by gxyf106** [comment]
i too had the same on the last nightly and release builds in cm 10.2, didnt have in 11...... made a clean install... my issue opened... https://github.com/LegacyXperia/local_manifests/issues/496

**Comment by basil911** [comment]
Iam using sk17i xperiamini pro yes I did a clean install...and yes I made it sure that I did install the correct ROM for the phone.....@ the present I am running on cm 10 which is from the freexperia project....PS I am a newbie to this

**Comment by mikeNG** [comment]
No logs
