### ISSUE TITLE
Haida - The phone turns off when I use web browser on 3g.

### ISSUE THREAD

**Issue by sasuuniee** [LegacyXperia/local_manifests#498]
Sometimes when I use web browser on 3g, my phone stops working and after few seconds it turns off. It has never happened on wifi. It's really annoying, because sometimes it works without any problems and sometimes gets reset (like once a day). I took logs right after the last reset.

Logcat: http://pastebin.com/xGK4J39C
dmesg: http://pastebin.com/SkG32rd9
last_kmsg: http://pastebin.com/Cd3SytPw
modem: http://pastebin.com/85SMUht2

**Comment by mikeNG** [comment]
Provide logs if this still happens in latest build which will be released tomorrow
