### ISSUE TITLE
No sound notification for sms

### ISSUE THREAD

**Issue by zxcvbnnm** [LegacyXperia/local_manifests#5]

**Comment by amishmm** [comment]
No notification for e-mail as well. Possibly anything that uses default notification does not work.

Whatsapp sound works though.

**Comment by mikeNG** [comment]
will probably be fixed in alpha2

**Comment by zxcvbnnm** [comment]
yeah it work great after changes in your sources

**Comment by mikeNG** [comment]
Fixed in alpha 2
