### ISSUE TITLE
Not able to add music files to specific contacts

### ISSUE THREAD

**Issue by skarthiksankaran** [LegacyXperia/local_manifests#50]
Hi --

I am trying to add a specific ringtone to a contact, I am using Jellybean 4.3 on my xperia neo v. running CM-10.2, I dont see an option to add custom ringtone to the contacts. When select add ringtones it only shows the default.

**Comment by djey47** [comment]
Hello.

I think it's not an issue, it's as is, by design.

There's a solution for this, just make a _media/audio/ringtones_ directory onto your sdcard then drop desired mp3 files into it, to make them appear in ringtone selector (reboot might be necessary)

**Comment by ghost** [comment]
Like djey47 said and you can do same for custom notifications ("notifications" folder).

**Comment by pcfighter** [comment]
install file manager like totalcmd, then in sound settings click to change ringtone and for continuing action select totalcmd and pick your ringtone on sdcard

**Comment by mikeNG** [comment]
This isn't a bug, android was always like that

**Comment by skarthiksankaran** [comment]
ThankYou, Using the Total Commander worked gr8 for me. But I feel it is something that needs to be taken in as an improvement to android.
