### ISSUE TITLE
google account manager stop working

### ISSUE THREAD

**Issue by sionharki** [LegacyXperia/local_manifests#500]
i just instal cm 11 by LegacyXperia  nightly 20131211 and also flash recomended gapps but when i finish boot for first time and sign in google account, and i press next it stoped working

any solution ?
thanks

**Comment by gxyf106** [comment]
http://forum.xda-developers.com/showpost.php?p=50122471&postcount=2161
download the file and flash it in recovery........ it should work...... issue already opened multiple times ...... please do a search before posting new issues.......

**Comment by sionharki** [comment]
thanks ! its work !
