### ISSUE TITLE
cm11 20140203 remain 3.4.77?

### ISSUE THREAD

**Issue by Zackzw** [LegacyXperia/local_manifests#501]
My current rom is cm11 20140120 , then I flashed to cm11 20140203 and the boot.img that comes with the 20140203 cm 11 zip, but when the device boot into systems, its kernel is still 3.4.77. And apps like whatsapp, messaging, line, browser and FC and cant be open. Whatsapp and messaging will crash when trying to open the message.
What should i do? do the step 1.1, 2, 3?

**Comment by mikeNG** [comment]
20140203 has 3.4.77, check changelog next time please
