### ISSUE TITLE
[CM 11][coconut] ART not working

### ISSUE THREAD

**Issue by gxyf106** [LegacyXperia/local_manifests#506]
I run cm 11  build 20140203 on my coconut. Recently I tried activating ART, without any success. I activated ART, phone rebooted, it bootlooped. stuck at the cm loading screen..... Had to format all partitions and then re flash zip to get dalvik working again......
Now, I know ART is not fully supported but still I'm eager to try it out. No logs. Can someone help me out??? Is Art running on your phones???

**Comment by mikeNG** [comment]
ART is not supported...

**Comment by gxyf106** [comment]
Is this a device specific issue or cm issue??? Is art working for anyone else??

**Comment by mikeNG** [comment]
I don't know, but since ART is not supported I won't look at it. ART is under "developer options" for a reason. There are more important things to fix first than ART. You can search in xda q&a thread for more info from other people, but I don't accept any bugreports regarding ART.
