### ISSUE TITLE
Calendar events get erased when connected to the internet

### ISSUE THREAD

**Issue by skarthiksankaran** [LegacyXperia/local_manifests#51]
Hi --

I have configured few calendar events on my xperia neo v running JB4.3 ( CM-10.2), Whenever I connect to the internet the calendar events get erased. I have to restore the events from the backup everytime whenever I connect to the internet.

Please let me know how to solve this issue.

**Comment by Gary733** [comment]
I think it has anything to do with the synchronisation with your google account.
have you switched on the calendar sync? Try to switch it off/on

**Comment by mikeNG** [comment]
Calendar works fine here, maybe something about calendar sync is wrong in your settings

**Comment by mikeNG** [comment]
Any news on this?

**Comment by skarthiksankaran** [comment]
I changed the firmware on my device from JB 4.3 to JB 4.2.2 and it seems to
be working fine without any issues. I had to go to 4.2.2 as it was the
stable release build, also 4.3 had a lot of battery drain prb.

On Tue, Oct 15, 2013 at 4:03 AM, Michael Bestas notifications@github.comwrote:

> Any news on this?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LegacyXperia/local_manifests/issues/51#issuecomment-26294585
> .

## 

Thanks & Regards

Karthik.S

**Comment by mikeNG** [comment]
Ok so I'm closing this for now.
