### ISSUE TITLE
[10.2] wifi doesn't work on iyokan

### ISSUE THREAD

**Issue by peti** [LegacyXperia/local_manifests#512]
The cm-10.2-20140304-RELEASE update broke wifi support on my Xperia Pro. I deleted 
`/data/misc/wifi/wl1271-nvs.bin`, ran `wifi-cal.sh` as super user, and rebooted, but that didn't help: I cannot switch wifi on. The "Settings -> Wifi -> Advanced" page didn't even show the wifi card's MAC address.

I also tried the latest CM11 nightly snapshot, but that version woludn't even boot. 

Anyway, the `dmesg` output from 10.2 is available at http://pastebin.com/d7evbjR4. If there is any other information that I can provide, please let me know!

Thanks a lot to you guys for running this awesome project, by the way!

**Comment by peti** [comment]
Duh, I managed to solve the problem by installing the stock ROM, enabling wifi there, and then re-installing CM10.2. Now it works. It's a bit scary, though.

**Comment by mikeNG** [comment]
By looking at the logs, it seems you hadn't flashed the new kernel, so wifi modules weren't able to load.

**Comment by peti** [comment]
Yes, I accidentally ran `fastboot boot boot.img`, i.e. I forgot the _flash_ parameter. And because of copy&pasting, I made that same mistake every time I tried to install a different version! Duh. Sorry for the noise.
