### ISSUE TITLE
Anzu -problem with roaming

### ISSUE THREAD

**Issue by massi-paci** [LegacyXperia/local_manifests#513]
I flashed the version of 20140122 of CM 11 on my Xperia Arc S. Everything appears perfect but I have a problem when I go out from Italy (Switzerland): though the roaming is disabled, automatically goes on internet and it consequently decreases phone credit. I established that it isn't a problem of the telephone operator, so it could be a problem of the phone. Without CM i didn't have any problem.

**Comment by mikeNG** [comment]
Still an issue?
