### ISSUE TITLE
hallon cm 10.2 download broken

### ISSUE THREAD

**Issue by hannob** [LegacyXperia/local_manifests#514]
The download for the latest (20140304) version of cm 10.2 for hallon seems to be broken:
http://legacyxperia.basketbuild.com/index.php?dir=main/hallon/cm-10.2/release/

It doesn't unpack and it's significantly smaller than the previous version (153 vs. 112 MB). So this looks like it was an incomplete upload.

**Comment by mikeNG** [comment]
Sorry for the late response, I'll reupload the build when I find some time.

**Comment by mikeNG** [comment]
should be fixed now :)
