### ISSUE TITLE
sd card mount problem

### ISSUE THREAD

**Issue by burhan07** [LegacyXperia/local_manifests#517]
recovery mode select mount sdcard menu not working.

**Comment by ghost** [comment]
What OS are you running?
Can you mount MASS STORAGE under Windows?

**Comment by burhan07** [comment]
It is windows seven.

Burhan KARADERE
İş Geliştirme Yöneticisi
www.webilizyon.com

2014-03-07 12:34 GMT+02:00 skaveelicious notifications@github.com:

> What OS are you running?
> Can you mount MASS STORAGE under Windows?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LegacyXperia/local_manifests/issues/517#issuecomment-37012803
> .

##

**Comment by ghost** [comment]
Try this:
Go into CWM and on your PC go into the device manager.
- Locate the Android ADB  Interface driver, rightclick "update driver" and then  "browser my Computer for driver software" after that "let me pick from a list ... " and chose "Composite device"
- This will install a sony sa0102 device driver
- rightclick the newly installed sony sa0102 and do the same as above and update the driver, pick from list and select "mass storage device"

now try mounting, I don't remember if I had to mount the sd-card before changing the sa0102 driver, but if something does not show up just mount/remount.

Just to point out, I know there were problems with USB aswell when mounting mass storage while usb debugging was on when doing it from the android interface. If you need mass storage while under android just disable usb debugging or if you need usb debugging untick mass storage.
