### ISSUE TITLE
CM11.0 - 20140203: SMS/MMS App crashes (External app handcent as well)

### ISSUE THREAD

**Issue by fountaink** [LegacyXperia/local_manifests#522]
On CM11.0 crashed the SMS app If I open it. Mostly if a new message is inside. So, with a new message inside I can't open the app. This happens at "CM11.0 - 20140203" and not at "CM11.0 - 20140113".

It happens with the SMS/MMS-App and with the external app "Handcent" as well.

Phone: Urushi

Here the log-files:
dmesg.log: http://pastebin.com/7ityxDQ2
last_kmsg.log: http://pastebin.com/5NPfPz5v
logcat.log: http://pastebin.com/9HDUdcrJ

Thanks a lot!!

**Comment by happyBOY78** [comment]
Do you try to read and search in Q&A thread of LX CM11 ? Many times answered.
Small hint: webview fix.

**Comment by fountaink** [comment]
Thanks. I didn't. Where can I find the 'Q&A thread of LX CM11'?
Oh, I found it:
forum.xda-developers.com/showthread.php?t=2543426&page=123

At the current changelog the webview is marked as fixed. So at the next nightly build the SMS issue is fixed and gone?

**Comment by happyBOY78** [comment]
http://forum.xda-developers.com/showpost.php?p=50122471&postcount=2161
