### ISSUE TITLE
[CM11]{NIGHTLY-20140207}[Anzu] - Video Recording delay

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#523]
On a sidenote: LX Changelog lists this is as 20140203 build, device info says 20140207.

This bug persisted after a clean reinstall of 20140207 build.

Video Recording
- From hitting the "start record button" to the actually start of the recording takes at least 5 seconds, while this doesn't sound like a lot it can feel like an eternity.
- Hitting "stop recording" stops the recording right away
- The record preview still lags a bit, but does not affect the final recording

Logcat link bellow. there is something suspicious related to 720p recording in there.
- Video Record button pressed at line: 400 (Time 19:27:04.416)
- Actual start seems around line: 493 (Time 19:27:10.251)
  Total recording time was about 2seconds, after that I stopped and closed the app.

https://gist.github.com/skaveelicious/80bd68486d984a9316ac

If you need some more logs let me know.

skaa

**Comment by mikeNG** [comment]
This is a known bug after the first alpha builds. I couldn't find what causes it yet.

**Comment by Nikhildangui** [comment]
This bug is also experienced by me on my  Haida , just for information

**Comment by pteek** [comment]
Also present on iyokan.

**Comment by ghost** [comment]
Felt like posting an update to this. 

ION build from 17.04.14 seems to have fixed the delay. Max delay I have seen so far is <2 seconds which is completely normal in my opinion. 

The only thing I have noticed is a fps drop  when recording (record preview). This however does not affect the final recording.

**Comment by mikeNG** [comment]
Yes, this is fixed with the new ION changes.
