### ISSUE TITLE
Kernel panic

### ISSUE THREAD

**Issue by happyBOY78** [LegacyXperia/local_manifests#524]
Last few days, i have unexpectable reboots, in random situations-after hangup call, when writing sms, when phone lying on table... 
I catch logs and hope, that will be usefull.
https://gist.github.com/happyBOY78/9533144

**Comment by zweif** [comment]
I'm far away from being an expert, but there is no Kernel panic logged.
There is an open Issue about Kernel panic caused by wifi drivers:
https://github.com/LegacyXperia/local_manifests/issues/403

Maybe your issue is similar.

**Comment by happyBOY78** [comment]
Logs i catch immediately after reboot and system booting.
Don´t know, if is ot usefull.
And don´t know, if my problem is wifi related, because it happened to me when i have wifi off or on too..

**Comment by zweif** [comment]
I just can guess, and can be wrong with my interpretation.
It says _Restarting system with command ''._ after remounting some ext4 filesystem (?).
Are you using mounts2sd or link2sd with an ext4 partition?
Maybe this info could help someone more experienced.

**Comment by happyBOY78** [comment]
Thank you for help,
Yes, i use mounts2sd with ext4 partition on sd card.

**Comment by ghost** [comment]
fyi, link2sd has worked excelent for me so far. It even managed a kernel+ROM update and relinked everything. I tried mounts2sd and apparently it does not have a feature to just move some apps. And well to be safe I rather have titanium file manager, etc on the internal.

**Comment by mikeNG** [comment]
Logs show nothing useful
