### ISSUE TITLE
FC: unable to view text message and similar app

### ISSUE THREAD

**Issue by Zackzw** [LegacyXperia/local_manifests#526]
When i upgrade from cm 11 20140121 to cm 11 20140203, the system messaging app and other apps like whatsapp, Line, and Browser fail to start and keeps forceclose.

i use alogcat to catch some log:

--------- beginning of /dev/log/main
E/webview ( 2776): failed to load JNI libraries
E/WebViewFactory( 2776): error instantiating provider
E/WebViewFactory( 2776): android.util.AndroidRuntimeException: java.lang.ClassNotFoundException: android.webkit.JniUtil
E/WebViewFactory( 2776):    at android.webkit.WebViewClassic$Factory.<init>(WebViewClassic.java:1309)
E/WebViewFactory( 2776):    at java.lang.Class.newInstanceImpl(Native Method)
E/WebViewFactory( 2776):    at java.lang.Class.newInstance(Class.java:1208)
E/WebViewFactory( 2776):    at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:109)
E/WebViewFactory( 2776):    at android.webkit.WebView.getFactory(WebView.java:2054)
E/WebViewFactory( 2776):    at android.webkit.WebView.findAddress(WebView.java:1531)
E/WebViewFactory( 2776):    at android.text.util.Linkify.gatherMapLinks(Linkify.java:468)
E/WebViewFactory( 2776):    at android.text.util.Linkify.addLinks(Linkify.java:234)
E/WebViewFactory( 2776):    at android.widget.TextView.setText(TextView.java:3749)
E/WebViewFactory( 2776):    at android.widget.TextView.setText(TextView.java:3671)
E/WebViewFactory( 2776):    at android.widget.TextView.<init>(TextView.java:1270)
E/WebViewFactory( 2776):    at android.widget.TextView.<init>(TextView.java:618)
E/WebViewFactory( 2776):    at java.lang.reflect.Constructor.constructNative(Native Method)
E/WebViewFactory( 2776):    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
E/WebViewFactory( 2776):    at android.view.LayoutInflater.createView(LayoutInflater.java:594)
E/WebViewFactory( 2776):    at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
E/WebViewFactory( 2776):    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
E/WebViewFactory( 2776):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
E/WebViewFactory( 2776):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
E/WebViewFactory( 2776):    at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
E/WebViewFactory( 2776):    at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
E/WebViewFactory( 2776):    at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
E/WebViewFactory( 2776):    at org.jtb.alogcat.FilterDialog.<init>(FilterDialog.java:36)
E/WebViewFactory( 2776):    at org.jtb.alogcat.LogActivity.onCreateDialog(LogActivity.java:521)
E/WebViewFactory( 2776):    at android.app.Activity.onCreateDialog(Activity.java:3023)
E/WebViewFactory( 2776):    at android.app.Activity.createDialog(Activity.java:982)
E/WebViewFactory( 2776):    at android.app.Activity.showDialog(Activity.java:3116)
E/WebViewFactory( 2776):    at android.app.Activity.showDialog(Activity.java:3075)
E/WebViewFactory( 2776):    at org.jtb.alogcat.LogActivity.onOptionsItemSelected(LogActivity.java:344)
E/WebViewFactory( 2776):    at android.app.Activity.onMenuItemSelected(Activity.java:2600)
E/WebViewFactory( 2776):    at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1065)
E/WebViewFactory( 2776):    at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:735)
E/WebViewFactory( 2776):    at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
E/WebViewFactory( 2776):    at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
E/WebViewFactory( 2776):    at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:177)
E/WebViewFactory( 2776):    at android.widget.AdapterView.performItemClick(AdapterView.java:298)
E/WebViewFactory( 2776):    at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
E/WebViewFactory( 2776):    at android.widget.AbsListView$PerformClick.run(AbsListView.java:2904)
E/WebViewFactory( 2776):    at android.widget.AbsListView$3.run(AbsListView.java:3638)
E/WebViewFactory( 2776):    at android.os.Handler.handleCallback(Handler.java:733)
E/WebViewFactory( 2776):    at android.os.Handler.dispatchMessage(Handler.java:95)
E/WebViewFactory( 2776):    at android.os.Looper.loop(Looper.java:136)
E/WebViewFactory( 2776):    at android.app.ActivityThread.main(ActivityThread.java:5081)
E/WebViewFactory( 2776):    at java.lang.reflect.Method.invokeNative(Native Method)
E/WebViewFactory( 2776):    at java.lang.reflect.Method.invoke(Method.java:515)
E/WebViewFactory( 2776):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
E/WebViewFactory( 2776):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/WebViewFactory( 2776):    at dalvik.system.NativeStart.main(Native Method)
E/WebViewFactory( 2776): Caused by: java.lang.ClassNotFoundException: android.webkit.JniUtil
E/WebViewFactory( 2776):    at java.lang.Class.classForName(Native Method)
E/WebViewFactory( 2776):    at java.lang.Class.forName(Class.java:251)
E/WebViewFactory( 2776):    at java.lang.Class.forName(Class.java:216)
E/WebViewFactory( 2776):    at android.webkit.WebViewClassic$Factory.<init>(WebViewClassic.java:1305)
E/WebViewFactory( 2776):    ... 47 more
E/WebViewFactory( 2776): Caused by: java.lang.NoClassDefFoundError: android/webkit/JniUtil
E/WebViewFactory( 2776):    ... 51 more
E/WebViewFactory( 2776): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.JniUtil" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/WebViewFactory( 2776):    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/WebViewFactory( 2776):    at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/WebViewFactory( 2776):    at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/WebViewFactory( 2776):    ... 51 more
--------- beginning of /dev/log/system
E/AndroidRuntime( 2776): FATAL EXCEPTION: main
E/AndroidRuntime( 2776): Process: org.jtb.alogcat, PID: 2776
E/AndroidRuntime( 2776): android.view.InflateException: Binary XML file line #5: Error inflating class <unknown>
E/AndroidRuntime( 2776):    at android.view.LayoutInflater.createView(LayoutInflater.java:620)
E/AndroidRuntime( 2776):    at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
E/AndroidRuntime( 2776):    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
E/AndroidRuntime( 2776):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
E/AndroidRuntime( 2776):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
E/AndroidRuntime( 2776):    at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
E/AndroidRuntime( 2776):    at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
E/AndroidRuntime( 2776):    at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
E/AndroidRuntime( 2776):    at org.jtb.alogcat.FilterDialog.<init>(FilterDialog.java:36)
E/AndroidRuntime( 2776):    at org.jtb.alogcat.LogActivity.onCreateDialog(LogActivity.java:521)
E/AndroidRuntime( 2776):    at android.app.Activity.onCreateDialog(Activity.java:3023)
E/AndroidRuntime( 2776):    at android.app.Activity.createDialog(Activity.java:982)
E/AndroidRuntime( 2776):    at android.app.Activity.showDialog(Activity.java:3116)
E/AndroidRuntime( 2776):    at android.app.Activity.showDialog(Activity.java:3075)
E/AndroidRuntime( 2776):    at org.jtb.alogcat.LogActivity.onOptionsItemSelected(LogActivity.java:344)
E/AndroidRuntime( 2776):    at android.app.Activity.onMenuItemSelected(Activity.java:2600)
E/AndroidRuntime( 2776):    at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1065)
E/AndroidRuntime( 2776):    at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:735)
E/AndroidRuntime( 2776):    at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
E/AndroidRuntime( 2776):    at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
E/AndroidRuntime( 2776):    at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:177)
E/AndroidRuntime( 2776):    at android.widget.AdapterView.performItemClick(AdapterView.java:298)
E/AndroidRuntime( 2776):    at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
E/AndroidRuntime( 2776):    at android.widget.AbsListView$PerformClick.run(AbsListView.java:2904)
E/AndroidRuntime( 2776):    at android.widget.AbsListView$3.run(AbsListView.java:3638)
E/AndroidRuntime( 2776):    at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime( 2776):    at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 2776):    at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 2776):    at android.app.ActivityThread.main(ActivityThread.java:5081)
E/AndroidRuntime( 2776):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2776):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 2776):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
E/AndroidRuntime( 2776):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/AndroidRuntime( 2776):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 2776): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 2776):    at java.lang.reflect.Constructor.constructNative(Native Method)
E/AndroidRuntime( 2776):    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
E/AndroidRuntime( 2776):    at android.view.LayoutInflater.createView(LayoutInflater.java:594)
E/AndroidRuntime( 2776):    ... 33 more
E/AndroidRuntime( 2776): Caused by: android.util.AndroidRuntimeException: android.util.AndroidRuntimeException: java.lang.ClassNotFoundException: android.webkit.JniUtil
E/AndroidRuntime( 2776):    at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:114)
E/AndroidRuntime( 2776):    at android.webkit.WebView.getFactory(WebView.java:2054)
E/AndroidRuntime( 2776):    at android.webkit.WebView.findAddress(WebView.java:1531)
E/AndroidRuntime( 2776):    at android.text.util.Linkify.gatherMapLinks(Linkify.java:468)
E/AndroidRuntime( 2776):    at android.text.util.Linkify.addLinks(Linkify.java:234)
E/AndroidRuntime( 2776):    at android.widget.TextView.setText(TextView.java:3749)
E/AndroidRuntime( 2776):    at android.widget.TextView.setText(TextView.java:3671)
E/AndroidRuntime( 2776):    at android.widget.TextView.<init>(TextView.java:1270)
E/AndroidRuntime( 2776):    at android.widget.TextView.<init>(TextView.java:618)
E/AndroidRuntime( 2776):    ... 36 more
E/AndroidRuntime( 2776): Caused by: android.util.AndroidRuntimeException: java.lang.ClassNotFoundException: android.webkit.JniUtil
E/AndroidRuntime( 2776):    at android.webkit.WebViewClassic$Factory.<init>(WebViewClassic.java:1309)
E/AndroidRuntime( 2776):    at java.lang.Class.newInstanceImpl(Native Method)
E/AndroidRuntime( 2776):    at java.lang.Class.newInstance(Class.java:1208)
E/AndroidRuntime( 2776):    at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:109)
E/AndroidRuntime( 2776):    ... 44 more
E/AndroidRuntime( 2776): Caused by: java.lang.ClassNotFoundException: android.webkit.JniUtil
E/AndroidRuntime( 2776):    at java.lang.Class.classForName(Native Method)
E/AndroidRuntime( 2776):    at java.lang.Class.forName(Class.java:251)
E/AndroidRuntime( 2776):    at java.lang.Class.forName(Class.java:216)
E/AndroidRuntime( 2776):    at android.webkit.WebViewClassic$Factory.<init>(WebViewClassic.java:1305)
E/AndroidRuntime( 2776):    ...

**Comment by Zackzw** [comment]
Ermm this was catched when i try to press the filter button in the alogcat app

**Comment by mikeNG** [comment]
#452
