### ISSUE TITLE
port zswap from 3.12 kernel

### ISSUE THREAD

**Issue by nefelim4ag** [LegacyXperia/local_manifests#529]
3.12 kernel has zswap, this is mean, what data compressing before writing to swap. This improve speedof swap and get lowest io.

I using swap on sd, because he speedup system more then zram.

**Comment by xange** [comment]
Sorry for interrupt here, but i suppose this website's main purpose is bug report, why you made your suggestion here? suggestion, question any helps should be post in XDA official Q&A site (tag mike if require or you want his attention), if everyone made a suggestion in this place (bug reporting site), github will be flooded. Close this issues and your previous issue. thanks
