### ISSUE TITLE
RIL crash

### ISSUE THREAD

**Issue by mikeNG** [LegacyXperia/local_manifests#53]
F/libc    ( 1734): Fatal signal 13 (SIGPIPE) at 0x000006c6 (code=0), thread 1737 (rild)
I/DEBUG   (  244): **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* ***
I/DEBUG   (  244): Build fingerprint: 'SEMC/ST15i_1254-2184/ST15i:4.0.4/4.1.B.0.587/tL1_3w:user/release-keys'
I/DEBUG   (  244): Revision: '0'
I/DEBUG   (  244): pid: 1734, tid: 1737, name: rild  >>> /system/bin/rild <<<
I/DEBUG   (  244): signal 13 (SIGPIPE), code -6 (SI_TKILL), fault addr --------
W/NativeCrashListener(  536): Couldn't find ProcessRecord for pid 1734
I/DEBUG   (  244):     r0 ffffffe0  r1 407f2fa4  r2 00000004  r3 0c000000
I/DEBUG   (  244):     r4 0000001a  r5 00000000  r6 00000004  r7 00000004
I/DEBUG   (  244):     r8 00000004  r9 407f2fa4  sl 0000316e  fp 01cb83a0
I/DEBUG   (  244):     ip 407f2fa4  sp 407f2f78  lr 40419ce1  pc 401f92c4  cpsr 80000010
I/DEBUG   (  244):     d0  6f6620746f4e205d  d1  4c71655220646e75
I/DEBUG   (  244):     d2  72746e6520747369  d3  656b6f74203a2079
I/DEBUG   (  244):     d4  0000000000000000  d5  0000000000000000
I/DEBUG   (  244):     d6  0000000000000000  d7  0000000000000000
I/DEBUG   (  244):     d8  0000000000000000  d9  0000000000000000
I/DEBUG   (  244):     d10 0000000000000000  d11 0000000000000000
I/DEBUG   (  244):     d12 0000000000000000  d13 0000000000000000
I/DEBUG   (  244):     d14 0000000000000000  d15 0000000000000000
I/DEBUG   (  244):     d16 656c706d6f432029  d17 52202d2d2d206574
I/DEBUG   (  244):     d18 0000000000000000  d19 0000000000000000
I/DEBUG   (  244):     d20 0000000000000000  d21 0000000000000000
I/DEBUG   (  244):     d22 0000000000000000  d23 0000000000000000
I/DEBUG   (  244):     d24 0000000000000000  d25 0000000000000000
I/DEBUG   (  244):     d26 0000000000000000  d27 0000000000000000
I/DEBUG   (  244):     d28 0000000000000000  d29 0000000000000000
I/DEBUG   (  244):     d30 0000000000000000  d31 0000000000000000
I/DEBUG   (  244):     scr 00000010
I/DEBUG   (  244): 
I/DEBUG   (  244): backtrace:
I/DEBUG   (  244):     #00  pc 0001b2c4  /system/lib/libc.so (write+12)
I/DEBUG   (  244):     #01  pc 00003cdd  /system/lib/libril.so
I/DEBUG   (  244):     #02  pc 00003d73  /system/lib/libril.so
I/DEBUG   (  244):     #03  pc 00004091  /system/lib/libril.so (RIL_onRequestComplete+236)
I/DEBUG   (  244):     #04  pc 0002c5c7  /system/lib/libril-qc-1.so (qcril_send_request_response+774)
I/DEBUG   (  244):     #05  pc 00059af7  /system/lib/libril-qc-1.so (qcril_cm_callsvc_request_get_current_calls+3338)
I/DEBUG   (  244):     #06  pc 0002d881  /system/lib/libril-qc-1.so
I/DEBUG   (  244):     #07  pc 0002e1c3  /system/lib/libril-qc-1.so
I/DEBUG   (  244):     #08  pc 0002e2b3  /system/lib/libril-qc-1.so
I/DEBUG   (  244):     #09  pc 00002029  /system/lib/libril.so
I/DEBUG   (  244):     #10  pc 000057e5  /system/lib/libril.so
I/DEBUG   (  244):     #11  pc 00005e87  /system/lib/libril.so (ril_event_loop()+406)
I/DEBUG   (  244):     #12  pc 00005b9b  /system/lib/libril.so
I/DEBUG   (  244):     #13  pc 0000cc60  /system/lib/libc.so (__thread_entry+72)
I/DEBUG   (  244):     #14  pc 0000cddc  /system/lib/libc.so (pthread_create+208)
I/DEBUG   (  244): 
I/DEBUG   (  244): stack:
I/DEBUG   (  244):          407f2f38  01cb2420  [heap]
I/DEBUG   (  244):          407f2f3c  01cb2418  [heap]
I/DEBUG   (  244):          407f2f40  0000000c  
I/DEBUG   (  244):          407f2f44  01cb2418  [heap]
I/DEBUG   (  244):          407f2f48  01cb2420  [heap]
I/DEBUG   (  244):          407f2f4c  401ef25f  /system/lib/libc.so (dlrealloc+122)
I/DEBUG   (  244):          407f2f50  401ef1e5  /system/lib/libc.so (dlrealloc)
I/DEBUG   (  244):          407f2f54  407f2fc0  [stack:1737]
I/DEBUG   (  244):          407f2f58  0000000c  
I/DEBUG   (  244):          407f2f5c  00000000  
I/DEBUG   (  244):          407f2f60  00000000  
I/DEBUG   (  244):          407f2f64  401ebc69  /system/lib/libc.so (realloc+16)
I/DEBUG   (  244):          407f2f68  00000004  
I/DEBUG   (  244):          407f2f6c  403bf09f  /system/lib/libbinder.so (android::Parcel::continueWrite(unsigned int)+314)
I/DEBUG   (  244):          407f2f70  df0027ad  
I/DEBUG   (  244):          407f2f74  00000000  
I/DEBUG   (  244):     #00  407f2f78  4041e98c  /system/lib/libril.so
I/DEBUG   (  244):          ........  ........
I/DEBUG   (  244):     #01  407f2f78  4041e98c  /system/lib/libril.so
I/DEBUG   (  244):          407f2f7c  0000000c  
I/DEBUG   (  244):          407f2f80  0000001a  
I/DEBUG   (  244):          407f2f84  01cb2420  [heap]
I/DEBUG   (  244):          407f2f88  00000008  
I/DEBUG   (  244):          407f2f8c  00000000  
I/DEBUG   (  244):          407f2f90  0000316e  
I/DEBUG   (  244):          407f2f94  40419d77  /system/lib/libril.so
I/DEBUG   (  244):     #02  407f2f98  01cb2420  [heap]
I/DEBUG   (  244):          407f2f9c  0000000c  
I/DEBUG   (  244):          407f2fa0  00000008  
I/DEBUG   (  244):          407f2fa4  0c000000  
I/DEBUG   (  244):          407f2fa8  01cb83a0  [heap]
I/DEBUG   (  244):          407f2fac  407f2fc0  [stack:1737]
I/DEBUG   (  244):          407f2fb0  01cb2420  [heap]
I/DEBUG   (  244):          407f2fb4  00000000  
I/DEBUG   (  244):          407f2fb8  00000008  
I/DEBUG   (  244):          407f2fbc  4041a095  /system/lib/libril.so (RIL_onRequestComplete+240)
I/DEBUG   (  244): 
I/DEBUG   (  244): memory near r1:
I/DEBUG   (  244):     407f2f84 01cb2420 00000008 00000000 0000316e  
I/DEBUG   (  244):     407f2f94 40419d77 01cb2420 0000000c 00000008  
I/DEBUG   (  244):     407f2fa4 0c000000 01cb83a0 407f2fc0 01cb2420  
I/DEBUG   (  244):     407f2fb4 00000000 00000008 4041a095 00000000  
I/DEBUG   (  244):     407f2fc4 01cb2420 0000000c 0000000c 0000000c  
I/DEBUG   (  244):     407f2fd4 00000000 00000000 00000000 00000000  
I/DEBUG   (  244):     407f2fe4 00010001 00000000 00000009 407f3c90  
I/DEBUG   (  244):     407f2ff4 4059c780 00008980 00000014 00000000  
I/DEBUG   (  244):     407f3004 00000009 407f3c90 404915c9 00000009  
I/DEBUG   (  244):     407f3014 00000000 00000014 4055c92c 00000000  
I/DEBUG   (  244):     407f3024 4055c148 6574656c 407f33f0 4c495220  
I/DEBUG   (  244):     407f3034 4055c92c 4055c934 4055c948 4055c958  
I/DEBUG   (  244):     407f3044 4055c96c 4055c978 4055c984 4055c99c  
I/DEBUG   (  244):     407f3054 4055c9a8 4055c9cc 4055c9ec 4055ca00  
I/DEBUG   (  244):     407f3064 4055ca0c 4055ca28 4055ca3c 4055ca50  
I/DEBUG   (  244):     407f3074 4055ca64 4055ca7c 00000000 3c204955  
I/DEBUG   (  244): 
I/DEBUG   (  244): memory near r3:
I/DEBUG   (  244):     0bffffe0 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     0bfffff0 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     0c000000 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     0c000010 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     0c000020 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     0c000030 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     0c000040 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     0c000050 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     0c000060 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     0c000070 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     0c000080 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     0c000090 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     0c0000a0 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     0c0000b0 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     0c0000c0 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     0c0000d0 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244): 
I/DEBUG   (  244): memory near r9:
I/DEBUG   (  244):     407f2f84 01cb2420 00000008 00000000 0000316e  
I/DEBUG   (  244):     407f2f94 40419d77 01cb2420 0000000c 00000008  
I/DEBUG   (  244):     407f2fa4 0c000000 01cb83a0 407f2fc0 01cb2420  
I/DEBUG   (  244):     407f2fb4 00000000 00000008 4041a095 00000000  
I/DEBUG   (  244):     407f2fc4 01cb2420 0000000c 0000000c 0000000c  
I/DEBUG   (  244):     407f2fd4 00000000 00000000 00000000 00000000  
I/DEBUG   (  244):     407f2fe4 00010001 00000000 00000009 407f3c90  
I/DEBUG   (  244):     407f2ff4 4059c780 00008980 00000014 00000000  
I/DEBUG   (  244):     407f3004 00000009 407f3c90 404915c9 00000009  
I/DEBUG   (  244):     407f3014 00000000 00000014 4055c92c 00000000  
I/DEBUG   (  244):     407f3024 4055c148 6574656c 407f33f0 4c495220  
I/DEBUG   (  244):     407f3034 4055c92c 4055c934 4055c948 4055c958  
I/DEBUG   (  244):     407f3044 4055c96c 4055c978 4055c984 4055c99c  
I/DEBUG   (  244):     407f3054 4055c9a8 4055c9cc 4055c9ec 4055ca00  
I/DEBUG   (  244):     407f3064 4055ca0c 4055ca28 4055ca3c 4055ca50  
I/DEBUG   (  244):     407f3074 4055ca64 4055ca7c 00000000 3c204955  
I/DEBUG   (  244): 
I/DEBUG   (  244): memory near sl:
I/DEBUG   (  244):     0000314c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     0000315c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     0000316c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     0000317c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     0000318c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     0000319c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     000031ac ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     000031bc ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     000031cc ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     000031dc ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     000031ec ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     000031fc ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     0000320c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     0000321c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     0000322c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244):     0000323c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  244): 
I/DEBUG   (  244): memory near fp:
I/DEBUG   (  244):     01cb8380 00000000 0000001b 00000013 4041e608  
I/DEBUG   (  244):     01cb8390 01cb82a0 00000000 00000018 0000001b  
I/DEBUG   (  244):     01cb83a0 00000014 4041e458 01cb8388 00000000  
I/DEBUG   (  244):     01cb83b0 00000000 000004c3 00000000 00000000  
I/DEBUG   (  244):     01cb83c0 00000000 00000000 00000000 00000000  
I/DEBUG   (  244):     01cb83d0 00000000 00000000 00000000 00000000  
I/DEBUG   (  244):     01cb83e0 00000000 00000000 00000000 00000000  
I/DEBUG   (  244):     01cb83f0 00000000 00000000 00000000 00000000  
I/DEBUG   (  244):     01cb8400 00000000 00000000 00000000 00000000  
I/DEBUG   (  244):     01cb8410 00000000 00000000 00000000 00000000  
I/DEBUG   (  244):     01cb8420 00000000 00000000 00000000 00000000  
I/DEBUG   (  244):     01cb8430 00000000 00000000 00000000 00000000  
I/DEBUG   (  244):     01cb8440 00000000 00000000 00000000 00000000  
I/DEBUG   (  244):     01cb8450 00000000 00000000 00000000 00000000  
I/DEBUG   (  244):     01cb8460 00000000 00000000 00000000 00000000  
I/DEBUG   (  244):     01cb8470 00000000 00000000 00000000 00000000  
I/DEBUG   (  244): 
I/DEBUG   (  244): memory near ip:
I/DEBUG   (  244):     407f2f84 01cb2420 00000008 00000000 0000316e  
I/DEBUG   (  244):     407f2f94 40419d77 01cb2420 0000000c 00000008  
I/DEBUG   (  244):     407f2fa4 0c000000 01cb83a0 407f2fc0 01cb2420  
I/DEBUG   (  244):     407f2fb4 00000000 00000008 4041a095 00000000  
I/DEBUG   (  244):     407f2fc4 01cb2420 0000000c 0000000c 0000000c  
I/DEBUG   (  244):     407f2fd4 00000000 00000000 00000000 00000000  
I/DEBUG   (  244):     407f2fe4 00010001 00000000 00000009 407f3c90  
I/DEBUG   (  244):     407f2ff4 4059c780 00008980 00000014 00000000  
I/DEBUG   (  244):     407f3004 00000009 407f3c90 404915c9 00000009  
I/DEBUG   (  244):     407f3014 00000000 00000014 4055c92c 00000000  
I/DEBUG   (  244):     407f3024 4055c148 6574656c 407f33f0 4c495220  
I/DEBUG   (  244):     407f3034 4055c92c 4055c934 4055c948 4055c958  
I/DEBUG   (  244):     407f3044 4055c96c 4055c978 4055c984 4055c99c  
I/DEBUG   (  244):     407f3054 4055c9a8 4055c9cc 4055c9ec 4055ca00  
I/DEBUG   (  244):     407f3064 4055ca0c 4055ca28 4055ca3c 4055ca50  
I/DEBUG   (  244):     407f3074 4055ca64 4055ca7c 00000000 3c204955  
I/DEBUG   (  244): 
I/DEBUG   (  244): memory near sp:
I/DEBUG   (  244):     407f2f58 0000000c 00000000 00000000 401ebc69  
I/DEBUG   (  244):     407f2f68 00000004 403bf09f df0027ad 00000000  
I/DEBUG   (  244):     407f2f78 4041e98c 0000000c 0000001a 01cb2420  
I/DEBUG   (  244):     407f2f88 00000008 00000000 0000316e 40419d77  
I/DEBUG   (  244):     407f2f98 01cb2420 0000000c 00000008 0c000000  
I/DEBUG   (  244):     407f2fa8 01cb83a0 407f2fc0 01cb2420 00000000  
I/DEBUG   (  244):     407f2fb8 00000008 4041a095 00000000 01cb2420  
I/DEBUG   (  244):     407f2fc8 0000000c 0000000c 0000000c 00000000  
I/DEBUG   (  244):     407f2fd8 00000000 00000000 00000000 00010001  
I/DEBUG   (  244):     407f2fe8 00000000 00000009 407f3c90 4059c780  
I/DEBUG   (  244):     407f2ff8 00008980 00000014 00000000 00000009  
I/DEBUG   (  244):     407f3008 407f3c90 404915c9 00000009 00000000  
I/DEBUG   (  244):     407f3018 00000014 4055c92c 00000000 4055c148  
I/DEBUG   (  244):     407f3028 6574656c 407f33f0 4c495220 4055c92c  
I/DEBUG   (  244):     407f3038 4055c934 4055c948 4055c958 4055c96c  
I/DEBUG   (  244):     407f3048 4055c978 4055c984 4055c99c 4055c9a8  
I/DEBUG   (  244): 
I/DEBUG   (  244): code around pc:
I/DEBUG   (  244):     401f92a4 e1a0700c e3700a01 912fff1e e2600000  
I/DEBUG   (  244):     401f92b4 ea008399 e1a0c007 e3a07004 ef000000  
I/DEBUG   (  244):     401f92c4 e1a0700c e3700a01 912fff1e e2600000  
I/DEBUG   (  244):     401f92d4 ea008391 e1a0c00d e92d00f0 e89c0070  
I/DEBUG   (  244):     401f92e4 e3a070b4 ef000000 e8bd00f0 e3700a01  
I/DEBUG   (  244):     401f92f4 912fff1e e2600000 ea008387 e1a0c00d  
I/DEBUG   (  244):     401f9304 e92d00f0 e89c0070 e3a070b5 ef000000  
I/DEBUG   (  244):     401f9314 e8bd00f0 e3700a01 912fff1e e2600000  
I/DEBUG   (  244):     401f9324 ea00837d e1a0c007 e3a07005 ef000000  
I/DEBUG   (  244):     401f9334 e1a0700c e3700a01 912fff1e e2600000  
I/DEBUG   (  244):     401f9344 ea008375 e1a0c007 e59f7014 ef000000  
I/DEBUG   (  244):     401f9354 e1a0700c e3700a01 912fff1e e2600000  
I/DEBUG   (  244):     401f9364 ea00836d 00000142 e1a0c007 e3a07006  
I/DEBUG   (  244):     401f9374 ef000000 e1a0700c e3700a01 912fff1e  
I/DEBUG   (  244):     401f9384 e2600000 ea008364 e1a0c007 e3a07013  
I/DEBUG   (  244):     401f9394 ef000000 e1a0700c e3700a01 912fff1e  
I/DEBUG   (  244): 
I/DEBUG   (  244): code around lr:
I/DEBUG   (  244):     40419cc0 47f0e92d 460f4604 25004616 eb07e010  
I/DEBUG   (  244):     40419cd0 ebc50905 46200806 46424649 e808f7fe  
I/DEBUG   (  244):     40419ce0 da0a2800 e80af7fe 2b046803 e7f2d107  
I/DEBUG   (  244):     40419cf0 d3ec42b5 e8bd2000 182d87f0 f7fde7f8  
I/DEBUG   (  244):     40419d00 4907effe 44794a07 6803447a f7fe2006  
I/DEBUG   (  244):     40419d10 4620e802 e828f7fe 30fff04f bf00e7eb  
I/DEBUG   (  244):     40419d20 000032b9 00003578 41ffe92d 46074e1e  
I/DEBUG   (  244):     40419d30 447e460d 2e006836 f5b1db0c d90c5f00  
I/DEBUG   (  244):     40419d40 2006491a f44f4a1a 44795300 447a9500  
I/DEBUG   (  244):     40419d50 efe0f7fd 38fff04f 4c16e021 4620447c  
I/DEBUG   (  244):     40419d60 e808f7fe ba1b462b 2204a904 f8414630  
I/DEBUG   (  244):     40419d70 f7ff3d04 2800ffa5 db074680 46394630  
I/DEBUG   (  244):     40419d80 f7ff462a 2800ff9d da034680 f7fd4620  
I/DEBUG   (  244):     40419d90 e004eff8 f04f4620 f7fd0800 4640eff2  
I/DEBUG   (  244):     40419da0 e8bdb004 bf0081f0 000046ae 00003275  
I/DEBUG   (  244):     40419db0 00003563 00004c2c e92d4b63 ed2d43f0

**Comment by n1kolaa** [comment]
ril fixed with last changes?

**Comment by mikeNG** [comment]
I don't know... no time to test 10.2 these days
