### ISSUE TITLE
Headset detection not working on mango

### ISSUE THREAD

**Issue by enveraltin** [LegacyXperia/local_manifests#531]
I've been using bluetooth headsets almost forever, but since bluetooth is draining the battery fast (#15) I bought a sony headset with a mic today.

Unfortunately cm10.2 20140304 build mango doesn't detect the headset properly. Sound is clearly broken and mic almost doesn't work. To be sure I tried the headset with another phone and it worked okay.

I tried a headset without a mic on mango, and it worked fine.

I didn't test it on stock Sony firmware, but I feel like CM 10.2 on mango doesn't detect the headset type properly.

Thanks,

**Comment by amey6a** [comment]
is that headset purely omtp type.....as i am using one which works great......please check again....using latest cm10.2 20140304.....

**Comment by enveraltin** [comment]
Sorry, my bad. Apparently the headset is for iPhone and there is an adaptor in the box, Sony FTW. When I was at the shop I asked the guy what that is for and he said it makes the straight jack L-shape.

I read the manual and tried the headphone with the adaptor and it worked just fine.

Sorry for the noise and thanks a lot.
