### ISSUE TITLE
previous to current port(related to video recording)

### ISSUE THREAD

**Issue by amey6a** [LegacyXperia/local_manifests#534]
hi, initially when i first installed cm11(the first build) there was no any lagging in video...no delay in starting video capture.....then after on each new build the problem arises as recording video not working at all....or delay in starting to record the video....is there some sources that can be re port to next build to make video recorder work as clean. i have deleted that build so can't actually search for the root cause which made that build for good video recording....
sorry...as i don't have any other media to tell you this...i wrote it under issues to make it visible....

**Comment by mikeNG** [comment]
#523

**Comment by amey6a** [comment]
thanks....it helped...
