### ISSUE TITLE
lot of android wakeups - coconut

### ISSUE THREAD

**Issue by godlesplay** [LegacyXperia/local_manifests#536]
![screenshot_2014-03-22-18-59-34](https://f.cloud.github.com/assets/6266223/2493455/1fc5b326-b295-11e3-80a1-c012609cd968.png)

and bugreport from legacyxperia center - http://www24.zippyshare.com/v/88387469/file.html

**Comment by mikeNG** [comment]
Please try latest build and provide logs if this still happens

**Comment by godlesplay** [comment]
seems to be ok, but as you can see battery life is not good, 11.6 %/h
![screenshot_2014-05-13-18-37-05](https://cloud.githubusercontent.com/assets/6266223/2960480/07d7d4b0-dabd-11e3-8238-7b44532b85be.png)
![screenshot_2014-05-13-18-37-12](https://cloud.githubusercontent.com/assets/6266223/2960481/07e12f24-dabd-11e3-9591-3b088e8540e6.png)
