### ISSUE TITLE
Low bitrate MP3s (<256 kbps) interrupt/pause during playback

### ISSUE THREAD

**Issue by mspacek** [LegacyXperia/local_manifests#537]
I know the issue of music playback being interrupted (i.e. momentarily pausing during playback) has been reported here before (see #83 and #371), and seemed to have gotten worse in some builds a few months ago, and then gotten better in newer builds, but I'm still having the problem on `cm-10.2-20140304-RELEASE-LegacyXperia-smultron`, and sometimes much more often (once or twice per minute) than what might be considered "normal" (every 10-15 min). It seemed to me that some albums were much more prone to this than others. Here's the data I've collected so far. Albums are listed by their encoding properties (I've excluded albums names), separated by commas. All are 44 kHz MP3s, unless otherwise indicated. CBR = constant bit rate, VBR = variable bit rate, in kbps:

don't pause at all:

```
CBR 320, CBR 320, CBR 320, CBR 320, CBR 320, CBR 320, CBR 320,
CBR 256,
ogg CBR 500,
ogg CBR 256,
ogg CBR 192, ogg CBR 192, ogg CBR 192
```

few pauses (once every few minutes):

```
VBR ~250
```

pause a lot (~once a minute):

```
CBR 160,
CBR 192, CBR 192, CBR 192,
VBR ~150, VBR ~150,
VBR ~200, VBR ~200
```

This is all with Omich music player, but the results are the same with Apollo and Rocket Music Player. I've also tried toggling various things in the DSP manager and in Rocket Music Player's built in equalizer, to no effect (I usually keep all DSP and equalizer stuff off). Whether the screen is off also makes no difference. Changing the background process limit in the developer options from standard to 3 or 4 also doesn't help. Rebooting does get rid of the pauses for a while, but after say 15 to 30 minutes, the guilty albums start pausing again.

Since I started paying detailed attention to album encoding properties, I have yet to find a single MP3 file with bitrate >= 256 kbps cause a single pause. So far, the only high bitrate MP3 albums I've come across are CBR. All my VBR albums seem to be less than 256 kbps. I guess I could try generating a higher bitrate VBR album and see if that reveals anything, but I suspect CBR vs VBR doesn't make a difference. For MP3s, it's the average bitrate that matters. For OGG files, I've only heard a single pause in hours of listening, regardless of bitrate. So the pausing seems to be confined to low bitrate MP3s.

This is quite mysterious. You'd think if it were a buffer issue, it would be the other way around, that the higher the bitrate, the more frequent the pausing (as described in this old AOSP bug: https://code.google.com/p/android/issues/detail?id=22763). It's also possible, but unlikely, that all the low bitrate MP3s came from the same encoder

Unfortunately, this problem seems to be confined to either LX builds, or to low resource devices like my smultron (512 MB RAM). I typically have about 150 MB free, and 235 used. I've spent some time listening to a variety of albums on my Nexus 7 2012 (grouper) with cm10.2.1 official, and I haven't heard a single pause. It uses the same default governor and IO scheduler as my smultron (interactive and CFQ). Besides being quad core, that device has 1 GB of RAM with about 300 MB free at any time, and plays from internal memory instead of an SD card like on my smultron, so any of those might make the difference.

@mikeNG, is there anything that be done to further diagnose and maybe fix this issue? Perhaps I should make available some sample albums that are causing the problem?

**Comment by mati865** [comment]
I have bad news for you.
It's bug affecting more devices than just Xperia 2011 smartphones.
Part of logcat and further readings here: http://forum.pac-rom.com/Thread-Haida-Stuttering-audio-playback
Although we should try changing bitrate and buffer.

EDIT: Don't forget about logcat. Search its for AudioSink.

**Comment by mspacek** [comment]
Thanks for the link. Read through the thread and its links, tried smartassv2 and sio, no luck. I also did a verbose logcat, and watched for any messages coming up during the stutter. None do. No mention of audiosink or underrun in the logcat. I've tried looking at the main logcat buffer, as well as the radio and events buffer, no different.

**Comment by ghost** [comment]
I remember noticing something similar with the bitrates when I encounterd the problem a few months ago. I noticed that PlayerPro and Poweramp (with increased audio buffer) didn't have these problems. I'd suggest you trying those two apps they are really good.

**Comment by mikeNG** [comment]
LPA is broken so music will stutter
Cannot be fixed yet

**Comment by mikeNG** [comment]
Actually, cm-10.2 is EOL, so I'm closing this issue

**Comment by mspacek** [comment]
I just installed cm-11-20140604-UNOFFICIAL-LegacyXperia-smultron, and the above described stuttering problems are perhaps even worse. High bitrate files now seem to stutter almost as much as low bitrate files, and rebooting doesn't seem to help as much as it did under the final cm10.2 release build. So, should this be reopened?

OK, so LPA will need to be fixed and enabled (#579). Is there a preferred existing bug report for this issue?

**Comment by mikeNG** [comment]
LPA will not be fixed, at least not in the near future. The code is 2 android versions old now and close to impossible to fix. I'm trying to find out more info about this issue and check if it can be fixed without LPA

**Comment by mspacek** [comment]
OK, thanks for the update Mike. I've since gone back to LX 10.2 release, and music playback is back to the way originally described.
