### ISSUE TITLE
Request to enable PPPoE in kernel

### ISSUE THREAD

**Issue by amishmm** [LegacyXperia/local_manifests#54]
Is it possible to enable PPPoE in kernel? ie. can you set and CONFIG_PPPOE=y?

The reason is this allows me to use my ADSL / PPPOE / wifi router in bridged mode.

There are many users asking for this feature on android:
http://www.google.com/search?q=android%20pppoe

There is app too but it appears not to work anymore on Jellybean plus its chinese and ad based. (so I do not trust either)

Thanks in advance.

**Comment by mikeNG** [comment]
Have you tried it and it works?

**Comment by amishmm** [comment]
I have tried with those app and yes it works. The apps in market uses module from kernel.

I dont know about Jellybean as I could not find suitable app.

If you can compile it as module (should be below 50k in size) and share that module then I can test it and report.

**Comment by mikeNG** [comment]
Which device are you using? cm-10.1 or 10.2?

**Comment by amishmm** [comment]
Coconut and CM 10.2

**Comment by mikeNG** [comment]
I will upload a kernel & module here soon for testing

**Comment by mikeNG** [comment]
Here is the kernel plus the module:
http://www.mediafire.com/download/wl8ngg9czps28js/boot.img
http://www.mediafire.com/download/fx6qehha2gqmds5/pppoe.ko

**Comment by amishmm** [comment]
Great thanks for your amazing gesture and support!

**Comment by amishmm** [comment]
Ok as I expected its not that easy!!

I was trying to do this in a linux way. (The way it is done in linux.)

I booted device through kernel. Boots fine. (fastboot boot boot.img)

Loaded pppoe.ko module. Module also loaded fine. (modprobe pppoe)

Then I realized that there is another "shared object" file missing. (for pppd)

I need a plugin for pppd which tells it to connect via pppoe. Not sure if the CM source has that plugin. Searched on github but there are way too many repositories to search in.

Overall I think its going to take too much effort and trial and error for a small thing.

So I am closing this issue.

Thanks a lot for letting me try it and sorry for taking away your time which did not produce required results.

**Comment by amishmm** [comment]
Re-opening as a request to compile/integrate pppoe.ko as a module in next release so that may be in future we can implement PPPoE feature. Its just 15kb more.

May be someone will go ahead and add support for PPPoE plugin in pppd.

You can close this issue once you read this comment. (Even if you decide not to integrate the module)

Thanks again for prompt support.

**Comment by amishmm** [comment]
I dont know why pcfighter closed this issue without giving explanation as mikeNG seemed to be interested in this feature.  (He marked it as enhancement and also provided kernel to me for testing)

but anyway, i continued to try to find a solution to this. (just reporting here for documentation purpose)

i probably found the solution as well but ran into following situations.

I extracted pppoe plugin from wifipppoe.apk available on google play store. It executes well on jellybean. So we can make use of this PPPD plugin for this feature.

Now unfortunately when i boot from kernel 3.4.60 (given above) Wifi does not work. Possibly because wifi modules in /system/lib/modules are that of 3.4.59

Wifi works on 3.4.59 but it appears PPP as well as PPPoE both the modules are disabled in it. As when I try to run LXP inbuilt pppd it complains that PPP module is not supported by kernel

It seems that mikeNG has just enabled support for PPP on kernel (3.4.60 for openvpn support).

So when I try to run pppd in 3.4.60 it does not complain missing PPP support anymore but then since wifi does not work. I can not test anything.

So overall I suppose I will wait for next release of LXP 10.2 where both PPP support will be there and wifi will also work.(as proper kernel modules will also be available)

Still have to figure out if PPPOE module will be needed or not, which I can test only after above conditions are met.

till then I wait and watch :)

**Comment by pcfighter** [comment]
Can't you download and build kernel from source ? You don't have to have all android source, just toolchain, and probably hardware/ti/wlan

**Comment by amishmm** [comment]
I wish I could!

I am completely new to android development. But I am not at all new to linux. So I can do lots of R&D with mobile. (as android is linux based)

I want to learn android development but there are several other commitments and resource limitations. May be someday in future I will get time for this as well.

**Comment by Andrewas** [comment]
I can help you build it if you can and have the files but I can't help you solving if there are any issues!

**Comment by mikeNG** [comment]
Well, if you use linux, have space on your disk & have a decent internet connection you can follow my guides on xda and build on your own. That's how I started building for myself a year ago, having almost no knowledge of android

**Comment by amishmm** [comment]
I have run into all kind of resource limitations. Just have 8GB free space, 4GB dual core machine and internet is just 512kbps! (blaming Government for low speeds!)

So currently can not do anything and I myself find me helpless!

**Comment by Andrewas** [comment]
@amishxda it's noth that hard to do but you must have synced all sources (23 gb approximatedly...it will take a long time on your current connection...and it is about 23gb of sources) I can build it for you if you want ;) just contact me

**Comment by amishmm** [comment]
@Andrewas thanks for your offer. But I think this feature should work in next release. So I will wait for few days. If there is any problem I will let you know.

**Comment by amishmm** [comment]
Ok, I have successfully setup WiFI pppoe. (Tested with LXP CM10.2 20130918 Nightly)

It just requires PPP based kernel (does not require pppoe.ko module)

Anybody interested, please find instructions here.
http://forum.xda-developers.com/showthread.php?t=2450863

Thanks to mikeNG for enabling PPP in kernel.

**Comment by mikeNG** [comment]
Nice
