### ISSUE TITLE
Battery life not good!  cm11  20140319 haida

### ISSUE THREAD

**Issue by ankurjain093** [LegacyXperia/local_manifests#549]
my phone used to last for about 4 hours screen on time in ICS
but on kk its just less than 2 hours ... and even if phone is on sleep it will last in less than 8 hours..

![screenshot_2014-03-28-19-20-16 1](https://cloud.githubusercontent.com/assets/7050766/2550232/d3db99c2-b680-11e3-8b60-e89e27d8b913.png)
![screenshot_2014-03-28-19-20-37 1](https://cloud.githubusercontent.com/assets/7050766/2550234/d9a59bd2-b680-11e3-8838-7b90c6e087c1.png)

**Comment by godlesplay** [comment]
something is wrong in your side because in my coconut on latest build battery life is good, from 100% to 14% after 3h 30 minutes

**Comment by ankurjain093** [comment]
its a fresh install ... with just whatsapp installed . 

and i am installing it for 2nd time and then i posted the problem

**Comment by godlesplay** [comment]
so I can see that your wifi is always on, try disable it when you are not using it...
