### ISSUE TITLE
iyokan - Panning while zoomed in causes photo to blur.

### ISSUE THREAD

**Issue by pteek** [LegacyXperia/local_manifests#551]
How to reproduce.

Go to camera.
Swipe to get to album.
Zoom in fully on any photo.
Try panning.
The photo blurs until panning is stooped(by lifting finger off the screen.)

THIS DOES NOT HAPPEN IF you go to album directly from the menu. Only happens if you reach album from camera app.

Edit: cm-11.0-20140320-NIGHTLY-LegacyXperia-iyokan

**Comment by mikeNG** [comment]
Please try latest build and provide logs if this still happens

**Comment by pteek** [comment]
Still present on 20140512.

http://pastebin.com/3iLQVySL(logcat)
http://pastebin.com/ibc5iwub(last_kmsg)
http://pastebin.com/kz7C5N8T(dmseg)

**Comment by pteek** [comment]
Still present on 20140703.

**Comment by mikeNG** [comment]
CM bug, won't fix
