### ISSUE TITLE
iyokan - Video is corrupted for a moment if touch focus or zoom is used while recording is paused.

### ISSUE THREAD

**Issue by pteek** [LegacyXperia/local_manifests#552]
How to reproduce:

Go to camera.
Start recording a video.
Pause.
Use touch focus to refocus AND/OR use zoom.
Un-pause.
Stop the recording.

The recoding will have a couple of corrupted frames near the pause.

This does not happen if the scene is changed while paused. Only if focus or zoom is used.

**Comment by pteek** [comment]
Still present on 20140512.
http://pastebin.com/LWU00V7v(logcat)
http://pastebin.com/vwhPb29T(dmseg)
http://pastebin.com/rWP3raKz(last_kmsg)

**Comment by mikeNG** [comment]
Probably cannot be fixed.
Our camera libs were not designed to support pause/resume
