### ISSUE TITLE
very urgent issue!![CM11] haida

### ISSUE THREAD

**Issue by ankurjain093** [LegacyXperia/local_manifests#558]
phone reboots when the browsing is done on 3g... 

its a sure shot bug as i have tried it many times on a fresh install ....

**Comment by daveliao** [comment]
Are you using the stock browser?
I'm on an iyokan device and ran into the same issue, so I installed another browser (Chrome), which seems to help as a workaround.

**Comment by ankurjain093** [comment]
yep i am on the stock browser and the problem do persist on stock  browser.. 

ill try a differnt one .. chrome is very heavy

**Comment by xange** [comment]
maybe changing the title from very ergent issue to 3g + stock browser will cause phone reboots? and this is a known issue since mike fixed the lags in stock browser. thanks. my meaning is that title is not appropriate.
