### ISSUE TITLE
Blacklist for Messages Ignored

### ISSUE THREAD

**Issue by gxgani** [LegacyXperia/local_manifests#560]
Blacklist seems to working for the calls but for the messages it doesn't.

**Comment by mikeNG** [comment]
Please try latest build and provide logs if this still happens

**Comment by MardonHH** [comment]
I know this bug.
Happens when u use a too old ContactsProvider.apk (patched for facebook contacts sync)
Didnt happen with original ContactsProvider.apk
So mike close this bug as its a 3rd party failure.
