### ISSUE TITLE
Mango: CPU Scaling reset after new boot

### ISSUE THREAD

**Issue by Telemuddi** [LegacyXperia/local_manifests#561]
I don't use performance profiles since this is not useful for me. I manually set the CPU to 1200Mhz and governor smartassv2. The option "set on boot" is chosen but after switching off the phone and turn it on again everything expect "set on boot" is resettet. The set scheduler stays right on sio.

**Comment by vassilis91** [comment]
Sometimes this happen on my smultron. Cpu settings and scheduler go to default values. I can confirm it

**Comment by avinashrocks1990** [comment]
I'm also facing same problem on haida

**Comment by mikeNG** [comment]
will probably be fixed in next build

**Comment by mikeNG** [comment]
Fixed in next build
