### ISSUE TITLE
iyokan - wifi don't connect under 802.11 TLS wifi network

### ISSUE THREAD

**Issue by Tiax93** [LegacyXperia/local_manifests#562]
[CM11]-iyokan-cm-11.0-20140320-NIGHTLY: when I try to connect to 802.11 TLS wifi network it's just stay on connecting, then it's stopping e then restart to try connect, 'till it says disconnect.

logcat: http://pastebin.com/CR28tt6n
log last_ksmg: http://pastebin.com/YVR9ScWW

**Comment by godlesplay** [comment]
paste logs to pastebin or other site, not here...

**Comment by mikeNG** [comment]
Still an issue?

**Comment by Tiax93** [comment]
I don't know, because I can't connect to this type of network for a while. Sorry
