### ISSUE TITLE
incoming call issue - haida

### ISSUE THREAD

**Issue by ankurjain093** [LegacyXperia/local_manifests#566]
there are circumstances when i am calling someone and at the same time the other person calls me ... 
at this moment the issue is that the incoming call ui is not shown and only the outgoin call ui appears .. neither i am able to answer that call neither i could decline ... it just keeps on ringing without showing options to answer or decline

**Comment by rtammekivi** [comment]
This happened on a different device too (Huawei IDEOS X5). It must be a bug in the CM-11.0 codebase.

**Comment by mikeNG** [comment]
Still an issue?
