### ISSUE TITLE
major bug while charging - haida

### ISSUE THREAD

**Issue by ankurjain093** [LegacyXperia/local_manifests#567]
i opened the performance menu while charging the phone and noticed the cpu frequencies ..
while charging the frequency reaches to the max and fluctuates i.e 1017mhz 468mhz etc 

and as soon as i remove the charger it stablises itself to 122 mhz... and this is the reason why my phone heats up to 40-50 degrees while i am on call while charging ....

please fix

**Comment by chraso** [comment]
I'm experiencing problem for keyboard while connected to usb/charger.
Keyboard types 2~3 other character automatically while typing something.
I will upload the log in few mins.

**Comment by SaatvikShukla** [comment]
i confirm  chraso's problem same with me, without the charger its fine.

**Comment by chraso** [comment]
I encountered it for the setup wizard.
Now with charger its ok but will test with pc usb on mtp and other modes and will report back.
phewww....
http://pastebin.com/f22QcAgZ
this has no effect while on usb mass storage mode.
and can be reproduced only while read/write something from it, otherwise its normal.
didn't checked the camera mode.
charger is ok.

**Comment by avinashrocks1990** [comment]
I'm also facing the same problem on haida

**Comment by Nikhildangui** [comment]
Do you People who are facing this problem use default sony charger?? 
some third party chargers makes touch screen of the phone respond crazy... or at times touch screen almost unusable, change your charger and respond back
Mike make note of it please

**Comment by ankurjain093** [comment]
yess the touch screen gets unresponsive with fake chargers .... 

but the issue posted by my is not related to unresponsiveness of screen ...  its about the cpu clock speeds while charging ....

**Comment by mikeNG** [comment]
Which build are you using?

**Comment by ankurjain093** [comment]
latest official your build 20140319 cm11

**Comment by mikeNG** [comment]
Please try latest build and provide logs if this still happens

**Comment by skarthiksankaran** [comment]
Hi --

I am using the latest Release build of CM-10.2. I see that while charging when I type something eg., If I put the unlock code on my home screen, the values gets typed 2 or 3 times. instead of once. This happens even while messaging ( when charging is on).
