### ISSUE TITLE
WL1271 BLE (bt 4.0)

### ISSUE THREAD

**Issue by mikeNG** [LegacyXperia/local_manifests#57]
Probably new firmware:
https://github.com/TI-ECS/bt-firmware

Opened for @pcfighter dev plans

**Comment by pcfighter** [comment]
I don't know if BLE will work on 4.2.2, but it must work on 4.3.x

**Comment by mikeNG** [comment]
right, I also pushed updated BT code in cm-10.2-next kernel branch for testing

**Comment by n1kolaa** [comment]
kernel form cm10.2next brunch cant be compiled here is output http://pastebin.com/cQanejDe
target anzu

**Comment by mikeNG** [comment]
I just tested and BT audio doesn't work with TI firmware...
