### ISSUE TITLE
[haida] {CM 10.2} Sixaxis controller doesn't work?

### ISSUE THREAD

**Issue by Artlar** [LegacyXperia/local_manifests#570]
Work perfect on stock ics and miuiv5(CM10). But on 10.2 i can't connect dualshock 3 to my smartphone.

**Comment by badboyasd** [comment]
me too

**Comment by mikeNG** [comment]
Hmm seems the kernel driver is disabled. I will enable it in the next cm11 build. Not sure if I will release any other updates for cm10.2/cm10.1

**Comment by Artlar** [comment]
Thank for all . It's great message for me but i using now cm 11 rom. I can't wait for play on my neo v in psx emulator witch ps3 controller. Sorry for my poor English.
