### ISSUE TITLE
urushi - some time multitasking doesn't show off app

### ISSUE THREAD

**Issue by badboyasd** [LegacyXperia/local_manifests#571]
some time, i clear all app in multitasking, and i go to an app like clock and i active multitasking, but it doesn't show any app ( it must show off clock in this time.) i must re-active multitasking few time and it show off app.

**Comment by mikeNG** [comment]
I don't understand what you mean

**Comment by badboyasd** [comment]
sorry for my english. some time, i run few app, and i active recents app list ( hold home button) and it show : no recent apps, i must re-active recent app list few time  and it show app

**Comment by mikeNG** [comment]
Please try latest build and provide logs if this still happens

**Comment by badboyasd** [comment]
how to get a log for this error? sorry for my english
Vào 12-05-2014 20:43, "Michael Bestas" notifications@github.com đã viết:

**Comment by BRAiNCHiLD95** [comment]
Use SysLog : https://play.google.com/store/apps/details?id=com.tortel.syslog
and whenever this issue occurs again...goto the app and take logs..and upload them here! :)

**Comment by badboyasd** [comment]
this is my logs http://www.4shared.com/zip/Sj9Zjzokce/2014-06-01_1242.html?
 hope you fix error soon

**Comment by pcfighter** [comment]
I think it is a Android Bug. In my Nexus 7 also sometimes I had to enter two times to list opened apps on task manager
