### ISSUE TITLE
touchscreen jitter issue - HAIDA

### ISSUE THREAD

**Issue by ankurjain093** [LegacyXperia/local_manifests#574]
whenever i do a long touch , may be to select somthing , or may be to open a new tab menu in browser or may be in gallery to zoom with two fingers ...  
the screen is never stable , i just keeps shaking and flickering as if its a pirated display... 

this did not happened on ics 4.0.4 or 2.3

**Comment by Artlar** [comment]
Me too...

**Comment by jaarandaz** [comment]
Hi!

do you have the same build version of Kernel and Rom? In my haida I had screen issues because I was using cm-11-20140703 kernel with Rom cm-11-20140718. It was fixed after updating the kernel.

Regards!
