### ISSUE TITLE
cell broadcast

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#575]
there's no option to off cell broadcast ..its really annoying. help

**Comment by mikeNG** [comment]
there is

**Comment by ghost** [comment]
then tell me....

**Comment by mikeNG** [comment]
It's extremely easy to find it in settings. This is a bug tracker, not a help desk

**Comment by ghost** [comment]
nope its not easy to find in settings..there is broadcast settings but there is no cell broadcast ... I can find only environment broadcast, emergency broadcast, earthquake broadcast, and so on but no cell broadcast

and I think its a bug idjit...my friend have the same xperia phone with same ROM but this annoying messages is happening in my phone

give me some help Mr.mike

**Comment by avinashrocks1990** [comment]
just delete the cell broadcast app 
problem solved

**Comment by pcfighter** [comment]
just uncheck all broadcasts, then you shouldn't got any messages from you cell network. Not every operator provides this.
