### ISSUE TITLE
Not displayed "Most visited sites" in default browser (CM11)

### ISSUE THREAD

**Issue by kiskv** [LegacyXperia/local_manifests#578]
![screenshot_2014-04-20-11-09-28](https://cloud.githubusercontent.com/assets/7351852/2750305/0b93fcda-c868-11e3-801c-4517cc7b3779.png)
![screenshot_2014-04-20-11-09-00](https://cloud.githubusercontent.com/assets/7351852/2750306/112bfad0-c868-11e3-8e45-0ff1a74c7ce9.png)

**Comment by mid-kid** [comment]
Probably a side-effect of using the webkit webview.
Our devices do not (yet) support the new chromium webview.

EDIT: Confirmed on haida CM11 (20140319)

**Comment by mikeNG** [comment]
@gixandr  Which build you are using?

**Comment by fqdb** [comment]
I have the same problem. Build I'm using is the latest nightly (19-03 IIRC)

**Comment by kiskv** [comment]
@mikeNG 20140319, and cm10.2 20140303, cm10.1 dont known.

**Comment by mikeNG** [comment]
Please try latest build and provide logs if this still happens

**Comment by kiskv** [comment]
@mikeNG  everything works fine on today build

**Comment by mikeNG** [comment]
nice
