### ISSUE TITLE
when the device in the balance mod(performance profile) intermittent playing music is pause 

### ISSUE THREAD

**Issue by ko-itbuddy** [LegacyXperia/local_manifests#579]
when the device in the balance mod(performance profile) playing music is intermittently pause.

**Comment by pcfighter** [comment]
Try to change default governor or/and I/O scheduler

**Comment by mikeNG** [comment]
Please try latest build and provide logs if this still happens

**Comment by ko-itbuddy** [comment]
i'm upgraded legacy xepria anzu ( arc ) latest version.
when i playing music for a long time it still intermittenly pause ( it
seems like a slow buffering!  ) please check my bug report. maybe in latest
log has a key.

2014-05-12 22:42 GMT+09:00 Michael Bestas notifications@github.com:

**Comment by mikeNG** [comment]
What bug report? I don't see any logs

**Comment by ko-itbuddy** [comment]
i don't know which logs have music playing logs so i attach all logs in
archive.

but now i check list of logs i think the radio logs have music playing logs.

my device's  CPU governer is SMARTASSV2
                                            minimum CPU frequency is 368mhz
                                            maximum CPU frequency is 1017
mhz
                   I/O schedular is SIO

and i changed several settings... but it still have music raggy

-mod edit-

**Comment by mikeNG** [comment]
LPA is not working so music will stutter.
This cannot be fixed yet

**Comment by pcfighter** [comment]
but can be disabled in build.prop

**Comment by mikeNG** [comment]
That's what I mean. If LPA is disabled, music will stutter.
We already disabled LPA in build.prop because it completely breaks audio

**Comment by ko-itbuddy** [comment]
for playing music, 20140319 build more stable than later builds.

**Comment by rtammekivi** [comment]
If I remember correctly, it was in February/March when this issue started appearing in Huawei U8800 aswell.

So far it seems like the decoder cannot keep up. Have you noticed same stutters when playing different types of audio files like aac, wav and so on?

**Comment by ko-itbuddy** [comment]
i checked wav and ogg file doesn't have any shutters on playing. but mp3 file have shutters on playing!

**Comment by mikeNG** [comment]
Should be fixed in next build
