### ISSUE TITLE
BATTERY LIFE !!! cm-11.0-20140319 coconut

### ISSUE THREAD

**Issue by braianrq** [LegacyXperia/local_manifests#581]
Hello I wanted to comment that there is very little battery life. Every minute I consume 1% battery will me almost an hour. And the truth is very bad. I have a Xperia Live With Walkman with the rom-20140319 cm-11.0 coconut. 
Do not tell me the problem is my battery that recently any rom other than this I will perfect the battery life is more with ICS 4.0.4 (rom that had little while ago) the battery lasted much longer. 
PLEASE FIX IT! 
sorry if my english is bad, my language is Spanish.

**Comment by ghost** [comment]
Confirm! My coconut has high battery drain even in deep sleep

**Comment by mikeNG** [comment]
Please try latest build and provide logs if this still happens

**Comment by BielMarques** [comment]
My battery life is a low too.
