### ISSUE TITLE
Camera bugs - urushi

### ISSUE THREAD

**Issue by bimantarakp** [LegacyXperia/local_manifests#583]
I don't know why but my camera do not work well, the pictures which I take is pretty poor in quality, I compare it with pictures which I shoot with stock rom camera. 

Beside that I can't install any 3rd camera app like camera-fv5, and I can't open camera when some social media app need to take a picture.

I don't know it happen only in my device or not, but please do something

**Comment by mikeNG** [comment]
Please try latest build and provide logs if this still happens
