### ISSUE TITLE
[omni] (haida) Lock screen "unlocker" misplaced

### ISSUE THREAD

**Issue by mid-kid** [LegacyXperia/local_manifests#584]
http://chunk.io/f/e7f4e89fe6db42f0a3ba1a97a0b8b31e
Also in portrait mode, the "unlocker" is far too low.
Not sure if it's an error on omni's side.

**Comment by mikeNG** [comment]
This is a general bug in 4.4. layout is also broken in cm

**Comment by mid-kid** [comment]
I never noticed in cm i guess :/ (I ususally use unlock patterns)
