### ISSUE TITLE
[omni] (haida) Phase Beam lags a lot

### ISSUE THREAD

**Issue by mid-kid** [LegacyXperia/local_manifests#585]
The Phase Beam live wallpaper makes the phone lag, while other wallpapers work just fine.
[logcat, when starting wallpaper chooser and selecting Phase Beam](http://chunk.io/f/0198896a08904c26b790df058b37a8f7)

**Comment by mikeNG** [comment]
ION_IOC_ALLOC failed with error - Out of memory
Seems like it uses a LOT of memory

**Comment by mikeNG** [comment]
try with latest sources (https://github.com/LegacyXperia/android_device_semc_msm7x30-common/commit/fb98aa48f0673bb87dd40a8a569251e6461f0a5d)

**Comment by mid-kid** [comment]
Thanks; will make a new build soon and report back.

**Comment by mid-kid** [comment]
Doesn't change a thing.
It's not just lagging when scrolling desktops, the FPS drops as a whole.

**Comment by mikeNG** [comment]
Have you tried CM's phasebeam?
If it's not lagging, I'll check if they have any optimization and port it over to omni

**Comment by mid-kid** [comment]
Last time I used Phase Beam was with PAC-MAN Rom, CM 10.2. It didn't lag.
I'll try soon on CM11.
