### ISSUE TITLE
[omni] (haida) Screen recording doesn't work

### ISSUE THREAD

**Issue by mid-kid** [LegacyXperia/local_manifests#586]
`E/ACodec  ( 5908): Unable to instantiate a decoder for type 'video/avc'.`
[logcat, when pressing the screen record button in the power menu](http://chunk.io/f/49a89bc375b14af29d2f0c5238d96954)

**Comment by mikeNG** [comment]
Something is very wrong with omni but I can't figure it out.
I'm closing the omni issues in the bug tracker now since we don't have any builds yet

**Comment by mikeNG** [comment]
Also, omni looks pretty much dead to me, my patches are sitting for about a month on their gerrit with no review
