### ISSUE TITLE
[omni] (haida) Video recording doesn't work

### ISSUE THREAD

**Issue by mid-kid** [LegacyXperia/local_manifests#587]
I'm talking about video recording in the camera app.
[logcat, when pressing the record button](http://chunk.io/f/0e32089a73324027ab301c921cc2f743)

**Comment by mikeNG** [comment]
have you tried with latest sources?

**Comment by mikeNG** [comment]
it works for me with latest sources

**Comment by mid-kid** [comment]
You update the repos too fast for my machine to build it. :P 
I tried with last night's nightly. Will build a new one and report.

**Comment by pcfighter** [comment]
I can also confirm it works well now (coconut)

**Comment by mid-kid** [comment]
Okay, enough evidence. :P
