### ISSUE TITLE
slow kernel coconut cm-11.0

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#588]
I'm using the latest kernel from the CM11 zip package.. 
Phone has very long startup: boot screen shows up for about a minute and then boots the system, CWM always freeze when loading for a minute and then show available options.

Sorry for my English, but I'm from Poland

**Comment by ankurjain093** [comment]
this is a very old reported problem... 
this has been fixed with the ion kernel ... just wait for it ...
let mike do his job ....

**Comment by mikeNG** [comment]
Please try latest build and provide logs if this still happens

**Comment by mikeNG** [comment]
Also, duplicate of #383
