### ISSUE TITLE
[10.2 release, smultron] High battery drain after full charge but not after reboot

### ISSUE THREAD

**Issue by mspacek** [LegacyXperia/local_manifests#591]
After flashing my smultron from `cm-10.2-20140207-NIGHTLY-LegacyXperia-smultron` to `cm-10.2-20140304-RELEASE-LegacyXperia-smultron` a month or so ago, I noticed that after fully recharging my phone, it would discharge much faster than usual, maybe 50% per day instead of the more usual 10% per day. However, after rebooting, the discharge rate returned to normal. I think the problem only manifested when charging up to 100%. If I did a partial charge, the high discharge rate wouldn't happen (I think).

I tried running Wakelock Detector (https://play.google.com/store/apps/details?id=com.uzumapps.wakelockdetector), but found nothing suspicious. I didn't know about BetterBatter Stats (http://forum.xda-developers.com/showthread.php?t=1179809), not sure if that would've revealed anything more.

Today I reverted back to `cm-10.2-20140207-NIGHTLY-LegacyXperia-smultron`, did a full charge, and I'm happy to say the high discharge rate problem has disappeared. According to the changelog, not much changed between the two version. The kernel went from 3.4.77 to 3.4.82:

https://github.com/LegacyXperia/local_manifests/wiki/Changelog#release-build-20140303---cm-102

**Comment by mspacek** [comment]
It seems I was being too optimistic. I am indeed still seeing the same problem in the older nightly build from 20140207, so I don't know what's changed on my phone to cause this fairly new behaviour. I have a very minimal number of apps installed. I installed BBS, charged up to 100%, then let it discharge to about 56% over half a day (11+ hours, 3.9%/hour), with very little use. Here are the dump, dmesg, and logcat files from BBS:

https://gist.github.com/mspacek/4d04809253563e3feb78
https://gist.github.com/mspacek/f833d8a3b46c9145ba71
https://gist.github.com/mspacek/978eac8f817f4f156c5b

I've looked through them and can't find anything very suspicious. Strangely, BBS says it was in deep sleep 98.7% of the time. I have excellent reception with full bars (data and wifi disabled), yet also strangely, BBS says `No or Unknown Signal` for the entire time.

If someone with a bit more experience could have a look, that would be great!

I'll recharge to 100% and then reboot right away to get rid of the rapid battery drain, and report a new set of files after another half day of light usage. Hopefully the difference in the two sets of files will reveal something.

**Comment by mspacek** [comment]
Upon further examination, this looks suspicious in the BBS dump file:

```
"rpcrotuer_smd_xprt" ():  (0 s) Cnt:(c/wc/ec)1227/88/0 0.0%
```

and show up very regularly in dmesg. mmc1_detect also shows up very regularly in dmesg.

Apparently, `rpcrotuer_smd_xprt` is misspelled. From a forum posting:

http://www.modaco.com/topic/332692-cm7-nightly-discussion-thread-old-please-use-new-thread/page-116#entry1626475

> Now the funny part, rpcrotuer is misspelt. In the config files of the kernel, it is always spelt as
> rpcrouter. So this looked suspicious. In the kernel source, under arch/arm/mach-msm, there is
> the file rpcrouter_smd_xprt.c and its object file. In that file I found rpcrotuer_smd_xprt and
> corrected it to rpcrouter_smd_xprt. And then I compiled a new kernel incorporating this change.
> I've been experiencing better standby now. 

@mikeNG, is this relevant to LX? I'd try it myself, but I don't have the ability to compile the kernel (or ROM).

**Comment by mspacek** [comment]
Just found it. The misspelling shows up twice in `rpcrouter_smd_xprt.c`:

https://github.com/LegacyXperia/android_kernel_semc_msm7x30/blob/cm-11.0/arch/arm/mach-msm/rpcrouter_smd_xprt.c

Not sure where to find the kernel code for the cm10.2 I'm running.

**Comment by mspacek** [comment]
After charging up, rebooting, and running for another half day, here are another set of BBS dump, dmesg and logcat files:

https://gist.github.com/mspacek/1c918499a10dbefadd96
https://gist.github.com/mspacek/b0ab34b647afeb299771
https://gist.github.com/mspacek/e5252c96a3f289cef736

As expected, battery drain was far less after rebooting: 0.7%/h instead of 3.9%/h before. `rpcrotuer_smd_xprt` again had 86 wakecounts, almost the same as the 88 before.

`"rpcrotuer_smd_xprt" ():  (0 s) Cnt:(c/wc/ec)1209/86/0 0.0%`

There are now 3 `rpc_read` entries and one `rpc_reply` entry in the dump file, some of which have negative counts. None of these were there before, during the high battery drain.

`rpcrotuer_smd_xprt` shows up about as often in dmesg as it did before.

**Comment by mikeNG** [comment]
cm-10.2 is EOL so I'm closing this issue.
If it's still present in cm11 feel free to reopen

**Comment by TheDukeVIP** [comment]
Hi,
I used LegacyXperia cm11-LegacyXperia-0611 on iyokan, no battery problem detected
I did a fresh install of cm11-LegacyXperia-0703 (ie: flash boot.img, reformat system/data/cache, wipe data-factory reset, install zip file and gapps-minimal 4.4.4)
Now I'm having battery problem and dmesg shows the same rpcrotuer_smd_xprt wakelocks
