### ISSUE TITLE
Gallery bug cm11 (haida)

### ISSUE THREAD

**Issue by sknerus75** [LegacyXperia/local_manifests#593]
I'm using on my xperia neo v (haida) the latest build of CM11-  cm-11.0-20140319-NIGHTLY-LegacyXperia-haida and included kernel.
When I'm browsing a picture gallery, stock or non stock, my device has soft reboot, and after this shows error of process "android.process.media" and "com.android.systemui", and I must reboot manually. On previous version of CM11 this issue also appeared. Any chance for solving this problem?

**Comment by mikeNG** [comment]
Please try latest build and provide logs if this still happens

**Comment by sknerus75** [comment]
Now it works great, thank you so much :)
