### ISSUE TITLE
[cm-11-20140511-UNOFFICIAL-LegacyXperia-hallon] "com.android.incallui" crush

### ISSUE THREAD

**Issue by zhangziang** [LegacyXperia/local_manifests#594]
When call in or call out,it can't into the Call Interface and alert “com.android.incallui ***”

**Comment by ashish-git** [comment]
I am also facing same issue on my Xperia Arc for cm-11-20140511 build.

**Comment by zhangziang** [comment]
Flash this build nend double wipe? now i flash back”20140319“ also appear many issues.

**Comment by zhangziang** [comment]
Flash this build nend double wipe? now i flash back”20140319“ also appear many issues.

**Comment by zhangziang** [comment]
Flash this build need double wipe? now i flash back”20140319“ also appear many issues.

**Comment by zhangziang** [comment]
Flash this build need double wipe? now i flash back”20140319“ also appear many issues.

**Comment by zhangziang** [comment]
Flash this build need double wipe? now i flash back”20140319“ also appear many issues.
