### ISSUE TITLE
Crash with "com.android.incallui" message on cm-11-20140511 build

### ISSUE THREAD

**Issue by ashish-git** [LegacyXperia/local_manifests#595]
I am facing issue for incoming & outgoing call with "com.android.incallui" crash message on cm-11-20140511 build.

ADB Crash Logs as follows:-
05-12 13:27:58.315: E/AndroidRuntime(8373): Process: com.android.incallui, PID: 8373
05-12 13:27:58.315: E/AndroidRuntime(8373): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.dialer/com.android.incallui.InCallActivity}: android.view.InflateException: Binary XML file line #53: Error inflating class fragment
05-12 13:27:58.315: E/AndroidRuntime(8373):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2215)
05-12 13:27:58.315: E/AndroidRuntime(8373):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2265)
05-12 13:27:58.315: E/AndroidRuntime(8373):     at android.app.ActivityThread.access$800(ActivityThread.java:145)
05-12 13:27:58.315: E/AndroidRuntime(8373):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206)
05-12 13:27:58.315: E/AndroidRuntime(8373):     at android.os.Handler.dispatchMessage(Handler.java:102)
05-12 13:27:58.315: E/AndroidRuntime(8373):     at android.os.Looper.loop(Looper.java:136)
05-12 13:27:58.315: E/AndroidRuntime(8373):     at android.app.ActivityThread.main(ActivityThread.java:5144)
05-12 13:27:58.315: E/AndroidRuntime(8373):     at java.lang.reflect.Method.invokeNative(Native Method)
05-12 13:27:58.315: E/AndroidRuntime(8373):     at java.lang.reflect.Method.invoke(Method.java:515)
05-12 13:27:58.315: E/AndroidRuntime(8373):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
05-12 13:27:58.315: E/AndroidRuntime(8373):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
05-12 13:27:58.315: E/AndroidRuntime(8373):     at dalvik.system.NativeStart.main(Native Method)
05-12 13:27:58.315: E/AndroidRuntime(8373): Caused by: android.view.InflateException: Binary XML file line #53: Error inflating class fragment
05-12 13:27:58.315: E/AndroidRuntime(8373):     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
05-12 13:27:58.315: E/AndroidRuntime(8373):     at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
05-12 13:27:58.315: E/AndroidRuntime(8373):     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
05-12 13:27:58.315: E/AndroidRuntime(8373):     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
05-12 13:27:58.315: E/AndroidRuntime(8373):     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
05-12 13:27:58.315: E/AndroidRuntime(8373):     at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
05-12 13:27:58.315: E/AndroidRuntime(8373):     at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:343)
05-12 13:27:58.315: E/AndroidRuntime(8373):     at android.app.Activity.setContentView(Activity.java:1929)
05-12 13:27:58.315: E/AndroidRuntime(8373):     at com.android.incallui.InCallActivity.onCreate(InCallActivity.java:94)
05-12 13:27:58.315: E/AndroidRuntime(8373):     at android.app.Activity.performCreate(Activity.java:5231)
05-12 13:27:58.315: E/AndroidRuntime(8373):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
05-12 13:27:58.315: E/AndroidRuntime(8373):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
05-12 13:27:58.315: E/AndroidRuntime(8373):     ... 11 more
05-12 13:27:58.315: E/AndroidRuntime(8373): Caused by: java.lang.NullPointerException
05-12 13:27:58.315: E/AndroidRuntime(8373):     at com.android.incallui.CallButtonFragment.onCreateView(CallButtonFragment.java:155)
05-12 13:27:58.315: E/AndroidRuntime(8373):     at android.app.Fragment.performCreateView(Fragment.java:1700)
05-12 13:27:58.315: E/AndroidRuntime(8373):     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:866)
05-12 13:27:58.315: E/AndroidRuntime(8373):     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1040)
05-12 13:27:58.315: E/AndroidRuntime(8373):     at android.app.FragmentManagerImpl.addFragment(FragmentManager.java:1142)
05-12 13:27:58.315: E/AndroidRuntime(8373):     at android.app.Activity.onCreateView(Activity.java:4786)
05-12 13:27:58.315: E/AndroidRuntime(8373):     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:689)
05-12 13:27:58.315: E/AndroidRuntime(8373):     ... 22 more

![notification](https://cloud.githubusercontent.com/assets/3125668/2941039/e30b7a50-d996-11e3-9dc8-cb73b394373a.png)
![callui](https://cloud.githubusercontent.com/assets/3125668/2941042/eefceec0-d996-11e3-9913-701a34673a50.png)

**Comment by ksranjith786** [comment]
I am also facing the same issue in Xperia Arc S with the latest build. ANZU

**Comment by ashish-git** [comment]
If you are rolling back to older builds again, you need to wipe data & cache. If you didn't your older build has issues too.

**Comment by ksranjith786** [comment]
I follow the procedure similarly as you suggested. But do we get any fix for this issue or we need to rollback to old build ?

**Comment by ashish-git** [comment]
As per XDA discussion, new fixed build is on the way. They already fixed this issue. You can check this link for more details:- http://review.cyanogenmod.org/#/c/63837/

**Comment by chepz** [comment]
I am also facing the same issue in coconut here..., maybe this is because "Added landscape support in dialer & in-call UI "...

**Comment by ksranjith786** [comment]
Thanks. Its better if they provide it as bug-fix.

**Comment by ashish-git** [comment]
For this issue new build is already updated. You can download latest build (cm-11-20140512-UNOFFICIAL-LegacyXperia-anzu.zip), It's working fine.

**Comment by ksranjith786** [comment]
Thanks. :)
