### ISSUE TITLE
com.android.incallui crashing on coconut cm11 20140511

### ISSUE THREAD

**Issue by prashantbhargava** [LegacyXperia/local_manifests#596]
The com.android.incallui crashes every time whenever there is an incoming call and you can't call too.
Attending an incoming call is totally impossible as black screen shows up saying com.android.incallui has stopped
I'm using cm11 4.4.2 20140511 ROM on my coconut with proper kernel too.
Please help me solve this issue ASAP.

**Comment by mikeNG** [comment]
Download the 20140512 build, it's fixed

**Comment by smultron-cm11** [comment]
I have the same problem on my device smultron
