### ISSUE TITLE
Random reboot-cm-11-20140512-anzu

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#597]
here is a kernel log(I will try to get more if it happens again)
http://pastebin.com/HPmTC2H6

It crashed randomly, first time when someone called, and second while browsing settings.
those are taken after reboot:
http://pastebin.com/1Yv4DZDL (dmesg)
http://pastebin.com/jvnUCPwp (logcat)

Sorry for my english.

**Comment by ksranjith786** [comment]
Iam facing similar issue while using Google Maps, accepting a call.

**Comment by ghost** [comment]
happened again
here is last_kmsg http://pastebin.com/ycaSSXUB
and logcat http://pastebin.com/E1AfpPF8

**Comment by emaijala** [comment]
Your last_kmsg doesn't look quite right. Maybe a file system problem?

Anyway, I've also encountered a couple of random crashes. Managed to get last_kmsg after a freeze and reboot when I was writing an SMS message. Here's the log: http://pastebin.com/0Jn7D0mG

**Comment by ghost** [comment]
What do you mean? 
I recently bought a new SD card and did fresh install.

**Comment by emaijala** [comment]
I mean http://pastebin.com/ycaSSXUB looks garbled to me.

**Comment by ghost** [comment]
cant even play a movie cuz it just restarts itself every time(im using mx player with 720p video) 
http://pastebin.com/CSLdfiwS
http://pastebin.com/mzEpwS4W

@emaijala, so what should I do?

**Comment by emaijala** [comment]
Sorry, I don't know. As I mentioned I've had a couple of crashes too, but yours looks different (this time the pastebin entry looks ok).

**Comment by xXZendomXx** [comment]
I have the same problem with the random reboots :/

**Comment by ksranjith786** [comment]
Hi LegacyXperia Team, Could you please provide patch fix for this bug.

**Comment by mikeNG** [comment]
http://forum.xda-developers.com/showpost.php?p=52711844&postcount=4057
