### ISSUE TITLE
cm-11.0-20140512 coconut I HAVE A QUESTION!

### ISSUE THREAD

**Issue by braianrq** [LegacyXperia/local_manifests#598]
I have questions. someone who has tested 11.0-cm-20140512 coconut, please tell me if they have already solved the problem of the large battery consumption, I am currently in the Android cm10.2 JB. if you have already fixed the problem then I will download and will install the newly released rom. 
Itself is very good rom cm11.0 only fucks KK battery. 
Please answer because I did not see this in the CHANGELOG.

**Comment by ghost** [comment]
Just create nandroid backup, change kernel, install new build and check. this page is for report issues, not questions
