### ISSUE TITLE
unable to open dialer

### ISSUE THREAD

**Issue by avinashrocks1990** [LegacyXperia/local_manifests#6]
Getting an error app isn't installed when opening the dialer

**Comment by avinashrocks1990** [comment]
logcat

https://docs.google.com/file/d/0B7z0NoNc5ecURDU0Z3dzQXZhS1E/edit?usp=sharing

**Comment by amishmm** [comment]
Delete that dialer icon.

Drag and drop PHONE app (which has same icon) from APP list.

**Comment by avinashrocks1990** [comment]
re flashed the rom the problem is solved but i reported so that the devs can look into the cause

**Comment by mikeNG** [comment]
Either make clean install or do what @ammdispose said above.
This solution is adviced by CM too https://plus.google.com/117962666888533781522/posts/VKPtc7DEYQy
