### ISSUE TITLE
[10.2] OTG flash drive mount issues

### ISSUE THREAD

**Issue by 7OH** [LegacyXperia/local_manifests#60]
"Build 20130908 - cm-10.1
##     Fixed USB OTG support"

OTG didn't worked. No mouse, no flash drives.

**Comment by pcfighter** [comment]
please paste output of "adb shell dmesg" after connecting USB acessory to phone on pastebin.com and paste link to it here

**Comment by 7OH** [comment]
http://pastebin.com/gw8g2VNA - after connecting flash
http://pastebin.com/nHVahmuZ - after disconnecting flash
http://pastebin.com/xzAGGxWJ - connected mouse

**Comment by pcfighter** [comment]
Seems that your flash drive is recognized properly, but it's not mounted, maybe. Check in file manager like totalcmd is there your flash drive appears. Connecting mouse causes drivers crashing, as I see. Try newer build and see if problem still persists (also make logs one more time for us)

**Comment by 7OH** [comment]
Do you mean (newer build) - "Nightly build 20130918 - cm-10.2" ?

**Comment by 7OH** [comment]
kernel 3.4.61 with cm10.1 - mouse working, flash - not. download cm10.2 for test

**Comment by pcfighter** [comment]
newer from cm-10.1, if it's released.

**Comment by 7OH** [comment]
no - we have no new release cm10.1 after 20130908 yet.

**Comment by pcfighter** [comment]
ok, so check for new "sda" drives after connecting flash. I think flash is properly initialized but it's not mounted, that's why it is not working.

**Comment by 7OH** [comment]
sorry - how to do check ? already connected to phone with flash connected via adb over network

**Comment by 7OH** [comment]
in /dev/block see sda and sda4

**Comment by pcfighter** [comment]
So u can mount it via shell or app like USB otg helper

**Comment by 7OH** [comment]
yes. helper mount succesfully (after looooong wait).
but problem is here. rom didn't recognize flash. and after dismount shows error "sdcard is missing".
So will waiting for fix.
If more logs needed - will send.

**Comment by pcfighter** [comment]
I have same problem with unmounting. It must be an app issue.

**Comment by mikeNG** [comment]
For me USB gets automatically mounted if I follow these steps:
1. connect the otg cable without anything attached on it
2. connect the usb stick to the otg cable
Then mounting/unmounting work fine from android's storage settings
Can you try this?

**Comment by 7OH** [comment]
cm-10.2_hallon-LX-20131112-NIGHTLY - still shows only on disconnect.

**Comment by mikeNG** [comment]
I cannot reproduce the issue, tried with 2 different OTG cables on all my 3 phones and 4 different flash drives.
10.1, 10.2 & 11.0 all work fine
