### ISSUE TITLE
Graphic related bug [CM11 Nightly Build20140512-Smultron]

### ISSUE THREAD

**Issue by JovieBrett** [LegacyXperia/local_manifests#601]
![](http://i.imgur.com/hIEXGSF.png)

Showing two screenshots from CM10.1 (last release build-left) and CM11 (latest release build-right). If you'll look on the magnified circle on CM11's screenshot, notice that it has a bad dithering quality of the surface of the wallpaper, unlike on CM10.1's screenshot it has a normal dithering look of the wallpaper. That is an issue since the first release of kitkat build and thought it will gonna be fixed with the help of ION kernel's new Adreno GPU libraries. Random high quality wallpapers has been tested but all of them has the same result, bad dithering surface. I also compared them on different launchers, the same output.
CM10-CM10.1 don't have this issue but as I remember, those previous builds with broken crt animation (like the previous PMEM builds of CM10.2 and CM11) have this issue, I'm not saying that they are related to the previous bug of crt animation, I just wanted to tell that these bugs appeared at the same time when the first kitkat build arrived.
Sorry for the bad english :/

**Comment by stefanverbeeck** [comment]
Could you try to set the wallpaper using Quickpick rather than the build-in gallery? I recall it always had better quality images.

**Comment by JovieBrett** [comment]
Nice! QuickPic app is a little buggy, got some FCs but it worked by setting
the wallpaper as Quickpic Wallpaper :)
Btw, so it means that there's something wrong about the Gallery and not the
Adreno Library's fault?

**Comment by stefanverbeeck** [comment]
It has always been like that. The stock gallery doesn't really preserve the quality when re sizing a pic as wallpaper, which is what happens on 4.4 (the wallpaper is less zoomed in as seen on your screenshot - thus looks worse).

**Comment by JovieBrett** [comment]
So does it mean that it happens on all devices with 4.4 on it? Or it's just
happening on our 2011 Semc devices? Hope there's a fix for this :/

**Comment by mikeNG** [comment]
I think it's an issue with all 4.4/cm11 devices, not device-specific to semc msm7x30

**Comment by JovieBrett** [comment]
@mikeNG ok, quick pic app fixed this issue through by setting a wallpaper there :) thanks!
