### ISSUE TITLE
Graphic Glitches [CM11 Nightly Build20140512-Smultron]

### ISSUE THREAD

**Issue by JovieBrett** [LegacyXperia/local_manifests#602]
![](http://i.imgur.com/a97cw6b.png)
Sometimes, rotating the device makes some glitches to appear. Sorry for the no-logs, I think this is not reproduceable on catlog.

**Comment by mikeNG** [comment]
still an issue?

**Comment by JovieBrett** [comment]
@mikeNG Nope, thanks alot!
