### ISSUE TITLE
CM11(Haida) Hight Battery Drain issue

### ISSUE THREAD

**Issue by pharandeamit** [LegacyXperia/local_manifests#603]
I'm using LX CM11 12-05-2014 since 2 days and i discovered that this build have high Battery drain as well same battery drain had in previous build too. Previously same apps used into Stock ICS but on ICS i every time got almost 1day & 10 hour Battery life & now on CM11 i'm not even getting 10 hours battery life... below is Log Cat of System download link.

Log Cat download link- http://d-h.st/SJr

Screen shot of Battery info.- http://postimg.org/image/r9n05zl0v/

Plz if possible increase the Battery Life of CM11 Roms...Thanks

**Comment by mikeNG** [comment]
https://github.com/LegacyXperia/Wiki/wiki/Reporting-problems
