### ISSUE TITLE
Nightly build 20140512 - cm-11. [Smultron] IN CALL UI NOT WORKING (FORCE CLOSE)

### ISSUE THREAD

**Issue by smultron-cm11** [LegacyXperia/local_manifests#606]
In call ui not working on my device st15i (smultron) I use the latest version of CyanogenMod Nightly build 20140512 - cm-11. [Smultron]

**Comment by mati865** [comment]
Don't open new issues just post comment here. 
We still need logcat to know something more. 
1. Make sure you have enabled USB Debugging in Developer Settings.
2. Connect your phone to the and start cmd.exe.
3. Type or paste following command " adb logcat -v long > logcat.txt".
4. Cause crash have described. 
5. Press Ctrl+c.
6. "logcat.txt" is saved where the cmd is pointing.
7. Upload it somewhere (pastebin is recommended site).
8. Post link to your logcat in comment.

I hope I'm clear enough.

**Comment by mati865** [comment]
Cannot edit comment. 

Point 2 should be:
"2. Connect your phone to computer the and start cmd.exe."

**Comment by smultron-cm11** [comment]
Yes i know, thanks brother.
