### ISSUE TITLE
android.process.media force close [CM11 Nightly Build20140512-Smultron] 

### ISSUE THREAD

**Issue by JovieBrett** [LegacyXperia/local_manifests#608]
After booting, android.process.media continuosly popping out. Rebooting the device makes the fc gone.
Log: http://pastebin.com/gDvzaSDD

**Comment by Harakhti** [comment]
Try dismounting and remounting the SD card in settings/storage. It might be similar to the issue on Samsung MSM7x27 devices if that works.

**Comment by ghost** [comment]
i had it earlier too
http://pastebin.com/rcqsdYgw

**Comment by xange** [comment]
direct to #491
