### ISSUE TITLE
Soft reboot [CM11 Nightly Build20140512-Smultron]

### ISSUE THREAD

**Issue by JovieBrett** [LegacyXperia/local_manifests#609]
So here's the scenario:
-Just using some apps 
-Suddenly the device lags and completely freezes
-The device soft rebooted (I thought my device got in bootloop because it took a very long time to soft reboot)
-After the boot, android.process.media and systemui continuosly force closes causing the device unusable to use so I hard reset it to be able to use the device again.
log: http://pastebin.com/6k2qjQDi
dmesg: http://pastebin.com/BAC5Vu7q

**Comment by xorgx3** [comment]
Exactly this same bug in coconut.
