### ISSUE TITLE
Bug while charging in CM-10.2 ( latest release build )

### ISSUE THREAD

**Issue by skarthiksankaran** [LegacyXperia/local_manifests#612]
Hi --

I am using the latest Release build of CM-10.2. I see that while charging when I type something eg., If I put the unlock code on my home screen, the values gets typed 2 or 3 times. instead of once. This happens even while messaging ( when charging is on).

**Comment by Norde** [comment]
I don't think this is a bug related to LegacyXperia but to your phone charger.

Some low-end chargers disturb the touchscreen.
Try to load the phone on a usb port of your computer.

**Comment by skarthiksankaran** [comment]
I am using the Sony Ericsson Original charger provided to me when the phone was bought. Does that mean that issue is not with the LegacyXperia Code and it is with the original charger that is being shipped with the Mobile Phone ? Should be crazy :)

**Comment by mikeNG** [comment]
This is an issue of the charger or the electric current of your region

**Comment by mikeNG** [comment]
Also, cm-10.2 is EOL, so I'm closing this issue
