### ISSUE TITLE
Random reboot + SystemUI freeze + Bluetooth [CM11 Nightly Build20140512-Coconut]

### ISSUE THREAD

**Issue by BRAiNCHiLD95** [LegacyXperia/local_manifests#613]
Issue 1:
Suddenly out-of-the-blue, my device reboots..1-2 times every hour of usage..and i get the android.process.media FC...which goes away with another reboot..

Issue 2:
Suddenly the device froze when I was using Whatsapp. It didn't soft reboot. I had to pull the battery out and reboot to get it working again..

Issue 3:
Bluetooth doesn't work for me..It doesnt turn on at all...here's what i did: Settings-> bluetooth->ON. go back, goto bluetooth again, and its OFF.. did this twice before taking the logs..here's seperate logs for the bluetooth issue..

http://forum.xda-developers.com/attachment.php?attachmentid=2745425&d=1400171051

here are the logs for issues 1 and 2 (taken via SysLog app)...

http://forum.xda-developers.com/attachment.php?attachmentid=2742837&d=1400047312

Issue 2 occurred again after clean install...here's the log..
https://s3.amazonaws.com/pushbullet-uploads/ujuWnwJYzwO-ymruKDuTNdghFNwyGAH2YiCLMMS20G1s/2014-05-16_14.02.zip

PS: Its my first time reporting on a bug tracker, i don't know if reporting all these together was a mistake..I apologize about that..:)

**Comment by sai0909** [comment]
Same Problem for me tooo...please fix the bugs soon n relase a new update..

**Comment by nguyentrunght** [comment]
same issue here for hallon.
System reboot randomly and must be pulled battery to reboot, or pop up a alert about com.android.systemiu has stopped, hope your team can fix this asap. rollback to 0319

**Comment by xange** [comment]
systemui crash is now fixed... check http://forum.xda-developers.com/showpost.php?p=52711844&postcount=4057 
(system ui memory leak fix)
about bluetooth I didnt really having trouble on hallon....

**Comment by mikeNG** [comment]
As mentioned above, systemUI is fixed now
Please file separage bugs for separate issues

**Comment by nguyentrunght** [comment]
Thank @mikeNG and @xange  for your effort.

**Comment by BRAiNCHiLD95** [comment]
Thanks alot @mikeNG and Sorry about the multiple bug reports..:) I'll post separate ones with newer logs whenever the issues occur..

PS: Did another clean install and Bluetooth works for now..:)

**Comment by nguyentrunght** [comment]
I confirmed about BT on my device (hallon cm11 20140512) work well with my
MW600 , now I can seek the song not like before.
BTW, I fix with the flashable file and for one day using , it does not
reboot any more.
