### ISSUE TITLE
CM11 big issue

### ISSUE THREAD

**Issue by Mohammad97** [LegacyXperia/local_manifests#618]
my contacts don't appear in whatsapp
and the calculator is not working it appear 189+151=2da what meaning that

**Comment by zweif** [comment]
You shouldnt open the same issue again and again. Your calculator simply is set to hexadecimal. And maybe whatsapp has no permission to view your contacs (see privacy guard).

**Comment by xange** [comment]
please close this issue if this has nothing to do with any part of the ROM system.....
