### ISSUE TITLE
[CM11][iyokan] 20140512. Enabling noise supression mutes mic(other party can't hear anything)

### ISSUE THREAD

**Issue by pteek** [LegacyXperia/local_manifests#619]
This feature was added in 20140512 and it does not seem to work.

Loud incall volume and noise suppression together makes a really great calling experience. Hoping this is a minor issue that can be fixed quickly.
Logs:
http://bayfiles.net/file/1el3L/hBawJ6/2014-05-19_18.54.zip

Last call before taking the log was with noise suppression enabled. It lasted 5 second and I replaced the number with private in the logs. I took log immediately after the call. The other side could not hear anything.

**Comment by mikeNG** [comment]
Closing this for now, reopen if the issue is still present in next build (probably released tomorrow)

**Comment by pteek** [comment]
Please reopen this as this is still present on 20140604.

I have noticed that noise suppression does work but the audio is not sent to other party.

There is a slight feedback of the mic in the headset. With noise suppression is disabled this is almost unnoticeable without headphones. But with noise suppression set to on, the faint feedback(echo) can be heard if listened carefully. This means the loudness of the voice is increased in comparison to the background.

Also, if when this starts working, I guess we should have a way to disable the mic feedback in the headset as it is distracting.

**Comment by pteek** [comment]
Reopen this please.

**Comment by pteek** [comment]
Working on 20140611.
