### ISSUE TITLE
torch blinks when notification leds changes state

### ISSUE THREAD

**Issue by marcopar** [LegacyXperia/local_manifests#621]
Device: urushi
Seen in:  cm-11.0-20140320 and cm-11-20140512

Switch on the torch, wait for a led notification to arrive.
Whenever the led changes state (on->off, off->on), the torch shuts down for the length of the state change (few tenth of seconds i guess)

**Comment by pteek** [comment]
This seems like a feature.

**Comment by badboyasd** [comment]
yes, me too

**Comment by marcopar** [comment]
it's pretty annoying when you are actually using the torch to see something, i don't think it's a feature

**Comment by mikeNG** [comment]
Not a feature

**Comment by mikeNG** [comment]
Relevant to #160

**Comment by mikeNG** [comment]
Should be fixed in latest build
