### ISSUE TITLE
[CM11]{NIGHTLY-20140512}[Anzu] - Battery Drain

### ISSUE THREAD

**Issue by sunekosuri** [LegacyXperia/local_manifests#622]
I have battery drain issue on my Arc S
I am using included Kernel and I think there is a problem with DEEP SLEEP. 
I have not done clean install, I just formated /system /cache and /dalvik. The /data and /.android-secure folder was left untouched. LOG FILES (logcat, dmesg and battery stats) below.
LOGCAT
http://pastebin.com/DiLHTzWw

DMESG
http://pastebin.com/1N8WENHJ

Better Batery
http://pastebin.com/0Yd4EWqP

**Comment by godlesplay** [comment]
paste logs to pastebin.com not here...

**Comment by sunekosuri** [comment]
ok, should I move logs from above to paste bin and delete from here?

**Comment by azakosath** [comment]
@sunekosuri, yes you should!
I can see that you have the following partial wakelock:

GpsLocationProvider (0): 11 h 3 m 40 s (39820 s) Count:0 97,2%

which is a common problem since CM10 and is generated after you turn off location. There are not any fixes available and the only solution is to reboot your phone, or not to turn off location.

Cheers

**Comment by sunekosuri** [comment]
Ok, you mean switch on GPS (Hardware) or could it be left on Battery saving (WiFi + network)?
And one another thing, there Was no battery drain in last version of CM11 available (2014-03-19) (GPS settings similar).

**Comment by godlesplay** [comment]
if you turn on gps:
- don't turn it off
- turn it off and reboot

**Comment by azakosath** [comment]
There are no exact steps to recreate this wakelock and it's not generated every time. Even if you turn off GPS and let only Battery saving on, the wakelock may start. On the other hand if you turn off Battery saving and use only GPS there is another wakelock that can be created, NlpLocationProvider, if I remember correctly. Every time I use "location" (usually I let it on until next reboot), if I turn it off, I set a custom reference on BBS and I check it after some time, if the wakelock is there, I simply reboot my device.

**Comment by sunekosuri** [comment]
Ok, so if this is know issue, please mark it appropriately and close.

**Comment by azakosath** [comment]
Actually, it has been reported before:
#161 , #243 

Either you or Mike can close this issue.

**Comment by sunekosuri** [comment]
I will close as it is duplicated and won't probably be fixed.
Thanks for comments I will try to avoid changing GPS from settings.

**Comment by mikeNG** [comment]
I have included a possible fix in the latest builds, if anyone still uses LX please test if this is fixed

**Comment by godlesplay** [comment]
it is working fine IMO,but today I will try again and give you feedback

**Comment by godlesplay** [comment]
so I can confirm that there are no battery drain after disable GPS (without restart of course) so miracle happened ;)
