### ISSUE TITLE
reboot after launch google play cm-11-20140512-UNOFFICIAL-LegacyXperia-coconut

### ISSUE THREAD

**Issue by godlesplay** [LegacyXperia/local_manifests#623]
logs from lx center here: http://forum.xda-developers.com/showpost.php?p=52844036&postcount=4187

**Comment by zweif** [comment]
Could be the same problem like here: https://github.com/LegacyXperia/local_manifests/issues/403
There's an issue with wifi driver.

**Comment by mikeNG** [comment]
Duplicate of #403
