### ISSUE TITLE
[CM11] Can't lock the screen by power button

### ISSUE THREAD

**Issue by v6ak** [LegacyXperia/local_manifests#624]
Is used to work, but it has stopped after a reboot.

```
Given the screen is on
When I press the power button
Then there is no change in UI
And nothing is appended to adb lolcat
And following line is added to dmesg:
"""<3>[ 2525.099121] simple_remote_pf simple_remote_pf.0: simple_remote_pf_button_handler - Button callback not registered"""
```

Note that it sometimes suddenly starts working without any apparent reason. In such case, it works _until_ reboot.

It does not look as a hadware failure, because:

```
Given the screen is on
When I hold the power button
Then the menu is shown as expected
```

**Comment by rtammekivi** [comment]
Can you confirm whether the power button starts working a while after reboot?

**Comment by godlesplay** [comment]
in mine lww I can't lock screen via power button 10 sec after end of bootanimation, after that when all apps run I can lock screen normally

**Comment by v6ak** [comment]
When I wait many minutes, it does not help. Note that even statusbar doubletap does not seem work, but maybe I can't make the correct doubletap.

It seems that it only starts working after I run Standby Touch ( https://play.google.com/store/apps/details?id=com.alinberce.standbytouch ).

a. It sometimes works correctly. In that case, everything (power button and statusbar doubletap) is OK until reboot.
b. But sometimes it just locks the screen and keeps it on. Power button and doubletap still don't work.

**Comment by mikeNG** [comment]
still an issue?
