### ISSUE TITLE
I cannot make a call or receive a call

### ISSUE THREAD

**Issue by bgokul95** [LegacyXperia/local_manifests#625]
Xperia Neo V (Haida)
cm 11
1.I have installed re-installed cm 11 many times(even the updated versions), but there is one great issue. I cannot make phone calls. If i do, the network signal goes low. When someone calls me, I could not see the incoming call in my screen, all the caller says is the ring is automatically disconnected. It says "Dialer has stopped". Someone was also having this same issue(Xda thread:http://forum.xda-developers.com/showthread.php?t=2543426&page=419) (POST#4185).Please fix it, I ve seen it several times.
2.Another one is When I click my Home button(middle bottom button) , the display screen shows the leftmost page(what we call screen), but the requirement is I want my middle page. Suppose I am having 3 pages on my home screen, when i click the home button, it moves to the 1st page(to the left), I need the 2nd page(middle) to be there.
3. In settings>under personalization we ve only few things ,like "homescreen" missing(10.2 has it) and many other.
4.Wifi is not working properly sometimes. I mean it doesnt give the constant wifi signal.
5.Video recorded via camera is of poor quality(with lots of noises).
Thank You. I think You look forward this issue and give me a solution.  
PS: Currently I am using 10.2 since I had that call issue, I shifted from cm 11 to cm 10.2. Thank you Legacy Xperia, 10.2 is brilliantly good, but I would like to have the latest kitkat ;).

**Comment by pcfighter** [comment]
Did you done factory reset/wipe after installing ROM ?

**Comment by bgokul95** [comment]
Why did u close this??

**Comment by bgokul95** [comment]
Ya .. Still I had the problem..
