### ISSUE TITLE
Reboot after unlock screen-cm-11-20140512-anzu

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#626]
http://pastebin.com/8t6uLedd
http://pastebin.com/xVHSDknK
after I unlocked the phone and opened opera mini it just crashed(I already did memory leak fix)

**Comment by pcfighter** [comment]
it seems that program last using root permissions caused exception ended with a reboot

**Comment by mikeNG** [comment]
Soft or hard reboot? If it's a hard reboot, please provide last_kmsg logs next time it happens

**Comment by ghost** [comment]
hard reboot, thought it didn't happen so far
