### ISSUE TITLE
[CM11 - SK17 mango] Native Internet Call freeze phone app 

### ISSUE THREAD

**Issue by glococo** [LegacyXperia/local_manifests#629]
When make a phone call, ask over Internet or Mobile networks. I chose Internet and then call time start instantly without ringing and if you touch END (big red button), app freeze.

This problem is related to cm-11-20140512-UNOFFICIAL-LegacyXperia-mango.zip.
In cm-11.0-20140320-NIGHTLY-LegacyXperia-mango.zip there is no problem. 

(tried cache, dalvik, app & data clear) No luck, :(

**Comment by mikeNG** [comment]
no logs
