### ISSUE TITLE
[CM11.0][smultron] wifi doesn't work

### ISSUE THREAD

**Issue by robertolos** [LegacyXperia/local_manifests#630]
I've download the latest release cm-11-20140601-UNOFFICIAL-LegacyXperia-smultron.zip, installed as usual (but now I come from CM10.2):
- flashing kernel fastboot flash boot boot.img
- wipe everithing /system /data /cache factory reset
- installed new release zip and gapps.

After the reboot the wifi doesn't work. If I click on the wifi swipe button in the settings, this remains grey and the wifi networks are not shown.

**Comment by pcfighter** [comment]
check if you flashed proper kernel (from zip package)

**Comment by robertolos** [comment]
yes I'm sure. I've tried to revert to the stock kernel through FlashTool and the reinstall the last CM11 but always the same problem with the wifi. With an oldest version the wifi works fine.

**Comment by pcfighter** [comment]
provide dmesg log

**Comment by robertolos** [comment]
In order to provide the dmesg log I've to install  cm-11-20140601 run it and execute the dmesg command in the terminal emulator?

**Comment by pcfighter** [comment]
better plug phone with usb to pc and paste the "adb shell dmesg" output (adb must be installed on pc) on pastebin and paste link here. also u can of course execute dmesg on terminal emulator (good forward output to file, for example:

dmesg >> /sdcard/dmesg.log

and then paste dmesg.log on pastebin and paste link
