### ISSUE TITLE
Nightly build 20140531 - cm-11.0 [Haida] Sound doesnt work

### ISSUE THREAD

**Issue by anilgupta003** [LegacyXperia/local_manifests#631]
Sound doesnt work during incoming call though it works when you call someone. Unable to hear any sound when playing music in appolo player as well as playing video in  gallery.

**Comment by anilgupta003** [comment]
Log Cat - http://tny.cz/0db99a6a

**Comment by mikeNG** [comment]
0531 will be removed, new builds to be released soon
