### ISSUE TITLE
Wifi does not work on 802.1x EAP

### ISSUE THREAD

**Issue by natanE** [LegacyXperia/local_manifests#632]
re-opening this issue after some more debug. i now using latest CM11.0 nightliy for coconut (UNOFFICIAL one), but this issue has started long ago in CM10.2

i've sat with our work expert and saw that the wpa_supplicant doesn't respond to the RADIUS server request:

I/wpa_supplicant(  774): wlan0: CTRL-EVENT-SSID-REENABLED id=1 ssid="EmployeeHotspot"
I/wpa_supplicant(  774): wlan0: SME: Trying to authenticate with 68:bd:ab:49:ec:e5 (SSID='EmployeeHotspot' freq=2462 MH
)
I/wpa_supplicant(  774): wlan0: Trying to associate with 68:bd:ab:49:ec:e5 (SSID='EmployeeHotspot' freq=2462 MHz)
I/wpa_supplicant(  774): wlan0: Associated with 68:bd:ab:49:ec:e5
I/wpa_supplicant(  774): wlan0: CTRL-EVENT-EAP-STARTED EAP authentication started
I/wpa_supplicant(  774): wlan0: CTRL-EVENT-EAP-PROPOSED-METHOD vendor=0 method=25
I/wpa_supplicant(  774): wlan0: CTRL-EVENT-EAP-METHOD EAP vendor 0 method 25 (PEAP) selected
I/wpa_supplicant(  774): wlan0: CTRL-EVENT-DISCONNECTED bssid=68:bd:ab:49:ec:e5 reason=3 locally_generated=1
I/wpa_supplicant(  774): wlan0: CTRL-EVENT-SSID-TEMP-DISABLED id=1 ssid="EmployeeHotspot" auth_failures=2 duration=20

**Comment by pcfighter** [comment]
maybe this can be useful 

http://azitech.wordpress.com/2010/02/22/deauthenticating-reason3/

**Comment by theblackhole** [comment]
Same issue on anzu device.

**Comment by choffm** [comment]
I have the same issue with a mango device. WPA2 Personal networks work fine, WPA2 Enterprise / 802.1X EAP networks do not work. Let me know which log or debug files are useful to fix this issue.

**Comment by highman** [comment]
I have the same issue with a hallon device. WPA2 Personal networks work fine, WPA2 Enterprise / 802.1X EAP networks do not work. I'm using the cm-11-20140703-UNOFFICIAL-LegacyXperia-hallon build.

**Comment by mikeNG** [comment]
Unfortunately I don't have access to any EAP network, so it's really hard to debug this issue

**Comment by ifcaro** [comment]
**11-20140907-UNOFFICIAL-LegacyXperia-hallon**

I/wpa_supplicant(20085): wlan0: CTRL-EVENT-SCAN-STARTED 
I/wpa_supplicant(20085): wlan0: SME: Trying to authenticate with xx:xx:xx:xx:xx:xx (SSID='WIFIUPM' freq=2437 MHz)
I/wpa_supplicant(20085): wlan0: Trying to associate with xx:xx:xx:xx:xx:xx (SSID='WIFIUPM' freq=2437 MHz)
I/wpa_supplicant(20085): wlan0: Associated with xx:xx:xx:xx:xx:xx
I/wpa_supplicant(20085): wlan0: CTRL-EVENT-EAP-STARTED EAP authentication started
I/wpa_supplicant(20085): wlan0: CTRL-EVENT-EAP-PROPOSED-METHOD vendor=0 method=21
I/wpa_supplicant(20085): wlan0: CTRL-EVENT-EAP-METHOD EAP vendor 0 method 21 (TTLS) selected

_and no more wpa_supplicant log._

**Connecting with other device to the same network**

I/wpa_supplicant(19980): wlan0: CTRL-EVENT-SCAN-STARTED 
I/wpa_supplicant(19980): wlan0: Trying to associate with xx:xx:xx:xx:xx:xx (SSID='WIFIUPM' freq=2412 MHz)
I/wpa_supplicant(19980): wlan0: Associated with xx:xx:xx:xx:xx:xx
I/wpa_supplicant(19980): wlan0: CTRL-EVENT-EAP-STARTED EAP authentication started
I/wpa_supplicant(19980): wlan0: CTRL-EVENT-EAP-PROPOSED-METHOD vendor=0 method=21
I/wpa_supplicant(19980): wlan0: CTRL-EVENT-EAP-METHOD EAP vendor 0 method 21 (TTLS) selected
I/wpa_supplicant(19980): wlan0: CTRL-EVENT-EAP-PEER-CERT depth=3 subject='/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root'
I/wpa_supplicant(19980): wlan0: CTRL-EVENT-EAP-PEER-CERT depth=3 subject='/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root'
I/wpa_supplicant(19980): wlan0: CTRL-EVENT-EAP-PEER-CERT depth=2 subject='/C=US/ST=UT/L=Salt Lake City/O=The USERTRUST Network/OU=http://www.usertrust.com/CN=UTN-USERFirst-Hardware'
I/wpa_supplicant(19980): wlan0: CTRL-EVENT-EAP-PEER-CERT depth=1 subject='/C=NL/O=TERENA/CN=TERENA SSL CA'
I/wpa_supplicant(19980): wlan0: CTRL-EVENT-EAP-PEER-CERT depth=0 subject='/OU=Domain Control Validated/CN=uac.upm.es'
I/wpa_supplicant(19980): wlan0: CTRL-EVENT-EAP-SUCCESS EAP authentication completed successfully
I/wpa_supplicant(19980): wlan0: WPA: Key negotiation completed with xx:xx:xx:xx:xx:xx [PTK=CCMP GTK=CCMP]
I/wpa_supplicant(19980): wlan0: CTRL-EVENT-CONNECTED - Connection to xx:xx:xx:xx:xx:xx completed (auth) [id=1 id_str=]

**Comment by mikeNG** [comment]
So, I just made some reading and I see that android does not officially support LEAP but only EAP/TLS (802.1x EAP). This combined with me not having access to such a network makes it impossible to debug/fix. Someone with better knowledge and access to EAP networks needs to step in here if we want this fixed. I'm marking this as wontfix for now.

**Comment by mikeNG** [comment]
You are trying to connect using LEAP or EAP/TLS method?

**Comment by ifcaro** [comment]
Security: 802.1x EAP 
EAP method: TTLS 
Phase 2 authentication: PAP

**Comment by mikeNG** [comment]
On #376 @pteek & @sdk16420 report success on connecting to both PEAP/MSCHAPV2 & TTLS.
Have things changed since then? If no, I'd like to hear how you got it working

**Comment by fqdb** [comment]
Connection still works fine, using the september 7 build on hallon. I am only using PEAP and MSCHAPV2 however, so I will try TTLS,PAP tomorrow to be sure. (edit: in my comment in #376 I said TTLS didn't work, anyway, I'll try again) Is everyone having this issue trying it on PEAP if possible?

I can take a log of succesfully connecting if it would be helpful.

**Comment by fqdb** [comment]
Succesfully connecting using PEAP
http://pastebin.com/cZsQUquh

Failure using TTLS
Action from line 19780. There isn't much to see in the log i think...
http://pastebin.com/6t72pgip

**Comment by rufussino** [comment]
Encryption: WPA-Enterprise
Security: 802.1x EAP 
EAP method: PEAP 
Phase 2 authentication: MSCHAPv2

Not working on actual unofficial build, logs here: https://dl.dropboxusercontent.com/u/1854214/bugreport.zip

But now I am living at dormitories where I have constant access to this network, so I might be able to help.

**Comment by rohitdhavale** [comment]
I'm able to connect to 802.1x EAP WiFi network with 20150309 build.

**Comment by ifcaro** [comment]
I am also able to connect with that build.

**Comment by mikeNG** [comment]
I am closing this for now since I got other reports that were successful too
