### ISSUE TITLE
Random soft reboot [CM11 Nightly build 20140603-Smultron]

### ISSUE THREAD

**Issue by JovieBrett** [LegacyXperia/local_manifests#634]
A while ago, the device suddenly soft rebooted for some reason while it is off (sleep state)
I tried to trigger the soft reboot issue by stressing the device (opening some huge apps)
Luckily, I managed to catch up the log, the device went really unresponsive, touching the screen won't react on any matter and it went soft rebooted by itself.
Here's the log: http://pastebin.com/91vw9BB6

**Comment by mikeNG** [comment]
still an issue?

**Comment by JovieBrett** [comment]
@mikeNG nope! thank you!
