### ISSUE TITLE
No offline charging animation [CM11 Nightly build 20140603-Smultron]

### ISSUE THREAD

**Issue by JovieBrett** [LegacyXperia/local_manifests#636]
I don't know if I can get a log about the 'missing' offline charging animation :/
But recently, just found out that there's no offline charging animation when my device is in offline charging.

**Comment by mikeNG** [comment]
Well the only thing that changed is the new offline charging images...

**Comment by JovieBrett** [comment]
@mikeNG when the device is charging in offline mode, the screen doesn't light up (even if the device doesn't have offline charging images, the device's screen should still lit up but only with blank screen, I'm not sure about that but that's what I saw when I'm testing those new images on the previous 5/12 nightly)

**Comment by krikoCodeCook** [comment]
I can confirm this on haida device - screen goes off after kernel logo and charging animation is not displayed.
NOTE: the charging animation is also gone in 28.5.2014 build, but it works fine in 24.5.2014 kernel build.

**Comment by JovieBrett** [comment]
The new offline charging images are there on the chargemon directory, weird doesn't show up when the device is connected to the power while it's on offline mode.
Anyway, these new images are tested on 5/12 build and it's working normally, maybe something's touched that is causing the offline charging images to not appear.

**Comment by theblackhole** [comment]
Same here on anzu device.

**Comment by krikoCodeCook** [comment]
Reverting this patch: https://github.com/LegacyXperia/android_device_semc_msm7x30-common/commit/533e90c57681f61048c06c472e14ff809624bb9b

seems to fix the issue for me (haida).

**Comment by krikoCodeCook** [comment]
I've compiled kernel now with 3 variations:
- stock source
- removed blanking altogether (reverting mikes patch https://github.com/LegacyXperia/android_device_semc_msm7x30-common/commit/533e90c57681f61048c06c472e14ff809624bb9b)
- applied patch: https://github.com/arco/android_device_samsung_ancora/commit/ca24c86bd395b85144c31c89319c257761fcf612

Results:
- stock: no charging animation
- removed blanking: animation works
- with external patch ca24c86: animation works

This patch could be a good compromise between bootlogo showing up on some activities while launching them and charging animation.

Tested on haida device.

**Comment by FibreFoX** [comment]
I can confirm this bug on Anzu too, fresh cm11-install, using cm-11-20140531-UNOFFICIAL-LegacyXperia-anzu, offline-charging-animation not visible

**Comment by mikeNG** [comment]
Will be fixed in next build
