### ISSUE TITLE
Iyokan not booting at all

### ISSUE THREAD

**Issue by DoctorWAT** [LegacyXperia/local_manifests#637]
Hi there!

I recently flashed your CM11 (20140512) on my old Iyokan. I precisely followed the steps. It worked and booted, but because the keyboard kept crashing and the battery state was 1% constantly although the battery was fully loaded, I decided to switch back to your CM10.1 (20140303), which I had on this very same phone before and worked fine.

So I flashed the boot.img for the CM10.1 on my phone and rebooted, but this time it wouldn't boot into recovery. It's not booting at all. Just the LegacyXperia logo shows up, disappears after a few seconds and leaves a black screen (still with background lighting on). And that's it. I tried flashing the very same CM11 again, including the corresponding kernel, since it seemed to work before, but the only thing I've achieved by that is that the LegacyXperia logo has changed to the newer version.

You can imagine that because I didn't get the phone to start the OS, I have no logs whatsoever. I was just hoping you could give me a hint what could be causing this problem. I want to get this phone up an running to give it to my friend and I don't want to disappoint her. So please forgive me that this issue report may not be exactly how you'd like it to be, because I really need you help! I couldn't find an answer by myself.

I honestly don't care which version is running on the phone as long as it's running. I just want it to work, whether it's CM10 or CM11.

Thank you very much in advance!

The Doctor ;-)

**Comment by mikeNG** [comment]
You can find instructions on how to return to older android versions after flashing cm11 in the wiki.
