### ISSUE TITLE
Incoming calls can not be answered while in landscape mode [mango]

### ISSUE THREAD

**Issue by osmank3** [LegacyXperia/local_manifests#638]
I'm using latest(2014/06/04) unoffical mango rom
Incoming calls can not be answered while in landscape mode
It is showing "com.android.incallui stopped" error message, it is crashing all system's theme

**Comment by mikeNG** [comment]
Provide logcat or this will be closed as invalid

**Comment by osmank3** [comment]
This error occurs only when the keyboard is open. I try compile rom myself, it is compiled and error continues.
Logs are here https://db.tt/8AdNRhgk

**Comment by zweif** [comment]
```
E/AndroidRuntime(11242): Process: com.android.incallui, PID: 11242
E/AndroidRuntime(11242): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.dialer/com.android.incallui.InCallActivity}: android.view.InflateException: Binary XML file line #53: Error inflating class fragment
...
E/AndroidRuntime(11242): Caused by: java.lang.ClassCastException: android.widget.Button cannot be cast to android.widget.ImageButton
E/AndroidRuntime(11242):    at com.android.incallui.CallButtonFragment.onCreateView(CallButtonFragment.java:164)
```

I think it's line 90 in this file:
https://github.com/CyanogenMod/android_packages_apps_InCallUI/blob/cm-11.0/res/layout-land/call_button_fragment.xml
which schould be an ImageButton like here (line 197):
https://github.com/CyanogenMod/android_packages_apps_InCallUI/blob/cm-11.0/res/layout/call_button_fragment.xml

I'll try to test it when I have time.

**Comment by zweif** [comment]
I was building few days ago and didn't sync since that. I tried to only build InCallUI and replace it in system, but that didn't help. So I decided to make a new build (with sync) and it works.
Will be fixed soon: http://review.cyanogenmod.org/#/c/65501/

~~An other problem is that Dialer doesn't work in landscape.~~ fixed: http://review.cyanogenmod.org/#/c/65502/

I think this issue can be closed.

**Comment by mikeNG** [comment]
Will be fixed in next build
