### ISSUE TITLE
Flashlight only works with screen on

### ISSUE THREAD

**Issue by hawrehas** [LegacyXperia/local_manifests#64]
Flashlight only works with screen on. Switches off some seconds after screen turns off.  When I wakeup my phone again the flashlight is still showing that it is switched on in the notification bar, but actually it's not.
I think it's a bug, not a feature, right? ;)
Using latest (20130918) cm10.2 build on smultron. Should I make a log or something?

**Comment by mikeNG** [comment]
It's a bug and I'm trying to figure out how to fix it. If there's no easy way I will have to disable death ray mode in order to restore the previous behaviour

**Comment by Klami** [comment]
I have no Problems with the Flashlight. If I turn on the Light the screen keep always on and if i shut down the screen manually it's still lighting.

**Comment by mikeNG** [comment]
@Klami device?

**Comment by Andrewas** [comment]
This is happening when death ray mode is enabled or even with normal flashlight?

**Comment by Klami** [comment]
I'm using Normal Flashlight on anzu latest cm10.2 (18/09/2013)

Edit: Date was false ;-) it's the latest

**Comment by hawrehas** [comment]
@Klami 19/08/2013 is not the latest version. seems like the bug is caused by enabling "Death Ray torch mode", which is only present since 2013/09/18.

@Andrewas: in both, but seems like mike fixed it anyway for the upcoming releases

And mike, shouldn't the changelog  of the 201309xx cm10.2 include the latest changes of cmn10.1 too? I guess you just didn't update them yet, right? Sorry for stupid question ;)

**Comment by mikeNG** [comment]
I'm working on 10.1 now, the changes will be applied to 10.2 at a later time because I have limited free time

**Comment by mikeNG** [comment]
Fixed in next build
