### ISSUE TITLE
music drop after 1 sec cm-11-20140604-UNOFFICIAL-LegacyXperia

### ISSUE THREAD

**Issue by godlesplay** [LegacyXperia/local_manifests#640]
as in title, on previous build 12.05 everything was ok, now with headset or on speaker after 1sec I can't hear anything, logs while "listening" music

http://www44.zippyshare.com/v/79774961/file.html

I hope you will fix it, regards

**Comment by Vynikal** [comment]
Temporary solution - delete SoundEnhancements.apk
Haven't found any other fix yet...

**Comment by mikeNG** [comment]
Do not report issues with mods installed
