### ISSUE TITLE
Phone shows contact name in incoming call after a very long delay, if even...

### ISSUE THREAD

**Issue by Itchythefirst** [LegacyXperia/local_manifests#641]
Hello, I have the Nightly build 20140603 - cm-11.0 installed on my iyokan. When someone is calling me, the phone really often does not show the contact name, it shows just phone number. It can take more than 10 seconds to show the name, if even. I have not installed many(<20) app. I use the interactive CPU governor with min. freq.: 122MHz and max. freq.: 1401MHz, so the phone response should be(and it is!) quite good...

**Comment by TechExhibeo** [comment]
yeah same thing happens with me in xperia mini pro in 20140320-cm11 build :/ i dont know why :(

**Comment by ghost** [comment]
Well nobody will ever know unless you give a logcat!

**Comment by Itchythefirst** [comment]
2 konstantinosj77 : You are absolutely right, but this behavior is not easily reproducible :-( Next time I will definitely provide the logs...
