### ISSUE TITLE
[CM11 20140604][urushi] Snapchat can't record video with rear camera.

### ISSUE THREAD

**Issue by johnnytifosi** [LegacyXperia/local_manifests#642]
Front camera works however.
https://www.dropbox.com/s/9jcgjgmdcg861px/bugreport.zip

**Comment by johnnytifosi** [comment]
In the last two nightlies even the front camera doesn't work, and Snapchat displays "Can't play this video".
https://www.dropbox.com/s/30mrrjxuuy37wsp/bugreport2.zip

**Comment by mikeNG** [comment]
Still an issue? guess I have to install snapchat to test -_-
