### ISSUE TITLE
Backup & reset, unable to select the backup account

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#644]
ROM: cm-11-20140603-UNOFFICIAL-LegacyXperia-anzu
Device: Sony Xperia Arc S
Flashed boot and factory reset the phone.

This is not terribly important, and I am sorry if I'm reporting something that wasn't planned, but I just performed Factory Reset on my phone and discovered that the backup wasn't there :(. Furthermore, there was no option to select the account for backup. I did select the backup option during initial account setup, but to no avail. See the screenshot.

![2014-06-06 10 02 21](https://cloud.githubusercontent.com/assets/7814432/3199058/b1994c56-ed62-11e3-983a-c24438eada41.png)

**Comment by mikeNG** [comment]
I can't reproduce this when performing factory reset & adding an account on setup wizard. My account shows up fine in that menu

**Comment by ghost** [comment]
I've noticed it's fixed in the version 11-2014-UNOFFICIAL-LegacyXperia-anzu
which I'm using now. I can define an account just fine now. Thanks.
