### ISSUE TITLE
Issue with messaging (cm-11-20140512-UNOFFICIAL & cm-11-20140604-UNOFFICIAL)

### ISSUE THREAD

**Issue by Michalis-Mich** [LegacyXperia/local_manifests#645]
I'm using Sony Ericsson Live With Walkman (coconut) and after my update to the versions I mentioned at title I'm having an issue with messaging. Every time I try to send a message (via the Messaging app) it will ask me for permission as it is showed in the screenshots. It's kinda frustating if you're trying to send a big number a messages.
![mess](https://cloud.githubusercontent.com/assets/7819202/3205897/441fb3f8-edbd-11e3-8053-e6c8213c9a71.jpg)
The permissions of the Messaging app can be changed but it won't have any effect and it'll auto change to "Ask" at the next time you're gonna send a message.
![perm](https://cloud.githubusercontent.com/assets/7819202/3205906/6c972d84-edbd-11e3-9980-016f6e3c746b.jpg)
At previous versions I didn't have any problems.

**Comment by azakosath** [comment]
Settings/security/SMS message limit

The default is 30 and this option was always there.

**Comment by Michalis-Mich** [comment]
I always put it to "None" so I guess it's not that.

Attempted to send with limit 200 but nothing changed.

**Comment by Michalis-Mich** [comment]
Problem fixed at cm-11-20140610-UNOFFICIAL with setting message limit at a value.

Closing topic...
