### ISSUE TITLE
Location based on Wi-Fi not working

### ISSUE THREAD

**Issue by tomasSK** [LegacyXperia/local_manifests#646]
location based on Wi-Fi not working.
device: iyokan
build: cm-11-20140604-UNOFFICIAL-LegacyXperia-iyokan.zip
kernel: from zip
description: location settings are OK - all turned ON.

**Comment by krikoCodeCook** [comment]
I cannot remember how it used to work in stock rom, does wifi based location fix it "instantly"?
E.g.: when you launch maps with battery saving location mode it should display your approximate location in about few seconds?

I remember that my router is correctly mapped to my house, however with LX it seems that GMaps prefer network based geolocation, showing I'm around a cell tower - kilometers away.

**Comment by tomasSK** [comment]
This is now fixed in latest build: Nightly build 20140702 - cm-11.0
