### ISSUE TITLE
Bad gsm reception

### ISSUE THREAD

**Issue by DanielMalmgren** [LegacyXperia/local_manifests#65]
This has been discussed in the Urushi thread. At least three users reported it there, seems nobody ever did a proper report though. So here goes:

Since upgrading from LX10.1 to 10.2 there is some problem with GSM reception. At home I get no reception at all, it's usually almost full. I've never had any 3G coverage at home though, so I don't know if this is a problem with GSM only areas? For example at work everything works fine.

I'm now on 20130918 release and the problem persists. Running on a Xperia Ray. Not really sure on how to provide any useful information on this one.

**Comment by JovieBrett** [comment]
I'm also having this issue with my Smultron [CM10.2 Build0918]
It happens but not too frequently occuring. Last night when I checked my device, I got no reception, the signal was blank (I'm on 2G network mode) when I try to switch to the other network modes (2G/3G and 3G network modes), still the 2G network mode in quicktile notification panel is not changing. Before I decided to reboot, I noticed in Power Menu that the device is in airplane mode and gone crazy O.o
I tried to turn off the airplane mode but it wasn't really turning off, just weird so I rebooted the device and then situations are now running good.

**Comment by mikeNG** [comment]
I don't use 10.2 daily so I can't comment on the issue yet, but I saw that RIL is crashing constantly in my dev phone. Better get some logs (also radio logs) to see if there is any hint about the problem

**Comment by DanielMalmgren** [comment]
You don't use 10.2 daily? That's a shame, it's really a great rom ;-)

Anyways, I don't know really which log to provide since this isn't something that happens on a specific time but rather all of the time. But I'll be happy to give you logs if you tell me what could be useful.

**Comment by DanielMalmgren** [comment]
I don't know if this is relevant, but since installing the latest nightly it has happened to me once or twice every day that my phone asks me for sim unlock pin when I take it out of my pocket.

**Comment by jlmcr87** [comment]
I have this problem with my anzu, signal is very bad and fluctuates a lot.

**Comment by jlmcr87** [comment]
Maybe this is connected with the thread i opened yesterday, 2g data interruptions

**Comment by jlmcr87** [comment]
I have to return to cm10.1 due to low signal in cm 10.2.

CM10.2 :- 99dbm
CM10.1: -67dbm

**Comment by DanielMalmgren** [comment]
I don't know about the rest of you, but I've noticed much better reception in last nightly, I would say that it's now back to normal levels.

**Comment by jlmcr87** [comment]
Solved in the latest release

**Comment by mikeNG** [comment]
So I'm closing this for now
