### ISSUE TITLE
CM11 cLock keeps waking up the device at constant intervals (only on WIFI).

### ISSUE THREAD

**Issue by pteek** [LegacyXperia/local_manifests#650]
Does not happen on data at all. I have been experiment with this since PMEM build.

Happens only on wifi and not every time. Here is a screen shot.
![screenshot_2014-06-08-09-48-08](https://cloud.githubusercontent.com/assets/6537027/3211917/aaafbe48-ef38-11e3-8843-6baac526941e.png)

I also had had another one which I lost, I will explain that one in words.

SEPARATE INCIDENT, LOST SCREENSHOT:

I 100% charged the battery. Turned on wifi and left the phone. At 82% there are 3 long interval of awake. I reboot the device. at about 70% there are 3 more. I turn off wifi. There are none till 65%. I turn on 3G data. There is no unwanted awake till 48%. I turn off 3G and turn on wifi. At 44% there is another long awake interval. BBS and android battery usage both shows it cLock.

I will try to get some relevant logs.

Edit: got some logs.

![screenshot_2014-06-12-19-08-05](https://cloud.githubusercontent.com/assets/6537027/3263573/ace20e8a-f273-11e3-96d5-88164ce6e9a8.png)

The last three long awake times. That is cLock. The logs were taken immediately after waking up teh device after a long time and checking the battery tab.

http://bayfiles.net/file/1fXXx/sCjUWw/bugreport.zip

The problem did not return after this.

**Comment by godlesplay** [comment]
try to disable weather in clock settings

**Comment by pteek** [comment]
Well I want the weather to be updated every hour.

**Comment by pteek** [comment]
logs added

**Comment by mikeNG** [comment]
still an issue?

**Comment by pteek** [comment]
I blocked wakeup of cLock after reporting the issue. I will test on dirty and new installs of 718 and report back.

**Comment by pteek** [comment]
Happened again on my home Wi-fi. But, since the last 11 days I was using a different TP-link hotspot. This did not happen even once with that.

So this is probably something specific to my setup or router. Still, if I could know why it happens or if it can can be fixed in the ROM or in my wifi config, that be great.

http://pastebin.com/6HnJE496 kmsg
http://pastebin.com/eqQh3yTz logcat

**Comment by pteek** [comment]
Still present on 814. This is the second boot and I have only setup a Google account.

http://www.datafilehost.com/d/edeb83d9

On the good side of things, the second boot was very quick.

**Comment by pteek** [comment]
To help you reproduce this if you have got the time.

In my scenario, I have a wifi router acting a simple bridge. It is connected to my Windows machine and the windows machine is configured to do ICS(Internet connection sharing). When the Internet connection on the windows machine goes down, I think it triggers this wake lock somehow.

Still present.
