### ISSUE TITLE
CM11 2014-06-04 - AWAKE PROBLEM

### ISSUE THREAD

**Issue by dnastew** [LegacyXperia/local_manifests#651]
Hello guys, I'm here because I have awake problem.
My battery drains out and I don't know what is happening.
Awake (in stock battery stats with bars) is always full.
I guess my Neo V doesn't go into deep sleep.
Any solutions? I don't want to change ROM because it's awesome:)

**Comment by krikoCodeCook** [comment]
Which wakelock causes this?

**Comment by enveraltin** [comment]
I think I know what you're talking about. Try removing gapps if you can.

There's a known problem with Google Play Services v4.4.52 from May 19 update.

**Comment by godlesplay** [comment]
maybe this can help you, and remember share logs for mike https://github.com/LegacyXperia/local_manifests/issues/643

**Comment by dnastew** [comment]
Does gapps cause this kind of bug? I have to try this.. but what gapps you think are good for thi ROM? I used "minimal gapps for kk", but no idea what is the date xd

**Comment by godlesplay** [comment]
I'm using same gapps since 1st cm11 build from mike

**Comment by dnastew** [comment]
Ok, I will try.
But on the other hand, I can't record snapchat videos from back camera.
Any ideas?

**Comment by godlesplay** [comment]
idk, I'm not using snapchat

**Comment by dnastew** [comment]
ok, I guess its caused of snapchat beta ;D

what kitkat ROM you recommend?:)
I don't like features like omniswitch, holo, multiwindow (I just don't use them and don't need).

I need 'stable' ROM with deep sleep working ;D
and of course camera (video recording in camera app).

would You help me?:)

**Comment by godlesplay** [comment]
I'm using latest official nightly from LX

**Comment by mikeNG** [comment]
No logs
