### ISSUE TITLE
Music stops playing on 20140606 build

### ISSUE THREAD

**Issue by Vynikal** [LegacyXperia/local_manifests#653]
Already updated to 4.4.3, but I realized that after some seconds music suddenly stops playing and doesn't turn on again. Doesn't matter if Walkman or Apollo.
http://pastebin.com/2RMniNat

**Comment by godlesplay** [comment]
same here... https://github.com/LegacyXperia/local_manifests/issues/640

**Comment by Vynikal** [comment]
First I thought it is caused by low ION_AUDIO size (my personal experiment), but logcat says there's something wrong with permissions.
I see you are also using Walkman on coconut. Coincidence?
Line 111:
W/PackageManager(  581): Not granting permission android.permission.WRITE_MEDIA_STORAGE to package com.sonyericsson.music (protectionLevel=18 flags=0x483e45)

And see changelog: "Testing fix for media storage crashes after hot reboot"
Well, I'll try to find it, revert it and build. I'll report if some news.

**Comment by godlesplay** [comment]
ok I will wait for news from you! thanks

**Comment by mikeNG** [comment]
Last nightly is 20140603. No bug reports for home builds
