### ISSUE TITLE
cm-11-20140608-anzu, can't turn off Screen-off animation

### ISSUE THREAD

**Issue by 16D** [LegacyXperia/local_manifests#654]
I can change option between "Electron beam" and "Fade out" and it changes, but when I choose "Disabled" last option is still active.

In mango with cm-11-20140604 this function works correct. At evening maybe, I will try cm-11-20140603 on anzu.

**Comment by 16D** [comment]
I have updated anzu to CM-11-20140611 and problem is still. Only steps 1, 4, 5 like written here:
http://forum.xda-developers.com/showthread.php?t=2545354

Maybe I should make full update with formatting everything?

**Comment by mikeNG** [comment]
It's still an issue with the cm11 code

**Comment by mikeNG** [comment]
Should be fixed in the next build http://review.cyanogenmod.org/65635
