### ISSUE TITLE
I cannot make or receive call

### ISSUE THREAD

**Issue by bgokul95** [LegacyXperia/local_manifests#655]
Xperia Neo V (Haida)
cm 11
1.I have installed re-installed cm 11 many times(even the updated versions), but there is one great issue. I cannot make phone calls. If i do, the network signal goes low. When someone calls me, I could not see the incoming call in my screen, all the caller says is the ring is automatically disconnected. It says "Dialer has stopped". Someone was also having this same issue(Xda thread:http://forum.xda-developers.com/showthread.php?t=2543426&page=419) (POST#4185).Please fix it, I ve seen it several times.
2.Another one is When I click my Home button(middle bottom button) , the display screen shows the leftmost page(what we call screen), but the requirement is I want my middle page. Suppose I am having 3 pages on my home screen, when i click the home button, it moves to the 1st page(to the left), I need the 2nd page(middle) to be there.
3. In settings>under personalization we ve only few things ,like "homescreen" missing(10.2 has it) and many other.
4.Wifi is not working properly sometimes. I mean it doesnt give the constant wifi signal.
5.Video recorded via camera is of poor quality(with lots of noises).
Thank You. I think You look forward this issue and give me a solution.

PS: Currently I am using 10.2 since I had that call issue, I shifted from cm 11 to cm 10.2. I had posted this issue earlier but was closed without giving any response. We re here not to simply post our issues and go away without getting any solution. Please give us a proper solution before closing any issue. PLEASE DONT CLOSE UNLESS I GET A SOLUTION TO IT !!!

**Comment by mati865** [comment]
There are few rules.
1. No logcat/dmesg = There is no bug.
2. One bug report per bug.
3. Check known issues on wiki and bug reports before posting.

**Comment by FibreFoX** [comment]
> I need the 2nd page(middle) to be there.

if you are at the homescreen, open the contextmenu (should be the right button), and tap on the HOME-icon WHILE BEING in the page you want as your home-screen. It seems that the launcher itself has changed so this is no bug at all. (i stubled upon this change-of-usage myself, but again: that is no bug)

**Comment by mikeNG** [comment]
@bgokul95 If you don't bother to follow the simple bugreport rules, I will continue closing the issues with no further notice.
