### ISSUE TITLE
[CM11] Camera - force close after stop video recording / Kernel panic

### ISSUE THREAD

**Issue by zweif** [LegacyXperia/local_manifests#657]
On discussion thread I read something about FCs while taking videos (stop video recording). So I tried if it does work for me. I get FCs too, but got additionaly a Kernel panic after some trys.
I think it's related.
Device: mango
Kernel log: https://www.dropbox.com/s/py01t7y60n08kvq/last_kmsg-Camera.txt

**Comment by ghost** [comment]
Attaching my logcat for this issue aswell:  Anzu build 11-06-2014

https://gist.github.com/skaveelicious/0c68f5078ea7f4f07a6a

**Comment by ghost** [comment]
I dont have that problem on anzu. About 5min of recording and nothing  :)
Do you have KSM enabled?

**Comment by mikeNG** [comment]
Do you have KSM enabled by chance? If yes, disable it.

**Comment by zweif** [comment]
No, I never enabled KSM and its disabled in settings.

**Comment by ghost** [comment]
I have it enabled and its fine

**Comment by Jithug** [comment]
I have the same problem in Haida and..camera force close after video recording..ksm is disabled by default..

**Comment by xange** [comment]
same problem here in Hallon on latest nightly, the video recorded is saved in sdcard and gallery is able to view the video detail like duration, size.... but it is corrupted (can't be played)

**Comment by JovieBrett** [comment]
Same here with Smultron on camera force close when done with recording, no KSM and I still experiencing kernel panic (even the first boot) booting after kernel logo seems to still take so long.

**Comment by xange** [comment]
spotted something new: If you change the audio settings of video from AAC to AMR-NB, the video will works fine, i guess AAC encoder is broken?

**Comment by ghost** [comment]
I can confirm that video recording works fine when switching the audio codec from ACC to AMR-NB. Attaching a logcat with 2 video takes: 1st one using ACC, 2nd one using AMR-NB.

https://gist.github.com/skaveelicious/8f08e78dfa096157a866

**Comment by mikeNG** [comment]
Fixed in next build https://github.com/LegacyXperia/android_device_semc_msm7x30-common/commit/a47cb7188cb746cae3fe01a0bf13537320049444
