### ISSUE TITLE
[CM11]-20140611-anzu-Youtube or any video playing leads to hard reset

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#658]
dmesg: http://pastebin.com/8rVpdJPC
last_kmsg: http://pastebin.com/5g8Xf8Mp

everytime i try to play any video(youtube or quickpic player) it just crashes

**Comment by ghost** [comment]
in todays build i think it is fixed

**Comment by ghost** [comment]
nope, still there
last_kmsg: http://pastebin.com/F0nnbU0s
logcat: http://pastebin.com/LpXJdVVY

**Comment by krikoCodeCook** [comment]
I was able to reproduce, but  so far just once. It doesn't happens that often and I don't play videos on my phone much.
Full report (last_ksmsg contains the crash log at the end): https://drive.google.com/file/d/0B1ZKsglImPy3QWY3OEY4U1RYSE0/edit?usp=sharing

Mplayer says the video was:
QuickTime / MOV (libavformat)
[lavf] stream 0: video (h264), -vid 0
[lavf] stream 1: audio (aac), -aid 0, -alang eng

**Comment by mikeNG** [comment]
Should be fixed in latest or next build
