### ISSUE TITLE
[CM11][Mango][20140611] no luancher & camera app

### ISSUE THREAD

**Issue by amirhakh** [LegacyXperia/local_manifests#659]
In the name of Allah

Salam (Hello)

Thank you for developing CM11.
I am upgrade CM11  0604 to 0611 (with BaNkS gapps) on my "mini pro" and get FC on luancher.
When install a clear CM-0611 and see lunchar not installed. I install another launcher from 'adb' . I did't see camera app in luncher (and gallery). I am try again and not change anything. I install 0611 with previous GAPPs and get FC on some app (launcher) .
Can you fix this bug ?

**Comment by amirhakh** [comment]
sory.
it is worked by install minimal GAPPS.

**Comment by azakosath** [comment]
Please read the rules before creating a new issue:
https://github.com/LegacyXperia/Wiki/wiki/Reporting-problems

You can close your report.
