### ISSUE TITLE
Reduce size of boot.img / initrd.img?

### ISSUE THREAD

**Issue by amishmm** [LegacyXperia/local_manifests#66]
Now that initrd.img is in LZO format I was able to look at its contents.

I do not know if this falls under Cyanogenmod or falls under LXP.

But since I have not seen initrd of any other ROM, I am posting here in case there is a way to do the following, when the ROM is built.

There are two big files in initrd.img:
ramdisk.cpio (1.4MB)
ramdisk-recovery.cpio (4.4MB)

One is used for normal boot and one is used for CWM recovery.

If we see contents of both the files, ramdisk-recovery.cpio almost has all the files of ramdisk.cpio and almost all the files are identical.

If we copy few files from ramdisk.cpio (init.*.rc) to ramdisk-recovery.cpio we can get rid of ramdisk.cpio completely and gain 1.2MB additional space in boot.img. (boot.img size will reduce to around 7MB)

Only two files differ in those ramdisks, default.prop and init.rc.

Lets say we copy these two files from ramdisk.cpio to ramdisk-recovery.cpio and rename them default.prop.normal and init.rc.normal

Now init.sh (in initrd.img) extracts either ramdisk.cpio OR ramdisk-recovery.cpio, based on if user press VOL-DOWN (recovery key) while booting.

The related line is:
busybox cpio -i < ${load_image}

If just after that line we smartly do the following: (rough code)

```
if [ -s /dev/keycheck -o -e /cache/recovery/boot ]
    # do nothing
else
        busybox cp default.prop.normal default.prop
        busybox cp init.rc.normal init.rc
fi
```

we can achieve a single common RAMDISK which can be used for normal as well as CWM booting.

So with just few changes to init.sh and little restructure of ramdisk-recovery.cpio we can get more than 1MB.

This 1MB can be used to include kernel modules (like wifi etc.) inside the kernel instead of userspace or can be used for something else.

Hope that idea makes sense.

**Comment by mikeNG** [comment]
Again, this idea seems not possible to me. We used to have the boot.img layout like this a year ago, but we switched to 2 stage boot from cm10 onwards for 3 main reasons:
1. People who build from source can very easily include another recovery instead of CWM (twrp for example)
2. It's clearly a better solution than mixing all recovery files with boot files
3. Most important, we don't get away from the CM/AOSP build system. Copying mixed recovery & boot files required some ugly changes in the makefiles that needed to updated almost every time there was a change in CWM. less things to maintain = less headache.

**Comment by mikeNG** [comment]
The 2 way boot we are using now is different from other phones too, because sony phones don't have a dedicated recovery partition like most other phones. We have to live with having both boot & recovery images in one partition

**Comment by amishmm** [comment]
No problem. I had a doubt that its how CWM works. Its strange why they kept different ramdisks when all files are exactly same. (except two)

But anyway thanks for your reply.

**Comment by mikeNG** [comment]
Maybe there's some other way to save some space but we've already searched for any possible solutions. Most of them would get us away from the build system, so they won't be implemented.

**Comment by amishmm** [comment]
Not reopening the issue but here is another suggestion. (Possibly better and easier)

This keeps two ramdisks (recovery and normal) but still allows us to reduce size of ramdisk.cpio.

I am assuming that there is an easy way to specify what files to include and which not to in ramdisk.cpio. This will make sure we dont get away from the build system.
- We DO NOT touch OR modify, ramdisk-recovery.cpio
- ramdisk.cpio will contain only files missing in or differing from ramdisk-recovery.cpio. (i.e. init*.rc files and default.prop)
- So size of ramdisk.cpio will reduce by 1.2MB or so

We just need single line addition in init.sh (in initrd.img)

```
else
        ...
        busybox cpio -i < /sbin/ramdisk-recovery.cpio
fi
```

(i.e. one line added in else part of code in init.sh)

## If user pressed recovery key:
1. then else part will **not** execute.
2. load_image will be ramdisk-recovery.cpio
3. it will be extracted by busybox cpio -i < ${load_image}

## If user did not press recovery key:
1. then else part will extract recovery first
2. load_image will be ramdisk.cpio
3. it will be extracted by busybox cpio -i < ${load_image}
4. Step 3 will make sure that correct init.rc and default.prop are in place.

Overall one line change in init.sh and exclusion of "repeated" files from ramdisk.cpio is all what is required.

Again its based on assumption that its easy to specify what files to put in ramdisk.cpio and what not to.

My main purpose is just to document a possible idea not to push/pressurize the idea! :)
