### ISSUE TITLE
[CM11][HAIDA] [20140611]bug: video recording..trebuchet launcher

### ISSUE THREAD

**Issue by Jithug** [LegacyXperia/local_manifests#661]
*video recording not working crashes after clicking stop recording button
(afterwards camera is stopped ,cant open it)
*trebuchet launcher crashes after first ROM install
*3g network getting signal loss.

important :: "how can i upload zip file"

Please fix these bug in upcoming release.

Release I used cm11haida20140611

**Comment by Christopher83** [comment]
Hi, 
about the video recording issue, please  check if KSM (kernel samepage merge) is enabled inside Settings -> Performance -> Memory Management. 
If so disable it and reboot. 
Let us know if the problem will disappear.
It seems that KSM and coherent dma allocation via CMA doesn't work well together.

**Comment by azakosath** [comment]
Please read the rules before creating a new issue:
https://github.com/LegacyXperia/Wiki/wiki/Reporting-problems

You can close your report.
