### ISSUE TITLE
[CM11][coconut] 20140611 File manager crashes when changing file permissions in system folder

### ISSUE THREAD

**Issue by azakosath** [LegacyXperia/local_manifests#662]
I remember this happening a long time ago, but I hadn't mentioned before because I could do what I wanted with other file managers (root access was granted). But, this time it wasn't just a force close, it ended by erasing everything in system/ app folder, I didn't capture a logcat before rebooting (I'll try to reproduce if you want the log). I got screenshots before and after reboot.
Before (from Link2SD):
![screenshot_2014-06-12-14-03-29](https://cloud.githubusercontent.com/assets/5717336/3257182/16a32906-f226-11e3-896d-3ea633b4b3a2.png)
After (from root browser):
![screenshot_2014-06-12-14-09-49](https://cloud.githubusercontent.com/assets/5717336/3257190/2f702d44-f226-11e3-90f3-5bf4f434339e.png)

**Comment by mikeNG** [comment]
Did this happen with CMFileManager? If yes, provide logs. I never had anything similar happen on my devices

**Comment by azakosath** [comment]
My wrong, sorry for the inconvenience Mike. Trying to reproduce it, I found out that instead of the selected file  I changed the folder's permissions :(
