### ISSUE TITLE
[CM11]-20140611-urushi

### ISSUE THREAD

**Issue by esemef** [LegacyXperia/local_manifests#663]
Screen-off animation style disabled doesn't work. It uses the last animation style that was selected.

**Comment by 16D** [comment]
I have posted same issue in anzu and mango with 20140611 build:
https://github.com/LegacyXperia/local_manifests/issues/654

There was no problem in 20140603/20140604 build.

**Comment by mikeNG** [comment]
Duplicate of #654

will be fixed in next build

**Comment by 16D** [comment]
I have found cm-11-20140612 build for anzu and now it works correct.
