### ISSUE TITLE
[cm11][haida][20140611]..Cwm recovery bug::error mounting /sd-ext!

### ISSUE THREAD

**Issue by Jithug** [LegacyXperia/local_manifests#664]
Gets error while installing new rom ( [cm11][haida][20140611]  )
in cwm recovery v6.0.4.9 
1. selected wipe data/factory reset
2. gets error : 
    Formatting /sd-ext..
    Error mounting  /sd-ext..
    Skipping Format...

Please Fix The Bug...

**Comment by ghost** [comment]
have you tried rebooting to recovery and then doing the wipe/factory reset. I have noticed that sometimes if you previously mounted the sdcard to i.e. copy .zip files you can not remount it (to install .zip from sdcard) and therefore have to reboot.
