### ISSUE TITLE
[CM11][urushi]suspend_backoff still present...

### ISSUE THREAD

**Issue by Angelvz** [LegacyXperia/local_manifests#669]
0611 build still have "suspend_backoff" wakelock.

-no sd card partitioning, any sd card and + no sd card still present. 
-in any cases, in any gapps combination (even non fitting gapps 4.4.0)
-no performance settings touched

additional:
in performance - set i/o sheduler - no i/o sheduler change present - just "set on boot option"

http://forum.xda-developers.com/showpost.php?p=53347446&postcount=4781
logs, dunno how 2 submit there

**Comment by mikeNG** [comment]
#643
