### ISSUE TITLE
[10.2] Trebuchet crashes

### ISSUE THREAD

**Issue by JovieBrett** [LegacyXperia/local_manifests#67]
Trebuchet frequently crashes at some random time. It's worst when the RAM usage is high. 
Attached logcat: http://goo.gl/f7b1lT

**Comment by Andrewas** [comment]
Have you changed the rows and the lines in home screen?

**Comment by JovieBrett** [comment]
@Andrewas yeah, I changed it to 6x4. Why? is it affected?

**Comment by Andrewas** [comment]
Yes. It seems so from the log. The widgets don't fit in screen.! Try reseting it to 4x4 (that must be the default) nad check if it solved your issues. Or try making it 6x6 or 6x5

**Comment by JovieBrett** [comment]
But I don't use any widget on my homescreen right now since the crash happened. About the "Minimalistictext" widget on the log, I don't know why it is included there even if I am not using it. Thanks by the way, I will try.

**Comment by Andrewas** [comment]
Ok and try changing it and let me now. The launcher is constantly crashing or from time to time? That's what the log says ;)

**Comment by JovieBrett** [comment]
Ok so here's the report now.
I changed the default grid alignment of Trebuchet Launcher and luckily I got to produce the crash, here's the log: http://goo.gl/G90rH5
It depends on some situations like when installing a new app & RAM usage is high and constantly happening.

**Comment by mikeNG** [comment]
Can't be fixed, android 4.3 is very memory hungry for our devices.
Also cm10.2 is EOL
