### ISSUE TITLE
[Haida] Since ION Kernel - Apps start very slow, Android Process takes much CPU

### ISSUE THREAD

**Issue by rkkoszewski** [LegacyXperia/local_manifests#670]
MISTAKE IN TITLE: ION not PMEM

Hello, Since the first ROM wich came with ION Kernel I had the same issue. The overal system performance seems to be much slower than with PMEM Kernel. 

The phone is getting hot (wichout overclocking) and there is a lot of battery drain. 

Don't know why but from the first ION ROM everything seems to start much slower.. 
Sometimes you pres a button.. and it gets stuck and it gets registered like a long touch. 
Sometimes everything seems to freeze and starts working again after a few seconds (or minutes).

Changing from app to app sometimes leaves a black screen for some seconds, then the app appears.

The CPU feels like it's doing something 24 hours a day or like the memory don't get flushed correctly and is always full.. But I have only few necesary apps installed (All of them were installed on the Pre ION ROMs of LX and things were working normally).

I don't know what logs should be posted here.. DMESG has nothing weird, just messages about WIFI wich the Pre ION version already had.

Here are some pictures of the Battery usage:
![](http://s30.postimg.org/r2rnzwzld/2014_06_14_13_51_42.png)
![](http://s7.postimg.org/ni78lldez/2014_06_14_13_51_52.png)

I would just like to know if other Haida (Neo V) users have the same issues with performance with the new ION ROM.

P.D: I always update the ROM with a clean fresh install.

**Comment by godlesplay** [comment]
you mean ION not PMEM

**Comment by rkkoszewski** [comment]
Oh crap.. Yes.. I meant ION. Does all the Haida devices have this problem?

**Comment by s-kostyuk** [comment]
Try to upgrade to the latest ROM (cm-11-20140611-UNOFFICIAL-LegacyXperia-haida), it must be helpful

**Comment by rtammekivi** [comment]
Do you happen to have KSM enabled? It decreases the performance quite a lot.
