### ISSUE TITLE
Custom brightness % in autobrightness config doesn't work.

### ISSUE THREAD

**Issue by pteek** [LegacyXperia/local_manifests#671]
In the auto brightness tweaking menu, if we tap and hold to get to the edit menu at a specific lux value, we are given a prompt to change the value with a slider or edit the % in text.

The text option does nothing.

**Comment by azakosath** [comment]
Check the FAQ section in wiki:
https://github.com/LegacyXperia/Wiki/wiki/FAQ
"Remember you can't increase a level over next one..."
I hope this is your case and please read the rules before reporting:
https://github.com/LegacyXperia/Wiki/wiki/Reporting-problems

**Comment by pteek** [comment]
That is not my case. I can adjust the value using the slider and it is saved. However, any changes made to the custom % text box are simply ignored.

**Comment by someuser1** [comment]
I have the same problem. I use [20140604] version for coconut.

**Comment by mikeNG** [comment]
Should be fixed with http://review.cyanogenmod.org/72204
