### ISSUE TITLE
[Haida] Screen brightness reduced to very low despite set 100

### ISSUE THREAD

**Issue by dr-fusion** [LegacyXperia/local_manifests#674]

**Comment by dr-fusion** [comment]
I have just installed  cm-11-20140611-UNOFFICIAL-LegacyXperia-haida.zip

After installation Screen brightness was ok. then suddenly after few minutes it started flickering.
No it becomes too much dim. although i have set it 100%. Please Help

**Comment by Angelvz** [comment]
is ajust sunrise and sunset enabled? manually configured ambient light sensor settings? pressing quick settings panel brighness button changes somnth?

**Comment by dr-fusion** [comment]
Hi Anglevz thanks for quick reply.
How to set sunrise & sunset disabled? or changing ambient sensor? auto brightness is disabled

**Comment by Angelvz** [comment]
settings->display&lights->Brightness->press gear in dialog window.----> try change theese settings

**Comment by dr-fusion** [comment]
I have disabled auto brightness and still screen is not lighting up properly

**Comment by Angelvz** [comment]
well, seems somnth wrong ^)
dunno what 2 suggest

**Comment by dr-fusion** [comment]
Its terribly dim.. can you suggest some help please.. or mark this as bug

**Comment by dr-fusion** [comment]
@mikeNG  Please help in dim brightness issue

**Comment by zweif** [comment]
what about boot? is kernel logo dark? if so, it could be your hardware

**Comment by krikoCodeCook** [comment]
If you disable auto brightness, make sure you slide the brightness slider all the way up. Did you do that?
Also test indoors - some weather conditions like bright cloudy day make the screen barely readable in any way.

**Comment by dr-fusion** [comment]
@zweif : i have done reboot 5 times 2 times boot logo was bright and for few seconds screen also bright  and 3 times it was dim.
@krikoCodeCook  i have disabled auto brightness. but still flickering occurs.. i have tried sunny environement , in office but no luck..

**Comment by dr-fusion** [comment]
Hi Guys. When i select Force GPU rendereing in developer option. it reduces flickering.. sometimes it event stops to flicker. and sometimes very minor flickering. but low brightness issue resolved by force GPU rendering

**Comment by krikoCodeCook** [comment]
For a few seconds bright... do you mean the backlight it's flickering?
In that case could be HW issue - bad backlight or bad connection.

**Comment by mikeNG** [comment]
You are the first person to report such an issue, so it's probably a hardware issue.
I can't reproduce in any of my 4 devices

**Comment by dr-fusion** [comment]
Then it's ok man. i will have to change my lcd.. thanks for reply :)
