### ISSUE TITLE
[CM11] anzu, problem with lock screen

### ISSUE THREAD

**Issue by 16D** [LegacyXperia/local_manifests#677]
Selection of function in lock screen in side view is to high and not match with screen resolution.
![screenshot_2014-06-19-09-28-30](https://cloud.githubusercontent.com/assets/7846808/3328193/965fc59e-f7b9-11e3-8a58-25a929161a22.png)

Similar thing with lock screen in side view is in my mango with CM11 20140611 build

**Comment by 16D** [comment]
Dialer was fixed in 20140619 build from Legaxy page, not in build 20140619 from androidfilehost. Lock screen problem is still.

**Comment by zweif** [comment]
I made a commit to gerit:
http://review.cyanogenmod.org/#/c/76918/

I'm on mango, and played with xmls and values.

Before:
![before](https://cloud.githubusercontent.com/assets/6281450/5010806/2ffe42d6-6a77-11e4-9413-91de444dbcdb.png)

After:
![after](https://cloud.githubusercontent.com/assets/6281450/5010810/40b3a986-6a77-11e4-85c5-8d21bb6b6778.png)

By the way @16D , how did you get lockscreen to landscape on anzu? I have to slide out keyboard.

**Comment by 16D** [comment]
I have normally turned on in options "Autorotating lockscreen". I will check what options are there.
You have edited them in filemanager in phone or on PC?

**Comment by zweif** [comment]
Thanks, I found it. Display & lights -> Rotation.
I've edited on PC and rebuilt Keyguard.

**Comment by mikeNG** [comment]
@zweif thanks, I'll include that in next build
