### ISSUE TITLE
[CM 11] Hallon- not able to use video recording in cm-11-20140620 build

### ISSUE THREAD

**Issue by kharbpunit** [LegacyXperia/local_manifests#678]
Steps: 
1. Open Camera
2. change camera to camcoder
3. tap on recording button

Expected: Camera should start video recording
Actual: Nothing happens

Find logs at : https://www.dropbox.com/s/yd6j8jx8wmqb8u6/bugreport.zip

**Comment by xange** [comment]
refer to #657 and close this issue.....

**Comment by kharbpunit** [comment]
I am still facing this issue after your fix. I am using cm-11-20140620 which is latest build.
Please suggest if I am doing something wrong.

**Comment by azakosath** [comment]
Did you try manually to clear data of gallery2.apk? Everything is working fine in  my coconut (except a couple of FCs after pressing the stop button).

**Comment by trader-crows** [comment]
Did you forget to flash the latest kernel? I did. Video recording didn't work. Newest kernel flashed, video recording works.

**Comment by 16D** [comment]
I have CM11 20140621 build in anzu, with flashing kernel and it's not recording after tap button. It was updated from 20140615, thru 0618 and 0619. By last update I have updated kernel, maybe I will try make fresh install with full format.
EDIT:
I have made full format and fresh installation of 20140622 build, camcorder still don't want record. On fresh 20140619 build camcorder works perfect.

**Comment by kharbpunit** [comment]
I flashed original kernel which is coming with build and recording is working fine now.
So closing this bug

**Comment by 16D** [comment]
In anzu I was trying new builds with proper kernel and it doesn't want to work, I will try last 20140623 build which I have found now.

EDIT:
In my anzu with build 20140623, camcorder works.
