### ISSUE TITLE
cm-11-20140620: no WiFi (Xperia Mini STi15 smulton)

### ISSUE THREAD

**Issue by gsb9** [LegacyXperia/local_manifests#679]
After clean install on Xperia Mini (STi15 smultron) phone is not able to activate WiFi

![screenshot_2014-06-20-13-31-58](https://cloud.githubusercontent.com/assets/7943454/3340388/c2155762-f87c-11e3-8e9c-c10c5e40299f.png)
![screenshot_2014-06-20-13-32-07](https://cloud.githubusercontent.com/assets/7943454/3340389/c2182780-f87c-11e3-96d0-5666c191310d.png)

last working legacy was cm-11-20140512

**Comment by azakosath** [comment]
I'm guessing that you didn't flash the latest boot.img...
