### ISSUE TITLE
2G Data interruptions [ANZU]

### ISSUE THREAD

**Issue by jlmcr87** [LegacyXperia/local_manifests#68]
I have problems with 2G data interruptions. For example, my girlfriend send me a whatsapp message and i don´t receive her message. After some minutes i receive a lot of messages at once time.
Also when this happens my messages are not sended, 2G date is like freeze, and i have to wait some minutes as I said.
I have a virtual mobile operator, maybe can be related with this?

**Comment by jlmcr87** [comment]
Dmesg, logcat and modem log here: http://www.mediafire.com/download/z6u01mrdn713l61/2013-09-18_20.22.zip

**Comment by mikeNG** [comment]
Any news with the latest build?

**Comment by mikeNG** [comment]
No input
