### ISSUE TITLE
[CM11] [20120620] Scheduler not being apply properly after reboot

### ISSUE THREAD

**Issue by xange** [LegacyXperia/local_manifests#680]
After a reboot or everytime you turn on phone, cat on "sys/block/(all mtdblock)/queue/scheduler" shows the partition using noop scheduler (Moar Bootspeed!) eventhough I'd set cfq and set on boot in settings. I had to apply again the scheduler in settings. The performance settings "Apply IO scheduler to all partitions" is working, but maybe the set on boot is not functioning.

**Comment by xange** [comment]
addon: found out IO scheduler only apply boot settings to mmcblock only but not all partition like mtdblock. but re-apply the IO scheduler will apply the settings to all partition.

**Comment by mikeNG** [comment]
http://review.cyanogenmod.org/#/c/65599/3 patchset 3 should fix this

**Comment by xange** [comment]
fixed in latest nightly 20140702. thanks for your effort.
