### ISSUE TITLE
[CM11] anzu, Facebook Messanger does not work with Extended desktop

### ISSUE THREAD

**Issue by 16D** [LegacyXperia/local_manifests#690]
I have 20140619 build, when Extended desktop is Enabled, chat heads are hidden or something, anyway I can't see them.

**Comment by 16D** [comment]
Similar head up of Calculator works when extended desktop is enabled, but Messenger still doesn't in 30.06.2014 build.

**Comment by mikeNG** [comment]
It's probably facebook's issue
