### ISSUE TITLE
[CM11] Wallpaper and lockscreen widget reset after rebooting

### ISSUE THREAD

**Issue by fqdb** [LegacyXperia/local_manifests#691]
After rebooting my device (Hallon), the wallpaper is often reset to the default CM11 wallpaper (http://s9.postimg.org/6616re6m7/default_wallpaper.jpg) and the default lockscreen widget/clock is added to my lockscreen (in a new page). The issue doesn't happen after every reboot, but more than half of the reboots at least.

This issue has been present for me in the June 4 nightly and also in the several ones before (May 21 IIRC).

**Comment by streumix** [comment]
at my end (on Xperia ray/urushi - starting with march 20th nightly) apps moved to the SD card are dropped from the launcher home screen with every reboot. Annoying ....

**Comment by theprov** [comment]
I nave the same problemi of streumix, urushi with cm11 20140620
