### ISSUE TITLE
[CM11][mango][20140620]Special (Fn+) keys layout doesn't switch with language

### ISSUE THREAD

**Issue by leadenmoth** [LegacyXperia/local_manifests#692]
I use cyrillic setting for hardware keyboard on Mango, which means there are two layouts (English and Russian) switched by a language key.
Each key has additional blue Fn function. The layout of the blue key properties (let's call it Fn-layout) should switch together with language. Instead the Fn-layout is always in its "Russian" mode, which back in stock days was created to make room for more letters, while spreading all the punctuation and special symbols around with no regard for the actual inscriptions on the keys, and while removing some of the symbols.
As a result on CM11 I can input those additional letters even while in English, while some special characters shown on the keyboard are impossible to enter in either language. And the blue inscriptions on the keys make no sense.

If it is possible to have two separate Fn-layouts with the current software, I'd appreciate it if someone directed me to where both default QWERTY and Cyrillic settings are stored (I wasn't able to find the proper cyrillic one in /system/usr/keychars), so I could fix it myself; if two fn-layouts are not supported, I'd like to suggest adding this feature.

On a side note, once this is done either way, I suggest making it a "Cyrillic alternative" setting in case different versions of keyboards existed and the current works fine for someone. Here's a photo of my version, for that matter.
![img_20140624_122601](https://cloud.githubusercontent.com/assets/7973245/3368999/5cb43b92-fb7c-11e3-8679-0bd964acdb96.jpg)

**Comment by leadenmoth** [comment]
@mikeNG I've created two additional layouts for different Cyrillic keyboards, which it would be great if you could add to the next build within MogamiKeypad. This is how it goes:
1)There are 2 or 3 different hardware layouts for mango that used to be sold in Russia. Current MogamiKeypad supports only one of them - this one http://developer-static.se-mc.com/wp-content/blogs.dir/1/files/2012/05/Cyrillic_keyboard.jpg Pictured above is a different one, which I have. Note the different blue symbols' locations
2)If I recall correctly, GB and ICS used to have slightly different blue key behavior. On keyboards such as mine one of them had single blue layout which correlated with what is actually on the keys for the most part. The other one had two different blue layouts. In Russian it was identical to what MogamiKeypad has right now for cyrillic, while in English it was as if in QWERTY mode.

I attach two additional layouts - cyrillic2 and cyrillic3. They are meant NOT to replace the current cyrillic, but to be added side by side to MogamiKeypad. Cyrillic2 is the version, where only QWERTY-style blue keys work in both layouts (except for the absolutely needed actual letters, which are "blue"), and Cyrillic3 is the one, which combines the two different blue layouts. It would be great if you could add both, but if for some reason you'd rather pick one, I'd vote for Cyrillic3, as it is the most universal. Thanks in advance (btw feel free to rewrite the license bit whichever way you like). The new layouts (kcm) are at this post on xda http://forum.xda-developers.com/showpost.php?p=55139751&postcount=6357 in an attached zip

**Comment by mikeNG** [comment]
Great, I will add both new layouts in MogamiKeypad so everyone is happy :)

**Comment by mikeNG** [comment]
https://github.com/LegacyXperia/android_device_semc_mogami-common/commit/3803e9bd812ea3b0bb991c8850d6995c58a98732
