### ISSUE TITLE
coconut[CM11] - "com.android.incallui"

### ISSUE THREAD

**Issue by panther-ra** [LegacyXperia/local_manifests#693]
Hi all. I installed latest Legacyxperia CM11 2014.06.19, and when i call or incoming, "com.android.incallui"  stopped and noway to hang up. i tried reflash firmware, wipe/factory reset, superwipe script, and nothing has changed. Is there bug of all CM11-based firmwares? 
P.S: Sorry for my bad english (non-native language)

**Comment by godlesplay** [comment]
I have same build on coconut and calling is working nice for me
