### ISSUE TITLE
[CM11][urushi] Device becomes unresponsive leading to the restart

### ISSUE THREAD

**Issue by dlastov** [LegacyXperia/local_manifests#694]
Once a day it happens that the device becomes unresponsive, sometimes it reboots automatically. If no I have to restart it myself with "home+power". After the restart the unresponsive behaviour usually continues.
After several restarts it is ok.
I have a clean install of cm-11-20140620-UNOFFICIAL-LegacyXperia-urushi.zip and I was trying to install only the minimum of applications that I need. I have experienced this behaviour already with the previous installation.
Some logs:
last kernel log
http://pastebin.com/dwHWFLkv
last kernel log - another example
http://pastebin.com/dwHWFLkv
logcat
http://pastebin.com/2ftr5YZN

**Comment by dlastov** [comment]
The restarts do not really help actually... I have to restore from CWM backup to get rid of the freezes. But sooner or later the problem appears again...
In the attached logcat the following lines seem to me to be the first relevant error:
E/qdmemalloc(  235): ION_IOC_ALLOC failed with error - Out of memory
W/qdmemalloc(  235): Falling back to system heap
E/qdmemalloc(  235): ION_IOC_ALLOC failed with error - Out of memory
W/qdmemalloc(  235): Falling back to system heap

**Comment by dlastov** [comment]
I can confirm that the "E/qdmemalloc" messages are not present in the log after restoring a backup when it works correctly. So possibly they could be related to the cause of the issue but I have no idea what are they triggered by.

**Comment by mikeNG** [comment]
Closing for now, possible fix included in next build
