### ISSUE TITLE
lose all apps and app data after reboot[Haida]

### ISSUE THREAD

**Issue by beasley007** [LegacyXperia/local_manifests#697]
After rebooting the phone.. I lose all the installed apps icons and shortcuts and they don't show up in settings, installed apps also. But when I visit the appstore there it shows an open button which opens the app. But no shortcuts or icons in the app drawer.

**Comment by fqdb** [comment]
Are using a mount to SD script (e.g. Link2SD)?

**Comment by harshitsinha** [comment]
try using other launchers

**Comment by Tanzbaerli** [comment]
cm-11-20140907-UNOFFICIAL-LegacyXperia-mango

After a reboot all my shortcuts to apps on the sd card (moved them with builtin apps mover) are lost. The apps are still there but i have to do the shortcut again. Annoying ....

**Comment by harshitsinha** [comment]
are you on ART or Dalvik, because if youre on dalvik and have apps on sd
card, when you switch to art, sd card apps are removed....

**Comment by FibreFoX** [comment]
Maybe the same as #774 ?

**Comment by harshitsinha** [comment]
think so..

**Comment by mikeNG** [comment]
Duplicate
