### ISSUE TITLE
Nightly build 20130918 - cm-10.2

### ISSUE THREAD

**Issue by bhanucbs-13** [LegacyXperia/local_manifests#70]
Face Unlock not working & SD Card unexpectedly removed. Blue-tooth Headset also not working properly unexpectedly disconnected. In (Xperia Pro - MK16i) iyokan

**Comment by tomasSK** [comment]
hi, what exactly happened with your sd card? because i had similar issue on my iyokan but SD card was total dead and i have to get a new one. your SD is working after restart?

**Comment by bhanucbs-13** [comment]
Ok, My sd card also dead. But then i think that and figure out that the partition table of my sd card destroy. So i rebuild that. but don't found any result. But suddenly after 4-5 Days my sd card get running properly. after that i use only MIUI5 rom for my xperia. thats working fine.. and  i just wait for next build of legacy Xperia.

**Comment by bhanucbs-13** [comment]
I think this problem is because of (sdcard0) path.

**Comment by mikeNG** [comment]
Please file seperate bug reports for each bug.
