### ISSUE TITLE
[CM11] [Urushi] Reboot with video in whatsapp and FB msn

### ISSUE THREAD

**Issue by theprov** [LegacyXperia/local_manifests#702]
When I record and send a video right from Whatsapp and Facebook Messenger, the phone immediately reboot.
It happens playing right from these app videos already sent too.

LOG

https://www.dropbox.com/s/3syn9dtaduhkka6/bugreport.zip

**Comment by mikeNG** [comment]
Closing for now, possible fix included in next build
