### ISSUE TITLE
Nightly build 20140702 - cm-11.0 Iyokan Not not boot.

### ISSUE THREAD

**Issue by bhanucbs-13** [LegacyXperia/local_manifests#703]
Hi today i download Nightly build 20140702 - cm-11.0 and try to install. but my xperia pro stuck in first boot, only black scree displaying...

**Comment by Itchythefirst** [comment]
No problem on my iyokan. Try flash the kernel again...

**Comment by xXZendomXx** [comment]
Go to the CWM and then Reboot your Phone now he must boot..
