### ISSUE TITLE
Increment build date by one in GitHub changelog to be in sync with BasketBuild files.

### ISSUE THREAD

**Issue by T0m0rr0w** [LegacyXperia/local_manifests#704]
Currently in GitHub the build date is for example 20140702 while in BasketBuild it's 20140703 (due to the ~1 day it takes to upload i presume). 

This causes some confusion but more importantly the program that i use to grab latest build date from GH does not work for BB downloads. For example the downloader grabs 20140702 from GH changelog and inserts it into direct link from BB: https://s.basketbuild.com/uploads/devs/LegacyXperia/smultron/cm-11.0/nightlies/cm-11-20140702-UNOFFICIAL-LegacyXperia-smultron.zip but errors out because in BB the build date is 20140703.

While this does not seem like a big issue and it problably isn't it means that i have to manually go to BB and download the latest build as opposed to using the program that i use to automatically find and download the latest (If anyone's intrested it's Ketarin: https://www.ketarin.org/ ).

**Comment by mikeNG** [comment]
This probably won't be fixed, since the builds start usually near the end of the day, so the first devices and the last devices have different date.

We are building for 11 devices now so it takes a lot of time to complete

**Comment by T0m0rr0w** [comment]
Ok. As a backup i asked BB support to consider implementing date based sorting. That too would solve the problem for me. The problem would not exist if not for regex limitation that does not allow capturing the "biggest" date in a directory listing. Atleast that's my understanding from what i've heard and read.

**Comment by enveraltin** [comment]
​Switching to a different version naming scheme will fix all this confusion
for good, but it's probably not worth the trouble and break-away from CM's
build strategy :)

On Fri, Jul 4, 2014 at 3:03 PM, T0m0rr0w notifications@github.com wrote:

> Ok. As a backup i asked BB support to consider implementing date based
> sorting. That too would solve the problem for me. The problem would not
> exist if not for regex limitation that does not allow capturing the
> "biggest" date in a directory listing. Atleast that's my understanding from
> what i've heard and read.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LegacyXperia/local_manifests/issues/704#issuecomment-48035710
> .

## 

Enver

**Comment by mikeNG** [comment]
Switching to different version naming would be confusing (new vs old builds)
I'm closing this for now
