### ISSUE TITLE
Youtube official app not working in cm-11-20140703-UNOFFICIAL-LegacyXperia-haida

### ISSUE THREAD

**Issue by shibliaftab** [LegacyXperia/local_manifests#709]
I flashed latest build (cm-11-20140703-UNOFFICIAL-LegacyXperia-haida). While streaming youtube video error comes "There was a problem while playing". I can browse the videos in app but unable to play. Although I'm not using any mod, xposed module, adblock. One thing to be noticed that when I cleared cache and dalvik cache, problem solved for sometime. After about one hour same problem happened. I can't figure out what is causing the problem. I flashed as a clean install. My wifi is working good on my pc. Wifi works in mobile browser and other app.
logcat: http://pastebin.com/embed_js.php?i=JRtnP1Nm
dmesg: http://pastebin.com/embed_js.php?i=sMs3edVu

![screenshot_2014-07-04-14-04-47](https://cloud.githubusercontent.com/assets/8070852/3484903/5af3d9f2-03ba-11e4-9319-4023e365d6f9.png)

**Comment by mikeNG** [comment]
Do you have KSM enabled in performance settings?

**Comment by shibliaftab** [comment]
yes, Is that setting causing problem?

**Comment by mikeNG** [comment]
Yes, you should not enable it.

**Comment by ghost** [comment]
Had exactly the same issue on my Anzu (Arc S). A reboot (without cache + dalvik wipe) fixed the issue for me. For how much it will last I still don't know.

KSM is not enabled.

@shibliaftab, just out of curiosity did you do a clean install with format /system + data ? This time I came from pmem_cma branch self build from 24-06 and just did a dirty flash.

@mikeNG maybe something again with the params in build.prop? I'll grab a log the next time it happens.

**Comment by shibliaftab** [comment]
Now problem is resolved after reverting KSM setting. Thanks mikeNG.
@skaveelicious  I came from Stock ICS ROM. Didn't format system. I formatted data, cache, dalvic cache.
You should try clearing youtube app cache and then reboot your device.

**Comment by ghost** [comment]
@shibliaftab I have experienced the problem not only on youtube but also on the gallery app (default video playback app) with selfrecorded videos. I think some other people experienced this aswell. It "magically" worked again after rebooting the device (cache + dalivk wipes were not needed). Just as a heads up I run all LX builds as stock as possible. So far it has not shown up but your report just made me curious because I got the exact same message on youtube and the gallery app.

Anyway I hope this was an isolated issue.

**Comment by shibliaftab** [comment]
@skaveelicious Yeah, rebooting may solved your problem. Report back after 24 hours if it will continue to work. If problem is not solve then come here with proper log. maybe mike help.
My problem is solved , never experienced same problem after that.

**Comment by shibliaftab** [comment]
@skaveelicious please give your device status

**Comment by ghost** [comment]
36h uptime, hasn't happened again. I guess it really was some isolated issue. I guess you can close this for now.
