### ISSUE TITLE
Phone and People app missing after some time from install of CM 10.2 0918 (mango)

### ISSUE THREAD

**Issue by ariespoge** [LegacyXperia/local_manifests#71]
I installed CM 10.2 nightly 0918. For the first 12 or so hours, everything was working perfectly but when I tried to open the dialer in Smart Launcher, it said Android: Intent blah blah. So I tried to open the Phone app itself from the drawer, suddenly it's icon and the icon of the People app vanished. 

This happened two times. The first one was when I upgraded from 10.1 to 10.2, I thought it was because I didn't wipe data/cache so I reinstalled 10.2 again, and the bug happened again.

**Comment by jlmcr87** [comment]
Phantoms

**Comment by ariespoge** [comment]
What?

**Comment by pcfighter** [comment]
Check if "Contacts.apk" and "ContactsProvider.apk" is in "/system/app" path.

**Comment by ariespoge** [comment]
They're there, as well as the Phone.apk, but they're missing in Smart Launcher.

**Comment by pcfighter** [comment]
check in apps settings is people, phone apk is visible and not disabled. Also, check in another launcher if problem is the same
you can also wipe dalvik cache

**Comment by ariespoge** [comment]
Ok, got it. I'll reinstall later, and see if it happens again. Will report back.

**Comment by ariespoge** [comment]
Also, if they are disabled, what could be the possible cause of them being disabled without my permission?

**Comment by pcfighter** [comment]
maybe a virus, maybe you have app that is malicious and you granted SuperUser access to it. I don't know what apps you have installed.

**Comment by ariespoge** [comment]
Ok, I'll monitor for now. But it's strange because every app I have installed were also installed when I was using cm10.1, but this bug never happened.

**Comment by mikeNG** [comment]
Everything working fine here. Make sure you follow all the right steps & you meet the requirements before installing

**Comment by ariespoge** [comment]
I guess it was the launcher itself. Everything is fine in trebuchet

**Comment by mikeNG** [comment]
So we can close this issue?
