### ISSUE TITLE
[CM11-20140703] [coconut] No option to control brightness adjustment in 'Automatic brightness'

### ISSUE THREAD

**Issue by Pacjonek** [LegacyXperia/local_manifests#710]
Hi,
In the older version of CM11 there was a slider to control brightness adjustment in 'Automatic brightness' how can you see below:
https://www.dropbox.com/s/rrfc9c1fjlo5gqs/stare.png
But in the newest version CM11-20140703 this option disappeared (sorry for Polish UI, this is the same option):
https://www.dropbox.com/s/hf8sjss415g3c9v/Screenshot_2014-07-05-21-43-51.png

Thank you for Your amazing work to port newest Android to our old devices.

**Comment by mikeNG** [comment]
It's automatic brightness, that means you can't manually adjust the brightness, that's why it was removed
