### ISSUE TITLE
[CM11] No way to change the font type to normal in trebuchet.

### ISSUE THREAD

**Issue by pteek** [LegacyXperia/local_manifests#712]
It is set to condensed by default and I don't like it.

It was used to be in the trebuchet settings but those are not available since CM11 M7. I am on 20140703. Dirty flash from 20140611.

Any xml I can edit?

**Comment by mikeNG** [comment]
Font selection was removed in favour of the new theme engine that allows font changing

**Comment by pteek** [comment]
Well I tried finding a similar font in the themes show application and on play store but no luck.

I like the font, but it's the condensed style that I want to change. I guess I will have to ask the CM guys.

**Comment by mikeNG** [comment]
I agree the font option needs to come back but it should simply change the style and not the actual font

**Comment by pteek** [comment]
Where can we make a request about this?

**Comment by mikeNG** [comment]
No new features in cm11
