### ISSUE TITLE
[CM11] [hallon] Android OS draining battery

### ISSUE THREAD

**Issue by Skull31** [LegacyXperia/local_manifests#713]
Android OS draining battery very fast while screen is off...
![screenshot_2014-07-07-14-32-50](https://cloud.githubusercontent.com/assets/8089916/3495267/795f66d8-05d4-11e4-8cf9-afe25fbc304a.png)
![screenshot_2014-07-07-14-40-55](https://cloud.githubusercontent.com/assets/8089916/3495278/ab41701a-05d4-11e4-9448-179ace00c857.png)

**Comment by ghost** [comment]
In the LX Wiki there is a topic on how to properly report problems and in it there is one specific section that describes how to report battery problems, as well as which app to get to grab the battery relevant logs.
