### ISSUE TITLE
[CM-11][hallon] WIFI can not be started

### ISSUE THREAD

**Issue by jazzran** [LegacyXperia/local_manifests#715]
From version cm-11-20140512-UNOFFICIAL-LegacyXperia-hallon (this works), wifi can not be started. In logcat, it reports that HW addr of wlan0 can not be obtained. Logs in pastebin

logcat
http://pastebin.com/TPW1zPXx

kmsg
http://pastebin.com/4GxVmpAD

radio
http://pastebin.com/seVC7FRX

**Comment by mikeNG** [comment]
bug reports are accepted only while using the latest build

**Comment by jazzran** [comment]
Hi  Mike,

I should not explain myself in the best way. 

The WIFI worked in my hallon device in version cm-11-20140512-UNOFFICIAL-LegacyXperia-hallon, but I could not do it in the new versions.

My report and logs are about the latest build ( you can check it -CyanogenMod-11-20140703-UNOFFICIAL-LegacyXperia-hallon-).

**Comment by mikeNG** [comment]
Did you flash the latest kernel? WiFi works fine on all my 5 devices on latest build

**Comment by jazzran** [comment]
I did an update over previous CM-11 version using CWM and install from zip
First without removing /sytem /data and /cache, and in a second try removing it, with the same result.

Will I need to flash the new kernel with flashtool?

**Comment by mikeNG** [comment]
Of course, this step was always required and mentioned in the installation guide.

**Comment by jazzran** [comment]
Yes, you were right, I needed to flash the image. Thanks a lot

I have found that link2sd needs ext4 filesystem (ext3 and ext2 are not supported)
