### ISSUE TITLE
[CM11] [hallon] Android OS draining battery

### ISSUE THREAD

**Issue by Skull31** [LegacyXperia/local_manifests#716]
Android OS draining battery very fast while screen is off...
CyanogenMod version: 11-20140703-UNOFFICIAL-LegacyXperia-hallon
Device name: Sony Ericsson Xperia Neo [hallon]
Log files:
dmsg: http://pastebin.com/0GJSTpRM
last_kmsg: http://pastebin.com/jAjE9RZD
logcat: https://gist.github.com/Skull31/65e67958437f68b469c8
BetterBatteryStats: http://pastebin.com/aA2avJYe

![screenshot_2014-07-08-09-53-17](https://cloud.githubusercontent.com/assets/8089916/3506943/36ce46fa-0678-11e4-8c9d-f26e626e0d07.png)

**Comment by azakosath** [comment]
BBS log shows :
"suspend_backoff" (): 6 h 16 m 37 s  (22597 s) Cnt:(c/wc/ec)2268/0/2268 37.1%
so, join the rest:
#643, #669, #711
