### ISSUE TITLE
Bluetooth headset not connecting..

### ISSUE THREAD

**Issue by Thanatoz-1** [LegacyXperia/local_manifests#724]
I am unable to connect my bluetooth headsets to the phone after installing cm-10.2-20140303-RELEASE-LegacyXperia-haida
The phone does not find any bluetooth device when i try to connect.

**Comment by pobrelkey** [comment]
I'm also unable to connect headsets using cm-10.2-20140304-RELEASE-LegacyXperia-mango.

Bluetooth isn't completely inoperable: I can switch it on and make the phone visible; my laptop will see the phone and can initiate pairing with it.  The bug appears to be that the phone can't see other visible Bluetooth devices (it didn't see my laptop when I made it visible, for example).

**Comment by mikeNG** [comment]
cm-10.2 is EOL so I'm closing this issue.

**Comment by Thanatoz-1** [comment]
I tried bluetooth fix repair by phk from play store and it fixed my problem. Go for it rlol key hope it fixes yours.

**Comment by pobrelkey** [comment]
Moved up to a recent CM11 nightly (cm-11-20140718-UNOFFICIAL-LegacyXperia-mango), which no longer has the issue.
