### ISSUE TITLE
Iyokan, camera hangs onShutterButtonClick

### ISSUE THREAD

**Issue by FlorentBrianFoxcorner** [LegacyXperia/local_manifests#725]
Camera was ok before update.
Updated from 20140620 to 20140703 and now camera does no longer work.

Things I tried; Clear Dalvik cache, clear cache partition, deleted settings and Cache in out-of-the-box Camera App, used different Camera App, deleted settings and Cache in torch app, turned of sound.

logcat:
V/CAM_PhotoModule( 8540): onShutterButtonClick: mCameraState=1
E/CameraClient(  239): __get_memory: fd -1, numbufs 1
E/CameraClient(  239): commonInitialization: heapbase 0x451af000, bufsize 7670662
E/CameraClient(  239): __get_memory: fd 70, numbufs 1
E/CameraClient(  239): commonInitialization: heapbase 0x45905000, bufsize 460800
I/caladbolg(  239): 1084467671 cald_camctrl.c                    (4528)  8614 P [SVR] 1084467640 + Cald_CamCtrl_ICamera_TakeSnapshot
I/caladbolg(  239): 1084468403 cald_camctrl.c                    (8986)  8614 P [SVR] 1084468403 + Cald_CamCtrl_FSM_Func_TakeSnapshot
I/caladbolg(  239): 1084471455 cald_camctrl.c                    (4117)  8622 P [SVR] 1084471455 + Cald_CamCtrl_ICBIqCtrl_PrepareSnapshotDone
I/caladbolg(  239): 1084472187 cald_camctrl.c                    (4131)  8622 P [SVR] 1084472187 - Cald_CamCtrl_ICBIqCtrl_PrepareSnapshotDone (0)
I/caladbolg(  239): 1084472828 cald_camctrl.c                    (9116)  8614 P [SVR] 1084472828 - Cald_CamCtrl_FSM_Func_TakeSnapshot (0)
I/caladbolg(  239): 1084473744 cald_capctrl.c                    (6468)  8616 P [CAP] 1084473713 + Cald_CapCtrl_FSM_Func_StartSnapshot
I/caladbolg(  239): 1084474079 cald_hal_qct.c                    (3054)  8616 P [HAL] 1084474079 + Cald_Hal_Qct_If_StopPreview
I/caladbolg(  239): 1084476032 cald_hal_qct.c                    (3087)  8616 P [HAL] 1084476032 - Cald_Hal_Qct_If_StopPreview (0)
I/caladbolg(  239): 1084476521 cald_hal_qct.c                    (7007)  8616 P [HAL] 1084476521 + Cald_Hal_Qct_If_DeleteImageConvert
I/caladbolg(  239): 1084477284 cald_hal_qct.c                    (7036)  8616 P [HAL] 1084477253 - Cald_Hal_Qct_If_DeleteImageConvert (0)
I/caladbolg(  239): 1084489063 cald_camctrl.c                    (4538)  8614 P [SVR] 1084489033 - Cald_CamCtrl_ICamera_TakeSnapshot (0)
E/caladbolg(  239): 1084501057 cald_capctrl.c                    (6554)  8616 E [CAP] ERROR:PAL SharedMem AllocImageBuffer for take snapshot Error <SystemCall>
I/caladbolg(  239): 1084501179 cald_camctrl.c                    (4015)  8616 P [SVR] 1084501179 + Cald_CamCtrl_ICBCapCtrl_SnapshotDone
I/caladbolg(  239): 1084501606 cald_camctrl.c                   (14456)  8616 P [SVR] 1084501576 + Cald_CamCtrl_FSM_Func_SnapshotDone
E/SEMC Camera HAL(  239): receivePictureDone takepicture was failed!!!
I/caladbolg(  239): 1084503071 cald_camctrl.c                   (14501)  8616 P [SVR] 1084503071 - Cald_CamCtrl_FSM_Func_SnapshotDone (0)
I/caladbolg(  239): 1084503498 cald_camctrl.c                    (4031)  8616 P [SVR] 1084503498 - Cald_CamCtrl_ICBCapCtrl_SnapshotDone (0)
I/caladbolg(  239): 1084504475 cald_capctrl.c                    (6711)  8616 P [CAP] 1084504475 - Cald_CapCtrl_FSM_Func_StartSnapshot
E/caladbolg(  239): 1084504871 cald_capctrl.c                    (3825)  8616 E [CAP] FSMSendEvent not normal end <SystemCall>
I/caladbolg(  239): 1084505329 cald_capctrl.c                    (6371)  8616 P [CAP] 1084505299 + Cald_CapCtrl_FSM_Func_StopPreview
I/caladbolg(  239): 1084505726 cald_hal_qct.c                    (3054)  8616 P [HAL] 1084505726 + Cald_Hal_Qct_If_StopPreview
I/caladbolg(  239): 1084506123 cald_hal_qct.c                    (3087)  8616 P [HAL] 1084506092 - Cald_Hal_Qct_If_StopPreview (0)
I/caladbolg(  239): 1084506794 cald_capctrl.c                    (6382)  8616 P [CAP] 1084506764 - Cald_CapCtrl_FSM_Func_StopPreview
I/caladbolg(  239): 1084509022 cald_capctrl.c                    (6128)  8616 P [CAP] 1084509022 + Cald_CapCtrl_FSM_Func_StartPreview
E/Camera  ( 8540): Error -2147483648
E/CameraErrorCallback( 8540): Got camera error callback. error=-2147483648
I/caladbolg(  239): 1084528767 cald_hal_qct.c                    (2983)  8616 P [HAL] 1084528767 + Cald_Hal_Qct_If_StartPreview
I/caladbolg(  239): 1084562794 cald_hal_qct.c                    (3042)  8616 P [HAL] 1084562763 - Cald_Hal_Qct_If_StartPreview (0)
I/caladbolg(  239): 1084562916 cald_hal_qct.c                    (6612)  8616 P [HAL] 1084562916 + Cald_Hal_Qct_If_CreateImageConvert
I/caladbolg(  239): 1084564137 cald_hal_qct.c                    (6890)  8616 P [HAL] 1084564137 - Cald_Hal_Qct_If_CreateImageConvert (0)
I/caladbolg(  239): 1084564625 cald_capctrl.c                    (6358)  8616 P [CAP] 1084564594 - Cald_CapCtrl_FSM_Func_StartPreview
E/caladbolg(  239): 1085799519 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1085897938 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1085998707 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1086099201 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1086199116 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1086299549 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1086398701 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1086500477 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1086599415 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1086703449 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1086800587 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1086900501 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1087000385 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1087105946 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1087200398 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1087300678 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1087400471 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1087502125 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
I/caladbolg(  239): 1087565235 cald_capctrl.c                    (6371)  8616 P [CAP] 1087565235 + Cald_CapCtrl_FSM_Func_StopPreview
I/caladbolg(  239): 1087565479 cald_hal_qct.c                    (3054)  8616 P [HAL] 1087565479 + Cald_Hal_Qct_If_StopPreview
I/caladbolg(  239): 1087567646 cald_hal_qct.c                    (3087)  8616 P [HAL] 1087567616 - Cald_Hal_Qct_If_StopPreview (0)
I/caladbolg(  239): 1087568562 cald_hal_qct.c                    (7007)  8616 P [HAL] 1087568531 + Cald_Hal_Qct_If_DeleteImageConvert
I/caladbolg(  239): 1087570332 cald_hal_qct.c                    (7036)  8616 P [HAL] 1087570301 - Cald_Hal_Qct_If_DeleteImageConvert (0)
I/caladbolg(  239): 1087573841 cald_capctrl.c                    (6382)  8616 P [CAP] 1087573811 - Cald_CapCtrl_FSM_Func_StopPreview
I/caladbolg(  239): 1087575184 cald_hal_qct.c                    (2863)  8614 P [HAL] 1087575153 + Cald_Hal_Qct_If_PowerDown
I/caladbolg(  239): 1087935597 cald_hal_qct.c                    (2891)  8614 P [HAL] 1087935597 - Cald_Hal_Qct_If_PowerDown (0)
I/caladbolg(  239): 1087935749 cald_hal_qct.c                    (2789)  8614 P [HAL] 1087935749 + Cald_Hal_Qct_If_PowerUp
I/caladbolg(  239): 1087936390 cald_hal_qct.c                    (2847)  8614 P [HAL] 1087936360 - Cald_Hal_Qct_If_PowerUp (0)
I/caladbolg(  239): 1088113178 cald_capctrl.c                    (6128)  8616 P [CAP] 1088113178 + Cald_CapCtrl_FSM_Func_StartPreview
I/caladbolg(  239): 1088130024 cald_hal_qct.c                    (2983)  8616 P [HAL] 1088130024 + Cald_Hal_Qct_If_StartPreview
I/caladbolg(  239): 1088202381 cald_hal_qct.c                    (3042)  8616 P [HAL] 1088202351 - Cald_Hal_Qct_If_StartPreview (0)
I/caladbolg(  239): 1088202564 cald_hal_qct.c                    (6612)  8616 P [HAL] 1088202534 + Cald_Hal_Qct_If_CreateImageConvert
I/caladbolg(  239): 1088203938 cald_hal_qct.c                    (6890)  8616 P [HAL] 1088203907 - Cald_Hal_Qct_If_CreateImageConvert (0)
I/caladbolg(  239): 1088204487 cald_capctrl.c                    (6358)  8616 P [CAP] 1088204487 - Cald_CapCtrl_FSM_Func_StartPreview
E/caladbolg(  239): 1089438221 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1089538380 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1089638508 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1089737995 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1089838947 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1089938923 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1090040638 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1090139240 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1090239643 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1090340382 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1090441181 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1090539387 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1090640705 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1090740620 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1090840412 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1090940998 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1091039936 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
E/caladbolg(  239): 1091140675 cald_capctrl.c                    (7126)  8616 E [CAP] ERROR:PAL QueuePop fail <NotFound>
I/caladbolg(  239): 1091200153 cald_capctrl.c                    (6371)  8616 P [CAP] 1091200123 + Cald_CapCtrl_FSM_Func_StopPreview
I/caladbolg(  239): 1091200245 cald_hal_qct.c                    (3054)  8616 P [HAL] 1091200245 + Cald_Hal_Qct_If_StopPreview
I/caladbolg(  239): 1091201191 cald_hal_qct.c                    (3087)  8616 P [HAL] 1091201191 - Cald_Hal_Qct_If_StopPreview (0)
I/caladbolg(  239): 1091201557 cald_hal_qct.c                    (7007)  8616 P [HAL] 1091201557 + Cald_Hal_Qct_If_DeleteImageConvert
I/caladbolg(  239): 1091202290 cald_hal_qct.c                    (7036)  8616 P [HAL] 1091202290 - Cald_Hal_Qct_If_DeleteImageConvert (0)
I/caladbolg(  239): 1091207935 cald_capctrl.c                    (6382)  8616 P [CAP] 1091207905 - Cald_CapCtrl_FSM_Func_StopPreview
I/caladbolg(  239): 1091208241 cald_hal_qct.c                    (2863)  8614 P [HAL] 1091208058 + Cald_Hal_Qct_If_PowerDown
I/ActivityManager(  560): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10200000 cmp=com.anddoes.launcher/.Launcher} from pid 560
E/DASH - ak897x(  560): ak897x_activate: unable to set accelerometer delay!
D/CAM_PhotoModule( 8540): remove idle handleer in onPause
V/CAM_PhotoModule( 8540): On pause.
I/AKMD2   (  243): akmd2 : Compass Closed.
V/CAM_PhotoModule( 8540): stopPreview
I/caladbolg(  239): 1091752003 cald_hal_qct.c                    (2891)  8614 P [HAL] 1091751972 - Cald_Hal_Qct_If_PowerDown (0)
I/caladbolg(  239): 1091752155 cald_hal_qct.c                    (2789)  8614 P [HAL] 1091752155 + Cald_Hal_Qct_If_PowerUp
I/caladbolg(  239): 1091752949 cald_hal_qct.c                    (2847)  8614 P [HAL] 1091752766 - Cald_Hal_Qct_If_PowerUp (0)
W/ActivityManager(  560): Activity pause timeout for ActivityRecord{42128e48 u0 com.android.camera2/com.android.camera.CameraLauncher t30}
I/caladbolg(  239): 1091935597 cald_capctrl.c                    (6128)  8616 P [CAP] 1091935566 + Cald_CapCtrl_FSM_Func_StartPreview
I/caladbolg(  239): 1091956745 cald_hal_qct.c                    (2983)  8616 P [HAL] 1091956715 + Cald_Hal_Qct_If_StartPreview
I/caladbolg(  239): 1092025990 cald_hal_qct.c                    (3042)  8616 P [HAL] 1092025990 - Cald_Hal_Qct_If_StartPreview (0)
I/caladbolg(  239): 1092026112 cald_hal_qct.c                    (6612)  8616 P [HAL] 1092026112 + Cald_Hal_Qct_If_CreateImageConvert
I/caladbolg(  239): 1092027119 cald_hal_qct.c                    (6890)  8616 P [HAL] 1092027088 - Cald_Hal_Qct_If_CreateImageConvert (0)
I/caladbolg(  239): 1092027485 cald_capctrl.c                    (6358)  8616 P [CAP] 1092027485 - Cald_CapCtrl_FSM_Func_StartPreview
I/caladbolg(  239): 1092028095 cald_camctrl.c                    (4583)  8614 P [SVR] 1092028065 + Cald_CamCtrl_ICamera_CancelAutoLock
I/caladbolg(  239): 1092028523 cald_camctrl.c                    (9440)  8614 P [SVR] 1092028523 + Cald_CamCtrl_FSM_Func_CancelAutoLock
I/caladbolg(  239): 1092029194 cald_camctrl.c                    (9463)  8614 P [SVR] 1092029194 - Cald_CamCtrl_FSM_Func_CancelAutoLock (0)
I/caladbolg(  239): 1092029835 cald_camctrl.c                    (4588)  8614 P [SVR] 1092029835 - Cald_CamCtrl_ICamera_CancelAutoLock (0)
I/CameraClient(  239): stopPreview: Disable picture related messages
I/caladbolg(  239): 1092032032 cald_camctrl.c                    (4583)  8614 P [SVR] 1092032032 + Cald_CamCtrl_ICamera_CancelAutoLock
I/caladbolg(  239): 1092032856 cald_camctrl.c                    (9440)  8614 P [SVR] 1092032856 + Cald_CamCtrl_FSM_Func_CancelAutoLock
I/caladbolg(  239): 1092033253 cald_camctrl.c                    (9463)  8614 P [SVR] 1092033253 - Cald_CamCtrl_FSM_Func_CancelAutoLock (0)
I/caladbolg(  239): 1092033650 cald_camctrl.c                    (4588)  8614 P [SVR] 1092033650 - Cald_CamCtrl_ICamera_CancelAutoLock (0)
I/caladbolg(  239): 1092034626 cald_capctrl.c                    (6371)  8616 P [CAP] 1092034626 + Cald_CapCtrl_FSM_Func_StopPreview
I/caladbolg(  239): 1092034992 cald_hal_qct.c                    (3054)  8616 P [HAL] 1092034992 + Cald_Hal_Qct_If_StopPreview
I/caladbolg(  239): 1092035969 cald_hal_qct.c                    (3087)  8616 P [HAL] 1092035938 - Cald_Hal_Qct_If_StopPreview (0)
I/caladbolg(  239): 1092036366 cald_hal_qct.c                    (7007)  8616 P [HAL] 1092036335 + Cald_Hal_Qct_If_DeleteImageConvert
I/caladbolg(  239): 1092037098 cald_hal_qct.c                    (7036)  8616 P [HAL] 1092037098 - Cald_Hal_Qct_If_DeleteImageConvert (0)
I/caladbolg(  239): 1092038502 cald_capctrl.c                    (6382)  8616 P [CAP] 1092038502 - Cald_CapCtrl_FSM_Func_StopPreview
V/CAM_PhotoModule( 8540): Close camera device.
I/caladbolg(  239): 1092046223 cald_camctrl.c                    (4583)  8614 P [SVR] 1092046223 + Cald_CamCtrl_ICamera_CancelAutoLock
I/caladbolg(  239): 1092046681 cald_camctrl.c                    (9440)  8614 P [SVR] 1092046681 + Cald_CamCtrl_FSM_Func_CancelAutoLock
I/caladbolg(  239): 1092047077 cald_camctrl.c                    (9463)  8614 P [SVR] 1092047077 - Cald_CamCtrl_FSM_Func_CancelAutoLock (0)
I/caladbolg(  239): 1092047474 cald_camctrl.c                    (4588)  8614 P [SVR] 1092047474 - Cald_CamCtrl_ICamera_CancelAutoLock (0)
I/caladbolg(  239): 1092048206 cald_camctrl.c                    (6729)  8614 P [SVR] 1092048176 + Cald_CamCtrl_PowerDown
I/caladbolg(  239): 1092048573 cald_camctrl.c                    (7575)  8614 P [SVR] 1092048573 + Cald_CamCtrl_FSM_Func_PowerDown
I/caladbolg(  239): 1092061695 cald_hal_qct.c                    (2863)  8614 P [HAL] 1092061665 + Cald_Hal_Qct_If_PowerDown
I/Timeline(  894): Timeline: Activity_idle id: android.os.BinderProxy@41c1f998 time:9772431
I/Timeline(  560): Timeline: Activity_windows_visible id: ActivityRecord{41fb5540 u0 com.anddoes.launcher/.Launcher t1} time:9772841
I/caladbolg(  239): 1092709004 cald_hal_qct.c                    (2891)  8614 P [HAL] 1092709004 - Cald_Hal_Qct_If_PowerDown (0)
I/caladbolg(  239): 1092711201 cald_camctrl.c                    (7613)  8614 P [SVR] 1092711201 - Cald_CamCtrl_FSM_Func_PowerDown (0)
I/caladbolg(  239): 1092711628 cald_camctrl.c                    (6734)  8614 P [SVR] 1092711628 - Cald_CamCtrl_PowerDown (0)
I/CameraClient(  239): Destroying camera 0
I/OMXNodeInstance(  239): OMX_FreeBuffer for buffer header 0x1912858 successful
I/OMXNodeInstance(  239): OMX_FreeBuffer for buffer header 0x1885f60 successful
I/OMXNodeInstance(  239): OMX_FreeBuffer for buffer header 0x1901910 successful
I/OMXNodeInstance(  239): OMX_FreeBuffer for buffer header 0x1902ae8 successful
I/OMXNodeInstance(  239): OMX_FreeBuffer for buffer header 0x1894cd0 successful
I/OMXNodeInstance(  239): OMX_FreeBuffer for buffer header 0x1892a80 successful
I/OMXNodeInstance(  239): OMX_FreeBuffer for buffer header 0x18b1050 successful
I/OMXNodeInstance(  239): OMX_FreeBuffer for buffer header 0x1886820 successful
I/OMXNodeInstance(  239): OMX_FreeBuffer for buffer header 0x1951c40 successful

**Comment by ruv1000** [comment]
I have the same problem!
