### ISSUE TITLE
Internet not working in National Roaming

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#729]
In Poland I am in Play (P4) GSM network. My provider has agrement with others, to use their network if Play has low or none signal.
When I am in location, when I have to use other provider, my phone switch network and all works, except mobile internet. On 10.2 Ther was option to turn on National Data Roaming, but it doesn't help. In 11.0 I don't see this option, but even if I have turned on Data Roaming.
It works on stock rom.

**Comment by mikeNG** [comment]
No logs
