### ISSUE TITLE
[urushi] [cm10.2-20130918] - No flash in Camera

### ISSUE THREAD

**Issue by gederickson** [LegacyXperia/local_manifests#73]
There is no flash setting in camera mode, only in video mode

**Comment by mikeNG** [comment]
Flash is working fine on my urushi

**Comment by gederickson** [comment]
![screenshot_2013-09-29-10-09-29](https://f.cloud.github.com/assets/5266469/1232364/b0544302-28ad-11e3-96c6-b74b9a5dfcb1.jpg)
![screenshot_2013-09-29-10-09-41](https://f.cloud.github.com/assets/5266469/1232365/b05395b0-28ad-11e3-9af3-6f079fd3914b.jpg)

**Comment by mikeNG** [comment]
hmm maybe I forgot to push some change... I will check that

**Comment by gederickson** [comment]
Fixed in latest release 
cm10.2-20131002
thanks
