### ISSUE TITLE
CM11: Haida- Launcher icons are very large by default

### ISSUE THREAD

**Issue by ajitkatte** [LegacyXperia/local_manifests#732]
After update to cm-11-20140604-UNOFFICIAL-LegacyXperia-haida, all icons from launcher are very large by default. I can't change the size of icons. It's very ugly to see such a big icons.
![screenshot_CM11-20140718](https://cloud.githubusercontent.com/assets/3326155/3657980/54c777d2-119d-11e4-85ab-05206d22136c.png)

**Comment by mikeNG** [comment]
Use the latest build
