### ISSUE TITLE
Phone shows contact name for incoming call after a very long delay, if even...

### ISSUE THREAD

**Issue by Itchythefirst** [LegacyXperia/local_manifests#733]
Hello, I have the Nightly build 20140718 - cm-11.0 installed on my iyokan. When someone is calling me, the phone really often does not show the contact name, it shows just phone number. It can take more than 10 seconds to show the name, if even. I have not installed many(<20) app. I use the interactive CPU governor with min. freq.: 122MHz and max. freq.: 1401MHz, so the phone response should be(and it is!) quite good...

I have just experienced the problem for the last incoming call and collected the logs:
kmsg.log:
http://pastebin.com/W2RmBt6g

last_kmsg.log:
http://pastebin.com/ZQHx1k86

logcat.log:
http://pastebin.com/AFCcZKHn

radio.log:
http://pastebin.com/B68CGFi8

system.log:
http://pastebin.com/yn59GvdX

**Comment by FibreFoX** [comment]
it sometimes happens for me too (LT18i /anzu), but i think its cyanogenmod/the phone-app itself due to its async nature of loading that information.

**Comment by wolkenschieber** [comment]
I had the issue with cm10.2 and having it with current cm11.0.

I noticed that only the first lookup of a contact is slow. On second lookup, the contact is found instantly. If you clean the recently opened apps, lookup will be slow again.

**Comment by Itchythefirst** [comment]
I have just experienced the problem with nightly build 20140906 :-(

**Comment by Itchythefirst** [comment]
I am facing this problem almost every day with nightly build 20140906 :-( Is there any hope that it would be solved or improved in future days? Or is there any hack that would help even a little bit?

**Comment by mikeNG** [comment]
I don't think so. What could be done to improve speed is already done. Memory just isn't enough on our devices.

**Comment by mikeNG** [comment]
Nothing can be done to improve this
