### ISSUE TITLE
Phone always rebooting

### ISSUE THREAD

**Issue by harshitsinha** [LegacyXperia/local_manifests#736]
hey mike, i flashed the latest version 0718 cm11 on my neo v and the kernel in the zip.
there's a wierd bug,
since the first boot, if you leave the phone idle for like 5 mins, it reboots
i clean flashed twice, but same result,
i am unable to use the phone, since it always reboots automatically even when you are using the phone
i managed to get a log from the lx app, please look into it
thanks
log http://forum.xda-developers.com/attachment.php?attachmentid=2868530&d=1406211758

**Comment by pcfighter** [comment]
try newest release. If problem still persist, try to boot your phone without microSD card inserted.

**Comment by harshitsinha** [comment]
got the solution, it was my sd card, formatted it
