### ISSUE TITLE
Games are crashing/not responding 

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#737]
Hi,

This ROM is simply awesome for my neo V and loved lot. Iam uing the latest build 0718. But not sure what was the problem since  I can't play most of the game as it showing not responding or crashing once it is opened. For example candy crush saga , it must be compatible with this phone but got crashed after certain minutes. Crash meants like, the game will be opened for some time and get redirected to home page. Could you please advise

**Comment by ghost** [comment]
Hey Mike,

I respect your work and thanks for that. At least you can share the information regarding this rather than closing this ticket.

**Comment by FibreFoX** [comment]
Its probably due to the game itself and our phones not having that much of available free RAM. Did you try stock rom?

**Comment by mikeNG** [comment]
I only look into issues that are properly reported
