### ISSUE TITLE
can't run phone in flashmode\fastboot and write new kernel (cm11,urushi)

### ISSUE THREAD

**Issue by liontari** [LegacyXperia/local_manifests#740]
can't run flashmode\fastboot as often, led got blue\green for a part of second and then phone go to offline charging (which comes if I just put turned off phone on charge) (through ADB phone also won't go to flashmode, just reboot to os)
on phone is cm-11-20140703 nightly 
in all other phone work normally

**Comment by mikeNG** [comment]
Not a ROM issue
