### ISSUE TITLE
No GApps Download available for cm-11

### ISSUE THREAD

**Issue by maystar** [LegacyXperia/local_manifests#744]
Where is the gapps download for cm-11 gone? It was here some time ago: https://s.basketbuild.com/devs/LegacyXperia/gapps/

**Comment by mikeNG** [comment]
Gapps are linked in LX xda threads

**Comment by maystar** [comment]
Hmm, I couldn't find. I start at this page to flash my devices: https://github.com/LegacyXperia/Wiki/wiki/Installing-LegacyXperia-for-Dummies
Neither on this site nor on the linked cm-11 discussion thread (first page) there is a link to a gapps archive. So I guess dummies are not able to install gapps with this how-to.

**Comment by mikeNG** [comment]
Wiki is maintained by community, so it's usually outdated.
http://forum.xda-developers.com/google-nexus-5/themes-apps/standard-minimal-gapps-t2012857
I just updated the wiki page to add this link
