### ISSUE TITLE
[CM11] [iyokan] Can't install any app after uninstalling.

### ISSUE THREAD

**Issue by pteek** [LegacyXperia/local_manifests#747]
I have to manually delete the app data folder from /data/data to successfully reinstall.

Logcat:
I/Timeline(10291): Timeline: Activity_launch_request id:com.android.packageinstaller time:9614245
I/ActivityManager( 2457): START u0 {dat=file:///storage/sdcard0/Download/CallRecorder_v.1.5.9.apk cmp=com.android.packageinstaller/.InstallAppProgress (has extras)} from pid 10291
W/ActivityManager( 2457): No content provider found for permission revoke: file:///storage/sdcard0/Download/CallRecorder_v.1.5.9.apk
I/ActivityManager( 2457): Displayed com.android.packageinstaller/.InstallAppProgress: +226ms
I/Timeline(10291): Timeline: Activity_idle id: android.os.BinderProxy@418edfa0 time:9614554
I/Timeline( 2457): Timeline: Activity_windows_visible id: ActivityRecord{42110d80 u0 com.android.packageinstaller/.InstallAppProgress t28} time:9614807
W/ActivityManager( 2457): No content provider found for permission revoke: file:///storage/sdcard0/Download/CallRecorder_v.1.5.9.apk
I/PackageManager( 2457): Copying native libraries to /data/app-lib/vmdl1227374650
W/PackageManager( 2457): Package couldn't be installed in /data/app/com.skvalex.callrecorder-1.apk
D/InstallAppProgress(10291): Installation error code: -24
I/InstallAppProgress(10291): Finished installing com.skvalex.callrecorder

**Comment by 3adrosy** [comment]
I have the same problem and I can't open any app normally specially gmail app.. Plz help me too

**Comment by pcfighter** [comment]
Try to run "fix permissions" from CWM

**Comment by mikeNG** [comment]
@pcfighter fix permissions is gone from cwm for almost a year

**Comment by pcfighter** [comment]
umm, okay.

so try to install some permission fix app by ADB or gplay. If it won't help, you should reflash the rom with full wipe

**Comment by mikeNG** [comment]
Still an issue? Can't reproduce in any of my 9 devices

**Comment by pteek** [comment]
Didn't happen again. Let's close for now.
