### ISSUE TITLE
CM 11 20140719 urushi - graphical glitches 

### ISSUE THREAD

**Issue by boris199** [LegacyXperia/local_manifests#748]
From version 20140719 graphical glitches are observed after clean install. This occurs everywhere , in the main menu, in camera window and etc... Looks like lack of sync and tear lines....

When i switched back to 20140703 all is ok. So there seem to be something that was changed in the latest build.

logcat.log: http://pastebin.com/3S9hDYq0

Please let me know if you need any other log/info.

Thanks.

**Comment by mikeNG** [comment]
You forgot to flash the kernel
