### ISSUE TITLE
Camera problems [Nightly build 20140718 - cm-11.0 anzu]

### ISSUE THREAD

**Issue by xXZendomXx** [LegacyXperia/local_manifests#749]
Since the last update I have problems with the camera that she does not respond either crashes or can even be opened at all.

Sorry for my English..

**Comment by xXZendomXx** [comment]
why you closed it?

**Comment by mikeNG** [comment]
No logs provided = no issue

**Comment by xXZendomXx** [comment]
Ok -.-
