### ISSUE TITLE
android.process.media crashes with ext4 formatted sd card mounted

### ISSUE THREAD

**Issue by lubo** [LegacyXperia/local_manifests#75]
MediaProvider crashes when it tries to attach ext4 formatted volume. The problem is linux cannot get UUID of the volume from /dev/fuse (which is used for mounting sd card to /storage/sdcard0). To be more accurate, blkid_get_tag_value returns NULL for /dev/fuse.

Here is trace from logcat:

```
E/AndroidRuntime( 3424): FATAL EXCEPTION: main
E/AndroidRuntime( 3424): java.lang.RuntimeException: Unable to get provider com.android.providers.media.MediaProvider: java.lang.IllegalArgumentException: Can't obtain external volume ID for external volume.
E/AndroidRuntime( 3424):    at android.app.ActivityThread.installProvider(ActivityThread.java:5068)
E/AndroidRuntime( 3424):    at android.app.ActivityThread.installContentProviders(ActivityThread.java:4671)
E/AndroidRuntime( 3424):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4611)
E/AndroidRuntime( 3424):    at android.app.ActivityThread.access$1300(ActivityThread.java:153)
E/AndroidRuntime( 3424):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329)
E/AndroidRuntime( 3424):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 3424):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 3424):    at android.app.ActivityThread.main(ActivityThread.java:5289)
E/AndroidRuntime( 3424):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 3424):    at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime( 3424):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
E/AndroidRuntime( 3424):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
E/AndroidRuntime( 3424):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 3424): Caused by: java.lang.IllegalArgumentException: Can't obtain external volume ID for external volume.
E/AndroidRuntime( 3424):    at com.android.providers.media.MediaProvider.attachVolume(MediaProvider.java:5064)
E/AndroidRuntime( 3424):    at com.android.providers.media.MediaProvider.onCreate(MediaProvider.java:596)
E/AndroidRuntime( 3424):    at android.content.ContentProvider.attachInfo(ContentProvider.java:1214)
E/AndroidRuntime( 3424):    at android.content.ContentProvider.attachInfo(ContentProvider.java:1189)
E/AndroidRuntime( 3424):    at android.app.ActivityThread.installProvider(ActivityThread.java:5065)
E/AndroidRuntime( 3424):    ... 12 more
```

**Comment by luisbandalap** [comment]
Android doesn't support ext4 as format for the first partition of sdcard.
you can create another partition for your sdcard, but the first must be formated as fat32 or fat16.

https://jira.cyanogenmod.org/browse/CYAN-332

**Comment by lubo** [comment]
Actually, that's not the problem. Kernel just cannot get UUID of ext4 partition because it's not mounted directly from /dev/block/vold/179:1, but it's mounted through FUSE device (/dev/fuse). You can test it on your PC, try to mount some block device formatted as ext4 using FUSE and `$ blkid` won't show its UUID. Possible workarounds are not to use FUSE or do some customizations in FUSE.

**Comment by luisbandalap** [comment]
i didn't notice that, but if you read from the link i put there's another issue

"MediaProvider is calling android.os.FileUtils.getFatVolumeID() to get an ID to identify the sdcard, but this method, as its name suggests, only works with fat file systems."

even if fuse issue is solved you would get the same crash.

**Comment by lubo** [comment]
I have already investigated this, check out android.os.FileUtils.getVolumeUUID(). I have found it in sources of this ROM and Android actually calls it when it detects ext4 formatted SD card.

**Comment by luisbandalap** [comment]
I see, i tried mounting a sdcard with ext4 and as you said it mounts the sdcard using fuse, after i unmount and mount the sdcard using /dev/block/mmcblk0p1 (where blkid can retrieve the uuid) and i still get the -1 uuid.

**Comment by lubo** [comment]
Well, it's still a problem of kernel. I'd really appreciate if Mike could take a look at this problem himself. I think there's need for deeper configuration of kernel.

**Comment by mikeNG** [comment]
it's not a kernel problem
android doesn't support ext4 as main sdcard partition.
this would require changes in several places, cm-10.2 is now feature-frozen so this won't happen.
maybe we'll have a chance in cm11

**Comment by nupogady** [comment]
CM-10.2-dogo is working fine with an ext4-first-partition on sd-card. CM-10.2 is not the issue.
