### ISSUE TITLE
High battery drain after updating to kitkat 4.4.4 Nightly build 20140718 - cm-11.0

### ISSUE THREAD

**Issue by skarthiksankaran** [LegacyXperia/local_manifests#750]
Hi -

I recently updated my Haida ( xperia neo v ) with the nightly build 20140718 - cm-11.0, But this is causing me a high battery drain, When I look for the apps that is causing the battery drain , I see the Android OS being listed at the top. 

Even when I dont use the phone at night ( say the battery % was 80 ) when I see in the morning the battery % goes below 40 %. 

Is there any way on how this can be fixed. ?

**Comment by 3adrosy** [comment]
Me too with xperia pro

**Comment by Yurik147** [comment]
Same problem with Xperia ST15i

**Comment by jaarandaz** [comment]
I'm having a 5% per hour with light usage and after wiki's recommendations (https://github.com/LegacyXperia/Wiki/wiki/Common-Problems). What was the consumption on CM 10.2?

**Comment by frbrno** [comment]
same problem here.
sk17i
11-20140718-UNOFFICIAL-LegacyXperia-mango
3.4.0-LX+
