### ISSUE TITLE
Google play services stopped working with xperia pro KitKat cm11

### ISSUE THREAD

**Issue by 3adrosy** [LegacyXperia/local_manifests#751]
I need to download apps from Google play but I can't as Google services stopped working. I install in the ROM gaps on your website with the last update. Please help me

**Comment by ghost** [comment]
Did you install Gapps from here: http://forum.xda-developers.com/google-nexus-5/themes-apps/standard-minimal-gapps-t2012857 ?

If not, erase everything, reflash the rom and install GApps Minimal 4.4.4 from the link above. If you need Browser and Calendar sync, install AOSP Calendar Sync 4.4.4 and AOSP Browser Sync 4.4.4 Addon, aswell from the link above.

**Comment by 3adrosy** [comment]
Unfortunately, no I downloaded another one not the minimal. Thank you alot . I will download it and repeat every thing again a.. And I will comment the result. Thank you again

**Comment by 3adrosy** [comment]
Thank you very much. It is done pe rfectly and also all issues is solved like battery power drapin . 
U r great
