### ISSUE TITLE
Clock shown in two places ( center and right side(default)) - Device - Haida

### ISSUE THREAD

**Issue by skarthiksankaran** [LegacyXperia/local_manifests#753]
Hi --

I see that the clock ( time ) is seen in two places. Click on Setting --> Status bar -->Clock style

Select Hidden. After this reboot the phone, Once the phone comes up , it shows the clock in two places, once at the center and another at the right corner. If I go into Setting --> Status bar --> Clock style and choose any option then it works correctly. Somewhere the status bar clock setting is messing up when the phone is rebooted.

**Comment by mikeNG** [comment]
I think this is already fixed in the sources, so just wait for the next build.
