### ISSUE TITLE
[cm11-20140718] [iyokan] battery drain seems like it's related to SD card issues

### ISSUE THREAD

**Issue by dafuki** [LegacyXperia/local_manifests#754]
This issues is only after this update, my previous version was "cm-11-20140620-UNOFFICIAL-LegacyXperia-iyokan".
I've seen a long "suspend_backoff" and thousands of "mmc1_detect" wake locks, and some of the apps say my SD card is not loaded (although it works for those apps too).
This mmc1/wl12xx error repeats many times in the dmesg log (even after a reboot):
http://pastebin.com/x8DscDz7

After connecting the phone to the computer i see many of this:
EXT4-fs (dm-7): re-mounted. Opts
http://pastebin.com/a7hi6XLF

Seems like the WiFi drop bug (which I've always had with LX)  drops the SD card mount?
Any idea? Thanks.

**Comment by xange** [comment]
#643 and direct ur issue there please
