### ISSUE TITLE
[CM11][Self build] Error while building

### ISSUE THREAD

**Issue by pteek** [LegacyXperia/local_manifests#758]
target thumb C++: libexternal <= hardware/qcom/display-caf/libexternal/external.cpp
target thumb C++: libvirtual <= hardware/qcom/display-caf/libvirtual/virtual.cpp
target thumb C: power.msm7x30 <= device/semc/msm7x30-common/power/power.c
target thumb C++: libFFmpegExtractor <= external/stagefright-plugins/libstagefright/FFmpegExtractor/FFmpegExtractor.cpp
target thumb C++: libffmpeg_utils <= external/stagefright-plugins/utils/ffmpeg_source.cpp
external/stagefright-plugins/utils/ffmpeg_source.cpp: In member function 'int android::FFSource::read(unsigned char_, size_t)':
external/stagefright-plugins/utils/ffmpeg_source.cpp:78:14: warning: comparison is always false due to limited range of data type [-Wtype-limits]
target thumb C: libOpenMAXAL <= frameworks/wilhelm/src/xa_entry.c
external/stagefright-plugins/libstagefright/FFmpegExtractor/FFmpegExtractor.cpp: In member function 'android::spandroid::MetaData android::FFmpegExtractor::setAudioFormat(AVStream_)':
external/stagefright-plugins/libstagefright/FFmpegExtractor/FFmpegExtractor.cpp:498:24: error: 'kKeySampleBits' was not declared in this scope
make: **\* [/home/newdev/cm/android/system/out/target/product/iyokan/obj/SHARED_LIBRARIES/libFFmpegExtractor_intermediates/FFmpegExtractor.o] Error 1
make: **\* Waiting for unfinished jobs....

**Comment by mikeNG** [comment]
will be fixed soon

**Comment by pteek** [comment]
Which linux distibution do you use for building? I am fedup with ubuntu and would like to switch :)

**Comment by mikeNG** [comment]
Mint
