### ISSUE TITLE
[CM11-20140718] [Anzu] Phone reboots when thrown

### ISSUE THREAD

**Issue by tangtony** [LegacyXperia/local_manifests#759]
First of all - not a joke. Whenever I place my phone down and it hits a surface even slightly hard, the screen will fade out and reboot. This happens consistently when I throw my phone onto my bed or any other (soft) surface.

system.log:
Device: 11-20140718-UNOFFICIAL-LegacyXperia-anzu
Kernel: 3.4.0-LX+ langes@vbox #1

kmsg.log: http://pastebin.com/zPfxaPPf
last_kmsg.log: http://pastebin.com/AwCAGvVt
logcat.log: http://pastebin.com/N7CyXMFx
radio.log: http://pastebin.com/S9Ef1xVB

**Comment by xange** [comment]
you have might a loose battery, use a small piece of paper fold untill a certain thickness (about 0.5-0.8mm) and then slot it at bottom of the battery and then you see..... or get a new battery...

**Comment by tangtony** [comment]
Thanks for the input, I thought about it and I don't think that's the case. If it was a loose battery, I would've expected the screen to instantly turn off - which is not the case here. In this case the screen darkens and slowly fades out like with some other previous bugs.

**Comment by mikeNG** [comment]
I can't reproduce this and I don't see anything in the logs indicating a crash.

**Comment by tangtony** [comment]
dang, If that's the case, I guess it's probably some hardware problem then..
