### ISSUE TITLE
router crash when connect the smartphone with wifi

### ISSUE THREAD

**Issue by robertolos** [LegacyXperia/local_manifests#76]
I've installed the last Legacy Xperia smultron 10.2 nightly 2013-09-18 on my Xperia mini ST15. When the phone connects to the wireless, the other computer and smartphones connected to the same router cannot navigate on internet. They keep connected but cannot open pages, sometimes the internet navigation works but only for some seconds and is very very slow. Everything goes back normal when I disconnect the Xperia wireless connection.

**Comment by mikeNG** [comment]
wait for next build, this should be fixed

**Comment by robertolos** [comment]
I've updated to the last build 2013-10-01, now the wifi simply don't work :( When I switch the Wi-Fi button in the settings it changes to ON but remains gray and no one network are found.

**Comment by mikeNG** [comment]
flash the included kernel

**Comment by robertolos** [comment]
Thanks solved!
