### ISSUE TITLE
The volume of the speaker of my xperia pro cm11, kitkat not stable (start loudly and goes very low) 

### ISSUE THREAD

**Issue by 3adrosy** [LegacyXperia/local_manifests#760]
I had a disturbed issue, the volume of my xperia pro starts high for 2 seconds and then become so low. Even in while the ringtone. I installed many apps to control the volume without any useful change.  I flashed the rom cm-11-20140718-UNOFFICIAL-LegacyXperia-iyokan and 7-29_GApps_Minimal_4.4.4_signed. please help me and please don't close this issue until solving it.

**Comment by mikeNG** [comment]
No logs provided = no issue.
Follow the bug report rules next time you want to file an issue.

**Comment by 3adrosy** [comment]
ok, i didn't know this before. i am sorry for this.  Any way i will search about these rules and follow it. thank you :)

**Comment by mikeNG** [comment]
Here you are https://github.com/LegacyXperia/Wiki/wiki/Reporting-problems

**Comment by 3adrosy** [comment]
sorry, i have a question i tried to attach the log files as a rar file but i had this text "Unfortunately, we don't support that file type.  Try again with a PNG, GIF, or JPG." 
if i upload it on other website like mediafire, is it allowed?. i am afraid to break the rules. excuse me as  English isn't my mother language. thank you in advance.

**Comment by mikeNG** [comment]
Would be better to post the logs on pastebin or gist so I can directly access them without downloading

**Comment by 3adrosy** [comment]
ok, i thank you. i had to learn new technologies :+1: .  i shared the log files here in gist:

https://gist.github.com/3adrosy/29a24302a193cde432ce

**Comment by 3adrosy** [comment]
@mikeNG  any help here please, the status of my phone go to more no good, the battery is 55% and suddenly it goes to 1% and the phone shut down. I wil try to reflash the phone with the same rom cm11 of kitkat as i loved it very much before these bad cases

**Comment by avinashrocks1990** [comment]
Calibrate your battery it's not the problem of ROM

**Comment by 3adrosy** [comment]
@avinashrocks1990 , thank you for replying to me. but i have another xperia miro with the same battery and i exchanged the battery and it was the same situation the battery goes down in minutes. Also i noticed that the phone didn't charge from the charger but it charged well from connecting usb cable to my laptop. here screenshots from BBS (BetterBatteryStats). i am waiting for your advise, urgently. please check also the instability of my phone speaker volume.
thank you in advance.
![screenshot_2014-08-20-11-05-16](https://cloud.githubusercontent.com/assets/8373655/3989687/0c74968a-28be-11e4-9023-92bafacce376.png)
![screenshot_2014-08-20-11-05-33](https://cloud.githubusercontent.com/assets/8373655/3989688/0c7d2f8e-28be-11e4-9895-6c24ababfdc0.png)
![screenshot_2014-08-20-11-05-39](https://cloud.githubusercontent.com/assets/8373655/3989689/0c86240e-28be-11e4-9767-d0312c745770.png)
![screenshot_2014-08-20-11-05-44](https://cloud.githubusercontent.com/assets/8373655/3989690/0c96c2dc-28be-11e4-8a62-b2195eb41ea9.png)
![screenshot_2014-08-20-11-05-54](https://cloud.githubusercontent.com/assets/8373655/3989691/0cdce406-28be-11e4-9c0d-d72739d7eec7.png)
![screenshot_2014-08-20-11-06-17](https://cloud.githubusercontent.com/assets/8373655/3989692/0ce33aea-28be-11e4-934a-b4982427a691.png)
![screenshot_2014-08-20-11-06-50](https://cloud.githubusercontent.com/assets/8373655/3989693/0cef07ee-28be-11e4-8d6d-c35febf2c11a.png)
![screenshot_2014-08-20-11-07-06](https://cloud.githubusercontent.com/assets/8373655/3989694/0d161c12-28be-11e4-8168-208bdea1c6c1.png)
![screenshot_2014-08-20-11-07-17](https://cloud.githubusercontent.com/assets/8373655/3989695/0d36a9aa-28be-11e4-9700-7d069235b404.png)
![screenshot_2014-08-20-11-48-13](https://cloud.githubusercontent.com/assets/8373655/3989696/0d4103c8-28be-11e4-85c2-0dff5cc3ffaa.png)
![screenshot_2014-08-20-11-48-54](https://cloud.githubusercontent.com/assets/8373655/3989697/0d4c94f4-28be-11e4-90f0-d32a3831e4ae.png)
![screenshot_2014-08-20-11-49-01](https://cloud.githubusercontent.com/assets/8373655/3989698/0d747a8c-28be-11e4-9b9c-8b52093506b3.png)
![screenshot_2014-08-20-11-49-21](https://cloud.githubusercontent.com/assets/8373655/3989699/0d9818ca-28be-11e4-86b6-6a646604311e.png)
![screenshot_2014-08-20-11-49-33](https://cloud.githubusercontent.com/assets/8373655/3989700/0da147ce-28be-11e4-8d65-ddaa3f180289.png)
![screenshot_2014-08-20-11-49-38](https://cloud.githubusercontent.com/assets/8373655/3989701/0dd474be-28be-11e4-8de7-a5f49430c453.png)
![screenshot_2014-08-20-11-49-47](https://cloud.githubusercontent.com/assets/8373655/3989702/0df4e488-28be-11e4-906d-1fb2d312bf39.png)
![screenshot_2014-08-20-11-49-53](https://cloud.githubusercontent.com/assets/8373655/3989703/0e30d39e-28be-11e4-9c01-821b66ee8cb1.png)
![screenshot_2014-08-20-12-46-40](https://cloud.githubusercontent.com/assets/8373655/3989704/0e39032a-28be-11e4-8b86-09780494d365.png)
![screenshot_2014-08-20-12-46-49](https://cloud.githubusercontent.com/assets/8373655/3989705/0e4fb03e-28be-11e4-84e8-d32bd4b4a4e1.png)
![screenshot_2014-08-20-12-47-05](https://cloud.githubusercontent.com/assets/8373655/3989706/0e8f0d38-28be-11e4-824f-e813def75c5d.png)
![screenshot_2014-08-20-12-47-17](https://cloud.githubusercontent.com/assets/8373655/3989707/0e97dfa8-28be-11e4-89a6-a430ae52dba0.png)
![screenshot_2014-08-20-12-47-27](https://cloud.githubusercontent.com/assets/8373655/3989708/0eac60e0-28be-11e4-983a-0224c1ae1923.png)
![screenshot_2014-08-20-12-47-35](https://cloud.githubusercontent.com/assets/8373655/3989709/0f431986-28be-11e4-947f-c4495d6c470c.png)

**Comment by avinashrocks1990** [comment]
Your battery is fine the calibration is wrong
Delete batterystats.bin and then charge the phone to 100% then discharge it until your phone shuts down after 2-3 charge cycles your phone will show correct battery readings and from next time take the pain of using Google search

**Comment by 3adrosy** [comment]
@avinashrocks1990  thank you and sorry for my not good english. i will do your advise accurately. 
but what do you mean with your expression "take the pain of using google search"; you mean that i will have to avoid using it on my phone; or i have to dig and search on google about solutions of my future issues.
sorry again for my english.
and thank you very much

**Comment by avinashrocks1990** [comment]
Use Google search and also search xda forums you will find the detailed solution of your problem
