### ISSUE TITLE
undervoltage interface not workin

### ISSUE THREAD

**Issue by 2vlado** [LegacyXperia/local_manifests#761]
on CM11 20140718 is not working undervoltage interface, every app that supports cpu undervoltage is saying the same: please try kernel offering voltage interface.
Tested on SE Xperia Mini Pro (mango)

<update> problem is present even on CM11 20140814

**Comment by xange** [comment]
if you want undervolt, go opt kernel, but stick to rules, once you are using custom kernel.... DO NOT report your issues here...
