### ISSUE TITLE
The volume of the speaker of my xperia pro cm11, kitkat not stable (start loudly and goes very low)

### ISSUE THREAD

**Issue by 3adrosy** [LegacyXperia/local_manifests#762]
I followed the bugs report rules as well i understand. 
I had a disturbed issue, the volume of my xperia pro starts high for 2 seconds and then become so low. Even in while the ringtone. I installed many apps to control the volume without any useful change. I flashed the rom cm-11-20140718-UNOFFICIAL-LegacyXperia-iyokan and 7-29_GApps_Minimal_4.4.4_signed. please help me. Thank you in advance.

here you are the logs files:
https://www.mediafire.com/?2i3v3hs8x2hvmm2

**Comment by mikeNG** [comment]
I could not reproduce this issue on any of my devices, it's probably a configuration mistake or hardware issue
