### ISSUE TITLE
[cm11] (all builds) music play lags & android os battery drain

### ISSUE THREAD

**Issue by PoryaPHA** [LegacyXperia/local_manifests#763]
Hi mike
I am a Iranian boy
Sorry for false English
I have music lags every seconds & my android os battery drain is very hiiiiiigh in all processor & I/o settings
Tnx for help

**Comment by PoryaPHA** [comment]
???
No answer...

**Comment by pcfighter** [comment]
You have to provide logs, otherwise nobody from us will look into.
