### ISSUE TITLE
Xperia Arc S won't deep sleep

### ISSUE THREAD

**Issue by tomasz89** [LegacyXperia/local_manifests#767]
I've had this problem for many of the recent builds now and can't seem to find the magic solution (even trying the wipe the device 3 times and reboot approaches) so I'll post it here as this happens from a clean device without any other software aside from the stock kernel and ROM.

Device: LT18i
Version: 11-20140817-UNOFFICIAL-LegacyXperia-anzu
Android version 4.4.4
Kernel version 3.4.0-LX+ (langes@vbox #1) Sun Aug 17 01:31:25 WAT 2014

https://gist.github.com/tomasz89/d0b391321a918329ea06

Some usage information:
I control WiFi manually.
Bluetooth I used to just leave on all the time (no toggle). Switching it off all the time makes no difference.
I don't have data with my phone plan so have disabled mobile data; everything that does its data transfers must do so over WiFi (and so only when enabled).

**Comment by mikeNG** [comment]
#643

**Comment by tomasz89** [comment]
Fair enough; I though #643 applied to coconut only..
