### ISSUE TITLE
No deep sleep on latest 0817 build CM11 ARC (anzu)

### ISSUE THREAD

**Issue by tornadox** [LegacyXperia/local_manifests#769]
I've flashed the latest build on top of 0702 build with leaving data, wiped dalvik and cache part, installed gapps and applied mount2sd patch. No reboots, crashes or orher nasty things. Compared to 0702 this build is super responsive and lagless but in CpuSpy I see to deesleep. Phone is all time in 122MHz mode and draining batter. I've hibernated all possible apps with Greenify but that did not helped, reboots also did not help. Logs https://drive.google.com/file/d/0B44u8YzM8nY6My0yY0NZR2VWRUk/edit?usp=sharing

**Comment by s-kostyuk** [comment]
Agree, only WiFi disabling helps. And not always

**Comment by tornadox** [comment]
With disabled wifi and after reboot I get no deep sleep at all.

**Comment by mikeNG** [comment]
#643
