### ISSUE TITLE
[HAIDA][cm-10.2_haida-LX-20131001-NIGHTLY] Fn Button crashes

### ISSUE THREAD

**Issue by shouvikonline** [LegacyXperia/local_manifests#77]
Fn button crashes every time in settings.

This is happening in cm-10.2_haida-LX-20131001-NIGHTLY.
Using the kernel inside the ROM.

Attached is the log.
https://docs.google.com/file/d/0BzhB1IjIFsZkNkNyN0FVTUllSEU/edit?usp=sharing

**Comment by amishmm** [comment]
Happens with coconut too! 20131001-Nightly

Related line from Log: http://pastebin.com/raw.php?i=bGYN4UNk

**Comment by Klami** [comment]
anzu (lt18i) too!  20131001 CM10.2

**Comment by mikeNG** [comment]
It's a CM bug, will be fixed in next build

**Comment by vahiddelnavaz** [comment]
And Me have Problem This Bug Haida 4.3

**Comment by djey47** [comment]
Fixed on Haida, 20131014, CM10.2.

**Comment by vahiddelnavaz** [comment]
Thanks your team , I use this file today morning , <3
