### ISSUE TITLE
[Haida] True 720p not working in latest 20140814 (Only 864x480)

### ISSUE THREAD

**Issue by rkkoszewski** [LegacyXperia/local_manifests#771]
Don't know what logs I should show here to prove it. Can upload a screen shot if needed. 
In previous build 20140718 I could record in smoothly 720p (1280x720) [Really grateful for that].

But in the latest build 20140814 when I set 720p it just records in (864x480). Is it a Bug or should it be like that? It was working butter smoothly in real 720p in last build.

Have noticed that while making the ion->pmem wrapper you disabled 720p temporarly but you enabled it again after some time (And even removed 720p from "Not Working" list). So maybe there is some misconfiguration in the encoder or something.

Somebody with Haida can confirm that in latest build 20140814 true 720p video recording is not working? 

Greetings.

**Comment by godlesplay** [comment]
just flash newer build

**Comment by rkkoszewski** [comment]
I'm allready running the lastest build (20140814). Or you mean compiled from source? Has this been fixed in the new 201408xx then?

**Comment by xange** [comment]
no, latest build was 0816.... https://s.basketbuild.com/devs/LegacyXperia/haida/cm-11.0/nightlies
check again.... the 0814 build has been removed..... the correct build is 0816 where mistakes were fixed... case close

**Comment by rkkoszewski** [comment]
Ok, just upgraded to 0816 and true 720p is working!!! Closing the issue. Thanks for the help.
