### ISSUE TITLE
[satsuma] back and menu buttons not working after 20140814 update

### ISSUE THREAD

**Issue by Larsene** [LegacyXperia/local_manifests#772]
The Back and Menu buttons aren't working anymore after flashing the Nightly build 20140814 - cm-11.

**Comment by mikeNG** [comment]
#12

**Comment by Larsene** [comment]
hmmm, but it's not due to high memory usage in this case...no game, no big apps loaded. directly on boot, the  buttons aren't working... flashing back the Nightly build 20140718 - cm-11.0 solve it anyway ...

**Comment by mikeNG** [comment]
No logs = no issue

**Comment by Larsene** [comment]
Sorry, here is the log : http://www.stalagtic.com/bugreport.zip

**Comment by azakosath** [comment]
Maybe this is the case #349, check it out.

**Comment by Larsene** [comment]
Thanks azakosath, this is this issue. just have to reselect the keyboard to solve it. Thanks again !
