### ISSUE TITLE
gps icon on quick setting bug

### ISSUE THREAD

**Issue by badboyasd** [LegacyXperia/local_manifests#773]
cm 11 16/8 device urushi 
when i turn on gps in setting, the icon gps on quick setting of status bar turn light. when i turn off gps in setting , icon gps on quick setting show battery save. mean gps not go off, it go to batery save. the icon gps on quick setting have 2 choise : turn on, battery saving, no choise to turn off.

**Comment by azakosath** [comment]
This is normal. The pin icon represents location and when it is half lighted means GPS sensor is off. The states of the icon in quick settings panel depend on what you have chosen in location's settings menu. Do some searching before reporting an issue and follow the rules.
Thank you.

**Comment by MardonHH** [comment]
@mikeNG 
close this false report

**Comment by mikeNG** [comment]
The GPS tile was a bit buggy lately but it should be fixed with today's changes from CM
