### ISSUE TITLE
Apps' home shortcuts disappear after reboot (cm11 20140816 urushi)

### ISSUE THREAD

**Issue by theprov** [LegacyXperia/local_manifests#774]
It happens every reboot, but only with apps moved to sd cards. Sometimes they all disappear, sometimes only a few, without a logic.
Some of them (like Facebook or Twitter) also need to re-login in such cases.
Apps moved with https://play.google.com/store/apps/details?id=com.buak.Link2SD&hl=it
LOG

https://www.dropbox.com/s/xg6t5adfn42fmzy/bugreport%20%281%29.zip?dl=0

**Comment by FibreFoX** [comment]
This even happens when having apps moved to SD-card via app-menu. I'm on anzu 11-20140718-build, but if i remember correctly, it was in the build before too. Maybe after a change in handling the SD-card made this bug appear? Maybe something like "sd-card isn't ready when scan for apps is started"?!

**Comment by mikeNG** [comment]
This is an annoying issue of Trebuchet that happens on all CM devices. Temporary solution is to use another launcher
