### ISSUE TITLE
Camera Bug (anzu)

### ISSUE THREAD

**Issue by MardonHH** [LegacyXperia/local_manifests#777]
Hi @mikeNG 
a user of my latest anzu testbuild still reported camera problems.
Video Cam is crashing or not recording.

Steps to reproduce it: (i could also reproduce it)
- Hold Device in portrait mode
- open Cam-App
- switch to Video-Mode
- record Video in portrait orientation
- press stop
- turn device 90° in landscape orientation
- Now press record ->Force Close or recording wont start when no F/C

**Comment by xange** [comment]
Hallon too, on both 0907 build and selfbuild 0911. Restart the phone will solve this.

**Comment by mikeNG** [comment]
No logs
