### ISSUE TITLE
wifi hotspot not working coconut 09-06-14

### ISSUE THREAD

**Issue by lsander** [LegacyXperia/local_manifests#778]
I can turn it on, set all things but devices are not able to connect. Tested with my laptop and friend's phone. Latest build, coconut. Bt tethering and usb tethering is working fine

**Comment by lsander** [comment]
I will put log if you need it. But first want to confirm if it is only me.

Checked and not working only when password is set. If it is open it works ok

**Comment by mikeNG** [comment]
Provide some logs, I can't test it at the moment

**Comment by theapu** [comment]
same problem here. mango.

**Comment by lsander** [comment]
From lxcenter. Collected after turning on wifi hotspot
http://d-h.st/tPD

**Comment by ghost** [comment]
Posting my logcat to gist for faster browsing. I will check aswell if I see something suspicious.

https://gist.github.com/skaveelicious/64a0d5257b84beb4bb2c

**Comment by mikeNG** [comment]
Maybe you can revert the two experimental p2p patches and test again

**Comment by ghost** [comment]
I guess it's done something like this.

Revert to a state prior the commit that added those cherries (Add mp3 patch) by doing:

```
git checkout a6d4efefcd8d351aa5eda4523d6431508909b287
```

then 

```
curl https://raw.githubusercontent.com/LegacyXperia/local_manifests/cm-11.0/updates.sh > ~/android/system/updates.sh
```

and then comment-out these cherries

```
# Android: Android.mk: Define ANDROID_P2P
cherries+=(70290)
# Android: driver_nl80211: implement NoA/p2p_ps/set_wps_ie stubs
cherries+=(71193)
```

and finally

```
chmod a+x updates.sh
./updates.sh
```

right?

**Comment by fqdb** [comment]
It works on my hallon if set it on 'open'  (no password), but even then, only one client can use the connection simultaneously.

**Comment by ghost** [comment]
It's fixed in the latest source. This can be closed.
