### ISSUE TITLE
Wi-fi doesn't work after update (urushi 2014-09-06 + gapps minimal X edition)

### ISSUE THREAD

**Issue by yellowmatter** [LegacyXperia/local_manifests#779]
Updated to the latest nightly on top of the previous nightly released, and updated gapps minimal 29-7-14 to the latest minimal X, and the wi-fi does not turn on. The kernel is the one included with the previous nightly.

**Comment by mikeNG** [comment]
You answered your own issue. Follow the rules. You must _always_ flash the included kernel

**Comment by yellowmatter** [comment]
That's what i thought, but wasn't sure. thanks

**Comment by yellowmatter** [comment]
Is it okay if i flash the kernel now? Or do i have to clean everything and flash again the rom and gapps?

**Comment by mikeNG** [comment]
You should be able to flash it now without wiping anything

**Comment by yellowmatter** [comment]
I did it and it all seems to be working fine. thanks for the quick answers
