### ISSUE TITLE
Issues on LX-coconut-1001 build

### ISSUE THREAD

**Issue by gxyf106** [LegacyXperia/local_manifests#78]
The new build has a lot of issues that need to be fixed right away.
Device: coconut (Lww)
Build: lx 1001
1. Home button: the home button does not work. Cannot wake screen from sleep, cannot return to home screen.
2. Wifi : this has been a issue from the previous build itself(build dates:0918, 1001). Cannot toggle WiFi from the quick toggle or from settings! This is bad.
   3.Music ( Walkman) button does not work. It started the music app in the prev build, not working now.
3. Call app lag: there's an unusual lag in the call app. Not present in previous build.

Due to these issues (mainly 1st one), switched back to the previous build. Please fix soon.

Nevertheless great work devs. Keep going.

Fix: proximity sensor issue (thanks :-) )

When is the stable release coming?
Does anyone here know????

TIA devs.

**Comment by gxyf106** [comment]
Oops: 4 issues in all... Sorry for the typo. (3 is occurring 2 times)

**Comment by ghost** [comment]
I feel that nobody competent will ever answer your last question so let me answer it for them: when its done. Any of the above bugs does not occur on anzu (idk about walkman I'm using apollo). And remember if you want to get your bugs fixed you need to provide logs.

**Comment by gxyf106** [comment]
OK.
Please tell me the logs you require.

Thanks

**Comment by mikeNG** [comment]
https://github.com/M66B/cm-xtended/wiki/How-to-report-issues

**Comment by gxyf106** [comment]
Here are the logs.....
https://app.box.com/s/2iq1mbbgl1sjl7dikiry

Also
The vibration intensity is very high while typing.

**Comment by mikeNG** [comment]
Are you sure you are using the kernel from the zip? Issues 1,2,3 indicate that you haven't updated the kernel...

**Comment by gxyf106** [comment]
I am indeed using zip CM 10.2 LX 20131001 NIGHTLY.
these issues were not a problem (except WiFi) in the prev build.
Now I'm back on the prev build 20130918 after getting the logs.
None of the new issues are causing a problem here.

Reverted back mainly due to the home button inactivity.
The home button works like a selector in the new build.
For eg. When pressed in the app launcher, the first app is highlighted.

Thx

**Comment by mikeNG** [comment]
Flashing the kernel included in the zip should solve all issues.

**Comment by gxyf106** [comment]
No..... I used only the zip's kernel....

**Comment by mikeNG** [comment]
You are the only person reporting this bug so you are clearly not doing something right.

If you follow the installation instructions _exactly_, you will have no issues. I have just tested this on my friend's coconut and everything works fine.
