### ISSUE TITLE
[CM11][coconut] 20140906 Minor tile bug in quick access ribbon

### ISSUE THREAD

**Issue by azakosath** [LegacyXperia/local_manifests#784]
The "mobile data" tile in quick access ribbon doesn't show the signal bars, only the type of connection and even the traffic arrows, screenshot below:
![screenshot](https://cloud.githubusercontent.com/assets/5717336/4184206/c10bb83a-3746-11e4-9b4e-8658878d8599.png)

**Comment by mikeNG** [comment]
Will be fixed in next build
