### ISSUE TITLE
haida dialler latest build

### ISSUE THREAD

**Issue by Strike87** [LegacyXperia/local_manifests#786]
when i press on a contact under dialler statistics the dialler stop
http://www.4shared.com/zip/-x1wQ6uFce/bugreport.html

**Comment by rkkoszewski** [comment]
Have the same issue on Haida. Running latest build 20140906.

**Comment by ghost** [comment]
Posting my own logcat to gist for faster browsing:

https://gist.github.com/skaveelicious/c476e1bc1031115aa8c4

**Comment by ghost** [comment]
FYI: This was an CM error btw and should be fixed in the next build.
