### ISSUE TITLE
conflict with viber

### ISSUE THREAD

**Issue by bingsibingsi** [LegacyXperia/local_manifests#787]
in latest build 20140907 smultron,after installing viber and signing in , in a few seconds rom crashes and reboot and after booting up,it crashes again and again.I can just uninstall viber immediately after booting up.

**Comment by Grof87** [comment]
I can confirm the same issue on my smultron. Unfortunately as I said in the forum I'm unable to get logs as in my case Viber autostarts when booting the phone so the phone freezes immediately after getting to the PIN input screen. ON previous CM builds (and every other ROM) there are no issues with Viber.

**Comment by mikeNG** [comment]
Does it soft reboot or hard reboot? If it's a hard reboot, press the button to enter recovery & grab a last_kmsg

**Comment by Grof87** [comment]
Hard reboot. I'm currently on CM10, I'll flash latest CM11 tonight or tomorrow and get the logs for you. Thanks for the help!

**Comment by Grof87** [comment]
Here's the log, there's not much in it.
https://gist.github.com/Grof87/bfd125cf1efb9c7d1802

**Comment by mikeNG** [comment]
This isn't the actual log... boot into recovery, mount sd card in the device, execute 'adb shell cat /proc/last_kmsg > /storage/sdcard0/last_kmsg.txt', then enable mass storage and take last_kmsg.txt from the sd card.

**Comment by Grof87** [comment]
Here's the log (I had some trouble getting it, but finally managed to get it). Hope it helps, and thank you a lot for taking the time to help us out!

https://gist.github.com/Grof87/1600b78654a4f0840035

**Comment by mikeNG** [comment]
Should be fixed in latest build
