### ISSUE TITLE
cm-11-20140907-UNOFFICIAL-LegacyXperia-mango does not work on mango

### ISSUE THREAD

**Issue by Tanzbaerli** [LegacyXperia/local_manifests#788]
I used cm-11-20140816-UNOFFICIAL-LegacyXperia-mango for some time and was very happy with it. So i thought try the new build!

After upgrading (without factory reset; no delete, just installing zip file and gapps) from cm-11-20140816-UNOFFICIAL-LegacyXperia-mango  to cm-11-20140907-UNOFFICIAL-LegacyXperia-mango the keyboard crashes after boot and no more input is possible (neither on screen nor through the hardware keyboard)

Downgraded to cm-11-20140816-UNOFFICIAL-LegacyXperia-mango (without factory reset) and several apps died and the phone did not work any longer.

Then i did a factory reset, formatted system, data and cache and now under  cm-11-20140907-UNOFFICIAL-LegacyXperia-mango it was not possible to turn the WLAN on.

Flashed back after factory reset to build cm-11-20140816-UNOFFICIAL-LegacyXperia-mango  and finally my phone works again!

It seems that the new build does not work for me !?

**Comment by mikeNG** [comment]
WLAN not turning on = you haven't flashed the included kernel.

**Comment by Tanzbaerli** [comment]
Thats correct! 
I thought that "on upgrade" from CM11 to another CM11 version i do not need to flash the kernel !? 

Here http://forum.xda-developers.com/showthread.php?t=2545367 is documented "Steps 1.1, 2 & 3 are not needed when you install new cm11 nightlies on top of older cm11 builds in the future" I thought that you have to install the kernel only once.

Is it possible to upgrade from one CM11 version to another without loosing all settings?

**Comment by mikeNG** [comment]
It says "Steps 1.1, 2 & 3 are not needed when you install new cm11 nightlies on top of older cm11 builds in the future". Step 1 still has to be done on every update. You should be able to upgrade without losing anything if you follow the installation steps correctly

**Comment by Tanzbaerli** [comment]
That "1.1" was a little confusing because 1 should be done!
But thank you, now its clear for me how it should work!

By the way ... Great work! I love my Xperia Mini Pro with your ROM!
