### ISSUE TITLE
Activate EAP-SIM

### ISSUE THREAD

**Issue by Larsene** [LegacyXperia/local_manifests#791]
Do you know if it's possible to activate the EAP-SIM wifi identification system in this rom ?

https://code.google.com/p/seek-for-android/wiki/EapSimAka

Anyway, thanks for your work. I will donate later this month to support your work.

**Comment by pcfighter** [comment]
it should be possible, the author of eapsimaka shared patches for android source

**Comment by mikeNG** [comment]
I doubt it, the patches are ancient (for gingerbread)

**Comment by pcfighter** [comment]
if you're right, why author posted instructions for building android for 4.4 ? He just said it's not tested on 2.3+

**Comment by mikeNG** [comment]
Where are the instructions for 4.4? I only see instructions for 2.3 and ancient wpa_supplicant_6

**Comment by pcfighter** [comment]
https://code.google.com/p/seek-for-android/wiki/BuildingTheSystem

anyway, it's not tested, we shouldn't merge it yet.

**Comment by mikeNG** [comment]
'It is essential that the device supports the necessary RIL and baseband modifications to allow APDU access to the SIM card, otherwise SIM access will not work!'

**Comment by pcfighter** [comment]
nevermind xD it will not work as hell

cos baseband is precompiled by vendor

**Comment by mikeNG** [comment]
One question: Does it work in stock ICS? If yes, there's little possibility that it can work here too

**Comment by llemoux** [comment]
Hi,

As far as I know, 2011 devices Stock ICS do not support EAP SIM. The first phone to support EAP SIM was the Xperia U in 2012. Could its RIL be re-used ?

Regards

**Comment by mikeNG** [comment]
No. RIL is baseband-specific and you can't cross flash basebands since they are device and chipset-specific.
