### ISSUE TITLE
ambiguous column name: account_name

### ISSUE THREAD

**Issue by Seegras** [LegacyXperia/local_manifests#792]
The newest nightly (20140907, on iyokan) did this: 

W/ContactsDatabaseHelper( 2310): Exception upgrading contacts2.db from 803 to 804 android.database.sqlite.SQLiteException: duplicate column name: subscription (code 1): , while compiling: ALTER TABLE calls ADD subscription INTEGER NOT NULL DEFAULT 0;

Which can be fixed with

sqlite3 /data/data/com.android.providers.contacts/databases/contacts2.db

sqlite> CREATE TABLE tmp_table AS SELECT _id, number, date, duration, type, new, name, numbertype, numberlabel, countryiso, voicemail_uri, is_read, geocoded_location, lookup_uri, matched_number, normalized_number, photo_id, formatted_number, _data, has_content, mime_type, source_data, source_package, state, presentation FROM calls; 
sqlite> drop table calls; 
sqlite> alter table tmp_table rename to calls; 

But then, also this:

E/DatabaseUtils( 2982): android.database.sqlite.SQLiteException: ambiguous column name: account_name (code 1): , while compiling: CREATE VIEW view_contacts AS SELECT contacts._id AS _id,contacts.custom_ringtone AS custom_ringtone, name_raw_contact.display_name_source AS display_name_source, name_raw_contact.display_name AS display_name, name_raw_contact.display_name_alt AS display_name_alt, name_raw_contact.phonetic_name AS phonetic_name, name_raw_contact.phonetic_name_style AS phonetic_name_style, name_raw_contact.sort_key AS sort_key, name_raw_contact.phonebook_label AS phonebook_label, name_raw_contact.phonebook_bucket AS phonebook_bucket, name_raw_contact.sort_key_alt AS sort_key_alt, name_raw_contact.phonebook_label_alt AS phonebook_label_alt, name_raw_contact.phonebook_bucket_alt AS phonebook_bucket_alt, has_phone_number, name_raw_contact_id, lookup, photo_id, photo_file_id, CAST(EXISTS (SELECT _id FROM visible_contacts WHERE contacts._id=visible_contacts._id) AS INTEGER) AS in_visible_group, status_update_id, contacts.contact_last_updated_timestamp, contacts.last_time_contacted AS last_time_contacted, contacts.send_to_voicemail AS send_to_voicemail, contacts.starred AS starred, contacts.pinned AS pinned, contacts.times_contacted AS times_contacted, account_name, account_type, (CASE WHEN photo_file_id IS NULL THEN (CASE WHEN photo_id IS NULL OR photo_id=0 THEN NULL ELSE 'content://com.android.contacts/contacts/'||contacts._id|| '/photo' END) ELSE 'content://com.android.contacts/display_photo/'||photo_file_id END) AS photo_uri, (CASE WHEN photo_id IS NULL OR photo_id=0 THEN NULL ELSE 'content://com.android.contacts/contacts/'||contacts._id|| '/photo' END) AS photo_thumb_uri, 0 AS is_user_profile FROM contacts JOIN raw_contacts AS name_raw_contact ON(name_raw_contact_id=name_raw_contact._id) JOIN accounts AS name_accounts ON(name_raw_contact.account_id=name_accounts._id)

This leads to "Unfortunately the process android.process.acore has stopped", which kills the Dialer, Messaging and Contacts, making the phone unuseable. 

Which is a bug in the code, most probably this one: 
http://www.miui.com/forum.php?mod=viewthread&tid=897489

**Comment by MardonHH** [comment]
@mikeNG should be alraedy fixed by cm
