### ISSUE TITLE
Back camera not working (now with logs)

### ISSUE THREAD

**Issue by Lionhrt** [LegacyXperia/local_manifests#794]
My back camera stop working after make a clean installation to the Nightly build 20140907 - cm-11.0 in my Mango, i open the camera app but no image shown it's a black screen it doesn't matter in wich mode (landscape, video or photo) and when i try to take a picture the app freeze and force close, i already check if the camera is recognized with hardware info app from Playstore and it is recognized. i comeback to original firmware but even there the problem perssist, try another roms same history, am i facing the problem of a bricked camera?

http://pastebin.com/xGSgKwPC <- logcat
http://pastebin.com/Tgpw6qMJ <-kmsg

**Comment by mikeNG** [comment]
There's a possibility that your flex cable is broken if camera doesn't even work on stock ICS
