### ISSUE TITLE
[20140906 Smultron] Music still cuts/stutters despite enabling qcom hardware mp3 decoder

### ISSUE THREAD

**Issue by uriah0** [LegacyXperia/local_manifests#795]
Hello,

I just wanted to let you know (in case you don't already know this) that I'm still experiencing cuts/stutters when playing music on my Xperia Mini. If you'd like me to try and debug the problem, could you please let me know what I need to run and what info will be useful to you?

Thank you,
uriah

**Comment by godlesplay** [comment]
what kind of mp3 are you using? 320kbps or lower? I was using 320kbps only and I didn't have cuts with decoder patch

**Comment by uriah0** [comment]
I'm usually using V0 (VBR) mp3's, which are lower than 320kbps. Actually, I think I remember there being a discussion earlier this year in this bug tracker about the fact that the 320kbps mp3's never had cuts, even before the decoder patch... Only the non-320kbps mp3's had cuts.

Anyway, I was wondering... How many KB's can the mp3 decoder buffer? Because if it's possible to put the entire mp3 file into the buffer, maybe there won't be any cuts anymore. However, I'm not sure how that will work with gapless playback (no cut between songs)...

Cheers,
uriah

**Comment by Stezii** [comment]
I can confirm those cuts (Xperia Mini w PowerAmp/Apollo) at CBR, VBR and ABR (128-320 kbps). Higher bitrates seem to be more susceptible to stutters.

**Comment by ghost** [comment]
Been listening to music via Apollo for about 2h yesterday on different mp3 files. Including 192kbps, 256kbps and did not notice any cuts.

Build is self-compiled from 1-October, I'm testing this one on Anzu and would like to know if anyone here that has build from source in the past days is still experiencing cuts or if they are gone aswell.

**Comment by Stezii** [comment]
Just flashed cm-11-20141006-UNOFFICIAL-LegacyXperia-smultron and tested 320 kbps CBR. Cuts do still exist.

**Comment by mikeNG** [comment]
@Stezii can you provide some logs or some mp3 files to test?

**Comment by Stezii** [comment]
MP3 192 CBR 7 min: http://goo.gl/yop2Wo
Log: http://goo.gl/29hgqs
Started this song a few seconds after logging. 
Cuts appearing at (track time): 01:31, 02:20, 02:42, 03:26, 04:37, 05:04, 05:20, 06:18 and 06:42

Additional info: Backitude is running in the background and is causing those location entrys (I think). Deactivating it doesn't fix it.

**Comment by Madridii** [comment]
I have these stuttering issues on msm7x30 (ancora) deivce too!
I merged all needed commits of HW Mp3 decoder

**Comment by Shirkohn** [comment]
I have this stutterers also repeatedly
Xperia Arc S (anzu)

**Comment by Madridii** [comment]
Stutters happened when you are listening to track from external SD card not in internal

**Comment by rtammekivi** [comment]
Can I get more logs on this problem? Full logcat would be appreciated.

**Comment by mikeNG** [comment]
No logs
