### ISSUE TITLE
[CM11] [coconut] Random reboot build 906

### ISSUE THREAD

**Issue by fabri20** [LegacyXperia/local_manifests#796]
Hi ,
I have a random reboot when launching whatsapp app, only once
logs:  http://www.4shared.com/zip/ijdq0hOXba/bugreport.html?

last_kmsg:

http://pastebin.com/Q2jLTAXd

**Comment by fabri20** [comment]
again

last_kmsg:

http://pastebin.com/789bPQ1j

[ 2411.827270] mdp4_mddi_off: Error, SET_CLK_OFF by force
[ 2412.256988] as3676 0-0040: Shutting down AS3676
[ 2412.264923] MFD is Null
[ 2412.265502] Restarting system with command ''.
[ 2412.266113] msm: proc_comm: proc comm disabled

**Comment by zkhan93** [comment]
maybe a fault sim card, i mean i don't know m noob,have the same case and found that the sim card was creating the issue

**Comment by fabri20** [comment]
should change it?

**Comment by rtammekivi** [comment]
The logs don't show any errors, it's as if it normally shut down/rebooted. If it happens often try removing the sim card and see if it still occurs.

**Comment by fabri20** [comment]
happened again , this time with the new build. Always log shows " MFD is Null " .

I will remove and replace the sim, to see if they fix it, since the random reboots occur within 5 to 7 days and I can not get along without sim hehe.

I leave the last log with build 1006

http://pastebin.com/2FdMUyn9

thanks

**Comment by fabri20** [comment]
appeared again in build 1006 and also log the " MFD is Null" . Should I use the phone as a tablet to prevent this from happening ? without simcard

sorry for my bad english

http://pastebin.com/ZbFUhDRb

**Comment by mikeNG** [comment]
"MFD is Null" doesn't relate to the reboot issue in any way

**Comment by fabri20** [comment]
Sorry , I was told that in another post. What I can do to stop having reboots ?

**Comment by mikeNG** [comment]
last_kmsg doesn't indicate anything about the reboot, you need a logcat before the reboot, which is difficult to get. Can't reproduce on any of my 9 devices in the past months
