### ISSUE TITLE
cm-11-20140906-UNOFFICIAL-LegacyXperia-anzu wont boot after installing

### ISSUE THREAD

**Issue by deagle751** [LegacyXperia/local_manifests#798]
I got cm-11,0-20140121-NIGHTLY-LegacyXperia-anzu installed for the last 8 months and i wanted to upgrade it. remembering how i installed on my last phone i just needed to go to CWM-based recovery and install from .zip but after installing the ROM it got stuck on the LegacyXperia screen when i restarted it, left it for about 30 min and it did nothing ;(. what have i done wrong, what can i do ?

**Comment by FibreFoX** [comment]
You also have to flash the firmware, not just upgrading via CWM.

Did you flash boot.img?

**Comment by mikeNG** [comment]
There are detailed installation instructions on the wiki.
