### ISSUE TITLE
Wrong parted version on haida

### ISSUE THREAD

**Issue by mid-kid** [LegacyXperia/local_manifests#80]
Using the latest update (20131001), when trying to partition the sd using the recovery, everything seems fine, until I check the log:

```
Patitoning SD Card... please wait...
fail1

checking script requirements...
 err: you are not using parted v1.8.8.1.179-aef3!

Done!
```

Running "parted --version" (via adb shell in recovery mode) gives:

```
parted (GNU parted) 1.8.8.1.179-aef3
-snip-
```

Maybe it's the "v" in front of the version number?

EDIT: The option to partition the sd does not exist anymore as of (20131013).

**Comment by mikeNG** [comment]
sd-ext partitioning is broken in 10.2, won't be fixed
maybe we'll have a chance in cm11
