### ISSUE TITLE
Apps disappear after reboot, but they occupy memory still [Urushi 20140906 - cm-11.0]

### ISSUE THREAD

**Issue by theprov** [LegacyXperia/local_manifests#800]
After shut off and power on, I found that a pair of apps disappeared, but since free memory didn't increased, they are actually still installed, but I can't see them anywhere, neither in home or drawer, and in app management too.
After a reboot they reappeared.

LOG
https://www.dropbox.com/s/3syn9dtaduhkka6/bugreport.zip?dl=0

**Comment by kermeat** [comment]
https://github.com/LegacyXperia/local_manifests/issues/774
