### ISSUE TITLE
Conflicts with different bugs 😑 (CM-11-20140907-UNOFFICIAL-LegacyXperia-smultron)

### ISSUE THREAD

**Issue by Meiuwa-zz** [LegacyXperia/local_manifests#801]
Here's I have different bugs since I've used CyanogenMod 11.0 LegacyXperia for my SONY Xperia mini ST15i (smultron)

I've been using CM version 11-20140907-UNOFFICIAL for 2 months and I've been encountered different bugs.

_Browser_ - Having trouble with YouTube, sometimes, after playing few videos, the other next videos you play won't be able to play even after you reboot your phone. 

_LockScreen_ - Sometimes, when the screen is locked for a few minutes and trying to unlock it, it shows only a solid DARK screen, but the Back & Menu buttons has its backlights and the only way to fix this is to remove the battery and power it on again.

_InstaledApps_ - I have installed apps directly to my SD Card using ADB and when it shuts down or rebooting my device my apps resets its settings and info

**Comment by mikeNG** [comment]
File separate bugs for separate issues and provide logs
