### ISSUE TITLE
[cm11-20141006][urushi] Snapchat bugs

### ISSUE THREAD

**Issue by johnnytifosi** [LegacyXperia/local_manifests#807]
I opened a similar issue some months ago but it was closed without being fixed.
There are the following bugs when using Snapchat:
-Flash doesn't work
-Video recording with back camera doesn't work.
-Video recording with front camera doesn't work (also there is a "can't play video" message").

I attach a bug report for each one.

https://www.dropbox.com/s/9jcgjgmdcg861px/bugreport.zip?dl=0

**Comment by johnnytifosi** [comment]
It seems the broken video recording was due to a xposed module, after I disabled all Snapchat related modules it was fixed. I will find which one exactly when I have tome. The flash however is still broken.

**Comment by mikeNG** [comment]
Please post the logs in a site like pastebin or gist so I don't have to download them to read them.

Still an issue in latest build?
