### ISSUE TITLE
[cm11-20141006][smultron] Notification led not pulsing anymore

### ISSUE THREAD

**Issue by wolkenschieber** [LegacyXperia/local_manifests#809]
In current cm11 nightly on smultron the notification led isn't pulsing anymore. In previous version the light of the led faded in, lit and then faded out. Now the light just switches on and off.

This is not a real issue, just a changed behaviour I noticed.

**Comment by rtammekivi** [comment]
Mike removed the feature for now because of #621 .

**Comment by mikeNG** [comment]
We are using the older driver for leds now, so that feature is disabled. It could be possible to reimplement it, but I didn't have the time to look into it.

**Comment by wolkenschieber** [comment]
Sorry. I should have read the release notes. It's all mentioned there :-/
