### ISSUE TITLE
Not able to turn on WiFi in smultron

### ISSUE THREAD

**Issue by pbharathimohan** [LegacyXperia/local_manifests#811]
When the wifi is turned on the toggle switch is not changing its color to blue and its saying that WiFi is turning on but it never turns on. The issue is happening after the 09/07/2014 update and its still exists in 10/06/2014 nightly.

**Comment by Grof87** [comment]
I'm using the latest build on my smultron and have no such issues. Have you tried performing a clean install?

**Comment by rtammekivi** [comment]
Always install new boot image (fastboot flash boot boot.img).
