### ISSUE TITLE
[CM 11] [mango] [2014-10-06] battery die so fast

### ISSUE THREAD

**Issue by minhazminar** [LegacyXperia/local_manifests#813]
i can not use my mini pro continously 2 hour. battery discharge so fast even my phone in sleep mode. what can i do? 

log_cat: --------- beginning of /dev/log/main
I/cm      (  214): ____ _   _ ____ _  _ ____ ____ ____ _  _ _  _ ____ ___ 
I/cm      (  215): |     _/  |**| |\ | |  | | __ |_** |\ | |\/| |  | |  \ 
I/cm      (  216): |___   |   |  | | | |**| |**] |___ | | |  | |**| |**/ 
I/cm      (  219): Welcome to Android 4.4.4 / CyanogenMod-11-20141006-UNOFFICIAL-LegacyXperia-mango 
--------- beginning of /dev/log/system
I/auditd  (  227): Starting up
I/audit_log(  227): Previous audit logfile detected, rotating
E/uim-sysfs(  226): uim: Inside main
E/uim-sysfs(  226): uim:ST built into the kernel ?
E/uim-sysfs(  226): uim:BT driver module un-available... 
E/uim-sysfs(  226): uim:BT driver built into the kernel ?
E/uim-sysfs(  226): uim:FM driver module un-available... 
E/uim-sysfs(  226): uim:FM driver built into the kernel ?
E/uim-sysfs(  226): uim:GPS driver module un-available... 
E/uim-sysfs(  226): uim:GPS driver built into the kernel ?
E/uim-sysfs(  226): uim:FM V4L2 driver module un-available... 
E/uim-sysfs(  226): uim:FM V4L2 driver built into the kernel ?
E/uim-sysfs(  226): uim:unable to chmod /dev/radio0, might not exist
E/uim-sysfs(  226): uim:found bluetooth rfkill entry @ 0
E/uim-sysfs(  226): 
E/uim-sysfs(  226): uim:change mode failed for /sys/class/rfkill/rfkill0/state (1)
E/uim-sysfs(  226): 
E/uim-sysfs(  226): uim:rfkill not enabled in st_drv - BT on from UI might fail
E/uim-sysfs(  226): 
I/AKMD2   (  245): AK8975/B for Android v 2.0.0.---- (Library: v1.2.3.114) started.
I/installd(  238): installd firing up
I/nv_param_loader(  251): read_nv: NV value is active. nv_id=60240 
I/nv_param_loader(  251): main_execution:prox_cal=1
I/nv_param_loader(  261): read_nv: NV value is active. nv_id=60240 
I/nv_param_loader(  261): main_execution:threshold=3
I/Vold    (  222): Vold 2.1 (the revenge) firing up
D/Vold    (  222): Volume sdcard0 state changing -1 (Initializing) -> 0 (No-Media)
D/Vold    (  222): Volume usbdisk state changing -1 (Initializing) -> 0 (No-Media)
W/libc    (  225): WARNING: generic atexit() called from legacy shared library
I/nv_param_loader(  269): read_nv: NV value is active. nv_id=60240 
D/Vold    (  222): Volume sdcard0 state changing 0 (No-Media) -> 2 (Pending)
D/DirectVolume(  222): DirectVolume::handlePartitionAdded -> MAJOR 179, MINOR 1, PARTN 1
D/DirectVolume(  222): DirectVolume::handlePartitionAdded -> MAJOR 179, MINOR 2, PARTN 2
D/DirectVolume(  222): DirectVolume::handlePartitionAdded -> MAJOR 179, MINOR 3, PARTN 3
D/Vold    (  222): Volume sdcard0 state changing 2 (Pending) -> 1 (Idle-Unmounted)
I/nv_param_loader(  269): main_execution:rfilter=0
I/Netd    (  228): Netd 1.0 starting
W/InterfaceController(  228): Warning (dlopen failed: library "/system/lib/libnetcmdiface.so" not found) while opening the net interface command library
V/cyttsp_fw_loader(  291): Cypress TTSP FW Loader.
V/cyttsp_fw_loader(  291): get_bl_info: tts_ver 0x1300, app_id 0x203, app_ver 0x3022, cid 0xc0c1c2
V/cyttsp_fw_loader(  291): New FW from '/system/etc/firmware/touch_mango_hitachi.hex': tts_ver 0x1300, app_id 0x203, app_ver 0x3022, cid 0xc0c1c2
V/cyttsp_fw_loader(  291): Current FW: tts_ver 0x1300, app_id 0x203, app_ver 0x3022, cid 0xc0c1c2
V/cyttsp_fw_loader(  291): Firmware update is not required.
W/libc    (  225): WARNING: generic atexit() called from legacy shared library
W/libc    (  225): WARNING: generic atexit() called from legacy shared library
I/SurfaceFlinger(  231): SurfaceFlinger is starting
I/SurfaceFlinger(  231): SurfaceFlinger's main thread ready to run. Initializing graphics H/W...
D/libEGL  (  231): loaded /vendor/lib/egl/libEGL_adreno.so
D/libEGL  (  231): loaded /vendor/lib/egl/libGLESv1_CM_adreno.so
D/libEGL  (  231): loaded /vendor/lib/egl/libGLESv2_adreno.so
W/Adreno-GSL(  231): <get_panel_settings:3802>: Android framework reported version 2. So, don't force ES30
I/Adreno-EGL(  231): <qeglDrvAPI_eglInitialize:381>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_KK_2.7_RB1.04.04.00.007.018_msm8960_KK_2.7_

**Comment by mikeNG** [comment]
Provide proper logs related to battery drain. Check the wiki for instructions

**Comment by minhazminar** [comment]
which log do you want?

**Comment by minhazminar** [comment]
# 

# General Information

BetterBatteryStats version: 1.16.1.0B2
Creation Date: 2014-10-14 16:09:50
Statistic Type: Unplugged to Current
Since 1 h 15 m 58 s 
VERSION.RELEASE: 4.4.4
BRAND: SEMC
DEVICE: mango
MANUFACTURER: Sony Ericsson
MODEL: SK17i
OS.VERSION: 3.4.0-LX+
BOOTLOADER: unknown
HARDWARE: semc
FINGERPRINT: SEMC/SK17i_1254-2184/SK17i:4.0.4/4.1.B.0.587/tL1_3w:user/release-keys
ID: KTU84Q
TAGS: test-keys
USER: mike
PRODUCT: SK17i
RADIO: 8x55A-AAABQOAZM-203028G-77
Rooted: true
BATTERY_STATS permission granted: true

# XPosed BATTERY_STATS module enabled: false

# Battery Info

Level lost [%]: Bat.: -56% (82% to 26%) [44.4%/h]

# Voltage lost [mV]: (4098-3603) [392.9%/h]

# Other Usage

Deep Sleep (): 3 m 56 s  (236 s) Ratio: 2.4%
Awake (): 1 h 12 m 2 s  (4322 s) Ratio: 94.8%
Screen On (): 1 h 10 m 58 s  (4258 s) Ratio: 93.4%
Moderate Signal (): 3 m 40 s  (220 s) Ratio: 4.8%

# Screen medium (): 1 h 10 m 58 s  (4258 s) Ratio: 93.4%

# Wakelocks (requires root / system app on Android 4.4+)

AudioMix (1013): 8 m 14 s  (494 s) Count:355 10.8%
AudioMix (com.friendlymonster.totalpool.Total Pool): 3 m 5 s  (185 s) Count:239 4.0%
RILJ (Phone): 42 s  (42 s) Count:2215 0.9%
ActivityManager-Launch (Android System): 33 s  (33 s) Count:49 0.7%
BBS_WAKELOCK_WHILE_SAVING_REF (com.asksven.betterbatterystats_xdaedition.BetterBatteryStats): 16 s  (16 s) Count:9 0.4%
AudioMix (Android System): 7 s  (7 s) Count:262 0.2%
AlarmManager (Android System): 4 s  (4 s) Count:213 0.1%
_vibrator_ (Android System): 3 s  (3 s) Count:118 0.1%
SCREEN_FROZEN (Android System): 3 s  (3 s) Count:58 0.1%
AudioMix (UID): 3 s  (3 s) Count:42 0.1%
TimedEventQueue (1013): 2 s  (2 s) Count:19 0.1%
_vibrator_ (UID): 1 s  (1 s) Count:27 0.0%
AlarmManager (com.whatsapp.WhatsApp): 1 s  (1 s) Count:45 0.0%

# NetworkStats (Android System): 1 s  (1 s) Count:13 0.0%

# Kernel Wakelocks 

"DATA5" (): 46 s  (46 s) Cnt:(c/wc/ec)1598/14/1598 0.5%
"mmc1_detect" (): 9 s  (9 s) Cnt:(c/wc/ec)36/0/1 0.1%
"PowerManagerService.WakeLocks" (): 7 s  (7 s) Cnt:(c/wc/ec)2115/0/0 0.1%
"audio_pcm" (): 6 s  (6 s) Cnt:(c/wc/ec)42/0/0 0.1%
"audpp" (): 6 s  (6 s) Cnt:(c/wc/ec)42/0/0 0.1%
"smdcntl0" (): 4 s  (4 s) Cnt:(c/wc/ec)592/0/592 0.0%
"alarm_rtc" (): 2 s  (2 s) Cnt:(c/wc/ec)14/0/2 0.0%
"mmc0" (): 1 s  (1 s) Cnt:(c/wc/ec)33/0/33 0.0%
"PowerManagerService.Broadcasts" (): 1 s  (1 s) Cnt:(c/wc/ec)4/0/0 0.0%
"alarm" ():  (0 s) Cnt:(c/wc/ec)352/0/0 0.0%
"PowerManagerService.Display" ():  (0 s) Cnt:(c/wc/ec)2/0/0 0.0%
"rpcrotuer_smd_xprt" ():  (0 s) Cnt:(c/wc/ec)13766/10/0 0.0%
"KeyEvents" ():  (0 s) Cnt:(c/wc/ec)14382/0/0 0.0%

# "qcril" ():  (0 s) Cnt:(c/wc/ec)7459/0/0 0.0%

# Alarms (requires root)

android (): Wakeups: 5 (4.0 / hr.)
  Alarms: 0, Intent: com.android.server.action.NETWORK_STATS_POLL
  Alarms: 0, Intent: android.net.ConnectivityService.action.PKT_CNT_SAMPLE_INTERVAL_ELAPSED
  Alarms: 0, Intent: android.intent.action.TIME_TICK
  Alarms: 1, Intent: android.content.syncmanager.SYNC_ALARM
  Alarms: 4, Intent: android.app.backup.intent.RUN

com.cyanogenmod.lockclock (): Wakeups: 4 (3.2 / hr.)
  Alarms: 2, Intent: com.cyanogenmod.lockclock.action.CANCEL_LOCATION_UPDATE cmp={com.cyanogenmod.lockclock/com.cyanogenmod.lockclock.weather.WeatherUpdateService}
  Alarms: 2, Intent: {com.cyanogenmod.lockclock/com.cyanogenmod.lockclock.weather.WeatherUpdateService}

com.oasisfeng.greenify (): Wakeups: 2 (1.6 / hr.)
  Alarms: 2, Intent: com.oasisfeng.greenify.CLEAN_NOW cmp={com.oasisfeng.greenify/com.oasisfeng.greenify.CleanerService}
  Alarms: 0, Intent: {com.oasisfeng.greenify/com.oasisfeng.greenify.CleanerService}

com.android.phone (): Wakeups: 2 (1.6 / hr.)
  Alarms: 2, Intent: com.android.internal.telephony.data-stall

com.buak.Link2SD (): Wakeups: 2

**Comment by minhazminar** [comment]
dmesg log: 2200 mV normal 
<6>[    4.322570] ldo19: 2400 <--> 2500 mV normal 
<6>[    4.322875] ldo20: 1500 <--> 3050 mV normal 
<6>[    4.323272] ldo21: 1100 mV normal 
<6>[    4.323577] ldo22: 1200 <--> 1300 mV normal 
<6>[    4.323883] ldo23: 1350 mV normal 
<6>[    4.324279] ldo24: 1200 mV normal 
<6>[    4.324584] ldo25: 1200 mV normal 
<6>[    4.324890] lvsw0: normal 
<6>[    4.325347] lvsw1: normal 
<6>[    4.325653] ncp: 1800 mV normal 
<6>[    4.326751] pm8058_probe: PMIC revision: E3
<6>[    4.327484] gpiochip_add: registered GPIOs 182 to 221 on device: pm-gpio
<6>[    4.328247] pm_gpio_probe: OK: base=182, ngpio=40
<6>[    4.328521] gpiochip_add: registered GPIOs 222 to 233 on device: pm8xxx-mpp
<6>[    4.328857] pm8xxx_mpp_probe: OK: base=222, ngpio=12
<4>[    4.333038] smps3: Failed to create debugfs directory
<6>[    4.334167] snddev_poweramp_gpio_init 
<4>[    4.334411] ncp: Failed to create debugfs directory
<6>[    4.335083] aux_pcm_gpio_init 
<4>[    4.335906] ldo10: Failed to create debugfs directory
<4>[    4.337127] ldo08: Failed to create debugfs directory
<5>[    4.372222] Boot Reason = 0x3a0000
<6>[    4.372375] hw-breakpoint: found 3 (+1 reserved) breakpoint and 1 watchpoint registers.
<6>[    4.372619] hw-breakpoint: maximum watchpoint size is 8 bytes.
<6>[    4.375640] fs_gfx2d0: normal 
<6>[    4.376586] fs_gfx3d: normal 
<6>[    4.376953] fs_mdp: normal 
<6>[    4.377746] fs_mfc: normal 
<6>[    4.378265] fs_rot: normal 
<6>[    4.378906] fs_vfe: normal 
<6>[    4.379394] fs_vpe: normal 
<6>[    4.393127] bio: create slab <bio-0> at 0
<6>[    4.393798] ION heap vmalloc created
<6>[    4.394042] ION heap mm created at 0 with size 3000000
<6>[    4.394226] ION heap audio created at e100000 with size 200000
<6>[    4.394470] ION heap sf created at e300000 with size 1c00000
<6>[    4.394653] ION heap wb created at ff00000 with size e1000
<5>[    4.395172] pm8xxx_pwm_probe: OK
<5>[    4.395660] SCSI subsystem initialized
<6>[    4.395965] usbcore: registered new interface driver usbfs
<6>[    4.396301] usbcore: registered new interface driver hub
<6>[    4.396545] usbcore: registered new device driver usb
<6>[    4.397003] msm_i2c_probe
<6>[    4.397247] msm_i2c_probe: clk_ctl 35d, 100000 Hz
<6>[    4.398071] msm_i2c_probe
<6>[    4.398468] msm_i2c_probe: clk_ctl 35d, 100000 Hz
<6>[    4.398895] Linux media interface: v0.10
<6>[    4.399108] Linux video capture interface: v2.00
<6>[    4.399536] Advanced Linux Sound Architecture Driver Version 1.0.25.
<6>[    4.400177] Bluetooth: Core ver 2.16
<6>[    4.400482] NET: Registered protocol family 31
<6>[    4.400604] Bluetooth: HCI device and connection manager initialized
<6>[    4.400878] Bluetooth: HCI socket layer initialized
<6>[    4.401000] Bluetooth: L2CAP socket layer initialized
<6>[    4.401336] Bluetooth: SCO socket layer initialized
<6>[    4.402130] msm_setup_fiq_handler : MSM FIQ handler setup--done
<6>[    4.402282] Switching to clocksource gp_timer
<6>[    4.407562] NET: Registered protocol family 2
<6>[    4.407928] IP route cache hash table entries: 4096 (order: 2, 16384 bytes)
<6>[    4.408569] TCP established hash table entries: 16384 (order: 5, 131072 bytes)
<6>[    4.409027] TCP bind hash table entries: 16384 (order: 4, 65536 bytes)
<6>[    4.409454] TCP: Hash tables configured (established 16384 bind 16384)
<6>[    4.409698] TCP: reno registered
<6>[    4.409820] UDP hash table entries: 256 (order: 0, 4096 bytes)
<6>[    4.409973] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
<6>[    4.410491] NET: Registered protocol family 1
<6>[    4.410919] RPC: Registered named UNIX socket transport module.
<6>[    4.411163] RPC: Registered udp transport module.
<6>[    4.411315] RPC: Registered tcp transport module.
<6>[    4.411560] RPC: Registered tcp NFSv4.1 backchannel transport module.
<6>[    4.411926] Unpacking initramfs...
<6>[    4.501403] Freeing initrd memory: 3816K
<3>[    4.504638] Notify: smsm init
<6>[    4.509246] rpcrouter_smd_r

**Comment by minhazminar** [comment]
logcat: --------- beginning of /dev/log/system
10-14 15:25:20.740 W/ViewRootImpl( 5677): Dropping event due to root view being removed: MotionEvent { action=ACTION_MOVE, id[0]=0, x[0]=227.0, y[0]=-12.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=7145203, downTime=7145186, deviceId=2, source=0x1002 }
10-14 15:27:18.962 W/ViewRootImpl( 5677): Dropping event due to root view being removed: MotionEvent { action=ACTION_MOVE, id[0]=0, x[0]=117.0, y[0]=-24.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=7263845, downTime=7263828, deviceId=2, source=0x1002 }
10-14 15:27:43.386 W/ViewRootImpl( 5677): Dropping event due to root view being removed: MotionEvent { action=ACTION_MOVE, id[0]=0, x[0]=144.0, y[0]=-24.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=7288306, downTime=7288291, deviceId=2, source=0x1002 }
10-14 15:32:08.845 W/ViewRootImpl( 5677): Dropping event due to root view being removed: MotionEvent { action=ACTION_MOVE, id[0]=0, x[0]=168.0, y[0]=-29.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=7553743, downTime=7553726, deviceId=2, source=0x1002 }
10-14 15:32:11.658 W/ViewRootImpl( 5677): Dropping event due to no window focus: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=158, metaState=0, flags=0xc8, repeatCount=1, eventTime=7556432, downTime=7555931, deviceId=10, source=0x101 }
10-14 15:32:11.658 W/ViewRootImpl( 5677): Dropping event due to no window focus: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=158, metaState=0, flags=0x48, repeatCount=2, eventTime=7556483, downTime=7555931, deviceId=10, source=0x101 }
10-14 15:32:11.668 W/ViewRootImpl( 5677): Dropping event due to no window focus: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=158, metaState=0, flags=0x48, repeatCount=3, eventTime=7556588, downTime=7555931, deviceId=10, source=0x101 }
--------- beginning of /dev/log/main
10-14 16:09:01.959 D/dalvikvm( 8498): Late-enabling CheckJNI
10-14 16:09:02.119 D/ActivityThread( 8498): handleBindApplication:com.asksven.betterbatterystats_xdaedition
10-14 16:09:02.119 D/ActivityThread( 8498): setTargetHeapUtilization:0.25
10-14 16:09:02.119 D/ActivityThread( 8498): setTargetHeapMinFree:524288
10-14 16:09:02.199 I/StatsActivity( 8498): OnCreated called
10-14 16:09:02.199 I/dalvikvm( 8498): DexOpt: illegal method access (call Landroid/content/res/TypedArray;.<init> (Landroid/content/res/Resources;[I[II)V from Landroid/content/res/XResources$XTypedArray;)
10-14 16:09:02.199 I/dalvikvm( 8498): Could not find method android.content.res.TypedArray.<init>, referenced from method android.content.res.XResources$XTypedArray.<init>
10-14 16:09:02.199 W/dalvikvm( 8498): VFY: unable to resolve direct method 82: Landroid/content/res/TypedArray;.<init> (Landroid/content/res/Resources;[I[II)V
10-14 16:09:02.199 D/dalvikvm( 8498): VFY: replacing opcode 0x70 at 0x0002
10-14 16:09:02.389 I/ReferenceStore( 8498): Populating cache
10-14 16:09:02.389 I/ReferenceStore( 8498): Added ref ref_boot
10-14 16:09:02.389 I/ReferenceStore( 8498): Added ref ref_unplugged
10-14 16:09:02.389 I/ReferenceStore( 8498): Added ref ref_current
10-14 16:09:02.389 I/ReferenceStore( 8498): Finished populating cache
10-14 16:09:02.459 I/ReferenceStore( 8498): Retrieved reference from storage: Reference ref_unplugged created 1 h 31 m 20 s  (Wl: 3 elements; KWl: 28elements; NetS: 8 elements; Alrm: 4 elements; Proc: 8 elements; Oth: 4 elements; CPU: 12 elements)
10-14 16:09:02.459 I/StatsActivity( 8498): onCreate state from preferences: refFrom=ref_unplugged refTo=ref_current
10-14 16:09:02.459 I/ReferenceStore( 8498): Retrieved reference from cache: Reference ref_unplugged created 1 h 31 m 20 s  (Wl: 3 elements; KWl

**Comment by mspacek** [comment]
I find that in LX10.2 on my smultron, I get very excessive battery drain, unless I reboot after charging, see #591. I even tried a new battery, but that didn't help. In that issue, I commented that the `rpcrotuer_smd_xprt` line in better battery stats (BBS) seemed suspicious. @minhazminar has the same line:

"rpcrotuer_smd_xprt" (): (0 s) Cnt:(c/wc/ec)13766/10/0 0.0%

with a high count and a non-zero wake count, even though it's using 0s of (kernel?) time. It's also spelled incorrectly, which is a known problem:

http://www.modaco.com/topic/332692-cm7-nightly-discussion-thread-old-please-use-new-thread/page-116#entry1626475

That report was from CM7, my report was from LX10.2, and now this report from LX11 seems to show it's still a problem. So, maybe #591 should be reopened? I'm still a bit too chicken to try LX11 (again) for myself. Didn't work so well for me the first time.

Could someone try renaming `rpc_rotuer` to `rpc_router` in the code (I found two instances when I checked back in May) and compile us a new ROM (or just a new boot.img) to test, to see if that helps?

**Comment by mikeNG** [comment]
It doesn't help, it's just a cosmetic issue and doesn't affect anything. I can't speak about 10.2, haven't used it since almost a year.

**Comment by amirhakh** [comment]
Hello
Thank you for your efforts.

 I am facing the same problem last 8 months. I even bought a new battery, but the problem is not solved. 
The problem gets worse when my phone go in the airplane mode or when I get out of it.. My battery drain about 40%. In the sometimes, it is reduce power concuption by runing "htop" in terminal for few seccond.

I was check this issu in many condition.

Also, when enable "adaptive backlight" in display setting, my display turn of backlight and can not use it. I forced to reset my phone.

**Comment by metafold-dev** [comment]
You try to do the battery calibration

2014-12-01 14:17 GMT+02:00 امیر حاجی علی خمسه notifications@github.com:

**Comment by amirhakh** [comment]
yes.

I was try two diffrent app and try to delete batteryState.bin in full charge mode.

In cm 10.1 & 10.2 i work with my phone about 4 day but in cm 11 it work max 1.5 day.

**Comment by mikeNG** [comment]
Improper/incomplete logs

**Comment by realcatgirly** [comment]
i just bought a new battery. now my phone gets trough a whole day
