### ISSUE TITLE
Xperia Mini Pro HW Keyboard light always on

### ISSUE THREAD

**Issue by dalef29** [LegacyXperia/local_manifests#814]
I have installed the 11.0 20141006 on my Xperia Mini Pro SK17I and it runs excellently, so far not found any issues, the touch screen response time is a little slow but that could be me.  What i did notice is that my battery was draining faster.  Initially I thought it was because I was using it more but have since realized that the HW keyboard light is always on even when the screen slide is closed.  I believe this is the cause of the added drain on the battery oh and the (back, home and options buttons) lights don't work but did prior to firmware upgrade.

Is there anyway to correct this?  

The sym button does not would via web browser but is ok in email, playstore and general system windows but this is a know issue, anyone made progress on correcting this? 

With all that said, still worth the upgrade :) so thank you for all your efforts.

**Comment by mikeNG** [comment]
Have you flashed the included kernel?

**Comment by dalef29** [comment]
Thank you for your reply,

I did have some difficulty initially getting my phone to take the rom so I am not totally sure that everything was flashed correctly.  I did as follows,

1) I downloaded. Cm-11 201406... rom, gapps 
2) Unlocked the bootloader with a code from sony
3) Using flashtool, I used fastboot option to flash boot.img.  this is where I may have gone wrong.  I did not use doomlord to flash the kernal, I selected the middle option to flash the rom , I unzipped the rom file to be able to find the boot.img file.  I selected said file and started the flash, it took three or four goes before it would accept the file, not sure why.

I was not sure if unzipping the rom was the correct way to obtain the boot.img file or if I had to rename .zip to .img as I could not select the zip rom file directly.

4) now I can boot to CW-recovery, I had to format system, data and cache, then installed the zipped rom file from sdcard.

in the descrition to install the firmware, there was update.zip. I do not have a file or could not find update.zip so guessed this ment to update the phone rom with the zip file.
5) I wiped the cache before installing gapps minimal.

The phone was then rebooted and almost everything work apart from wifi which would not activate (I did not notice if the keyboard light had this fault).

I then tried installing version 20141006 by downloading rom to sd card, booting to CW-recovery and formating system, data and cache.  Installing zip by selecting the newer zipped rom file.  I then installed the gapps as before, rebooted the phone and this is were I am at now.

I did not rerun the flashtool and use the boot.img file from the newer version of the rom.

Sorry my explanation is so long winded but maybe I missed a process.

I am happy to redo any or all of these processes if needed. :)

**Comment by dalef29** [comment]
Hello again,

In sort NO :)

I thought I would read through the posts (so should have started on the last
page :D)  I did not realize that the kernel needed reloading so ref lashed
the phone with the boot.img from 20141006, formatted, reinstalled rom and
gapps, and guess what: hw keyboard light switch on and off , back button
etc also.

How think do I feel

Thank you so much. 

Any issues I will let you know.
