### ISSUE TITLE
[cm11-20141006][urushi] Proximity Sensor

### ISSUE THREAD

**Issue by theprov** [LegacyXperia/local_manifests#817]
Since last nightly, proximity sensor doesn't work anymore.

https://www.dropbox.com/s/3syn9dtaduhkka6/bugreport.zip?dl=0

**Comment by zweif** [comment]
I had this with self compiled rom few days ago. After reboot it was back. Don't know why it wasn't recognized.

**Comment by mikeNG** [comment]
Please post the logs in a site like pastebin or gist so I don't have to download them to read them.

Still an issue on latest build?
