### ISSUE TITLE
20141006 - cm-11.0 - WiFi hotspot - mogami (mango) - Not fixed

### ISSUE THREAD

**Issue by Kadunki** [LegacyXperia/local_manifests#819]
Hi!

I just installed the 20141006 - cm-11.0 build on my Mango, and was very hopeful to finally be able to use Wifi hotspot.

Not the case. It works exactly as before - as in, not very well. Sometimes you can load one webpage, but then the connection drops. Usually it doesn't work at all.

Thanks for a great ROM, regardless. :-)

**Comment by mikeNG** [comment]
Fixed = works as before, not completely fixed. No way to completely fix it
