### ISSUE TITLE
[CM11] [iyokan] Android OS keep awake (wakelock issue) due to 2G network.

### ISSUE THREAD

**Issue by pteek** [LegacyXperia/local_manifests#824]
I have noticed that rpc_read, mmc1_detect and mmc0 wakelocks don't drain the battery excessively when network mode is set to 3G only.

I have collected logs for about 1 hours twice. Each time, when the network was 3G only, there were no rpc_read, mmc1_detect and mmc0. These came back as soon as I swictehd to 2G only.

I keep my phone in either of the two because the 2G/3G mode results in long hours of no network. I have reported this issue previously and don't know if this is because of my carrier, network conditions or bug in CM. I will also investigate this thoroughly.

I rebooted and deleted battery stats before each of the following test. Phone was not charged during the testing. The wakelocks come back and GO away with network mode(2G/3G only ) even without reboot. I rebooted to get comparable logs.

I am on a test build(20141014). No link2sd or mounts2sd.

https://gist.github.com/pteek/d54abe69283c67cc1b5a

Sorry for the wall of text.

**Comment by mspacek** [comment]
I'll try messing with the 2G/3G setting on my smultron running LX10.2 and report back. I've been having some battery-related problems with it (see #591) and I think rpc stuff might have something to do with it.

**Comment by pteek** [comment]
Any update on this? Still a big issue, I can't use 2G/3G mode because that results in long hours of no network. 2G only drains the battery and 3G only isn't possible because we don't have 100% 3G coverage.

**Comment by mikeNG** [comment]
Please wait for the next build where we included opensource libril to see if there is any improvement

**Comment by pteek** [comment]
This seems like it was a carrier caused issue. It stopped as soon as I changed my provider. My old provider sent a lot of channel-50 broadcast which I couldn't turnoff from the builtin app. So I used to deleted it from /system/app.

I'll close it for now, unless I see this on my new provider.
