### ISSUE TITLE
Boom beach causes kernel panic-cm-11-20141006-anzu

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#827]
Lately after launching some apps(mostly boom beach) my phone just crashes.
http://pastebin.com/ZdeDr7Z2 last_kmsg
http://pastebin.com/iqY2tWdQ dmesg

**Comment by ghost** [comment]
Happened again.
http://pastebin.com/KyeewX0g dmesg
http://pastebin.com/DuJcMHhk last_kmsg
I can provide any other logs if needed.

**Comment by MardonHH** [comment]
Known bug of this Game.
Check Game Forum
So 3rd party problem.

@mikeNG you can close it

**Comment by ghost** [comment]
It happens quite frequently with all "heavy"/"demanding" apps

**Comment by FibreFoX** [comment]
Thats normal, our phone does not have super-powers that modern apps/games are requiring. We can be happy that we can have latest cyanogenmod :)

**Comment by ghost** [comment]
Things like that are pushing me to one m7. So its "normal", ok im closing.

**Comment by mikeNG** [comment]
This might be fixed in the next build, I've picked some kgsl commits from CAF that are related to the crash you get.

**Comment by mikeNG** [comment]
If anyone is interested to test, pull the 'next' kernel branch: https://github.com/LegacyXperia/android_kernel_semc_msm7x30/commits/next

**Comment by ghost** [comment]
I would be interested but i dont know how to pull it.
Or will it be included if I make new build?

**Comment by ghost** [comment]
It's still happening after that commit.
http://pastebin.com/cB81Y1Q7 dmesg
http://pastebin.com/9TDqKuy0 lastkmsg
