### ISSUE TITLE
[Urushi] Notification Light not Pulsing

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#829]
My Notification Light not pulsing at all, but light working fine.
after updating latest build (20141006).
and flash won't turn on??

Log from bug tracker: https://www.dropbox.com/s/xug4fnw5gh96fit/bugreport.rar?dl=0

**Comment by FibreFoX** [comment]
Its no bug, it came with changes of the driver:
https://github.com/LegacyXperia/local_manifests/wiki/Changelog#nightly-build-20141006---cm-110

```
Replace kernel as3676 LED driver with the stock ICS one
Fading led effect is removed since the old driver doesn't support it (at least not yet)
```

**Comment by ghost** [comment]
i see 
so i need to flash new included kernel??? then install ROM???

anyway Thanks

**Comment by mikeNG** [comment]
Per instructions, _ALWAYS_ flash the included kernel
