### ISSUE TITLE
[CM11][IYOKAN]use WIFI can not upload pictures.

### ISSUE THREAD

**Issue by Lawyoryuan** [LegacyXperia/local_manifests#830]
when my phone conected wifi,it can not upload pictures ,like share pictures with twitter.

change another WIFI hotspot is no use.

when I use 2G/3G, share pictures are OK

so what should I do?

**Comment by FibreFoX** [comment]
at least you should provide logs

**Comment by mikeNG** [comment]
No logs = no issue
