### ISSUE TITLE
No 3G connection (Hallon)

### ISSUE THREAD

**Issue by EsamShahlol** [LegacyXperia/local_manifests#858]
I had flashed 20141006 into my hallon and it was running smoothly (no bugs) until i updated to 20141224.zip and it seems that i can't connect to 3G. 
My APNs are fine, i tried restoring the previous ROM (20141006) but no luck. It connects only to 2G.
I used Cyandelta app this time just out of curiosity (this when the problem appeared), then flashed the update manually trying to fix it (and i forgot to flash the kernel) lastly wiped everything flashed the kernel and then the update and the problem still there.
I will try to flash mt15i_4.1.b.0.587_global.ftf and start from scratch. i will inform you later.
here are the logs : https://drive.google.com/open?id=0B46h9l8IMP_uc1FCaXVxTEh0emM&authuser=0

**Comment by EsamShahlol** [comment]
flashed mt15i_4.1.b.0.587_global.ftf and the 3g is working again, i'll stick to the stock (which sucks) for a while until some fix is available..

**Comment by mikeNG** [comment]
Please wait for the next build where we included opensource libril to see if there is any improvement

Also please post the logs in a site like pastebin or gist so I don't have to download them to read them.
