### ISSUE TITLE
CM11 [smultron] 20141224 UI/Touch Freeze

### ISSUE THREAD

**Issue by Spyrus** [LegacyXperia/local_manifests#865]
On latest smultron build 20141224 have touchscreen buttons and screen freeze / unrespond, after a call made.
Had to press power + home buttons for hard reset.

**Comment by Tanzbaerli** [comment]
XPERIA Mini pro.
Unlocking the phone on the startscreen sometimes freezes the phone totally (have to remove battery to use it again). I never hat this problem with previous builds.

**Comment by mikeNG** [comment]
No logs = no issue

**Comment by alextsits** [comment]
I have the same problem (smultron). Latest night build (20150326). Currently trying to reproduce to get a log. Seems to be random as of now. Although first time it happened when I was receiving a call. There have been two more times though that I just woke the phone from sleep and couldn't use touchscreen. Please @mikeNG  keep an eye on this issue. I will give log when bug is reproduced.

**Comment by alextsits** [comment]
@mikeNG as promised, I have logs for the touchscreen problem. There is no reboot or anything, so I only give logcat and dmesg, no last_kmsg. I will keep my phone in this state for as long as possible, so as to be able to give more feedback, if you contact me soon enough.
logcat: http://pastebin.com/PFAa1MSc
dmesg: http://pastebin.com/NwCgY5s0
