### ISSUE TITLE
[CM11] anzu, Mobile data doesn't work in national roaming

### ISSUE THREAD

**Issue by 16D** [LegacyXperia/local_manifests#869]
I have problem with Mobile data in roaming. In my network I have option of internal roaming, I can use others networks without extra cost, when I use it to phone it works ok, but it doesn't want to work for mobile data, what log should I make to make easier repairing this issue?

My fiancee have unmodded Galaxy S4 in same network and doesn't have this problem.

**Comment by mikeNG** [comment]
Please wait for the next build where we included opensource libril to see if there is any improvement

**Comment by 16D** [comment]
I have this problem still

**Comment by 16D** [comment]
New logcat on latest 20150407 build
https://www.sendspace.com/file/a8dceq

**Comment by 16D** [comment]
Sorry for archaeology :)

I have changed phone to Z3 Compact and mobile data was not working in roaming too. It was problem with configuration of permissions at my network provider. Mobile data in roaming where blocked.
