### ISSUE TITLE
Mass Storage and Camera

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#87]
1.In Media Storage Mode when i copy some file from my pc to mobile, the transfer speed is very less like 250kb per second.

2.Sometime the camera clarity is not good. Some shadow is coming

**Comment by mikeNG** [comment]
We can't do anything about these 2 issues.
Mass storage is slow in 3.x+ kernels.
Camera is closed source so we can't fix anything.

Next time please open seperate issues for seperate bugs
