### ISSUE TITLE
[cm11][haida] Random lags/freezes

### ISSUE THREAD

**Issue by sknerus75** [LegacyXperia/local_manifests#870]
Hello, I'm using the latest LX CM11 buid (included kernel, clean install). Urfortunately I'm frequently experiencing massive phone freezes and lags, and the only solution is to remove the battery for reboot. Today because of freeze, alarm didn't wake me:p  Any chance for solving this problem? Thanks in advance :)

Logs taken after freeze and reboot here: http://d-h.st/0A5s

**Comment by mikeNG** [comment]
Please post the logs in a site like pastebin or gist, so I don't have to download them to check them
