### ISSUE TITLE
[cm12] outgoing call and data connection does not work and the reason

### ISSUE THREAD

**Issue by SquallATF** [LegacyXperia/local_manifests#871]
I try to compile cm12 but outgoing call and data connection does not work.
I googled and found fakeiccid ([79834](http://review.cyanogenmod.org/#/c/79834/),[79835](http://review.cyanogenmod.org/#/c/79835/)) can make them work, but the two patch are abandoned and replaced by [80227](http://review.cyanogenmod.org/#/c/80227/)
80227 is try to read iccid from sim card, but on my device(xperia arc s) it doesn't work
here is the not work log

> D/SUB     ( 1165): [SubInfoRecordUpdater]handleMessage : <EVENT_QUERY_ICCID_DONE> SIM1
> D/SUB     ( 1165): [SubInfoRecordUpdater]Query IccId fail: com.android.internal.telephony.CommandException: RADIO_NOT_AVAILABLE
> D/SUB     ( 1165): [SubInfoRecordUpdater]sIccId[0] = 
> D/SUB     ( 1165): [SubInfoRecordUpdater]All IccIds query complete
> D/SUB     ( 1165): [SubInfoRecordUpdater][updateSimInfoByIccId]+ Start

and when use fakeiccid the work log is

> D/SUB     (  995): [SubInfoRecordUpdater]handleMessage : <EVENT_QUERY_ICCID_DONE> SIM1
> D/SUB     (  995): [SubInfoRecordUpdater]Query IccId fail: com.android.internal.telephony.CommandException: RADIO_NOT_AVAILABLE
> D/SUB     (  995): [SubInfoRecordUpdater]sIccId[0] = 00000000000001
> D/SUB     (  995): [SubInfoRecordUpdater]All IccIds query complete
> D/SUB     (  995): [SubInfoRecordUpdater][updateSimInfoByIccId]+ Start
> D/SubController(  995): [clearSubInfo]+
> D/SubController(  995): [clearSubInfo]- no simInfo size=0
> D/SUB     (  995): [SubInfoRecordUpdater]insertedSimCount = 1
> D/SubController(  995): [getSubInfoUsingSlotIdWithCheck]+ slotId:0
> D/SubController(  995): [getSubInfoUsingSlotId]- null info return
> D/SUB     (  995): [SubInfoRecordUpdater]No SIM in slot 0 last time
> D/SUB     (  995): [SubInfoRecordUpdater]oldIccId[0] = , sIccId[0] = 00000000000001
> D/SubController(  995): [addSubInfoRecord]+ iccId:00000000000001 slotId:0
> D/SubController(  995): [addSubInfoRecord] SubInfo not ready, name = SIM 1

when use fakeiccid if SubInfoRecordUpdater query iccid failed,it will replice a fake id
but 80227 can get iccid in SIMRecords 

> D/RILJ    ( 1165): [3721]< SIM_IO IccIoResponse sw1:0x90 sw2:0x0
> D/SIMRecords( 1165): [SIMRecords] EVENT_GET_SMS_RECORD_SIZE_DONE Size 176 total 8800 record 50
> D/RILJ    ( 1165): [3728]< SIM_IO IccIoResponse sw1:0x90 sw2:0x0
> D/SIMRecords( 1165): [SIMRecords] iccid: 898600xxxx
> D/SIMRecords( 1165): [SIMRecords] onRecordLoaded 8 requested: true
> D/RILJ    ( 1165): [3729]< SIM_IO IccIoResponse sw1:0x90 sw2:0x0
> D/SIMRecords( 1165): [SIMRecords] MSISDN: xxxxxxx
> D/SIMRecords( 1165): [SIMRecords] onRecordLoaded 7 requested: true
> D/RilRequest( 1165): [3734]< SIM_IO error: com.android.internal.telephony.CommandException: GENERIC_FAILURE ret=IccIoResponse sw1:0x6a sw2:0x82
> D/SIMRecords( 1165): [SIMRecords] Invalid or missing EF[MAILBOX]
> D/SIMRecords( 1165): [SIMRecords] onRecordLoaded 6 requested: true
> D/RILJ    ( 1165): [3735]< SIM_IO IccIoResponse sw1:0x90 sw2:0x0
> D/SIMRecords( 1165): [SIMRecords] EF_AD: 00000002
> D/SIMRecords( 1165): [SIMRecords] setting4 mMncLength=2
> D/SIMRecords( 1165): [SIMRecords] mccmncCode=460005
> D/SIMRecords( 1165): [SIMRecords] update mccmnc=46000

in SubInfoRecordUpdater have very low probability can query iccid success, I try to switch airplane mode many times but only succeeded once

**Comment by mikeNG** [comment]
There are no 'official' cm12 builds

**Comment by SquallATF** [comment]
I know that, I just want to give an idea to solve this problem, but I don't known how to tell you so submit here~ sorry to make you confused.
