### ISSUE TITLE
[cm11 20141224][urushi] Phone not ringing during incoming call

### ISSUE THREAD

**Issue by johnnytifosi** [LegacyXperia/local_manifests#872]
This bug happens randomly and I can't reproduce it. Phone is not set in silent mode and there are no weird profile settings as far as I know. Pretty serious bug I think. I got the logs right after ending the call.

http://pastebin.com/7CEVp10K
http://pastebin.com/Ky40ighq
http://pastebin.com/cVunUWig
http://pastebin.com/mW3h456H
http://pastebin.com/hY0e3eNd

**Comment by mikeNG** [comment]
#855
