### ISSUE TITLE
Offline charging - mango, cm11

### ISSUE THREAD

**Issue by zweif** [LegacyXperia/local_manifests#875]
There seems to be a problem with offline charging. I read that some people can't fully boot their phone after connecting to charger.
As I tried the boot logo didn't disappear and charging status wasn't displayed. So there was no reaction pressing power button. I could reboot using home + power.
Here is last_kmsg (2 tries):
https://www.dropbox.com/s/phyma2euklxwl0k/last_kmsg_1.txt?dl=0
https://www.dropbox.com/s/96yl4k86n2udgql/last_kmsg_2.txt?dl=0

**Comment by UphyGnrz** [comment]
In coconut also. Can't charging when power off mode.

**Comment by UphyGnrz** [comment]
https://www.dropbox.com/s/lg6z39lwc1mxkn5/bugreport.zip?dl=0

**Comment by pingflood** [comment]
Confirmed on Mango and Smultron.

Tried to modify ramdisk (init.rc and init.semc.rc) and delete chargemon to bypass offline charging (to boot when charging), but no success.

**Comment by mikeNG** [comment]
Fixed in http://review.msm7x30.org/181
