### ISSUE TITLE
RILJ wakelock (cm11-10/03/2015)(mango)

### ISSUE THREAD

**Issue by jobbousix** [LegacyXperia/local_manifests#877]
Hi , 
I'm suffering a huge wake lock from phone app under the process RILJ as shown in screenshot tried to fix but no luck . It seem related to the rom it self (?).

**Comment by jobbousix** [comment]
http://www.4shared.com/file/sFbPemXVce/18819.html

**Comment by mikeNG** [comment]
Please follow the bug reporting rules https://github.com/LegacyXperia/Wiki/wiki/Reporting-problems
Logs need to be available to read without downloading them
