### ISSUE TITLE
Some mp3 files won't play

### ISSUE THREAD

**Issue by unrealdtc** [LegacyXperia/local_manifests#880]
I noticed that some of my favorite podcasts suddenly stopped playing in Pocket Casts (with a nasty "Failed" message) so I reinstalled the app and re-downloaded the podcasts, without success. Then I noticed that even the default "Apollo" player wouldn't play those files either.

Basically, I would seem that the Qualcomm mp3 decoder is failing to play certain files.

Example of file not playing: http://feeds.thisamericanlife.org/~r/talpodcast/~5/aGZD8KlU7qA/520.mp3

And below, an extract of the logcat:

<snip>
D/ExtendedUtils( 7421): printFileName fd(18) -> /storage/sdcard0/Android/data/au.com.shiftyjelly.pocketcasts/files/PocketCasts/podcasts/8c716080-ab5a-0132-31a5-0b39892d38e0.mp3
E/WVMExtractor( 7421): Failed to open libwvm.so
D/ExtendedUtils( 7421): extended extractor not needed, return default
E/cutils-trace( 7421): Error opening trace file: No such file or directory (2)
V/MediaFocusControl(  584): updating focussed RCC change to RCD: CallingPackageName:au.com.shiftyjelly.pocketcasts isFocussed:false isAvailable:true
E/AwesomePlayer( 7421): LPAPlayer::Clip duration setting of less than 30sec not supported, defaulting to 60sec
E/QC_MP3DEC( 7421): component_init[0xaf3a8]component init: role = OMX.qcom.audio.decoder.mp3
D/OMXCodec( 7421): Successfully allocated OMX node 'OMX.qcom.audio.decoder.mp3'
I/OMXCodec( 7421): Codec outputs a different number of channels than the input stream contains (contains 1 channels, codec outputs 2 channels).
I/AwesomePlayer( 7421): Could not offload audio decode, try pcm offload (16-bit)
D/AudioPolicyManagerBase( 7421): copl: PCM offload disabled by property audio.offload.pcm.enable
I/OMXCodec( 7421): [OMX.qcom.audio.decoder.mp3] allocating 2 buffers of size 8192 on input port
I/OMXCodec( 7421): [OMX.qcom.audio.decoder.mp3] allocated buffer 0xadf78 on input port
I/OMXCodec( 7421): [OMX.qcom.audio.decoder.mp3] allocated buffer 0xae1a8 on input port
I/OMXCodec( 7421): [OMX.qcom.audio.decoder.mp3] allocating 2 buffers of size 32768 on output port
I/OMXCodec( 7421): [OMX.qcom.audio.decoder.mp3] allocated buffer 0xae3e8 on output port
I/OMXCodec( 7421): [OMX.qcom.audio.decoder.mp3] allocated buffer 0xae650 on output port
I/MediaFocusControl(  584):  AudioFocus  requestAudioFocus() from android.media.AudioManager@41acd770au.com.shiftyjelly.pocketcasts.audio.a@41ec7350
V/MediaFocusControl(  584): updating focussed RCC change to RCD: CallingPackageName:au.com.shiftyjelly.pocketcasts isFocussed:true isAvailable:true
I/MediaFocusControl(  584):   Remote Control   registerMediaButtonIntent() for PendingIntent{41c94b58: PendingIntentRecord{41b4cc38 au.com.shiftyjelly.pocketcasts broadcastIntent}}
V/MediaFocusControl(  584): updating focussed RCC change to RCD: CallingPackageName:au.com.shiftyjelly.pocketcasts isFocussed:false isAvailable:true
V/MediaFocusControl(  584): updating focussed RCC change to RCD: CallingPackageName:au.com.shiftyjelly.pocketcasts isFocussed:true isAvailable:true
E/MediaPlayer( 1730): Should have subtitle controller already set
V/MediaFocusControl(  584): updating focussed RCC change to RCD: CallingPackageName:au.com.shiftyjelly.pocketcasts isFocussed:false isAvailable:true
V/MediaFocusControl(  584): updating focussed RCC change to RCD: CallingPackageName:au.com.shiftyjelly.pocketcasts isFocussed:true isAvailable:true
E/AwesomePlayer( 7421): LPAPlayer::Clip duration setting of less than 30sec not supported, defaulting to 60sec
D/AudioPlayer( 7421): start of Playback, useOffload 0
I/OMXNodeInstance( 7421): OMX_FreeBuffer for buffer header 0xae3e8 successful
I/OMXNodeInstance( 7421): OMX_FreeBuffer for buffer header 0xae650 successful
I/OMXCodec( 7421): [OMX.qcom.audio.decoder.mp3] allocating 2 buffers of size 32768 on output port
I/OMXCodec( 7421): [OMX.qcom.audio.decoder.mp3] allocated buffer 0xac620 on output port
I/OMXCodec( 7421): [OMX.qcom.audio.decoder.mp3] allocated buffer 0xac8a8 on output port
F/OMXCodec( 7421): frameworks/av/media/libstagefright/OMXCodec.cpp:3529 CHECK_EQ( (int)mState,(int)EXECUTING) failed: 7 vs. 4
F/libc    ( 7421): Fatal signal 6 (SIGABRT) at 0x00001cfd (code=-6), thread 7623 (OMXCallbackDisp)
I/DEBUG   (  231): **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* ***
I/DEBUG   (  231): Build fingerprint: 'SEMC/SK17i_1254-2184/SK17i:4.0.4/4.1.B.0.587/tL1_3w:user/release-keys'
I/DEBUG   (  231): Revision: '0'
I/DEBUG   (  231): pid: 7421, tid: 7623, name: OMXCallbackDisp  >>> /system/bin/mediaserver <<<
I/DEBUG   (  231): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
W/NativeCrashListener(  584): Couldn't find ProcessRecord for pid 7421
I/DEBUG   (  231):     r0 00000000  r1 00001dc7  r2 00000006  r3 00000000
I/DEBUG   (  231): AM write failure (32 / Broken pipe)
I/DEBUG   (  231):     r4 43415dd8  r5 00000006  r6 00000000  r7 0000010c
I/DEBUG   (  231):     r8 000adb20  r9 43415dd0  sl 42d9f9cc  fp 00000000
I/DEBUG   (  231):     ip 00001dc7  sp 43415778  lr 4050b12f  pc 4051a098  cpsr 00030010
I/DEBUG   (  231):     d0  37203a64656c6920  d1  662029474e495476
I/DEBUG   (  231):     d2  4f2f746867697273  d3  2e6365646f43582e
I/DEBUG   (  231):     d4  393235333a707063  d5  455f4b4345484320
I/DEBUG   (  231):     d6  29746e6928202851  d7  282c65746174536d
I/DEBUG   (  231):     d8  0000000146c0d4c1  d9  0000000000000000
I/DEBUG   (  231):     d10 0000000000000000  d11 0000000000000000
I/DEBUG   (  231):     d12 0000000000000000  d13 0000000000000000
I/DEBUG   (  231):     d14 0000000000000000  d15 0000000000000000
I/DEBUG   (  231):     d16 3f17959c986f4e97  d17 3ff0000000000000
I/DEBUG   (  231):     d18 401c000000000000  d19 3f8370dee0000000
I/DEBUG   (  231):     d20 3fc555533bceb625  d21 bf66c168e3a87def
I/DEBUG   (  231):     d22 3f8368ff41104b1b  d23 3fb0000000000000
I/DEBUG   (  231):     d24 3f07b25be6f1e05d  d25 bf07b27620e115d6
I/DEBUG   (  231):     d26 3fffb49800000000  d27 4000000000000000
I/DEBUG   (  231):     d28 3fffd92e017ddf6a  d29 bf8388915620e116
I/DEBUG   (  231):     d30 3ff0000000000000  d31 3fb0271122ac41c2
I/DEBUG   (  231):     scr 20000010
I/DEBUG   (  231): 
I/DEBUG   (  231): backtrace:
I/DEBUG   (  231):     #00  pc 00022098  /system/lib/libc.so (tgkill+12)
I/DEBUG   (  231):     #01  pc 0001312b  /system/lib/libc.so (pthread_kill+50)
I/DEBUG   (  231):     #02  pc 00013323  /system/lib/libc.so (raise+10)
I/DEBUG   (  231):     #03  pc 0001207f  /system/lib/libc.so
I/DEBUG   (  231):     #04  pc 0002194c  /system/lib/libc.so (abort+4)
I/DEBUG   (  231):     #05  pc 00006b53  /system/lib/libcutils.so (__android_log_assert+86)
I/DEBUG   (  231):     #06  pc 0008d525  /system/lib/libstagefright.so (android::OMXCodec::onPortSettingsChanged(unsigned long)+140)
I/DEBUG   (  231):     #07  pc 0008d613  /system/lib/libstagefright.so (android::OMXCodec::onEvent(OMX_EVENTTYPE, unsigned long, unsigned long)+106)
I/DEBUG   (  231):     #08  pc 0008d791  /system/lib/libstagefright.so (android::OMXCodec::on_message(android::omx_message const&)+64)
I/DEBUG   (  231):     #09  pc 0008ddcb  /system/lib/libstagefright.so
I/DEBUG   (  231):     #10  pc 00011b67  /system/lib/libstagefright_omx.so (android::OMXNodeInstance::onMessage(android::omx_message const&)+138)
I/DEBUG   (  231):     #11  pc 0000f93b  /system/lib/libstagefright_omx.so (android::OMX::CallbackDispatcher::loop()+90)
I/DEBUG   (  231):     #12  pc 0000f6d5  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+216)
I/DEBUG   (  231):     #13  pc 0000f1f3  /system/lib/libutils.so
I/DEBUG   (  231):     #14  pc 0000d300  /system/lib/libc.so (__thread_entry+72)
I/DEBUG   (  231):     #15  pc 0000d498  /system/lib/libc.so (pthread_create+240)
I/DEBUG   (  231): 
I/DEBUG   (  231): stack:
I/DEBUG   (  231):          43415738  00000000  
I/DEBUG   (  231):          4341573c  46c0d4c1  
I/DEBUG   (  231):          43415740  00000001  
I/DEBUG   (  231):          43415744  00000000  
I/DEBUG   (  231):          43415748  00000000  
I/DEBUG   (  231):          4341574c  000003ff  
I/DEBUG   (  231):          43415750  00000000  
I/DEBUG   (  231):          43415754  43415d38  [stack:7623]
I/DEBUG   (  231):          43415758  43415d38  [stack:7623]
I/DEBUG   (  231):          4341575c  000adb20  [heap]
I/DEBUG   (  231):          43415760  43415dd0  [stack:7623]
I/DEBUG   (  231):          43415764  42d9f9cc  [stack:7618]
I/DEBUG   (  231):          43415768  403ed5b5  /system/lib/libcutils.so
I/DEBUG   (  231):          4341576c  40f8fb96  /system/lib/libstagefright.so
I/DEBUG   (  231):          43415770  434157e4  [stack:7623]
I/DEBUG   (  231):          43415774  00000000  
I/DEBUG   (  231):     #00  43415778  43415dd8  [stack:7623]
I/DEBUG   (  231):          4341577c  00000006  
I/DEBUG   (  231):          43415780  00000000  
I/DEBUG   (  231):          43415784  00001dc7  
I/DEBUG   (  231):          43415788  00001dc7  
I/DEBUG   (  231):          4341578c  4050b12f  /system/lib/libc.so (pthread_kill+54)
I/DEBUG   (  231):     #01  43415790  43415dd0  [stack:7623]
I/DEBUG   (  231):          43415794  00000006  
I/DEBUG   (  231):          43415798  00000000  
I/DEBUG   (  231):          4341579c  43415d38  [stack:7623]
I/DEBUG   (  231):          434157a0  43415d38  [stack:7623]
I/DEBUG   (  231):          434157a4  4050b327  /system/lib/libc.so (raise+14)
I/DEBUG   (  231):     #02  434157a8  434157b4  [stack:7623]
I/DEBUG   (  231):          434157ac  4050a083  /system/lib/libc.so
I/DEBUG   (  231): 
I/DEBUG   (  231): memory near r1:
I/DEBUG   (  231):     00001da4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001db4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001dc4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001dd4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001de4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001df4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001e04 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001e14 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001e24 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001e34 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001e44 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001e54 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001e64 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001e74 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001e84 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001e94 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231): 
I/DEBUG   (  231): memory near r4:
I/DEBUG   (  231):     43415db8 000ad828 000ad858 42d9fdd8 00000000  
I/DEBUG   (  231):     43415dc8 00000078 4050549c 43415dd0 000ad858  
I/DEBUG   (  231):     43415dd8 00000000 00000000 00000000 2f9c593d  
I/DEBUG   (  231):     43415de8 00000000 00000000 00000000 00000000  
I/DEBUG   (  231):     43415df8 00000000 00000000 00000000 00000000  
I/DEBUG   (  231):     43415e08 00000000 00000000 00000000 00000000  
I/DEBUG   (  231):     43415e18 00000000 00000000 00000000 00000000  
I/DEBUG   (  231):     43415e28 00000000 00000000 00000000 00000000  
I/DEBUG   (  231):     43415e38 00000000 00000000 00000000 00000000  
I/DEBUG   (  231):     43415e48 00000000 00000000 00000000 00000000  
I/DEBUG   (  231):     43415e58 00000000 00000000 00000000 00000000  
I/DEBUG   (  231):     43415e68 00000000 00000000 00000000 00000000  
I/DEBUG   (  231):     43415e78 00000000 00000000 00000000 00000000  
I/DEBUG   (  231):     43415e88 00000000 00000000 00000000 00000000  
I/DEBUG   (  231):     43415e98 00000000 00000000 00000000 00000000  
I/DEBUG   (  231):     43415ea8 00000000 00000000 00000000 00000000  
I/DEBUG   (  231): 
I/DEBUG   (  231): memory near r8:
I/DEBUG   (  231):     000adb00 20202020 513c2020 6b726975 6d616e20  
I/DEBUG   (  231):     000adb10 72223d65 69757165 2d736572 0000010b  
I/DEBUG   (  231):     000adb20 40fb5aa4 40fb5ad8 000a77d0 702d7401  
I/DEBUG   (  231):     000adb30 00000001 20000000 00000000 20200000  
I/DEBUG   (  231):     000adb40 000acf60 000adc40 000a9ee0 000a96d8  
I/DEBUG   (  231):     000adb50 40fb5960 00000000 00000000 00000007  
I/DEBUG   (  231):     000adb60 00000004 00000000 000ade78 000ac520  
I/DEBUG   (  231):     000adb70 00000007 40fb59a8 000ae0d0 00000002  
I/DEBUG   (  231):     000adb80 00000000 0000001c 40fb59a8 000ac3f0  
I/DEBUG   (  231):     000adb90 00000002 00000000 0000001c 00000000  
I/DEBUG   (  231):     000adba0 00000003 20650000 0a3e2d2d 20200100  
I/DEBUG   (  231):     000adbb0 ffffffff ffffffff 00000002 20636564  
I/DEBUG   (  231):     000adbc0 ffffffff ffffffff 6f672e00 000aca60  
I/DEBUG   (  231):     000adbd0 00000000 00000001 fffffff8 79742000  
I/DEBUG   (  231):     000adbe0 00000000 65646976 2d782f6f 40fb4e20  
I/DEBUG   (  231):     000adbf0 000adc60 fffffff8 40fb37b0 000adc70  
I/DEBUG   (  231): 
I/DEBUG   (  231): memory near r9:
I/DEBUG   (  231):     43415db0 000ad828 40505304 000ad828 000ad858  
I/DEBUG   (  231):     43415dc0 42d9fdd8 00000000 00000078 4050549c  
I/DEBUG   (  231):     43415dd0 43415dd0 000ad858 00000000 00000000  
I/DEBUG   (  231):     43415de0 00000000 2f9c593d 00000000 00000000  
I/DEBUG   (  231):     43415df0 00000000 00000000 00000000 00000000  
I/DEBUG   (  231):     43415e00 00000000 00000000 00000000 00000000  
I/DEBUG   (  231):     43415e10 00000000 00000000 00000000 00000000  
I/DEBUG   (  231):     43415e20 00000000 00000000 00000000 00000000  
I/DEBUG   (  231):     43415e30 00000000 00000000 00000000 00000000  
I/DEBUG   (  231):     43415e40 00000000 00000000 00000000 00000000  
I/DEBUG   (  231):     43415e50 00000000 00000000 00000000 00000000  
I/DEBUG   (  231):     43415e60 00000000 00000000 00000000 00000000  
I/DEBUG   (  231):     43415e70 00000000 00000000 00000000 00000000  
I/DEBUG   (  231):     43415e80 00000000 00000000 00000000 00000000  
I/DEBUG   (  231):     43415e90 00000000 00000000 00000000 00000000  
I/DEBUG   (  231):     43415ea0 00000000 00000000 00000000 00000000  
I/DEBUG   (  231): 
I/DEBUG   (  231): memory near sl:
I/DEBUG   (  231):     42d9f9ac 00000004 000adb6c 40fb887c 00000064  
I/DEBUG   (  231):     42d9f9bc 40505d75 40fb5cc0 000a9eb8 42d9fa3c  
I/DEBUG   (  231):     42d9f9cc 40854d99 40fb5cc0 42d9fa3c 000ae7d0  
I/DEBUG   (  231):     42d9f9dc 40ef2dd1 000adb20 40f27af5 000ae650  
I/DEBUG   (  231):     42d9f9ec 40f95191 40f95191 00004000 000c1978  
I/DEBUG   (  231):     42d9f9fc 00010000 40673c19 40f95191 40f95198  
I/DEBUG   (  231):     42d9fa0c 40f95191 40f95198 40f8fb96 000ae1a8  
I/DEBUG   (  231):     42d9fa1c 000ae5f0 000ae650 42d9fb18 00000240  
I/DEBUG   (  231):     42d9fa2c 00000377 00000002 000ae1a8 00000000  
I/DEBUG   (  231):     42d9fa3c 000a9e98 00000000 000ae5f0 00008000  
I/DEBUG   (  231):     42d9fa4c 40885000 000ae760 00000100 00000004  
I/DEBUG   (  231):     42d9fa5c 00000101 00000001 00000001 00000002  
I/DEBUG   (  231):     42d9fa6c 00000002 00008000 00000001 00000000  
I/DEBUG   (  231):     42d9fa7c 00000000 000aad90 00000000 00000001  
I/DEBUG   (  231):     42d9fa8c 00000002 fffffff5 000adbd4 fffffffe  
I/DEBUG   (  231):     42d9fa9c 00000000 42d9fb30 40507028 00000000  
I/DEBUG   (  231): 
I/DEBUG   (  231): memory near ip:
I/DEBUG   (  231):     00001da4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001db4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001dc4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001dd4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001de4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001df4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001e04 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001e14 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001e24 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001e34 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001e44 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001e54 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001e64 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001e74 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001e84 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231):     00001e94 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  231): 
I/DEBUG   (  231): memory near sp:
I/DEBUG   (  231):     43415758 43415d38 000adb20 43415dd0 42d9f9cc  
I/DEBUG   (  231):     43415768 403ed5b5 40f8fb96 434157e4 00000000  
I/DEBUG   (  231):     43415778 43415dd8 00000006 00000000 00001dc7  
I/DEBUG   (  231):     43415788 00001dc7 4050b12f 43415dd0 00000006  
I/DEBUG   (  231):     43415798 00000000 43415d38 43415d38 4050b327  
I/DEBUG   (  231):     434157a8 434157b4 4050a083 00000034 ffffffdf  
I/DEBUG   (  231):     434157b8 00000000 00000000 00000000 2f9c593d  
I/DEBUG   (  231):     434157c8 00000000 40f8fb96 00000000 40519950  
I/DEBUG   (  231):     434157d8 403ed5b5 403edb57 43415bf4 6d617266  
I/DEBUG   (  231):     434157e8 726f7765 612f736b 656d2f76 2f616964  
I/DEBUG   (  231):     434157f8 7362696c 65676174 67697266 4f2f7468  
I/DEBUG   (  231):     43415808 6f43584d 2e636564 3a707063 39323533  
I/DEBUG   (  231):     43415818 45484320 455f4b43 28202851 29746e69  
I/DEBUG   (  231):     43415828 6174536d 282c6574 29746e69 43455845  
I/DEBUG   (  231):     43415838 4e495455 66202947 656c6961 37203a64  
I/DEBUG   (  231):     43415848 2e737620 00003420 00000000 00000000  
I/DEBUG   (  231): 
I/DEBUG   (  231): code around pc:
I/DEBUG   (  231):     4051a078 e8bd00f0 e3700a01 912fff1e e2600000  
I/DEBUG   (  231):     4051a088 ea006eb8 e92d50f0 e3a07f43 ef000000  
I/DEBUG   (  231):     4051a098 e8bd50f0 e3700a01 912fff1e e2600000  
I/DEBUG   (  231):     4051a0a8 ea006eb0 e92d50f0 e3a070ee ef000000  
I/DEBUG   (  231):     4051a0b8 e8bd50f0 e3700a01 912fff1e e2600000  
I/DEBUG   (  231):     4051a0c8 ea006ea8 e1520003 8a00008c f5d1f040  
I/DEBUG   (  231):     4051a0d8 e92d4001 e3520010 3a000024 e2603000  
I/DEBUG   (  231):     4051a0e8 e213300f 0a00000e e0422003 e1b0cf83  
I/DEBUG   (  231):     4051a0f8 44d1e001 44c0e001 24d1c001 24d1e001  
I/DEBUG   (  231):     4051a108 24c0c001 24c0e001 e1b0ce83 aa000001  
I/DEBUG   (  231):     4051a118 f4a1030d f480031d 3a000001 f421070d  
I/DEBUG   (  231):     4051a128 f400071d e2522040 3a000006 f421020d  
I/DEBUG   (  231):     4051a138 f421420d f5d1f100 e2522040 f400022d  
I/DEBUG   (  231):     4051a148 f400422d 2afffff8 e2922020 3a000002  
I/DEBUG   (  231):     4051a158 f421020d e2422020 f400022d e2822020  
I/DEBUG   (  231):     4051a168 e3120010 0a000001 f4210a0d f4000a2d  
I/DEBUG   (  231): 
I/DEBUG   (  231): code around lr:
I/DEBUG   (  231):     4050b10c 4b11ec1c e010447b d10e42bb 480f6a1f  
I/DEBUG   (  231):     4050b11c f7fb4478 f00dec90 4639e9ee f00e462a  
I/DEBUG   (  231):     4050b12c 3001efb0 2500d00a 681be009 d1eb2b00  
I/DEBUG   (  231):     4050b13c 25034807 f7fb4478 e000ec7e 60266825  
I/DEBUG   (  231):     4050b14c bdf84628 0003b294 0003b288 0003b280  
I/DEBUG   (  231):     4050b15c 0003b25c bf82f7ff 4a3a4b39 e92d447b  
I/DEBUG   (  231):     4050b16c b08a47f0 4607589e 6833460d 930946b1  
I/DEBUG   (  231):     4050b17c fa20f001 f8d04604 2d008000 4628d04a  
I/DEBUG   (  231):     4050b18c ff18f00f 4606280f f7ffd846 4287ffe3  
I/DEBUG   (  231):     4050b19c 200fd106 f00d4629 2800e8bc e032d03d  
I/DEBUG   (  231):     4050b1ac 44784829 ebc8f7fb 44784828 42b8e015  
I/DEBUG   (  231):     4050b1bc 6a07d113 44784826 ec3cf7fb 463b4a25  
I/DEBUG   (  231):     4050b1cc 447a2120 f013a801 2101faa1 f01aa801  
I/DEBUG   (  231):     4050b1dc 1c43fdcb d1044607 6800e015 d1e62800  
I/DEBUG   (  231):     4050b1ec 4638e023 46324629 e8f6f00d 3ffff1b0  
I/DEBUG   (  231):     4050b1fc d1024682 29046821 4638d0f3 e946f00d  
I/BootReceiver(  584): Copying /data/tombstones/tombstone_00 to DropBox (SYSTEM_TOMBSTONE)
I/ServiceManager(  223): service 'media.audio_flinger' died
I/ServiceManager(  223): service 'media.player' died
I/ServiceManager(  223): service 'media.camera' died
I/ServiceManager(  223): service 'media.audio_policy' died
W/AudioSystem( 1730): AudioFlinger server died!
W/IMediaDeathNotifier( 1730): media server died
E/MediaPlayer( 1730): error (100, 0)
W/AudioSystem(  584): AudioFlinger server died!
W/AudioSystem(  584): AudioPolicyService server died!
W/CameraBase(  668): Camera service died!
E/AudioService(  584): Media server died.
<snip>

**Comment by unrealdtc** [comment]
It would appear that mono mp3 files are failing to play since I upgraded to 20150309 (not exactly sure which version I had before).

**Comment by johnnytifosi** [comment]
I think this might be related to the bugs I posted about custom ringtones not playing and Apollo skipping tracks. VLC player plays everything seamlessly however.

**Comment by rtsui-harmonicinc** [comment]
VLC doesn't use codec native to system, I think that's why VLC is immune

**Comment by mikeNG** [comment]
I'm afraid I have to remove qcom's mp3 hardware decoder, since it has too many issue currently. This will introduce music skipping again though.

**Comment by johnnytifosi** [comment]
That's too bad :(
For me the ringtone problem was appearing randomly in previous builds, but with the latest build the phone won't ring at all with this certain mp3 file. Similarly, Apollo will persistently force close with that file and some others or skip them if it's playing a playlist, while with the 20141224 build it didn't have this problem that often. It could randomly skip a track but it would play it eventually if I moved back to it. I don't know anything about developing but it looks like some update in the decoder or somewhere else broke more stuff in the latest build. Since the problem is specific for some mp3 files I could share them if you can find a pattern.

**Comment by mikeNG** [comment]
HW mp3 decoder has been removed, is this still an issue on latest build?

**Comment by johnnytifosi** [comment]
The issue is fixed for me and custom ringtones are working again. There are audio cuts now but by using VLC for listening to music this problem is solved.
