### ISSUE TITLE
[LX AOSP 5.0.2] BT send and recieve problems

### ISSUE THREAD

**Issue by uunium** [LegacyXperia/local_manifests#882]
Hi all.
LT18i, LX AOSP alpha 1
Have problem with recieving and sending files via bluetooth. Recieving from nexus 7 (2013) [rooted official 5.0.2] and sending on it. Than i tried send file from PC and i got it. In log file i tried 3 times first 2 failed and third send it.
Logs created in Catlog
BT send: http://pastebin.com/H5eEGYEv
BT recieve: http://pastebin.com/2EfgXgqx
BT recieve from PC: http://pastebin.com/3Dh9tztm
Thank you for help.
Update*
*.jpg and *.zip files are sending normally, but *.fb2 and *.apk is not.

**Comment by mikegapinski** [comment]
That's bcos we are using AOSP bluedroid, will need to get some cherries done in alpha3. Could you test ad2p bt audio for me? 

The file formats you were tring to send are not suppoted in AOSP however, it's not a bug:

 mimeType is null or in unacceptable list, reject the transfer

**Comment by uunium** [comment]
Ok i'm understand what is the problem. I'm think i can't help you with ad2p bt audio cuz i don`t have headphones or audiosystem with BT or i can do it in another way ?

**Comment by badboyasd** [comment]
i have issue with bluetooth too, when i send files to other device, my urushi go to restart
 os.

**Comment by realcatgirly** [comment]
Try this: go to settings - bt, press menu and activate: accept all file formats. In cm12 it works perfectly
