### ISSUE TITLE
[LX AOSP 5.0.2] File download 

### ISSUE THREAD

**Issue by uunium** [LegacyXperia/local_manifests#883]
Hi all!
LT18i, LX AOSP alpha 1
Have problems with downloading files in opera (https://play.google.com/store/apps/details?id=com.opera.browser), but from standart browser files downloading just fine.
Logs from catlog:
Opera: http://pastebin.com/PtxAGQva
Browser: http://pastebin.com/ecPHxJrp
Thank you for help.

**Comment by rtsui-harmonicinc** [comment]
#922
