### ISSUE TITLE
[CM12]Can't choose any default ringtone as alarm clock sound.

### ISSUE THREAD

**Issue by vabi** [LegacyXperia/local_manifests#887]
That's all, not really important, but it would be nice to choose some default ringtones.
I use Xperia Pro (iyokan).

**Comment by legas1** [comment]
I had this on Smultron one time, but suddenly default ringtones appeared. IDK what I did... full reboot or something when I uploaded music to my device.

**Comment by MDiman** [comment]
I have this issue on Ray too. Not all ringtones are present in the list. Perhaps this is a performance issue because i have builded the rom that use internal memory for /data, this rom not have this issue.

**Comment by legas1** [comment]
On latest build of CM12.1 for smultron its working as intended.
