### ISSUE TITLE
Camera fc in scene mode.

### ISSUE THREAD

**Issue by XDynamite** [LegacyXperia/local_manifests#892]
Hi, I'm on the last CM11 build (20150318) and I have camera fc when I try to select a scene mode (sport, night, etc.). Camera works again only if I delete data app.

http://pastebin.com/wViWxg9r
http://pastebin.com/PP9xHDPz
http://pastebin.com/FLtgQqB7
http://pastebin.com/PxMNe1d4

**Comment by ghost** [comment]
Tested on post 20150318 build (self-compiled) and now on 20150326. Have not encountered this, issue.

 I also can't see any information in the logs about the camera forceclosing. Just a lot of warnings about permissions.

**Comment by XDynamite** [comment]
I have just installed the last build (20150326), clean install, and it's the same, fc when I select a scene in camera. I don't know why... However I could remember in the past with older nightly builds that this function worked well.

**Comment by badboyasd** [comment]
i have same issue on cm11, i report that long time ago, but that issue still there, over so many build ( xperia ray)

**Comment by mikeNG** [comment]
The logs show nothing related to camera crashing and I can't reproduce this issue on any of my devices.

**Comment by XDynamite** [comment]
I have tried to flash an original ftf firmware for my Ray (.587), then I have flashed the kernel and then the rom, but the problem is still present, camera mode doesn't work. The build installed is the 20150501.

**Comment by mikeNG** [comment]
After long time, I started looking into this issue as I can reproduce on my urushi. Looks like this is the change that breaks urushi, as it doesn't support auto flash mode: http://review.cyanogenmod.org/75163

Wondering what's the best way to fix that

**Comment by mikeNG** [comment]
This should be fixed in next build for all cm versions, I added a workaround in the camera wrapper for urushi
