### ISSUE TITLE
320Kbps @ MP3 @ External SD Card Class 4 gaps when playing with Apollo

### ISSUE THREAD

**Issue by Spyrus** [LegacyXperia/local_manifests#895]
As title says. It applies on latest build 
Nightly build 20150326 - cm-11.0
    Latest cm11.0 changes
    Fix Google Play Services wakelocks
    Remove config_sf_limitedAlpha overlay
    Remove qcom hardware mp3 decoder

due to qcom (to my opinion) removal

Previous build 
Nightly build 20150318 - cm-11.0
works.

MP3 have been produced from flac files with lame @ 320kbps

**Comment by ICHx** [comment]
Provided that you have shown no log.

**Comment by mikeNG** [comment]
#881
