### ISSUE TITLE
cm-12-20150402 fails to install

### ISSUE THREAD

**Issue by unrealdtc** [LegacyXperia/local_manifests#896]
I'm trying to upgrade from cm-12-20150314-UNOFFICIAL-LegacyXperia-mango to cm-12-20150402-UNOFFICIAL-LegacyXperia-mango.

fastboot flash boot boot.img : OK
Reboot to recovery : OK
Then:

$ adb sideload cm-12-20150402-UNOFFICIAL-LegacyXperia-mango.zip
serving: 'cm-12-20150402-UNOFFICIAL-LegacyXperia-mango.zip'  (~47%)    \* failed to read command: 

Following that, the phone is blocked in boot loop.

Same thing loading directly from SDCard.

**Comment by unrealdtc** [comment]
OK, so I managed to upgrade, but I had to "fastboot erase system" and "adb sideload System-Formating-Tool_signed.zip" in recovery. Strange since this is an upgrade.

**Comment by legas1** [comment]
@unrealdtc I upgraded it normally throught SD Card without this step.

**Comment by rtsui-harmonicinc** [comment]
@unrealdtc Did the upgrade erase your Data?

**Comment by unrealdtc** [comment]
@Noah1911 Strange. This did not work for me (I tried several times). I was able however to reflash cm-12-20150314.
@ICHx No, data is intact!

**Comment by mikeNG** [comment]
Have you tried redownloading the build? Maybe the zip is corrupt

**Comment by theapu** [comment]
I also have to flash System-Formating-Tool_signed.zip on my mango to format system to successfully upgrade.

**Comment by realcatgirly** [comment]
I had no Problem. I wiped the cache and it worked for me.
