### ISSUE TITLE
problem with f2fs in cm12

### ISSUE THREAD

**Issue by ariacat** [LegacyXperia/local_manifests#898]
when i try to flash cm12 in recovery mode, i got a error rapidly.
this error: 
"could not detect filesystem for /dev/block/mmcblk0p2, assuming f2fs
mount: failed to mount /dev/block/mmcblk0p2 at /
data: no such file or directory unmount of /data failed; no such volume

i boot the kernel
i flash the system-formatting-tools_signed zip
i use legacyxperia cm11 last build before this and don't have any problem

**Comment by mikeNG** [comment]
You haven't followed the installation instructions & requirements.

**Comment by jeet-chanchawat** [comment]
Any solution ? m stuck with the same.

**Comment by stranger345** [comment]
Today had the same problem...spend a lot of time and solved. Instalation instructions miss one very important thing!  Cm12 needs linux partition on sd-card (ext4 or f2fs) besides windows partition (fat of fat32). If your sd card don't have linux partition - you'll have this error durind flashing. So, you need to "prepare" sd-card first. Backup files from sd-card. New partition adding is possible using TWRP-recovery. Don't forget to backup files from sd-card, all data will be lost. About partition size - I created 2gb size partition, (don't know for sure is this enough).

**Comment by realcatgirly** [comment]
i have 4 gb and i have only 500mb left with all my apps installed. 2gb is Minimum but i advise to have 5-10gb (this Partition will be added to internal storage)

**Comment by jeet-chanchawat** [comment]
Example explanation of this line: 
" Minimum 2GB secondary ext4 partition for /data on class 10 SD card."
- Example solution-> Suppose if you are having a 8GB CLASS10 micro SD card. Then you have to partition your SD card as 6GB FAT32 and 2GB EXT4.

and then run these 2 zip files in CWM
- Format /system using System-Formating-Tool_signed.zip here (https://www.androidfilehost.com/?fid=95916177934549844) , then /data and then /cache (Important step!)
- Flash data f2fs format from here (https://www.androidfilehost.com/?fid=95916177934549845)

P.S. : I tried a class-6 16GB SD card. The phone got very slow (I could literally tap and go to grab a Coffee till the action was completed.) Don't try it if it is your only device.
