### ISSUE TITLE
cm-11-20150309-UNOFFICIAL-LegacyXperia-haida(No charge off)

### ISSUE THREAD

**Issue by wugli** [LegacyXperia/local_manifests#899]
Hello! Thank you for doing so much better ROM, I am your loyal fans, I discovered that all CM11 version of the WiFi Internet browsing Webpage speed slow, this version is relatively good. But the kernel cannot charge off, there is a solution? Thank you again!!!

**Comment by rtsui-harmonicinc** [comment]
sorry? http://www.investopedia.com/terms/c/chargeoff.asp

**Comment by realcatgirly** [comment]
I think he means offline charging
