### ISSUE TITLE
Home button not working on anzu after update to 

### ISSUE THREAD

**Issue by tomasz89** [LegacyXperia/local_manifests#90]
I have a Sony Xperia Arc S and I know about #25 but this appears different --

I was running cm-10.2_anzu-LX-20130918-NIGHTLY.zip and my home button worked perfectly. (In fact, the whole firmware worked really well good job!).

I updated from cm-10.2_anzu-LX-20130918-NIGHTLY.zip to cm-10.2_anzu-LX-20131001-NIGHTLY.zip and cleared the cache only. After a reboot, my Home button no longer worked. I then did a backup, cleared cache, and factory reset from CWM recovery and rebooted, the home button still did not work on cm-10.2_anzu-LX-20131001-NIGHTLY.zip.

**Comment by mikeNG** [comment]
Install the right kernel...

**Comment by tomasz89** [comment]
Thanks for the fast response. Yes you were correct, that fixed it.
