### ISSUE TITLE
Add Support for True-CD Emulation

### ISSUE THREAD

**Issue by gtz42** [LegacyXperia/local_manifests#901]
I got an (old) Xperia Mini Pro (SK17i/mango) just to run DriveDroid.
Unfortunately the CD Emulation does not work.
Could you please add support for it in the Kernel?
See 
http://softwarebakery.com/projects/drivedroid
and
http://review.cyanogenmod.org/#/q/change:I30a0ffc7f6e9a7f12d95ca1ab07949868aba440c+OR+change:Idf83c74815b1ad370428ab9d3e5503d5f7bcd3b6,n,z

BTW: I tried the sm-12-20150402 image, but it would not finish booting, so I used cm-11-20150407, which works.

BTW2: Thanks a lot for the LegacyXperia builds.

**Comment by mikeNG** [comment]
LX kernel already has the needed commit for DriveDroid in all CM versions.
