### ISSUE TITLE
[CM11][20150406][haida] Gesture typing not working

### ISSUE THREAD

**Issue by jaarandaz** [LegacyXperia/local_manifests#903]
Hi,

I flashed this version yesterday and I'm not getting any word suggestion using gesture typing. I can see the path nevertheless. My system language is Spanish, but if I set English as my language it doesn't work either.

**Comment by ghost** [comment]
Flash this via cwm recovery:
http://forum.xda-developers.com/showpost.php?p=60022494&postcount=8041
