### ISSUE TITLE
[kernel][mango] Unable to format /data /system /cache

### ISSUE THREAD

**Issue by axydavid** [LegacyXperia/local_manifests#905]
It seems that mango users including myself can't format in case anything goes wrong, a workaround would be to install any ICS+ kernel, formatting then flashing the modded kernel that mounts the ext4 partition as /data, interesting enough it seems other supported devices by legacyxperia have these options in CM recovery

**Comment by mikeNG** [comment]
/data /cache are formatted with factory reset, /system is formatted with the zip provided in the LX thread.

**Comment by axydavid** [comment]
That would be true if the recovery would stop complaining about the signing of the package, I can't install anything else than CM and untouched Gapps, even the minimalistic one recommended in the tread recovery complains about package signing in, tried to flash the kernel again but to no avail.
