### ISSUE TITLE
contacts force close, can not open

### ISSUE THREAD

**Issue by badboyasd** [LegacyXperia/local_manifests#907]
Device: 12-20150402-UNOFFICIAL-LegacyXperia-urushi
Kernel: 3.4.0-LX+ langes@vbox #1

http://pastebin.com/yTwL5Pzx
https://gist.github.com/badboyasd/8468064f15bc5755182c
https://gist.github.com/badboyasd/bb9de0347e699c4d1005

**Comment by realcatgirly** [comment]
tried to wipe cache?

**Comment by badboyasd** [comment]
even i wipe everything. bug still there

**Comment by realcatgirly** [comment]
Kernel updated before flashed New Version?
