### ISSUE TITLE
[CM11][20150406][haida] There is no vibration

### ISSUE THREAD

**Issue by jaarandaz** [LegacyXperia/local_manifests#908]
Also when I press volUp or VolDown there is no sound to show selected volume. As with the gesture typing bug, maybe this is a problem with recommended Gapps?

**Comment by ghost** [comment]
It's not related to GApps. Are you sure volume adjustment sound is activate under settings>sound? Same for vibration? 

Since vibration is achieved by a mechanical hardware component it may aswell be damaged. Best check you can do to be sure is test stock sony ROM.

**Comment by jaarandaz** [comment]
Vibration works with sony stock ROM. Also it did work on 20150406 before installing Gapps. Now rebooting.. Ok, now it works. Maybe the problem was when updating; going back to stock and doing a clean install works.
