### ISSUE TITLE
[CM12][20150406][mango]Pressing and holding the camera button won't open the camera app.

### ISSUE THREAD

**Issue by axydavid** [LegacyXperia/local_manifests#911]
Whenever I hold the camera button nothing happens, except when I'm in Trebucket(stock cm12 homescreen), then my phone vibrates for a bit followed by nothing happening.

**Comment by fred777** [comment]
Did you configure camera button to start camera app in Android Settings / Device / Buttons ? It is not set up by default...

**Comment by axydavid** [comment]
It should be enabled by default, Thanks for the tip!
