### ISSUE TITLE
Strong system hang (mango), SK17i cm12 android 5.0.2

### ISSUE THREAD

**Issue by umbrella880** [LegacyXperia/local_manifests#912]
04-13 20:44:21.383 D/RilRequest(  947): [4695]< RIL_REQUEST_IMS_REGISTRATION_STATE error: com.android.internal.telephony.CommandException: GENERIC_FAILURE ret=

04-13 20:44:21.454 D/RilRequest(  947): [4700]< RIL_REQUEST_IMS_REGISTRATION_STATE error: com.android.internal.telephony.CommandException: GENERIC_FAILURE ret=

04-13 20:44:21.482 E/GsmSST  (  947): [GsmSST] error parsing GprsRegistrationState: java.lang.NumberFormatException: Invalid int: "null"

04-13 20:44:21.715 E/audio_a2dp_hw(  253): adev_set_parameters: ERROR: set param called even when stream out is null

04-13 20:44:32.679 E/InCall  (  927): TelecomAdapter - error switchToOtherActiveSub, mPhone is null

04-13 20:44:48.061 E/InCall  (  927): TelecomAdapter - error switchToOtherActiveSub, mPhone is null

04-13 20:44:48.102 E/InCall  (  927): TelecomAdapter - error switchToOtherActiveSub, mPhone is null

04-13 20:45:06.287 D/RilRequest(  947): [4706]< RIL_REQUEST_IMS_REGISTRATION_STATE error: com.android.internal.telephony.CommandException: GENERIC_FAILURE ret=

04-13 20:45:06.323 D/RilRequest(  947): [4711]< RIL_REQUEST_IMS_REGISTRATION_STATE error: com.android.internal.telephony.CommandException: GENERIC_FAILURE ret=

**Comment by umbrella880** [comment]
it's not all the errors in the input field so many mistakes does not fit ...

**Comment by mikeNG** [comment]
Use pastebin or gist to post the logs

**Comment by umbrella880** [comment]
Thank you for the quick response, the problem was in the swap, without running faster, but just as many mistakes ...

**Comment by umbrella880** [comment]
sorry for my english ...
