### ISSUE TITLE
[CM11][20150326][hallon]Audio player causes system freeze

### ISSUE THREAD

**Issue by fqdb** [LegacyXperia/local_manifests#915]
While playing mp3 files, the phone becomes unresponsive and the music stutters for minutes, after which the phone usually recovers and the music continuous to play normally.

```
W/AudioSink(  235): Event underrun
E/AudioPlayer(  235): This indicates the event underrun case for LPA/Tunnel
```

[**full logcat**](http://pastebin.com/Cr9q2QfU)

**Comment by mikeNG** [comment]
#881
