### ISSUE TITLE
Hangs on Charging

### ISSUE THREAD

**Issue by rcreation33** [LegacyXperia/local_manifests#916]
I have Xperia Pro CM12 5.0.2 iyokan. When I connect my phone to plug in charger ( not the usb charger to computer ) My phone hangs with black screen and charging light on and I have to remove battery and turn it on again.

**Comment by rtsui-harmonicinc** [comment]
what about the adb log?

**Comment by rcreation33** [comment]
How to check ADB log it hangs and I have to remove the battery and turn it on again.
