### ISSUE TITLE
[AOSP5.1][anzu] SU binary not installed.

### ISSUE THREAD

**Issue by ClashTheBunny** [LegacyXperia/local_manifests#917]
The LegacyXperiaAOSP_anzu-ota-9-beta1.zip from 2015-4-13 lacks the su binary.  I had to install it manually.

Sorry if this isn't the right place.  I couldn't find issues on LegacyXperiaAOSP's manifests and the devs seem to be the same between these two projects.

Thanks so much for such a great project.  It's amazing that openness makes the difference between a great handset and a terrible one.  My Galaxy Note is less updated than these awesome little phones because it's Exynos.  My NVIDIA Tegra 2 tablet is dead because of NVIDIA's closed source crap.  These phones are still kicking though!

**Comment by ghost** [comment]
It is a pure AOSP build and AOSP is unrooted by default.
