### ISSUE TITLE
[CM11][20150407][smultron] Audio lags when playing music

### ISSUE THREAD

**Issue by gogeccc** [LegacyXperia/local_manifests#918]
I've seen that you have done something about this in 20140906 build, but unfortunately, I am still experiencing noticeable lags while playing music, though they are rarer and more random now.

It doesn't matter whether I am using Apollo or ES Music Player (comes with ES File Explorer).
I haven't used any other music player.

I remember that this was happening before and that is why I used UrmiGen ROM v3 (built atop yours) for about a year now and what is unclear to me is why is there almost zero issues with music playback while using that ROM compared to your builds where lags are present.

UrmiGen xda thread: http://forum.xda-developers.com/showthread.php?t=2644333

Gist with log files: https://gist.github.com/gogeccc/13dae4452d8ed60b2a29

Test song: https://www.dropbox.com/s/cm1txwayk8krlrj/05.%20Shadow%20of%20the%20Day.mp3?dl=0

**Comment by mikeNG** [comment]
#915

**Comment by lordicus21** [comment]
I used the CM11 nightly 20150831 in my st15 and there is the same issue, i just install Neutron player and i haven't no more problems.
