### ISSUE TITLE
Haida Mt11a and Mt11i

### ISSUE THREAD

**Issue by Astu04** [LegacyXperia/local_manifests#92]
a and i stand for American and International. 
I'm trying to install it via CWM, but the grep prep is looking for the a version and doesn't allow the i version to apply the update. 

Edit. The log, maybe it could be that I'm reading it wrong.  

assert failed: getprop("ro.product.device") == "MT11i" || getprop("ro.build.product") == MT11a" || getprop("ro.build.product") == "MT11a" || getprop("ro.build.product") == "hada"
E:Error in /<LOCATION>/ 
(Status 7)
Installation aborder

**Comment by mikeNG** [comment]
I don't understand, what's the problem?

Following the installation steps exactly should work fine with no status 7 error.

If you missed the instructions from xda first post, here they are again:
1. Flash boot.img (in the zip) with fastboot or FlashTool
2. Install update zip in CWM recovery
3. Install Google Apps (gapps) zip in CWM recovery (this step is optional for those who don't want Google Apps)
4. Wipe data (do this only if you come from stock ics or if you have problems like Force Close after installation)

**Comment by djey47** [comment]
Is this log a copy-paste ?

assert failed: getprop("ro.product.device") == "MT11i" || getprop("ro.build.product") == MT11a" || getprop("ro.build.product") == "MT11a" || getprop("ro.build.product") == "hada"
1. getprop("ro.build.product") == MT11a" || getprop("ro.build.product") == "MT11a"
   is exactly the same thing and is no use. typo ?
2. getprop("ro.build.product") == "hada"
   should be "haida".

**Comment by Astu04** [comment]
@mikeNG: I'm in step two. I flashed the kernel via 'fastboot flash boot boot.img', and when installing the .zip 'via choose zip from sdcard' in CWM, it returns me the error. 
@djey47: I don't know how to copy&paste it. And yes, those are typos. I'll write it again and I'll check it. 

I'm also using 'fastboot boot recoveryNeo.img' to boot the CWM without flashing it. 

ClockworkMod Reocvery v4.0.0.5 - FreeXperia

-- Installing: /sdcard/cm-10.2_haida-LX20131001-NIGHTLY.zip

Finding update package...
Opening update package...
Installing update.. 
assert failed: getprop("ro.product.device") == "MT11i" || getprop("ro.build.product") == MT11i" || getprop("ro.product.device") == "MT11a" || getprop("ro.build.product") == MT11a" || getprop("ro.product.device") == "haida" || getprop("ro.build.product") == haida" || 
E:Error in /sdcard/cm-10.2_haida-LX20131001-NIGHTLY.zip
(Status 7)
Installation aborted.

**Comment by mikeNG** [comment]
```
ClockworkMod Reocvery v4.0.0.5 - FreeXperia
```

What kernel are you using? this is ancient stuff. Please use the kernel inside the zip.
If you still can't install the zip, you should simply read the FAQ, the answer to your problem is there.
