### ISSUE TITLE
big downloads are slowing down complete system

### ISSUE THREAD

**Issue by realcatgirly** [LegacyXperia/local_manifests#922]
When i'm downloading big files like updates, etc... The complete System is slowing down. Device: urushi with cm12

**Comment by mikeNG** [comment]
Logs?

**Comment by realcatgirly** [comment]
Wich logs?

**Comment by uunium** [comment]
Had same on anzu and i think it is  a memory card problem, it don`t have enough speed for file download and UI working on CM12 and AOSP 5.X. Am i think wrong? Have class 10 UHS 1 Read speed with large files 25 mb/s, small files ~500 kb/s; write: large 9 mb/s, small 100 kb/s. Can make some logs if need to.

**Comment by rtsui-harmonicinc** [comment]
though no log provided, it is advised not to use noop(default)/sio/deadline when there is a heavy io event ongoing, try switching to bfq/cfq/row instead.

**Comment by uunium** [comment]
I made some logs (via adb) with noop i\o http://pastebin.com/2WExz9y2 , and cfq http://pastebin.com/dFmq2w5w . It seems like with cfq i\o system work faster, you was right, ICHx.

**Comment by rtsui-harmonicinc** [comment]
I guess, it is because the bus is not large enough...(2011 xperias are already considered as ancient gadgets, and being single threaded)

**Comment by uunium** [comment]
So, this is not a bug, just our device is too old. Is lollipop wrote in device memory works faster ?

**Comment by rtsui-harmonicinc** [comment]
Old device can work well, but inappropriate settings would hurt performance. ;
Not sure

**Comment by realcatgirly** [comment]
ok. i will close the issue now.
