### ISSUE TITLE
AOSP 5.1.1 Keyboard - Gesture typing does not work

### ISSUE THREAD

**Issue by tangtony** [LegacyXperia/local_manifests#926]
Anzu here, but I don't think this is device specific. I've tried a variety of different GAPPS, but I haven't been able to get gesture typing to work. I'm currently using Mardon's GAPPS provided here: http://forum.xda-developers.com/android/apps-games/hdpi-google-apps-5-1-t3066172

Also, gesture typing works fine with CM12 but not with AOSP which leads me to believe this is a problem with AOSP.

**Comment by tangtony** [comment]
I think I may have found the problem, but I'm not sure how LX-AOSP is built so I'm not completely sure. According to http://forum.xda-developers.com/nexus-4/general/guide-how-to-enable-googles-gesture-t2012628/post34605586, there is a flag that needs to be set to enable gesture input.

packages/inputmethods/LatinIME/java/res/values/gesture-input.xml:
`<bool name="config_gesture_input_enabled_by_build_config">true</bool>`

**Comment by neurer** [comment]
Looks like there's been a change recently: "_Removed "libjni_latinime.so" from GApps packages (Use Google Keyboard instead)_" -- [source](http://forum.xda-developers.com/android/software/gapps-google-apps-minimal-edition-t2943330)

Not sure what Mardons GApps package is based on, but try **adding** "libjni_latinimegoogle.so" to /system/lib and reboot.

LatinIME gesture input appears to work now with the added lib. I'm on cm-12.1-20150514-UNOFFICIAL-LegacyXperia-smultron without any GApps installed.

**Comment by tangtony** [comment]
@neurer, I am aware of the libjni_latinimegoogle.so file, and I know gesture typing works in CM, this is only a problem on AOSP.
