### ISSUE TITLE
[cm 12.1] [urushi] system ui force close

### ISSUE THREAD

**Issue by realcatgirly** [LegacyXperia/local_manifests#927]
i have a big problem with cm12.1. i cleared cache, updated, wiped cache again and... "system ui closed"  
i clicked "ok" and... "system ui closed" 
i rebooted and i cant click "ok"
so i had to downgrade.

**Comment by realcatgirly** [comment]
i updated 5.0.2 to 5.1(cm12 to cm12.1)

**Comment by sebastiansiedlarz409** [comment]
I had this problem too, but I made some tweaks build prop and oc my wt19i to 1,2 Ghz. After this i have not more this error.

**Comment by ICHx** [comment]
Bloodx logs

**Comment by realcatgirly** [comment]
but it must be possible without this. or there must be instructions  how to update without this error.

**Comment by ottopfeiffer2** [comment]
Got same problem on anzu, after installing via adb instead of sd card it worked fine. Don t know , why.

**Comment by realcatgirly** [comment]
data intact?

**Comment by realcatgirly** [comment]
please reopen!
adb sideload dont fix this issue

**Comment by mikeNG** [comment]
Bug reports not following the bug report template are closed without further notice.

**Comment by realcatgirly** [comment]
FIXED! 
i just updated the kernel via pc and BAMM it works
