### ISSUE TITLE
ANZU | cm-12-20150401 | Unable to Install

### ISSUE THREAD

**Issue by ksranjith786** [LegacyXperia/local_manifests#928]
I have downloaded the ANZU cm-12-20150401 build, In BOOTLOADER mode, I have flashed the boot.img, In RECOVERY mode, wiped data, cache, dalvik cache, and Install the ZIP is triggered.

After a minute, my phone restarted abruptly. I tried 4-5 times, but of no use.

Could you please let me know, why does the installation of zip failed ?

Let me know if there are any other things I have to do.

**Comment by realcatgirly** [comment]
try to catch recovery logs

**Comment by ottopfeiffer2** [comment]
Did you format your SD card in 2 partitions as mentioned here. https://github.com/LegacyXperia/Wiki/wiki/Installing-Lollipop   ?

**Comment by rtsui-harmonicinc** [comment]
and system-format-something.zip too

**Comment by ksranjith786** [comment]
I havent tried formatting SD Card in 2 partitions. I will try that and let you know.
