### ISSUE TITLE
deleted

### ISSUE THREAD

**Issue by muatazawil** [LegacyXperia/local_manifests#932]
can't enable camera flash in  cm12.1 (URUSHI)

**Comment by realcatgirly** [comment]
i had this since i flashed cm12 from legacy xperia

**Comment by muatazawil** [comment]
The most special thing in urushi is the camera,so it is a big problem 
Except this ,the ROM is wonderful really thanks guys

**Comment by muatazawil** [comment]
Any description !!!

**Comment by mikeNG** [comment]
Bug reports not following the bug report template are closed without further notice.

**Comment by muatazawil** [comment]
ok
