### ISSUE TITLE
[CM12.1][URUSHI]Long delay when a call comes in

### ISSUE THREAD

**Issue by eldoctor94** [LegacyXperia/local_manifests#933]
I have an Urushi (xperia ray) device.
cyanogenmod12.1 (Lollipop 5.1.1) 20150514 UNOFFICIAL LegacyXperia

When the screen is off and I get a call, delay between 4-10 seconds and then the display shows me who is calling me and answer the call in question. There are times when I miss a call because the phone never reacts. The same thing happens when I go to make a call (or accidentally call it) lasts between 3-6 seconds to hang up.

I attatch the logcat with the possible errors or things for see and the reg of dmesg...

http://pastebin.com/embed_js.php?i=m72jvnsV logcat

http://pastebin.com/embed_js.php?i=Wk3mpJjh dmesg

**Comment by FibreFoX** [comment]
I'm having this on ANZU too, pressing home-button sometimes makes it better. It seems to me there is a "problem" with slowed down CPU not being fast enough for proper reaction. I've recently upgraded to Class 10 UHS-I sd-card (wasn't able to use cm12.1 before, too slow sd-card).

Maybe having more controll over cpu-governor would help?!

**Comment by ICHx** [comment]
try disabling art_small_mode

**Comment by rtsui-harmonicinc** [comment]
## 

try disabling art_small_mode

originally in system/build.prop, there is a line
'dalvik.vm.dex2oat-filter=interpret-only'
try changing interpret-only to speed or space

## 

then, reboot phone to recovery, plug in phone to an adb-recognized computer and open adb shell

## 

after that, type 'mount /dev/block/mmcblk0p2 /data' and then 'rm -rf /data/dalvik-cache'

## 

finally, type 'adb reboot' and wait(nearly for good)

**Comment by eldoctor94** [comment]
ICHx, that you mean with "interpret-only" with speed or space? Sorry, I'm a bit of a novice jjjj...

FibreFoX, i have an SDcard class 10 16gb samsung and the fluidity of the phone is quite good, except the InCall UI app... i will try to test the CPU frequencies and the home button trick...

**Comment by eldoctor94** [comment]
**ICHx**, before making changes to _build.prop_, I tried to _test in recovery by restarting the phone and connecting to the computer_ to see if it's recognized him properly (which is used to make the logcat from adb) and it seems that the phone is not recognized because I run **adb devices** to detect the phone and not get on the list, it seems that does not have the software installed mobile, when it's turn on, the PC recognizes the phone. Some trouble?

**Comment by ICHx** [comment]
Sorry, I can't fully understand what you mean. But I guess, you didn't fully trust the PC when the phone is operating.

**Comment by rtsui-harmonicinc** [comment]
![](http://www.androidpolice.com/wp-content/uploads/2013/02/nexusae0_Screenshot_2013-02-12-11-47-41.png)
Sorry, I can't fully understand what you mean. But I guess, you didn't fully trust the PC when the phone is operating.

**Comment by eldoctor94** [comment]
_Sorry for my bad english_ 😅 , i tried to say that **if it's necessary that the phone should to be off (booted into recovery mode) to execute the commands**, since I tried to connect the phone into recovery mode on the PC via USB and **ADB does not recognize it.**

in regard to the imagen that you mean, my phone it's recognized only when it's turned on and ADB also can recognize... I've added the RSA key fingerprint to the trusted list of ADB and I marked the check _always allow from this computer_.

Shortly, the phone should to be on or into recovery mode to run the commands?:

> mount /dev/block/mmcblk0p2 /data
> rm -rf /data/dalvik-cache

**Comment by rtsui-harmonicinc** [comment]
open adb shell after entered recovery

**Comment by shenlong** [comment]
@eldoctor94 , you need to make sure you have the drivers install properly for recovery on your computer. Try to run the drivers from the android sdk again if necessary.

Then make sure to end the adb.exe before starting adb shell again.

**Comment by eldoctor94** [comment]
Thanks @ICHx and @shenlong !! I'll try ... maybe my phone was not recognized in recovery mode for _not having the SDK updates installed for lollipop_ 😜... I'll be warning for any inconvenience that may happen, and again ... Thanks

**Comment by eldoctor94** [comment]
I do not know what I'm doing wrong, I installed the "missing drivers" of Android 5.1.1 API 22 (as I understood) as the image ... 

![sdk actually installed](https://cloud.githubusercontent.com/assets/12568005/7822864/9bfd8528-03b5-11e5-857c-e724d428c85b.png)

I stopped the process adb.exe from the Windows Task Manager, I connected the phone again in recovery mode, execute "adb shell" and still did not recognize the driver missing (It appears on CMD  line **error: device not found**) ... I rebooted the computer and went back to do it again and still did not recognize the phone (Ignore the spanish language).

![foto0027](https://cloud.githubusercontent.com/assets/12568005/7823447/c5a119dc-03b8-11e5-88b8-fab88f7ea8b3.jpg)

![none_controller](https://cloud.githubusercontent.com/assets/12568005/7823004/7122134a-03b6-11e5-96f3-6763c89d570c.png)

There will be a missing driver? What am I doing wrong?

EDIT: I tried downloading the OEM drivers sony's official website (if those drivers were required) and unzipped the SDK folder driver (<sdk> / extras / google / usb driver) and yet still does not recognize...

**Comment by shenlong** [comment]
Go flashtool.net and install the flash tool. 
Then install drivers in the drivers folder.

Profit.

**Comment by eldoctor94** [comment]
Already i had installed flashtool and have re-installed the drivers (xperia ray, and Flashmode fastboot drivers) and nothing yet. I think I will give this issue by closed and live with the problem until it may be solved by the developer. thanks in advance. 😞

**Comment by shenlong** [comment]
@eldoctor94, you can go to device manager and uninstall the exclamation mark driver and try again.

Also, try a different USB port. Try not to use USB 3.0 port as they may have drivers issue.

**Comment by rtsui-harmonicinc** [comment]
Installing the sdk package is totally a waste of time if you are not needing the IDE.
IF you are using 64BIT WINDOWS, make sure to disable driver verification. Installing only Flashtool and adb would be enough.

**Comment by eldoctor94** [comment]
i Tried to **uninstall the exclamation mark driver (ST18i and unknown device)**, changed to other USB port **(i don't have 3.0 usb ports)**, I **uninstalled and re-installed** the _flashtool and mogami drivers_ (downloaded from the official page), I revoked **all the connections** from the _development menu_ and went back to add the computer to the trusted list of the RSA fingerprint, **I changed the USB cable to another cable**, and nothing yet... **Clearly i'm a noob.** Maybe a possible solution: Do it in another computer...

**PD: I have a 32-bit win7 Ultimate !!!!**

**Comment by reymarbc** [comment]
http://visualgdb.com/tutorials/android/usbdebug/manualinstall.php

thats your answer

**Comment by FibreFoX** [comment]
Hi @eldoctor94 ,

EDIT: just being in recovery worked for me. I've downloaded android SDK (not the android studio) and downloaded and installed the Google USB Driver from within "SDK Manager", after that I started `adb shell` and could run the commands.

**Comment by eldoctor94** [comment]
@reymarbc THOUSANDS OF THANKSSS !! I got install the missing driver! The problem was that I was using the "Sony USB driver" as the "missing driver" normally used to unlock the bootloader, not the "google usb driver" that comes with the SDK by default ... Thousands of thanks !

**Comment by eldoctor94** [comment]
Solved the issue... I'll wait how it works...

**Comment by rtsui-harmonicinc** [comment]
after installing next update, it is no longer neccessary to edit build.prop, but required to wipe dalvik cache

**Comment by eldoctor94** [comment]
OK no problem.! i'll remember..!

**Comment by fred777** [comment]
On my Iyokan, I still have exactly the same trouble with incoming and outging calls. Currently I'm on 12.1-20150825 (self-built), with a later build, the kernel refused to boot and I didn't try to update since then.

According to https://source.android.com/devices/tech/dalvik/configure.html small ART mode will improve boot time, but decrease runtime performance. It is defined by 

```
dalvik.vm.dex2oat-filter=interpret-only
dalvik.vm.image-dex2oat-filter=speed
```

But my CM stock build.prop says 

```
dalvik.vm.dex2oat-filter=balanced
dalvik.vm.image-dex2oat-filter=balanced
```

Not sure what the culprit is here... does the phone app get swapped to ZRAM or unloaded from memory? Is there a way to force-keep it in memory?

Also, I wonder why dalvik.vm.heapsize is 128m - it used to be lower on earlier ROMs (like 64m if I remember correctly....).

**Comment by realcatgirly** [comment]
another trick: if the phone isnt responding on an incoming call, activate in Settings -> keys -> answer call with home button. if a call Comes in and you hear the ringtone just press home.

**Comment by fred777** [comment]
Unfortunately, this doesn't help very much for me. I already have home and power configured for accepting/rejecting calls and after pressing home on incoming calls it still takes several seconds until the phone stops ringing and I can hear the caller (or the caller has canceled because it took too long....)
