### ISSUE TITLE
[CM12.1][URUSHI] Unstability when send a file via Bluetooth

### ISSUE THREAD

**Issue by eldoctor94** [LegacyXperia/local_manifests#935]
Yesterday tried to send a file via Bluetooth, the bluetooth turns on succesfully and searches the targets appropriately, but when starts to send, the phone becomes unstable (will not responding), next **system UI and System** processes request to force close and then the process "Share via bluetooth" closes unexpectedly. Finally, i try again to re-send the file again and it is as if I had not done anything because, apparently, the bluetooth is "off" literally, having to reboot to be restored.

I include the dmesg and last kmsg (if were found errors) and the relevant logcat.

LOGCAT https://gist.github.com/83291e30e10bbe9185c6

DMESG https://gist.github.com/d8f0be9f13d85c74401c

LAST_KMSG https://gist.github.com/b5f08cad112b3f61422a

**Comment by eldoctor94** [comment]
Nobody has a solution?

**Comment by rtsui-harmonicinc** [comment]
Blue-tooth is so slow that I always use other pathways like Dukto
