### ISSUE TITLE
cm12.1 hallon no sound when normal call and internet call

### ISSUE THREAD

**Issue by allonid** [LegacyXperia/local_manifests#937]
Please fix it , i have more problem is cant create new contact  unfortunately 
Thanks

**Comment by eldoctor94** [comment]
Was followed the instructions pattern?

> Flashed the last build kernel with the last build (boot.img)?
> Done the correctly wipes: **flash system_tool.zip - wipe data/factory reset?** (this is for first install)
> Was created the ext4 second partition? F2FS often cause problems, even data corruption in some cases.

**Comment by allonid** [comment]
Ya, i flashed the last kernel and created second partition ext4 , no problem when flash i do step by step same as in xda guide , everything work fine , i used class 10 sdcard i dont know why no sound when i calling , i have  whatsapp , facebook messenger , viber , line , imo and more apps in my phone i need that all apps to call my friends but sometimes when i used 1 of those apps i get no sound if i reboot everything work fine again without trouble , i always check website maybe any new update and fixed .

I like cm12.1 because i think run better than  cm12 in my phone

I tried other custom rom already as aosp, ressurection, pacman but i get same problem. 

I used cm11 4.4.4 kk before i try cm12 and cm12.1 Everything work good no one trouble

Thanks

**Comment by allonid** [comment]
Yes ..i extract boot.img from the last rom and i format system used tool
via cwm. I created second partition ext4 4gb class 10 sdcard but still no
sound when call and internet call. I dont know whats wrong
I flash back to cm11 everything work fine.
Thanks for answer

**Comment by allonid** [comment]
i flashed latest version cm-12.1-20150723-UNOFFICIAL-LegacyXperia-hallon.zip
but still got same trouble 
i must restart my phone before using internet call

please fix it 
thanks
