### ISSUE TITLE
use swap on sdcard

### ISSUE THREAD

**Issue by LadyNamedLaura** [LegacyXperia/local_manifests#939]
I am going to be honest, I don't like zswap/zram,... It only burns cpu cycles, and those too com at a premium on our old devices, so while i need a fast sd-card anyhow (for /data) my idea was to have a swap partition on /dev/block/mmcblk0p3.

So the feature request is as foolows:
try to swapon  /dev/block/mmcblk0p3 before activating zram (and don't activate zram if it works)

ps: yes i know this will wear out my sdcard, but I am not in the business of caring about that.

**Comment by rtsui-harmonicinc** [comment]
swap on sdcard hurt your cpu more

**Comment by rtsui-harmonicinc** [comment]
plus, it hurt io performance. Just imagine, your system read apps, dalvik-cache and data, all on sdcard right now. The bus cant withstand any more heavy task.

**Comment by LadyNamedLaura** [comment]
@ICHx I'm not enterly sure, I am testing it now, and it seems slightly faster with swap on sd, also, why would swap on sd hurt the cpu more than zram? It doesn't load the cpu at all.

**Comment by mikeNG** [comment]
I don't think we should put more load on SD...
