### ISSUE TITLE
[AOSP 5.1.1] Blank space where notification bar should be

### ISSUE THREAD

**Issue by Neuen1** [LegacyXperia/local_manifests#940]
Getting this bug really often with AOSP beta 2. Nothing too important, but I tought it worth mentioning
![screenshot_2015-06-02-03-22-37](https://cloud.githubusercontent.com/assets/11819421/7954190/90ee9020-09a3-11e5-922e-6228f2a99198.png) ![screenshot_2015-06-02-03-22-43](https://cloud.githubusercontent.com/assets/11819421/7954191/90efa6fe-09a3-11e5-818d-b09e7ce80e1d.png)

**Comment by tangtony** [comment]
For me, this happens after I receive and finish a call while the phone is locked.

**Comment by rtsui-harmonicinc** [comment]
try figuring out the available ram size when this happen

**Comment by mikeNG** [comment]
I think this is a known AOSP bug and fixed in CM... just need to find which commit it was
