### ISSUE TITLE
[AOSP 5.1.1] [anzu] Rebooting phone -> black screen + red LED -> reboot -> optimizing apps

### ISSUE THREAD

**Issue by Soukyuu** [LegacyXperia/local_manifests#941]
For some reason turning the device off and on again lands me on a black screen after the LegacyXperia logo, with the notification LED blinking red. Shutting the device down with home+power and starting it again boots fine, but seemingly deletes the cache, as I'm shown the "android is starting..." screen and it of course takes half an eternity (and my battery charge) until it's ready to be used again. I'm running the beta2 of AOSP 5.1.1

Tell me what info I can provide to help debug this, please.

**Comment by realcatgirly** [comment]
Logs

**Comment by Soukyuu** [comment]
...how/where? I'm completely new to this.

Also, it hasn't happened again so far, 3 reboots and counting.

**Comment by rtsui-harmonicinc** [comment]
red light is set to be the low-bat notification
 by default. Maybe you have some software causing the problem, if likely it is not about the battery.

**Comment by realcatgirly** [comment]
try to clear cache or flash this build again(no data lost)

**Comment by intruder16** [comment]
Happens on unclean shutdown of device. A file "/data/dalvik-cache/booting" is created in that case indicating unclean shutdown and the system is forced to re-create all cache hence "optimizing app/android is starting".

Not device specific. AFAIK, happens with all LP devices. 

One solution is to create a flashable zip with a script to remove the aforementioned file in case of unclean shutdown thus preventing "android is starting".

**Comment by Soukyuu** [comment]
That might be, but it would mean that shutting it down via the shutdown menu ends up shutting down unclean. I tried clearing cache and reflashing, but the ROM just didn't stabilize itself. Sometimes everything went fine without a hitch but after multiple reboots it would do that again.

I'm back to CM11 for now, runs more stable so far.

**Comment by realcatgirly** [comment]
cm 12.1 is stable enough for me (thank you for developing the rom) :P
