### ISSUE TITLE
Torch turns off when screen is off

### ISSUE THREAD

**Issue by niks255** [LegacyXperia/local_manifests#944]
I have this issue on CM12.1. I will try to fix it myself, but the issue needs to be open anyway since somebody may already have a solution.

**Comment by gabri-hell** [comment]
Hi, same issue on iyokan CM12.1.
Doesn't occur when phone is charging or USB connected.
Moreover I find that the flash has lower intensity than before.
Here the logcat : https://gist.github.com/gabri-hell/673a87b4024016c0a451#file-gistfile1-txt

**Comment by niks255** [comment]
So, basically, seems like torch is missing wake lock permission. When the phone is connected, it doesn't go into deep sleep - that's why torch stays on. I'll try it and report.

**Comment by zweif** [comment]
This seems to be fixed for me in a today's build

**Comment by niks255** [comment]
Probably not, check it out after some time.

**Comment by niks255** [comment]
So, it's not fixed yet. What do we do?

**Comment by realcatgirly** [comment]
for me it works fine. there is only delay but it works. it also creates a notification

**Comment by niks255** [comment]
That is not possible. You probably use high performance profile or your device isn't Xperia Pro. I know for sure that Xperia Ray doesn't have this issue, but Pro does.

**Comment by realcatgirly** [comment]
Yep i have ray

**Comment by niks255** [comment]
Well, as I said, Ray doesn't have this issue. Only Pro does. I tried to figure out why but I can't make logcat cause it works fine when cable is connected, which means it doesn't work when the phone goes into deep sleep.

**Comment by niks255** [comment]
Oh, BTW. The same issue was on OmniROM 4.4,.but wasn't on CM11 from legacyxperia. Guess something happened there.

**Comment by niks255** [comment]
I managed to make a logcat http://pastebin.com/b0p4YEw0

**Comment by avsaponchik** [comment]
Bumping this (iyokan) since this bug still persists with latest build

**Comment by niks255** [comment]
It seems that CM12.1 is not supported anymore.

**Comment by ghost** [comment]
Why you think so? There was a new build at the beginning of December. Mike doesn't post any progress updates usually.

**Comment by niks255** [comment]
They are not pushing anything new to CM12.1 branch. 
Anyway, I would like to have this bug fixed.

**Comment by mikeNG** [comment]
The new torch implementation in 5.0+ is totally different from the old Torch app we were using, so it isn't an easy fix, need to dig deeper to find what's going on. The old Torch app held a wakelock when torch was enabled, so we didn't notice the issue. urushi doesn't have this issue because it's using a different chip for the flash led.

**Comment by niks255** [comment]
Well, the only solution I could think of is to add wakelock to this method https://github.com/CyanogenMod/android_frameworks_base/blob/cm-12.1/services/core/java/com/android/server/TorchService.java#L243 something like:

```
    if (mTorchEnabled != enabled) {
        mTorchEnabled = enabled;
        mTorchEnabled ? wakelock.acquire() : wakelock.release();
        setListenForScreenOff(enabled);
        postUpdateFlashlight();
    }
```

But I have never done anything like that. This method is being called every time you change torch state, so it should work fine.

**Comment by avsaponchik** [comment]
http://review.msm7x30.org/#/c/1126/

**Comment by niks255** [comment]
It's my commit https://github.com/CyanogenMod/android_frameworks_base/commit/43e3f86b25099220cf3cc37133e042d17f64f86b
I can backport it to CM12.1 as well but don't see the point, it's gonna be abandoned soon.
