### ISSUE TITLE
Cannot activate Wifi on hallon (cm-10.2_hallon-LX-20131013-NIGHTLY.zip)

### ISSUE THREAD

**Issue by kitabema** [LegacyXperia/local_manifests#95]
Wifi cannot be activated on current hallon build (button in settings is grayed out). I don't know for sure but if I remember correctly with "cm-10.2_hallon-LX-20131001-NIGHTLY.zip" it started not working (previous CM 10.2 builds had working Wifi but (a lot) other issues).

Last (more or less) fully working build (for my hallon phone) was "cm_hallon-LX-20130925-NIGHTLY.zip" (CM 10.1).

Some logcat output (complete file cannot be attached here...):

--------- beginning of /dev/log/system
...
I/WifiService(  532): WifiService trying to set country code to de with persist set to true
...
--------- beginning of /dev/log/main
D/CommandListener(  226): Trying to bring down wlan0

D/WifiHW  (  532): added/removed p2p interface. add: 1

I/wpa_supplicant( 2146): Successfully initialized wpa_supplicant
...
E/WifiHW  (  532): Supplicant not running, cannot connect
...
E/WifiHW  (  532): Supplicant not running, cannot connect
...
E/WifiHW  (  532): Supplicant not running, cannot connect
E/WifiHW  (  532): Supplicant not running, cannot connect
...
D/CommandListener(  226): Trying to bring down wlan0
D/WifiHW  (  532): added/removed p2p interface. add: 1
...
E/wpa_supplicant( 2182): Could not set interface wlan0 flags: Invalid argument
E/wpa_supplicant( 2182): nl80211: Could not set interface 'wlan0' UP
E/wpa_supplicant( 2182): wlan0: Failed to initialize driver interface

**Comment by mikeNG** [comment]
Use the kernel from the zip.

**Comment by kitabema** [comment]
I did use the (appropriate) kernel from the zip file, I always do. Am I the only one with that problem?

**Comment by FibreFoX** [comment]
Did you clean your (dalvik-)cache-partition? I had that kind of problem some time ago ... i forgot to clean the caches after flashing a new version, maybe it helps you too.

**Comment by mikeNG** [comment]
Every "Cannot activate Wifi" bug is a problem of the user not following the installation steps exactly. I test wifi on every single build before releasing. It always worked since my first builds on March.

**Comment by kitabema** [comment]
I'm a software engineer myself and that could be my words to our quality assurance. ;) I did clean up (wipe) caches (including data) and I'm back to "cm_hallon-LX-20130925-NIGHTLY.zip" - wifi working again.

Only problem I can think of is that I save settings on my Google account - including wifi settings. Perhaps that's the problem: restored wifi settings from cm 10.1 on cm 10.2?

**Comment by mikeNG** [comment]
If you try the latest build again, get a dmesg log too so I can get more info. Usually when wifi is not working there is some problem with the wifi modules not loading

**Comment by N2Blue** [comment]
Problem solved.
I did lot of thinks to solve it. Factory reset didn't work. I delete adb-bundle and I downloaded it again. I installed the flashtool-driver again. I deleted Google Account Settings.
I took the same boot.img, flashed it again and now Wlan works fine!

Original comment:

Exactly same problem here.
I flashed the right kernel from the zip, had no problems while flashing.
I also wipe data and cache before i installed the zip.
My SD Card was in the beginning complitly empty and i also think the save settings from Google account couldn't be the reason, because it didn't work even before i could login into my Google account.
One Minuat ago, i deleted the settings on my Google account (including Wlan password), wiped cache again and restarted the phone - same problem, the wifi button is grey and does nothing.

I could create a dmesg log, can you say me the command line, wich you need, because i don't know much about dmesg and what you need.

**Comment by mikeNG** [comment]
http://forum.xda-developers.com/showpost.php?p=46091341&postcount=3

**Comment by kitabema** [comment]
Though trying "N2Blue"s suggestions unfortunately it does not work for me,
log files are here:

logcat.txt: http://pastebin.com/rqmbuy5Z

last_kmsg.txt: http://pastebin.com/4mtnvrCi

dmesg.txt: http://pastebin.com/XirNVjU9

**Comment by mikeNG** [comment]
```
wl12xx: ERROR could not get nvs file ti-connectivity/wl1271-nvs.bin
```

**Comment by kitabema** [comment]
What does that mean? I had installed the latest ICS firmware before trying FreeXperia and
afterwards your builds. My current baseband version is 8x55A-AAABQOAZM-203028G-77.

**Comment by mikeNG** [comment]
There's something wrong with the calibration file, it's missing. It should be there, it seems that somehow the calibration script isn't getting executed

**Comment by kitabema** [comment]
#101 seems to be similar. I did not test without google apps.

**Comment by siyman** [comment]
As stated in this comment (https://github.com/LegacyXperia/local_manifests/issues/123), I also executed /system/bin/wifical.sh as root and rebooted. Afterwards I could login to my wifi again. I did everything as expected in the installation guidelines and haven't had such problems before.

**Comment by adrientetar** [comment]
I confirm this and has the same problem as @siyman. Still occasional dropouts after flashing but they're sparse and short compared to e.g original CM10 kernel. Maybe fixed with latest wifi changes? Not reflashing for now personally.

**Comment by kitabema** [comment]
With MT11i (Neo V) ftf flashed on my Neo (MT 15i) - not so easy to accomplish with Windows 8.1 (not working at all) and Fedora 19 (a bit tinkering with flashtool start script and libusb necessary) - Wifi is working fine again.

Therefore this issue can be closed in my opinion.

**Comment by mikeNG** [comment]
ok
