### ISSUE TITLE
[anzu][CM11] Vibration only present at boot time

### ISSUE THREAD

**Issue by Soukyuu** [LegacyXperia/local_manifests#950]
I'm having troubles with vibration on CM11. When booting the phone, it vibrates a few times, but once fully booted, no matter which settings related to vibration I change or reset to defaults, vibration is not working.

Logs are [here](https://dl.dropboxusercontent.com/u/19330332/anzu_cm11_novibe.zip).

**Comment by Soukyuu** [comment]
So... anything else I can provide to solve this? I tried flashing the same ROM over itself and it didn't solve it.

**Comment by mikeNG** [comment]
I can't reproduce in any of my devices. Are you using any mods/apps that could cause this?

**Comment by Soukyuu** [comment]
Not that I know of. I have recently clean re-flashed the ROM again and now it works as expected. 
So might have been a bad flash.
