### ISSUE TITLE
[CM12.1] [ANZU] Incoming/Outgoing call takes time

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#952]
As i mentioned in title, there's a problem with calls, every time someone calls i have to wait at least 2-3 seconds till i can answer a call.Outgoing calls take same time. And it irritates me pretty much. That's only downside of this rom, and yea, mp3 skipping but I solved that by installing another player. Anyway if you need any logs just say so.

**Comment by rtsui-harmonicinc** [comment]
#933 please inform whether the update solved your problem

**Comment by ghost** [comment]
Ive tried that but my adb console cant find  /dev/block/mmcblk0p2 /data
