### ISSUE TITLE
[CM11.0][20150722][haida] boot.img dont work

### ISSUE THREAD

**Issue by cabbyy123** [LegacyXperia/local_manifests#957]
Cwm not open. It remains on the Legacyxperia screen.

**Comment by SageSages** [comment]
A have the same problem. After 'fastboot reboot' recovery don't work.

**Comment by cabbyy123** [comment]
You can find the solution?

**Comment by cabbyy123** [comment]
My solution was to install the old boot.img.

**Comment by mikeNG** [comment]
I just tested and it works fine on my haida

**Comment by mikeNG** [comment]
You are supposed to enter recovery with volume buttons. I have tested on all devices I own and the builds work correctly.

**Comment by cabbyy123** [comment]
problems zImage file extension .
