### ISSUE TITLE
[CM11.0][20150722][anzu] Recovery problem and reboots 

### ISSUE THREAD

**Issue by SageSages** [LegacyXperia/local_manifests#958]
I flashed new kernel and after reboot, recovery don't work. If I pressing menu button, recovery don't boot and after several seconds phone restarts over and over again. If I pressing volume down button, recovery is starting and it freezes on the first screen.

**Comment by mikeNG** [comment]
You are supposed to enter recovery only with volume buttons. I have tested on all devices I own and the builds work correctly.

**Comment by SageSages** [comment]
Well, what should we do when we have this problem?

**Comment by realcatgirly** [comment]
Volume buttons are working fine on my urushi
