### ISSUE TITLE
[CM11] [ANZU] ext4 partition

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#959]
How can I mount ext4 partition in cm11? I am using cm12.1 right now but it is still laggish, so I want to flash cm11 because it is more stable than cm12.1 but i have lack of space in cm11.

**Comment by rtsui-harmonicinc** [comment]
please rewrite in details

**Comment by ghost** [comment]
How can I mount ext4 partition in cm11, in cm12.1 it mounts automatically

**Comment by ghost** [comment]
If I create ext4 partition in windows phone cant see it, in cm11

**Comment by rtammekivi** [comment]
You need to recompile boot.img and edit fstab.semc in such a way that it mounts your SD like in cm-12.1. Check cm-12.1 boot.img for info.

I will not give you any tutorials on how to unpack/repack boot.img however.

**Comment by ghost** [comment]
I have unpacked boot.img but i dont know where to find "fstab.semc"

**Comment by ghost** [comment]
Never mind, I found it in ramdisk.cpio, also do I need to edit ramdisk_recovery.cpio

**Comment by MardonHH** [comment]
this is no bug.
@mikeNG you can close it
