### ISSUE TITLE
CWM Recovery Problem

### ISSUE THREAD

**Issue by RuskaKosiarka** [LegacyXperia/local_manifests#960]
Hi, after flashing kernel to haida from 20150722 i cant start cwm recovery, because after start freeze in logo and "CWM-based..." title.

**Comment by s-kostyuk** [comment]
Same issue on haida. Unable to open recovery or boot Android. How to debug?

**Comment by hansdorfer** [comment]
Same issue flashing to mango from 20150723

**Comment by 9omorra** [comment]
Same issue on iyokan (cm-11-20150723-UNOFFICIAL-LegacyXperia-iyokan.zip).
(see https://i.imgur.com/EMwQtDW.jpg, sorry for image quality)

I tried the advice from http://forum.xda-developers.com/showpost.php?p=62035917&postcount=979

> Finally i did it,the only way was putting the old kernel,make a full wipe/format,install new kernel,boot into recovery (now it enter),install rom and reboot.

But I got stuck during installation, although I even wiped again (see https://i.imgur.com/yvhRqgx.jpg).
The zip file md5sum was correct.

Finally I got back to cm-11-20150511-UNOFFICIAL-LegacyXperia-iyokan.zip

**Comment by ireun** [comment]
@9omorra Thank you Man, finally got this to work!

**Comment by 9omorra** [comment]
@ireun What did you get to work? 20150511 or 20150723?

**Comment by ireun** [comment]
@9omorra I've flashed 20150723, i needed to flash kernel from 20150511  go to recovery, wipe everything (format system also), flash kernel from 20150723, flash ROM.

**Comment by 9omorra** [comment]
It finally works for me, too:

I tried again with cm-11-20150811-UNOFFICIAL-LegacyXperia-iyokan.zip. The base was an almost clean installation of 20150511 (wiped, installed, hardly any changes afterwards). After flashing 20150811 kernel, recovery got stuck for several seconds or minutes, but finally got through. I wiped again and could install the 20150811 zip without getting stuck. Booting 20150811 also worked. So the issue seems to be resolved for me.

**Comment by SageSages** [comment]
I have problem all time. I'm traing do it for 4 hours...

**Comment by lubo** [comment]
The same problem on my haida, @9omorra's fixed helped me.

**Comment by andrew-boyarshin** [comment]
The same problem. Can't perform wipe because of apps data. Backups are not the way to go.

**Comment by siyman** [comment]
@9omorra Thanks a ton! I experienced this behavior some builds before back in 2014 but your solution made it possible for me to finally get back to the latest release.

**Comment by realcatgirly** [comment]
@mikeNG i think this can be closed
