### ISSUE TITLE
[CM-12.1-20150514] [smultron] randomly reboots

### ISSUE THREAD

**Issue by twonky4** [LegacyXperia/local_manifests#961]
The phone randomly reboots. It often happens when I use an app (different). But even if it is in standby. Usually it happens when there is only a quarter loaded and not in red area. Before that I had a battery problem, the new battery is now 2 months old.

last kernel log: http://pastebin.com/HaFmU1zs

Should i use BetterBatteryStats too, if it is the battery again?

**Comment by rtsui-harmonicinc** [comment]
We can found much more information with an adb logcat log.

**Comment by twonky4** [comment]
After I [recalibrates](https://play.google.com/store/apps/details?id=com.nema.batterycalibration) the battery, this issue no longer occurs. I close it.
