### ISSUE TITLE
Phone reboots after switching oft WLAN tethering.

### ISSUE THREAD

**Issue by ottopfeiffer2** [LegacyXperia/local_manifests#962]
Cm12.1 20150723 anzu reboots after switching oft WLAN tethering.

Last_kmsg.log:

Snip

[ 7258.357696] PM: resume of devices complete after 47.758 msecs
[ 7258.420989] PM: suspend exit 2015-07-28 12:54:51.078824991 UTC
[ 7258.421081] suspend: exit suspend, ret = 0 (2015-07-28 12:54:51.078946972 UTC)
[ 7258.421477] active wake lock mmc1_detect
[ 7258.421569] active wake lock PowerManagerService.WakeLocks
[ 7258.421721] active wake lock PowerManagerService.Display
[ 7258.421813] active wake lock PowerManagerService.Broadcasts
[ 7258.425445] request_suspend_state: wakeup (3->0) at 7255754250821 (2015-07-28 12:54:51.083277581 UTC)
[ 7265.562652] wl12xx: ERROR command complete timeout
[ 7265.563262] ------------[ cut here ]------------
[ 7265.566070] WARNING: at /mnt/out/langes/lx/target/product/anzu/obj/KERNEL_OBJ/modules/compat_wl12xx/drivers/net/wireless/wl12xx/main.c:1437 wl12xx_queue_recovery_work+0x2c/0xa0 [wl12xx]()
[ 7265.571502] ---[ end trace 33bf12b270e852db ]---
[ 7265.572356] wl12xx: ERROR failed to initiate cmd remove peer
[ 7265.575683] wl12xx: watchdog interrupt received! continue with recovery
[ 7265.576690] wl12xx: Reading FW panic log
[ 7265.578490] wl12xx: Hardware recovery in progress. FW ver: Rev 6.3.10.0.139
[ 7265.579864] wl12xx: pc: 0xc000f854
[ 7265.580443] wl12xx: removing interface 90:c1:15:18:df:cb
[ 7265.585662] ieee80211 phy1: Hardware restart was requested
[ 7265.586944] ieee80211 phy1: failed to remove key (2, ff:ff:ff:ff:ff:ff) from hardware (-11)
[ 7265.587829] ieee80211 phy1: failed to remove key (1, ff:ff:ff:ff:ff:ff) from hardware (-11)
[ 7265.589324] Unable to handle kernel paging request at virtual address 00100104
[ 7265.590331] pgd = d9f14000
[ 7265.590880] [00100104] *pgd=4d9db831, *pte=00000000, *ppte=00000000
[ 7265.593871] Internal error: Oops: 817 [#1] PREEMPT ARM
[ 7265.594420] Modules linked in: wl12xx_sdio(O) wl12xx(O) mac80211(O) cfg80211(O) compat(O) [last unloaded: wl12xx_sdio]
[ 7265.598998] CPU: 0    Tainted: G        W  O  (3.4.0-LX+ #1)
[ 7265.600097] PC is at wl1271_op_suspend+0x25c/0x47c [wl12xx]
[ 7265.600707] LR is at wl1271_op_suspend+0x240/0x47c [wl12xx]
[ 7265.601714] pc : [<bf079ee4>]    lr : [<bf079ec8>]    psr: 40020113
[ 7265.601745] sp : d9f19e10  ip : 00100100  fp : d9f18000
[ 7265.603271] r10: dd4cc480  r9 : 00000100  r8 : 00000000
[ 7265.603820] r7 : d9f18000  r6 : d418cb40  r5 : d418d8e0  r4 : d418d8e0
[ 7265.604857] r3 : 00200200  r2 : 00100100  r1 : 00200200  r0 : bf09e770
[ 7265.605437] Flags: nZcv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment user
[ 7265.606444] Control: 10c57c7d  Table: 49f14059  DAC: 00000015
[ 7265.606994] 
[ 7265.607024] SP: 0xd9f19d90:
[ 7265.608489] 9d90  d9f19dfc c06600dc d9f19d98 d9f19d98 d4455680 00000001 d4455680 c00b1d08
[ 7265.613494] 9db0  bf079ee4 40020113 ffffffff d9f19dfc 00000000 c000de98 bf09e770 00200200
[ 7265.619018] 9dd0  00100100 00200200 d418d8e0 d418d8e0 d418cb40 d9f18000 00000000 00000100
[ 7265.624572] 9df0  dd4cc480 d9f18000 00100100 d9f19e10 bf079ec8 bf079ee4 40020113 ffffffff
[ 7265.630065] 9e10  00000000 d418d910 d418d8e0 bf07a130 bf07a104 d418cb40 00000000 bf04b7e0
[ 7265.635161] 9e30  d418d188 bf03b950 00000200 d9f18000 00000004 dd4cc000 d9f19e80 00000001
[ 7265.640655] 9e50  00001003 00000000 00000000 00000001 d9f18000 bf03bc7c bf03bc6c c050148c
[ 7265.646148] 9e70  dd4cc09c dd4cc000 00001042 c05014f8 dd4cc09c dd4cc09c d9f18000 c0504884
[ 7265.651153] 
[ 7265.651183] FP: 0xd9f17f80:
[ 7265.652190] 7f80  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 7265.657653] 7fa0  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 7265.662688] 7fc0  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 7265.668151] 7fe0  00000000 00000000 00000000 00000000 00000000 00000000 4ef91821 4ef91c21
[ 7265.673583] 8000  00000200 00000002 00000000 d4455680 c08f024c 00000000 00000015 d4455680
[ 7265.678588] 8020  de831680 00000000 dd111700 d9f18000 c08f2010 c08f2010 d9f19b74 d9f19ae8
[ 7265.683593] 8040  c065f7c4 00000000 00000000 00000000 00000000 00000000 01010000 01000000
[ 7265.689086] 8060  4001ee30 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 7265.694488] 
[ 7265.694488] R4: 0xd418d860:
[ 7265.695495] d860  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 7265.700927] d880  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 7265.706023] d8a0  d418d8a0 d418d8a0 00000001 00000000 bf02a000 00000000 d418d430 d418d4c4
[ 7265.711089] d8c0  d418d4c4 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 7265.716582] d8e0  d418cb40 00000001 dd015c08 00000000 bf002838 00000000 00000113 00000000
[ 7265.722045] d900  00000000 00000000 00000001 00000000 00000000 d418d914 d418d914 00000000
[ 7265.727019] d920  00014fc0 00040000 0000a000 00300000 00000004 003004f8 00000000 00040404
[ 7265.732543] d940  04030111 20766552 2e332e36 302e3031 3933312e 00000000 00000000 00000000
[ 7265.738036] 
[ 7265.738067] R5: 0xd418d860:
[ 7265.739104] d860  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 7265.744597] d880  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 7265.750060] d8a0  d418d8a0 d418d8a0 00000001 00000000 bf02a000 00000000 d418d430 d418d4c4
[ 7265.755034] d8c0  d418d4c4 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 7265.760467] d8e0  d418cb40 00000001 dd015c08 00000000 bf002838 00000000 00000113 00000000
[ 7265.765899] d900  00000000 00000000 00000001 00000000 00000000 d418d914 d418d914 00000000
[ 7265.771361] d920  00014fc0 00040000 0000a000 00300000 00000004 003004f8 00000000 00040404
[ 7265.776427] d940  04030111 20766552 2e332e36 302e3031 3933312e 00000000 00000000 00000000
[ 7265.781920] 
[ 7265.781920] R6: 0xd418cac0:
[ 7265.782958] cac0  00000000 00000000 00000000 00000000 00000000 00000000 00000000 d418cadc
[ 7265.788421] cae0  d418cadc 00000000 00000000 00000000 00000000 00000000 00000000 d418cafc
[ 7265.793883] cb00  d418cafc ddd7388c ddd7388c ddd7388c 00000001 bf01f1fc 00000000 00000000
[ 7265.799438] cb20  00000001 d85f4a80 bf05aadc 00000000 00000000 00000000 00000000 00000000
[ 7265.804473] cb40  00000004 00000014 00000000 00000000 04000014 00000007 bf09e8b0 00000001
[ 7265.809905] cb60  00000001 d418c100 00000000 d418d8e0 0cde5741 00000014 00002710 00000140
[ 7265.815398] cb80  00000001 00000000 00140004 00010100 00004008 bf0934fc d418cb98 d418cb98
[ 7265.820464] cba0  00000000 00000000 00000000 c09bbe80 bf038538 d418cb40 ffffffff ffffffff
[ 7265.825561] 
[ 7265.825591] R7: 0xd9f17f80:
[ 7265.827025] 7f80  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 7265.832091] 7fa0  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 7265.837523] 7fc0  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 7265.843047] 7fe0  00000000 00000000 00000000 00000000 00000000 00000000 4ef91821 4ef91c21
[ 7265.848022] 8000  00000200 00000002 00000000 d4455680 c08f024c 00000000 00000015 d4455680
[ 7265.853087] 8020  de831680 00000000 dd111700 d9f18000 c08f2010 c08f2010 d9f19b74 d9f19ae8
[ 7265.858550] 8040  c065f7c4 00000000 00000000 00000000 00000000 00000000 01010000 01000000
[ 7265.864013] 8060  4001ee30 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 7265.869018] 
[ 7265.869048] R10: 0xdd4cc400:
[ 7265.870482] c400  00000000 00000000 00000000 00010000 00000000 00000000 00000000 00000000
[ 7265.875518] c420  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 7265.880492] c440  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 7265.885955] c460  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 7265.891387] c480  d418d168 d418d168 d418c100 00000003 d418c050 d418c050 dd4cc000 d6156b00
[ 7265.896270] c4a0  d2271f00 00000001 dd4cc4a8 dd4cc4a8 00000200 dd4cc4b4 dd4cc4b4 bf004514
[ 7265.901732] c4c0  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 7265.907195] c4e0  00000000 00000000 00000000 00000000 dd4cc4f0 dd4cc4f0 00000000 00000000
[ 7265.912719] Process hostapd (pid: 4088, stack limit = 0xd9f182f0)
[ 7265.913268] Stack: (0xd9f19e10 to 0xd9f1a000)
[ 7265.914275] 9e00:                                     00000000 d418d910 d418d8e0 bf07a130
[ 7265.914886] 9e20: bf07a104 d418cb40 00000000 bf04b7e0 d418d188 bf03b950 00000200 d9f18000
[ 7265.915954] 9e40: 00000004 dd4cc000 d9f19e80 00000001 00001003 00000000 00000000 00000001
[ 7265.916991] 9e60: d9f18000 bf03bc7c bf03bc6c c050148c dd4cc09c dd4cc000 00001042 c05014f8
[ 7265.917602] 9e80: dd4cc09c dd4cc09c d9f18000 c0504884 00000000 dd4cc000 00001003 be8177ac
[ 7265.918639] 9ea0: 00008914 c05049b0 00000000 d9d4ca0c be8177ac c0584360 be8177ac c0b2d750
[ 7265.919707] 9ec0: d9d4ca00 00000014 d9d4ca0c dd4cc000 6e616c77 00000030 00000000 00000000
[ 7265.920745] 9ee0: 00001042 00000000 00000000 00000000 00001043 00008914 be8177ac 0000001f
[ 7265.921355] 9f00: dd01ac00 d84624a0 d9f18000 be8177ac 00000001 c04f1688 00000000 dd01ac00
[ 7265.922393] 9f20: 0000001f c01404e0 d9f19f4c 00000000 dd01ac08 c0234fe8 00000000 dd01a180
[ 7265.923430] 9f40: 00000000 00000000 00000000 00000001 00000000 de810f10 d8460800 d9f19f44
[ 7265.924468] 9f60: 00000000 be8177ac 00000000 be8177ac 00008914 dd01ac00 0000001f d9f18000
[ 7265.925078] 9f80: 00000200 c0140a8c 00000001 00000000 00000000 be8177ac 013e7780 00000036
[ 7265.926116] 9fa0: c000e484 c000e45c 00000000 be8177ac 0000001f 00008914 be8177ac be817798
[ 7265.927154] 9fc0: 00000000 be8177ac 013e7780 00000036 40452de4 0000001f 00000000 00000001
[ 7265.927764] 9fe0: 00000000 be817788 4043b3ad 40435d80 a0010010 0000001f 1e4f55d3 77e05497
[ 7265.928954] [<bf079ee4>](wl1271_op_suspend+0x25c/0x47c [wl12xx]) from [<bf07a130>](wl1271_op_stop+0x2c/0x348 [wl12xx])
[ 7265.930266] [<bf07a130>](wl1271_op_stop+0x2c/0x348 [wl12xx]) from [<bf04b7e0>](ieee80211_stop_device+0x40/0x78 [mac80211])
[ 7265.931579] [<bf04b7e0>](ieee80211_stop_device+0x40/0x78 [mac80211]) from [<bf03b950>](__ieee80211_recalc_idle+0x4e4/0x800 [mac80211])
[ 7265.932891] [<bf03b950>](__ieee80211_recalc_idle+0x4e4/0x800 [mac80211]) from [<bf03bc7c>](ieee80211_stop+0x10/0x734 [mac80211])
[ 7265.934081] [<bf03bc7c>](ieee80211_stop+0x10/0x734 [mac80211]) from [<c050148c>](__dev_close_many+0x88/0xcc)
[ 7265.935149] [<c050148c>](__dev_close_many+0x88/0xcc) from [<c05014f8>](__dev_close+0x28/0x3c)
[ 7265.936217] [<c05014f8>](__dev_close+0x28/0x3c) from [<c0504884>](__dev_change_flags+0x7c/0x13c)
[ 7265.937285] [<c0504884>](__dev_change_flags+0x7c/0x13c) from [<c05049b0>](dev_change_flags+0x10/0x48)
[ 7265.938384] [<c05049b0>](dev_change_flags+0x10/0x48) from [<c0584360>](devinet_ioctl+0x75c/0x870)
[ 7265.939086] [<c0584360>](devinet_ioctl+0x75c/0x870) from [<c04f1688>](sock_ioctl+0x5c/0x280)
[ 7265.940154] [<c04f1688>](sock_ioctl+0x5c/0x280) from [<c01404e0>](do_vfs_ioctl+0x84/0x5c4)
[ 7265.941192] [<c01404e0>](do_vfs_ioctl+0x84/0x5c4) from [<c0140a8c>](sys_ioctl+0x6c/0x7c)
[ 7265.942260] [<c0140a8c>](sys_ioctl+0x6c/0x7c) from [<c000e45c>](__sys_trace_return+0x0/0x24)
[ 7265.942901] Code: e3a03c02 e3402010 e3403020 e59f0218 (e58c1004) 
[ 7265.947936] ---[ end trace 33bf12b270e852dc ]---
[ 7265.948028] Kernel panic - not syncing: Fatal exception
[ 7265.948211] Rebooting in 5 seconds..
[ 7274.216796] msm: proc_comm: proc comm disabled

No errors detected

**Comment by mikeNG** [comment]
#929
