### ISSUE TITLE
Bug with mini tool partition wizard

### ISSUE THREAD

**Issue by reymarbc** [LegacyXperia/local_manifests#963]
After partitioning sdcard using LXP cm 11 kernel (because cm12.1 doesnt have parted binaries)
http://s30.postimg.org/ukejxq3ap/Capture.png

After putting the sdcard to usb microsd reader and checking the status in minitool partition wizard, it shows Ext3 without flashing any rom
http://s30.postimg.org/huabkmvch/Capture2.png

**Comment by GauriSpears** [comment]
What is the question? You format it as ext4 but it is shown as ext3? It's minitool issue. Ext4 is generally ext3 with advanced journaling so programs may tell that it's ext3. The most robust way to know the truth is to look into listing of mount command.
