### ISSUE TITLE
[CM11] Camera bugs Nightly build 20150722 and 20150810

### ISSUE THREAD

**Issue by fabri20** [LegacyXperia/local_manifests#969]
I was using the latest Nightly build (20150722 and 20150810) in which the camera has serious bugs.
After holding on the phone for a while , it is when the camera starts to give this kind of random bugs.

Sorry for my bad english.

"You can not connect to the camera"

<a href="http://es.tinypic.com?ref=2h4ykxd" target="_blank"><img src="http://i58.tinypic.com/2h4ykxd.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

after reboot...

<a href="http://es.tinypic.com?ref=5nmz2b" target="_blank"><img src="http://i58.tinypic.com/5nmz2b.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by fabri20** [comment]
KSM disable, and this was solved ... sorry for the inconvenience

**Comment by rtsui-harmonicinc** [comment]
this is an known (cause is unknown) error, better leave it.
