### ISSUE TITLE
Wifi drops

### ISSUE THREAD

**Issue by kosvrouvas** [LegacyXperia/local_manifests#97]
Sometimes there are some drops, even when connection to WiFi is perfect. I haven't been able to determine when this happens exactly, only thing I noticed is that the device might be a bit heated when this happens.

A quick solution is to turn WiFi off and on again.

This happens to every app requiring internet connection, I'll try to get a logcat when it happens again.

20131013
haida

![screenshot_2013-10-15-00-42-17 1](https://f.cloud.github.com/assets/3307723/1332879/8995182e-3585-11e3-8d13-20b38a500da1.png)

**Comment by djey47** [comment]
[Device: haida]

Hi,

maybe the same thing here ... since latest 20131013, I'm experiencing disconnects a few seconds after succesfull login to my corporate wifi network.
Signal quality is ok according to wifi connection list.

I don't encounter this issue at home.

Log:
http://pastebin.com/TVW70Q6T

**Comment by djey47** [comment]
Reproduced on 20131024, same issue.

Log contents are the same.

**Comment by ghost** [comment]
I used to get this but 20131112 fixed it.

**Comment by djey47** [comment]
Seems ok for me now.
I can connect and stay connected to wifi network with latest CM10.2 release (2013-11-12, haida)

**Comment by Institor666** [comment]
djey47, please test SIP over wifi, #189

**Comment by mikeNG** [comment]
I can't seem to reproduce this issue anymore

**Comment by bgokul95** [comment]
I am having an issue that my wifi totally drops when screen goes off. Download continues only when the screen gets on.
Haida.
#456 post

**Comment by v6ak** [comment]
bgokul95: Whan't your configuration of Wi-Fi sleep policy (see Settings -> Wi-Fi -> menu key -> Advanced)?

**Comment by mikeNG** [comment]
@bgokul95 the issue you are describing is not the same as the bug we're talking about.

**Comment by Institor666** [comment]
With last 10.2 build (cm-10.2-20140207-NIGHTLY-LegacyXperia-coconut.zip) wl12xx firmware reboots frequently. SIP (internet calls) not working. (ERROR watchdog interrupt received! starting recovery....... etc).
other internet (http etc) works, but sometimes slowly (suppose interrupts not so critical for http)

**Comment by maystar** [comment]
I have the same behavior on my haida device with build cm-11.0-20140319.

**Comment by dlastov** [comment]
I have this issue when streaming music in "Google Play Music".
When I go to the Wifi Settings so it seems to me that the connection drops shortly when the list of available networks is refreshing, but it is difficult to say 100% whether it is related.

**Comment by foresto** [comment]
Does anyone know what causes these wifi drops, or whether it's likely that we'll have a fix any time this year? Is some kind of help needed? I don't know what I could offer, but since this is the only issue keeping me from replacing my stock Gingerbread ROM, I'd certainly consider getting involved if I felt I could make much difference.

**Comment by dlastov** [comment]
foresto: The easiest way to help is probably to install the rom and accurately describe your problems if you experience them. Personally I didn't experience with this rom bigger Wifi issues than with the stock rom. I suggest you to go to the xda thread and discuss there the users' experiences to see whether it is blocking for you. I don't remember anyone complaining about unusable Wifi.

**Comment by v6ak** [comment]
Well, the WiFi works well for webbrowsing, but I can't call via SIP using Groundwire when being on WLAN. I haven't tested other SIP apps, but there have been some complaints by others.

I can also play Youtube videos, which should be also data consuming activity, although it is in may ways different. (In Youtube, in consrast to SIP, latency and jitter do not matter much. Youtube may use TCP, while SIP uses UDP.) Maybe there is some problem related to UDP on WLAN.

Note that calls via Groundwire work when I am on mobile network.

**Comment by dlastov** [comment]
v6ak: I don't know whether there is technically difference between SIP and Skype but Skype is ok for me, certainly without video. With video streaming (e.g. in MX Player but also the built in video plugin) I don't have problems neither. The Google Play Music problem, that I mentioned above, goes away after few minutes when there is enough data in the cache - but it maybe problem with the server or the application.

**Comment by v6ak** [comment]
As far as I know, Skype has various fallbacks and can call even via TCP:80, if nothing other is available.

**Comment by GTNeo** [comment]
based on my post
http://forum.xda-developers.com/showthread.php?p=53381758#post53381758

Can someone confirm that the "SIP-WiFi-Problem" depends on hardware of AccessPoint too?

**Comment by paulmcauley** [comment]
I'm also having lots of these on the latest 20140718 CM11 on Xperia Pro (Iyokan) on an WPA2-PSK 802.11n network. It is difficult to browse an image-heavy site without a drop-out occuring, with the result being that many images become broken. It seems to occur when the CPU gets busy (though I can't say that for sure).

**Comment by maystar** [comment]
I can confirm that the problem depends on the access point. My home network is in a very wifi overcrowded downtown region using a fritzbox 7390. I'm not able to use any voip app when connected to that wifi directly. This is possible with my asus tablet and there was no issue with the stock rom. But if I am at work I can use wifi, create a VPN connection to my fritzbox and make voip calls without noticeable distortion.  
There are definitely less foreign networks at my work place. I don't know if there are other important differences. There are about 25 neighbour networks at home. Can anybody make voip calls in a similar environment?

**Comment by Keryax** [comment]
Have the same issue on urushi. It seems that DNS service stop working because I get error "ERR_NAME_NOT_RESOLVED"

So, I've got this bug on 3G too, not only wifi.

**Comment by knetor** [comment]
i dont get any IM messages while connected to my wifi, drops still exist. makes my wifi quite useless

**Comment by mikeNG** [comment]
Possible fix: http://review.msm7x30.org/#/c/124/

**Comment by foresto** [comment]
@mikeNG, I don't see why you closed this issue. Did you commit a fix someplace?

**Comment by mikeNG** [comment]
@foresto yes, the commit linked above

**Comment by foresto** [comment]
Thanks! (That link was failing for me earlier today, but it's working now.)
