### ISSUE TITLE
Data integration problem.

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#972]
When I installed new ROM (20150724)for my st15i it just not importing contents from SD card to the music or gallery.And also there is no ringtone,notification tone to select from the list,only showing 'none'

**Comment by rtsui-harmonicinc** [comment]
you should clear /data and try again

**Comment by ghost** [comment]
What data? I'm a normal user,I don't understand .Explain it to me pls

**Comment by realcatgirly** [comment]
Shutdown phone, start it again, if the led is purple on the LegacyXperia screen press volume down. Now select wipe data/factory reset, yes and it is done. You will lose all data. Or try to clear the cache.

Maybe you can use a root file manager and delete /data.

**Comment by realcatgirly** [comment]
Ps: SD card content won't be deleted🔒

**Comment by ghost** [comment]
Thank you

**Comment by realcatgirly** [comment]
Flashed the New kernel?
