### ISSUE TITLE
[Solved][CM12.1][20150723][mango]Bootloop after installing

### ISSUE THREAD

**Issue by Sarahcc** [LegacyXperia/local_manifests#974]
Hello, I installed the nightly named in the topic but my phone doesn't boot. It only shows the CM-face but doesn't finish booting.

Am I the only one with that problem?
Kernel is from the .zip, installed the way which is mentioned in http://forum.xda-developers.com/xperia-arc/development/dev-2011-unofficial-cyanogenmod-12-0-t3053950
"1: Flash boot.img in fastboot & reboot into recovery
2 (optional): If the device is not booting, reboot to bootloader again and run:
fastboot erase system
3: Enter recovery
4: Format /system using System-Formating-Tool_signed.zip (can be found here) , then /data and then /cache (Important step!)
5: Flash update zip
6: Flash gapps"

I chose first the HDPI gapps then the MDPI, but still doesn't work... :(

**Comment by Sarahcc** [comment]
[20150607] still the same issue...
What's wrong here with my phone?

**Comment by grio** [comment]
This is known problem in russians forums. If you are purge the dalvik cash in 12.1 it could be init bootloop. To fix this problem just reinstall the core to the different version ROM and install the 12.1 one more time.

**Comment by Sarahcc** [comment]
I saw this: "Minimum 2GB secondary ext4 partition for /data on class 10 SD card."
I thought while installation / booting for the first time it would create this partition.
Or do I have to do this manually?

You mean I should take the core from an older nightly and install the newer ROM on it? Or the other way round?

**Comment by grio** [comment]
Yes, you should make two partition on sd card manually. 1 partition FAT32, and the second EXT4
I have used 5GB for first and 10GB for second on 16GB sd card. Please search for more details in xda-developers forum.
Yes, you should take the core from an older rom. I have used the Rage Kernel v3.2 (ICS) and v3.0 (GB) http://forum.xda-developers.com/showthread.php?t=1398910

**Comment by Sarahcc** [comment]
Oh, maybe this with the partition COULD be one mistake. My fault :D Thanks :)
I'll buy a new SD-Card and try it later.
ICS-Kernel on CM12.1? Really? Do they match? I thought you said from an older 12.1 Nightly :D

**Comment by grio** [comment]
No, I mean _any_ older rom.

**Comment by Sarahcc** [comment]
Ok, it was really my fault forgetting to partionate... Now everything works (kernel from the zip) and this thread can be closed.
