### ISSUE TITLE
[cm-12.1 20150724] Notification issue

### ISSUE THREAD

**Issue by ntdvj** [LegacyXperia/local_manifests#975]
my device is xperia mini. have issue on notification as shown on the screen shoot.
for first time i open notification bar after reboot, there is no problem.
but, when opened for second time and so on, all the notification stacked into one, clear all button also not appear. the notification on lock screen also like that.
sometimes, the notification is still shown on the bar althought i already open it (in actual there is no notification, but when notification bar opened or enter lock screen, the last notification that should be disappeared still there but cant clicked like there is nothing there).

![screenshot_2015-08-18-08-04-10](https://cloud.githubusercontent.com/assets/13862126/9347798/0ea9bc70-4661-11e5-8b88-2d495fd1d615.png)

![screenshot_2015-08-18-08-04-19](https://cloud.githubusercontent.com/assets/13862126/9347803/1c2ebd00-4661-11e5-9876-787a2c105647.png)

![screenshot_2015-08-18-08-07-00](https://cloud.githubusercontent.com/assets/13862126/9347807/21eba7bc-4661-11e5-94a3-3a8897eb011c.png)

**Comment by fred777** [comment]
I do have the same problem on my Xperia Pro - killing SystemUI helps for while.

But it's a CM issue, not kernel-related.

**Comment by dafuki** [comment]
Same here on my Iyokan.
Was fine since it was released, but after disabling and re-enabling dev options, all the system UI started acting up. Home button task manager shows just the apps title with an empty frame, and can't swipe notifications on the lock screen too.
Killing SystemUI didn't help in my case though.

**Comment by devtryongit** [comment]
I am also affected in the way described by @dafuki ... I will see if I find some time to flash the official build and collect logs, but it should be easily reproducible anyway...

**Comment by fred777** [comment]
Is it really related to dev options? Have you verified this via full wipe?

I'm also facing empty frames in task manager BTW.

**Comment by dafuki** [comment]
I myself didn't verify it, but it never happened before, and started happening exactly after dev options dis/enable

**Comment by devtryongit** [comment]
I don't know if it is related to dev options, but I understood some people have less problems, so that might be the reason, it wouldn't be the first time that that enabling dev setting you also enable some bugs... I will verify that too if I have the time...

**Comment by dafuki** [comment]
Just notices my systemui has high CPU usage.
Googling suggests it's related to some widget, I might try killing them one by one after the weekend.

PS: no dropbox on my side

**Comment by cukong** [comment]
Hy bro,, i have the same problem like you, try to deactivated "animation transition duration" at developer options, and then try to activated "force high end graphics" at performance options,

**Comment by fred777** [comment]
That's it!!! 

Taskmanager-Preview is working again and I didn't have any issues with notifications so since.

**Comment by dafuki** [comment]
My "Animation transition duration" was already off.
So "Force high end graphics" was the fix for me.

Great job cukong,
Life saver :)

**Comment by ntdvj** [comment]
wow.. thanks for the solution.. i enable "force high end graphic" and the problem is gone. the notification, brightness slider, and task manager now working fine.

**Comment by camslice** [comment]
Enabling "Force high-end graphics" fixes the problem for me too.

I'm on a Mini Pro sk17a

**Comment by realcatgirly** [comment]
@mikeNG issue fixed = close
