### ISSUE TITLE
Long boot time

### ISSUE THREAD

**Issue by realcatgirly** [LegacyXperia/local_manifests#977]
I have Cyanogenmod 12.1 20150724 on my urushi and its a great ROM.
But the phone needs five minutes to boot up. If you need logs, I collected all logs.
Can you view logs in the Dropbox preview?

**Comment by MardonHH** [comment]
use a faster sdcard

**Comment by realcatgirly** [comment]
I have class 10/UHS 1

**Comment by MardonHH** [comment]
hope its a good card with fast random R/W speed 
class 10 uhs1 should be ok but that defines normal read write speeds not the random speed which is more important when we use sd for data/apps

**Comment by realcatgirly** [comment]
It's a SanDisk Extreme 32GB with ~4GB ext4. I want a bigger ext4 partition. How can I expand it? Mini partition wizard let's me only expand the normal partition

**Comment by mikeNG** [comment]
You can't expect a lot from 5 year old devices

**Comment by realcatgirly** [comment]
OK.
