### ISSUE TITLE
2013-10-13 Increased battery consumption

### ISSUE THREAD

**Issue by DanielMalmgren** [LegacyXperia/local_manifests#98]
This has been mentioned in the forums, but I can't see any issue regarding it here, so I guess I'll make one.

Battery consumption in 2013-10-13 is drastically increased. My Urushi uses up almost double the amount of power compared to 2013-10-01 nightly. Android system stands for most of it, I can't really see more than that. I see no specific wakelocks other than the normal ones. It's got nothing with BT to do as I have that disabled.

**Comment by mikeNG** [comment]
Any info from BetterBatteryStats? do you mind providing some battery logs? You can find instructions in the Q&A thread

**Comment by DanielMalmgren** [comment]
Ok, I've bought and installed BetterBatteryStats now. I'll get back with some results.

For the time being I can say that putting the phone in flight mode seems to have stopped the drain. I also think it was lower yesterday when I was at home using my home wifi than it is today when I'm only using mobile data, so my initial conclusion would be that this have with radio to do.

**Comment by DanielMalmgren** [comment]
Ok. Seems like it never ever enters deep sleep, and the infamous st_wake_lock is the bad guy.

I had wifi enabled the first 30 minutes or so and then disabled it. Still don't know if it's just a feeling, but it sure feels like it uses more power when it's on mobile data.

Anyway, here goes: http://pastebin.ca/2467323

Another dump, after a full days usage: http://pastebin.ca/2467820

**Comment by DanielMalmgren** [comment]
Did some more experimenting yesterday. I inactivated wifi, mobile data and also disabled location completely and then waited a few hours. Still 0,0% deep sleep. So I guess I was wrong, this hasn't got anything with mobile data to do after all. I'm thinking about simply downgrading to 131001 to compare with the numbers there.

**Comment by mikeNG** [comment]
Might be fixed in next build

**Comment by DanielMalmgren** [comment]
Yep. Upgraded an hour ago and since then I've got 84% deep sleep and a consumption of below 2% per hour, so at least for me this problem is fixed. Good work!
