### ISSUE TITLE
cm12.1 for lollipop status bar transparency gone

### ISSUE THREAD

**Issue by chrononin** [LegacyXperia/local_manifests#982]
Initially status bar and notification drawer were transparent. But now background is black only.

**Comment by niks255** [comment]
Enable high-end graphics in developer settings

**Comment by chrononin** [comment]
It resolved the issue. Thanks much for the help. During exploration I
disable it and later not able to identify the settings. :)

On Mon, Sep 14, 2015 at 1:25 AM, niks255 notifications@github.com wrote:

> Enable high-end graphics in developer settings
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LegacyXperia/local_manifests/issues/982#issuecomment-139912987
> .

## 

Regards.
_@pradip._
pradip.spdm@gmail.com
