### ISSUE TITLE
[CM12.1 self-built 20150918] Intermittent kernel panics

### ISSUE THREAD

**Issue by emaijala** [LegacyXperia/local_manifests#988]
I upgraded my iyokan from 20150723 to a self-built build 20150918 and since then I've been experiencing intermittent crashes/reboots. Here's one last_kmsg log: http://pastebin.com/h60Uh9pX . This one happened when I tried to kill Firefox with long back press. Others have happened when the phone has been idle or updating apps.

**Comment by mikeNG** [comment]
It would be useful to try reverting recent commits and see what happens. I suspect the recent mm kernel commits

**Comment by emaijala** [comment]
I can try if I just get a bit of help identifying the commits (not quite sure where to look).

**Comment by mikeNG** [comment]
https://github.com/LegacyXperia/android_kernel_semc_msm7x30/commits/cm-12.1

I would revert these:
https://github.com/LegacyXperia/android_kernel_semc_msm7x30/commit/164a6e7495c7877398432444db31b2a240f5bd03
https://github.com/LegacyXperia/android_kernel_semc_msm7x30/commit/40afc1fcec20ef68d3502ab0e1ac2673769a15a7

**Comment by emaijala** [comment]
Okay, thanks. I'll try with those reverted and report back.

**Comment by emaijala** [comment]
Almost two days without crashes. I'll try flashing a kernel with no reverted changes back to double-check.

**Comment by emaijala** [comment]
Okay, it's still inconclusive. I had it crash now before I managed to flash the other kernel, but for some reason last_kmsg is not available, so I don't know why it happened.

**Comment by emaijala** [comment]
Okay, crashed again and it was zram-related. Looks like I can make it crash consistently by trying to rename a large folder on SD card using the built-in (I guess) file manager. But that's another story, I'll report back about the original issue.

**Comment by emaijala** [comment]
Still inconclusive. I've had one complete hang where even power+home didn't restart the phone, but last_kmsg was garbled.

**Comment by realcatgirly** [comment]
I have crashes when I'm in the browser and put the device to sleep. After some time it reboots completely (from legacy xperia logo) . i try to catch logs if this happens again

**Comment by fred777** [comment]
Hm... every time I built CM12.1 for my iyokan since beginning of September, the phone did not boot at all, showing "LegacyXperia" logo only. I also couldn't get into recovery mode.

Had to remove battery and flash older kernel in order to get it working again... I wish it would display kernel log during bootup...

**Comment by realcatgirly** [comment]
log during boot: https://play.google.com/store/apps/details?id=eu.chainfire.liveboot

**Comment by fred777** [comment]
Thanks, but doesn't help in my case... After flashing new boot.img, it still won't boot but just stay at LegacyXperia-logo.

Also, it only vibrates once. Normaly it vibrates twice when booting.

Boot log will just be shown after LegacyXperia boot logo and Cyanogenmod boot logo.

**Comment by realcatgirly** [comment]
On some older builds i had another problem: the legacy xperia logo was displayed for 2 minutes before booting

**Comment by fred777** [comment]
Hm... I didn't wait for 2min...

What happened for you after reboot? Did it take 2min again?

**Comment by emaijala** [comment]
The two-minute delay was typical with YAFFS data partition in the internal memory because there was an issue with clean shutdown. It should not be present with CM 12.1 anymore since it's not using YAFFS. This is off-topic though, I suggest the discussion be continued in the XDA discussion forum.

I haven't been able to reproduce the crash anymore, so I'll close this issue now.

**Comment by realcatgirly** [comment]
i dont know what happened if i straight choose reboot in the power menu
