### ISSUE TITLE
sd-ext won't mount automatically

### ISSUE THREAD

**Issue by mid-kid** [LegacyXperia/local_manifests#99]
Using version (20131013) on haida, I followed [this](http://androidandme.com/2009/08/news/how-to-manually-partition-your-sd-card-for-android-apps2sd/) guide to partition my sd card and [this](http://www.ghacks.net/2010/08/11/convert-ext23-to-ext4/) guide to convert the ext2 sd-ext partition to ext4.

This is my partition table in parted (recovery mode)

```
Model: SD SU04G (sd/mmc)
Disk /dev/block/mmcblk0: 3965MB
Sector size (logical/physical): 512B/512B
Partition Table: msdos

Number  Start   End     Size    Type     File system     Flags
 1      32.3kB  2624MB  2624MB  primary  fat32           lba
 2      2624MB  3697MB  1073MB  primary  ext4
 3      3697MB  3965MB  268MB   primary  linux-swap(v1)
```

AFAIK, cyanogenmod is supposed to mount the sd-ext and swap partitions manually, but when running mount, I can't see either of those.
I can't find any info on how to mount them manually.

**Comment by mikeNG** [comment]
Not an LX issue, better ask on xda
