### ISSUE TITLE
My experiente with CM11 20150831 [Smultron] LegacyXperia

### ISSUE THREAD

**Issue by lordicus21** [LegacyXperia/local_manifests#994]
I really like this ROM by LegacyXperia. Very smooth and stable... But sure, I have found some bugs, the principal is some randomly lags when playing songs, I used Apollo and many other players, including the main Whatsapp player. But I, so, find I way to play songs without problems using Neutron player, that us very smooth. 
Rarely I have some problems with he Camera. I fell some random bugs related with vibration so. 
That's all, I'm using that ROM a lot of weeks all the time, and I think that fixing these bugs that will be a perfect ROM for the Old Smultron. Thanks! (And sorry for my English).

**Comment by realcatgirly** [comment]
what is the issue?

**Comment by lordicus21** [comment]
Music playing cuts
