### ISSUE TITLE
Michael Bestas - please help me

### ISSUE THREAD

**Issue by dinesheleven** [LegacyXperia/local_manifests#996]
I'm user of Sony xperia neo l, 
I Have a problem please help me, 
After flashing my neo l with legacyxperia CM 12.1 , 
I can't able to record video, 
Here is the link of logcat -http://pastebin.com/dhh8P6Ds

Please if you can't, than tell me any other way to solve it.

**Comment by FibreFoX** [comment]
Hi @dinesheleven , you should not open same bug-tickets multiple times! The problem won't go away faster this way.

**Comment by dinesheleven** [comment]
Sorry :(
